### ISSUE TITLE
still working on this?

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#1]
Hi Kaushal, just wondering if you were still working on this and if so what plans you have. I'm in the process of moving from Wordpress to Hugo and setting up my publishing framework with some ugly code munged from the links youcite i nthe README. I would love to use a mature/systainable exporter instead if you're going to be writing one... but will stick with my crappy system if I have to.  
My code quality is so low I'm not sure I can offer much help but at least I could be enthusiastic!

**Comment by kaushalmodi** [comment]
Yes! This is not abandoned by any chance. I am fairly active blogging using Hugo on my work blog (not so much on my public blog (scripter.co)). Each time I write the post in Markdown, I wish that I could finish this project. Let me find some time to put together a bare bones version. Thanks for the interest :)

**Comment by titaniumbones** [comment]
Excellent!

It's true that recnet versions of Hugo support Org, but the feature set
is so diminished that I seem to be getting better results with the gfm
exporter.. Once you have the bare bones version up and running, it would
be nice to try for feature parity e.g. by exporting images as Hugo
figure shortcodes, and things like that; I think that sort of thing
might be in my range as a programmer and Id be happy to try to help with
it.

Thanks for this and your many other org-related projects!

Kaushal Modi <notifications@github.com> writes:

> Yes! This is not abandoned by any chance. I am fairly active blogging using Hugo on my work blog (not so much on my public blog (scripter.co)). Each time I write the post in Markdown, I wish that I could finish this project. Let me find some time to put together a bare bones version. Thanks for the interest :)


--

**Comment by titaniumbones** [comment]
Closing in favor of the more specific issues I've been adding.
