### ISSUE TITLE
Enable export of images to /static/ directory

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#10]
Add a defcustom which allows images (and maybe also other local links?) to be exported to the `/static/` directory, and the link target to be rewritten to point to the new file.  

- [ ] add defcustom
- [ ] add export option(s)
- [ ] modify export behaviour, either by rewriting ` org-md-link` from `ox-md.el`, or by adding an export filter.  

cf. also #3 which also affects image export.

**Comment by titaniumbones** [comment]
Gah, this is difficult, in org exports images are a type of link, and the code for `org-md-link` is long and a little over my head.  Would love some guidance!

**Comment by kaushalmodi** [comment]
Do we need to implement this?

Image export works fine; see [this example][1].

## Directory structure under `example-site`

```
.
├── archetypes
│   └── default.md
├── config.toml
├── content
│   └── posts       <-- Markdown posts exported using ox-hugo        
│       ├── image.md
│       ├── post-1.md
│       ├── post-2.md
│       └── prep.md
├── content-org
│   └── all-posts.org       <-- All the posts in Org mode
├── data
├── layouts
├── README.org
├── static       <-- Images and other things go in here; use "file:./images/.." or "./images/.." in Org file
│   └── images
│       └── org-mode-unicorn-logo.png
└── themes
    └── bare_min
        └── layouts
            ├── _default
            │   └── baseof.html
            ├── index.html
            └── posts
                └── single.html
```

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/67e81d310ff3db6963257764c84f11d109081d67/example-site/content-org/all-posts.org

**Comment by titaniumbones** [comment]
yes, I'll lcose now, we can reopen if the code needs fixing.

**Comment by kaushalmodi** [comment]
# Clickable link that opens the image

    [[/images/org-mode-unicorn-logo.png][Click here to see the unicorn]]

exports to:

    [Click here to see the unicorn](file:///images/org-mode-unicorn-logo.png)

instead of:

    [Click here to see the unicorn](/images/org-mode-unicorn-logo.png)

# Clickable image that opens the image

    [[file:/images/org-mode-unicorn-logo.png][file:/images/org-mode-unicorn-logo.png]]

exports to:

    [![img](/images/org-mode-unicorn-logo.png)](file:///images/org-mode-unicorn-logo.png)

instead of:

    [![img](/images/org-mode-unicorn-logo.png)](/images/org-mode-unicorn-logo.png)

**Comment by kaushalmodi** [comment]
Can you please review this commit ( https://github.com/kaushalmodi/ox-hugo/commit/f02b4808a090dc7b74d66e77d8cd917cd14a34a7 )? If image exports still work fine in your workflow, you can close this issue.

Thanks.

**Comment by kaushalmodi** [comment]
@titaniumbones Can you confirm if this issue can be closed? Thanks.

**Comment by titaniumbones** [comment]
yes plese close.  Sorry not to do it myself, travelling with limited Internet
and will send my emails in bulk when I get back to reliable access.

Looks like you've implemented tons of new features, I'm excited to try
them out as soon as I can!

Kaushal Modi <notifications@github.com> writes:

> @titaniumbones Can you confirm if this issue can be closed? Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by kaushalmodi** [comment]
> Looks like you've implemented tons of new features, I'm excited to try
them out as soon as I can!

Let's hope I didn't break anything :)

Sure, try it out when you can.
