### ISSUE TITLE
Single Row Table Export Error

### ISSUE THREAD

**Issue by primerpy** [kaushalmodi/ox-hugo#100]
Trying to export a result containing only single row table, however got this error message

org-blackfriday-table-col-width: Symbol’s function definition is void: table
Mark set

**Comment by kaushalmodi** [comment]
Hmm.. I fixed that last week in https://github.com/kaushalmodi/ox-hugo/commit/553c5108bf312fcb643f47a5223841e05863324a

Can you make sure you are using the latest version from Melpa? If it's still not fixed, please provide a minimal Org file that recreates that error.

As you can see, the test for single row Org table works: https://ox-hugo.scripter.co/test/posts/table-with-single-row/

**Comment by kaushalmodi** [comment]
@primerpy Just checking again to see if you still see this issue.

**Comment by kaushalmodi** [comment]
I would have loved to hear something back from you. But in the absence of any response, I am closing this issue.
