### ISSUE TITLE
Export not using highlight shortcodes for src blocks

### ISSUE THREAD

**Issue by dieggsy** [kaushalmodi/ox-hugo#102]
# Issue

The documentation of `org-hugo-src-block` implies the default is to use highlight shortcodes for src blocks, unless the `HUGO_CODE_FENCE` property is set to a non-nil value **_and_**  if none of the Hugo "highlight" shortcode features are used. 

For a regular block, with no `HUGO_CODE_FENCE` property at all, and no highlight shortcode features, that is, just:
```
#+begin_src sh
echo example
#+end_src
```
I'm seeing triple-backquoted blocks rather than highlight shortcode blocks.

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.24)
     of 2017-11-18

## Org Version

    Org mode version N/A (N/A !!check installation!! @ /home/diego/.emacs.d/straight/build/org/)

### Org `load-path` shadows

**Warning**: Possible mixed installation of Org

    /home/diego/.emacs.d/straight/build/org/org-w3m hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-w3m
    /home/diego/.emacs.d/straight/build/org/ox-man hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-man
    /home/diego/.emacs.d/straight/build/org/org-agenda hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-agenda
    /home/diego/.emacs.d/straight/build/org/org-ctags hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-ctags
    /home/diego/.emacs.d/straight/build/org/ob-ref hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-ref
    /home/diego/.emacs.d/straight/build/org/ob-plantuml hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-plantuml
    /home/diego/.emacs.d/straight/build/org/org-table hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-table
    /home/diego/.emacs.d/straight/build/org/ob-perl hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-perl
    /home/diego/.emacs.d/straight/build/org/ob-sass hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-sass
    /home/diego/.emacs.d/straight/build/org/ob-lua hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-lua
    /home/diego/.emacs.d/straight/build/org/ob-asymptote hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-asymptote
    /home/diego/.emacs.d/straight/build/org/org-archive hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-archive
    /home/diego/.emacs.d/straight/build/org/ob-dot hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-dot
    /home/diego/.emacs.d/straight/build/org/ob-table hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-table
    /home/diego/.emacs.d/straight/build/org/org-mhe hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-mhe
    /home/diego/.emacs.d/straight/build/org/ob-picolisp hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-picolisp
    /home/diego/.emacs.d/straight/build/org/org-clock hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-clock
    /home/diego/.emacs.d/straight/build/org/ox-ascii hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-ascii
    /home/diego/.emacs.d/straight/build/org/ob-matlab hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-matlab
    /home/diego/.emacs.d/straight/build/org/ob-latex hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-latex
    /home/diego/.emacs.d/straight/build/org/org-loaddefs hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-loaddefs
    /home/diego/.emacs.d/straight/build/org/ob-C hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-C
    /home/diego/.emacs.d/straight/build/org/ob-processing hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-processing
    /home/diego/.emacs.d/straight/build/org/org-habit hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-habit
    /home/diego/.emacs.d/straight/build/org/org-compat hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-compat
    /home/diego/.emacs.d/straight/build/org/org-colview hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-colview
    /home/diego/.emacs.d/straight/build/org/org-capture hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-capture
    /home/diego/.emacs.d/straight/build/org/ox-icalendar hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-icalendar
    /home/diego/.emacs.d/straight/build/org/ob-ruby hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-ruby
    /home/diego/.emacs.d/straight/build/org/ob-ditaa hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-ditaa
    /home/diego/.emacs.d/straight/build/org/ob-shell hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-shell
    /home/diego/.emacs.d/straight/build/org/ob-lob hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-lob
    /home/diego/.emacs.d/straight/build/org/ox hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox
    /home/diego/.emacs.d/straight/build/org/org-info hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-info
    /home/diego/.emacs.d/straight/build/org/ob-octave hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-octave
    /home/diego/.emacs.d/straight/build/org/org-inlinetask hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-inlinetask
    /home/diego/.emacs.d/straight/build/org/ob-core hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-core
    /home/diego/.emacs.d/straight/build/org/org-footnote hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-footnote
    /home/diego/.emacs.d/straight/build/org/ob hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob
    /home/diego/.emacs.d/straight/build/org/org-entities hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-entities
    /home/diego/.emacs.d/straight/build/org/ox-latex hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-latex
    /home/diego/.emacs.d/straight/build/org/ob-exp hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-exp
    /home/diego/.emacs.d/straight/build/org/org-element hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-element
    /home/diego/.emacs.d/straight/build/org/ob-emacs-lisp hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-emacs-lisp
    /home/diego/.emacs.d/straight/build/org/org-faces hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-faces
    /home/diego/.emacs.d/straight/build/org/ob-gnuplot hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-gnuplot
    /home/diego/.emacs.d/straight/build/org/org-irc hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-irc
    /home/diego/.emacs.d/straight/build/org/org-indent hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-indent
    /home/diego/.emacs.d/straight/build/org/org-gnus hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-gnus
    /home/diego/.emacs.d/straight/build/org/org-duration hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-duration
    /home/diego/.emacs.d/straight/build/org/org-list hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-list
    /home/diego/.emacs.d/straight/build/org/ob-css hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-css
    /home/diego/.emacs.d/straight/build/org/ob-fortran hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-fortran
    /home/diego/.emacs.d/straight/build/org/ox-odt hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-odt
    /home/diego/.emacs.d/straight/build/org/ob-mscgen hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-mscgen
    /home/diego/.emacs.d/straight/build/org/ob-coq hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-coq
    /home/diego/.emacs.d/straight/build/org/ob-maxima hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-maxima
    /home/diego/.emacs.d/straight/build/org/org-bibtex hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-bibtex
    /home/diego/.emacs.d/straight/build/org/ob-groovy hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-groovy
    /home/diego/.emacs.d/straight/build/org/ob-python hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-python
    /home/diego/.emacs.d/straight/build/org/org-lint hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-lint
    /home/diego/.emacs.d/straight/build/org/org-crypt hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-crypt
    /home/diego/.emacs.d/straight/build/org/org-macs hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-macs
    /home/diego/.emacs.d/straight/build/org/ob-comint hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-comint
    /home/diego/.emacs.d/straight/build/org/ob-lisp hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-lisp
    /home/diego/.emacs.d/straight/build/org/ob-forth hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-forth
    /home/diego/.emacs.d/straight/build/org/org-feed hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-feed
    /home/diego/.emacs.d/straight/build/org/org-macro hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-macro
    /home/diego/.emacs.d/straight/build/org/org-plot hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-plot
    /home/diego/.emacs.d/straight/build/org/ob-eval hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-eval
    /home/diego/.emacs.d/straight/build/org/ob-awk hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-awk
    /home/diego/.emacs.d/straight/build/org/org-protocol hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-protocol
    /home/diego/.emacs.d/straight/build/org/ox-publish hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-publish
    /home/diego/.emacs.d/straight/build/org/org-datetree hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-datetree
    /home/diego/.emacs.d/straight/build/org/ob-sed hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-sed
    /home/diego/.emacs.d/straight/build/org/ob-haskell hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-haskell
    /home/diego/.emacs.d/straight/build/org/org-mobile hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-mobile
    /home/diego/.emacs.d/straight/build/org/ob-lilypond hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-lilypond
    /home/diego/.emacs.d/straight/build/org/ob-vala hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-vala
    /home/diego/.emacs.d/straight/build/org/ob-tangle hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-tangle
    /home/diego/.emacs.d/straight/build/org/ob-hledger hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-hledger
    /home/diego/.emacs.d/straight/build/org/ob-J hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-J
    /home/diego/.emacs.d/straight/build/org/ob-R hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-R
    /home/diego/.emacs.d/straight/build/org/ox-org hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-org
    /home/diego/.emacs.d/straight/build/org/org-install hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-install
    /home/diego/.emacs.d/straight/build/org/org-eww hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-eww
    /home/diego/.emacs.d/straight/build/org/ob-sql hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-sql
    /home/diego/.emacs.d/straight/build/org/org-src hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-src
    /home/diego/.emacs.d/straight/build/org/org-bbdb hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-bbdb
    /home/diego/.emacs.d/straight/build/org/org-attach hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-attach
    /home/diego/.emacs.d/straight/build/org/ob-io hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-io
    /home/diego/.emacs.d/straight/build/org/ob-screen hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-screen
    /home/diego/.emacs.d/straight/build/org/ox-texinfo hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-texinfo
    /home/diego/.emacs.d/straight/build/org/org-pcomplete hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-pcomplete
    /home/diego/.emacs.d/straight/build/org/ob-stan hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-stan
    /home/diego/.emacs.d/straight/build/org/ob-calc hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-calc
    /home/diego/.emacs.d/straight/build/org/ob-js hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-js
    /home/diego/.emacs.d/straight/build/org/ob-ocaml hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-ocaml
    /home/diego/.emacs.d/straight/build/org/org-rmail hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-rmail
    /home/diego/.emacs.d/straight/build/org/org-docview hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-docview
    /home/diego/.emacs.d/straight/build/org/org hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org
    /home/diego/.emacs.d/straight/build/org/org-timer hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-timer
    /home/diego/.emacs.d/straight/build/org/ob-sqlite hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-sqlite
    /home/diego/.emacs.d/straight/build/org/ob-clojure hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-clojure
    /home/diego/.emacs.d/straight/build/org/ob-ebnf hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-ebnf
    /home/diego/.emacs.d/straight/build/org/ob-makefile hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-makefile
    /home/diego/.emacs.d/straight/build/org/ox-beamer hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-beamer
    /home/diego/.emacs.d/straight/build/org/ob-abc hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-abc
    /home/diego/.emacs.d/straight/build/org/org-id hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-id
    /home/diego/.emacs.d/straight/build/org/ob-ledger hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-ledger
    /home/diego/.emacs.d/straight/build/org/ob-keys hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-keys
    /home/diego/.emacs.d/straight/build/org/ox-md hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-md
    /home/diego/.emacs.d/straight/build/org/ob-org hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-org
    /home/diego/.emacs.d/straight/build/org/ob-java hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-java
    /home/diego/.emacs.d/straight/build/org/ox-html hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ox-html
    /home/diego/.emacs.d/straight/build/org/ob-scheme hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-scheme
    /home/diego/.emacs.d/straight/build/org/ob-shen hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/ob-shen
    /home/diego/.emacs.d/straight/build/org/org-eshell hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-eshell
    /home/diego/.emacs.d/straight/build/org/org-mouse hides /nix/store/mhdibzx2972kjj9v238jg4my7qa86g8c-emacs-master/share/emacs/27.0.50/lisp/org/org-mouse

Study the output of `M-x list-load-path-shadows`.

## Hugo Version

`hugo` binary not found in PATH

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-default-section-directory</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "pdf" "odt")</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

**Comment by kaushalmodi** [comment]
Hello,

> The documentation of org-hugo-src-block implies the default is to use highlight shortcodes for src blocks, unless the HUGO_CODE_FENCE property is set to a non-nil value and if none of the Hugo "highlight" shortcode features are used.

That correct. The default value of HUGO_CODE_FENCE is `t` though ([ref][1]).

The aim for that condition is to keep "noise" at the minimum in the generated markdown, as IMO:

````
```shell
echo "Hi"
```
````

is a bit cleaner/easier to read than:

```
{{< highlight shell >}}
echo "Hi"
{{< /highlight >}}
```

But of course, that is my subjective view. For your use-case, you can do:

```
#+HUGO_CODE_FENCE: nil
```

(or even add that to a common SETUPFILE that you include in your blog posts).

Functionally though, hugo renders them equally, right?

[1]: https://github.com/kaushalmodi/ox-hugo/blob/fd7eb8494766fa9a31e7b5aeb2d6d7d686ea30c6/ox-hugo.el#L581

**Comment by dieggsy** [comment]
Ah, gotcha. I don't know if they're rendered equally actually, I hadn't even heard of the highlight shortcodes before reading this docstring :), so I thought I might give them a try and got a little tripped up by the behavior.

Perhaps it should be stated that the default value of `HUGO_CODE_FENCE` is `t` in the docstring for `org-hugo-src-block`.

(By the way, I wrote the post on whyarethingsthewaytheyare.com - I like what I've used of this package so far! I think I can finally get rid of that extremely hacky method I was using now)

**Comment by kaushalmodi** [comment]
> Perhaps it should be stated that the default value of HUGO_CODE_FENCE is t in the docstring for org-hugo-src-block.

Will do.

> By the way, I wrote the post on whyarethingsthewaytheyare.com - I like what I've used of this package so far!

👍

**Comment by kaushalmodi** [comment]
@dieggsy I have updated the documentation [here][1] and also in the `org-hugo-src-block` doc string and few other places.

[1]: https://ox-hugo.scripter.co/doc/source-blocks/

**Comment by dieggsy** [comment]
Great, thanks!
