### ISSUE TITLE
Export Org keywords AUTHOR, CREATOR to front-matter

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#106]

**Comment by kaushalmodi** [comment]
Example use on the doc site: https://github.com/kaushalmodi/ox-hugo/commit/09ba254839d7ab4f776a52ac174b95b77f1ef56e

**Comment by kishvanchee** [comment]
@kaushalmodi Thank you for this feature. Does the `CREATOR` feature still work? I tried this and I don't see it. Maybe I'm doing something wrong...(?)

**Comment by kaushalmodi** [comment]
@kishvanchee Do you have the creator export enabled? It's disabled by default.

```
#+OPTIONS: creator:t
```

**Comment by kaushalmodi** [comment]
> Does the #+CREATOR feature still work?

I had added a test when I enabled this feature: https://github.com/kaushalmodi/ox-hugo/commit/72481d7599aff597ac60cf61ca8c400e55632a89

So it still has to work.

**Comment by kishvanchee** [comment]
@kaushalmodi You're right. It does work. I added `creator: t` instead. The whitespace was messing with me. Apologies.

**Comment by kaushalmodi** [comment]
Thanks for confirming. For future, you can search for any feature's test on the ox-hugo test site.

Example: https://ox-hugo.scripter.co/test/search/?q=creator

**Comment by kishvanchee** [comment]
Thank you :) I did search, that's how I ended up in this issue :D Thanks again.
