### ISSUE TITLE
export blocks not working

### ISSUE THREAD

**Issue by Titan-C** [kaushalmodi/ox-hugo#107]
I was using HTML export blocks inside my posts but know they don't work anymore.
I used to embed HTML in export blocks(some inline javascript,iframes,forms) and the use emacs special webmode to work on them. But know they don't get exported anymore.

I guess based on the commit message (because my Elisp is not good) here https://github.com/kaushalmodi/ox-hugo/commit/1149f20cd7b499545aaeb9006c238ff0cfcce6ba that now you want to use `hugo` to be considered in the export, in such case I loose the possibility to use emacs dedicated modes to work on those sections. Using export hugo does send in verbatim the content of the block.

```org
#+BEGIN_EXPORT html
<div id="bethe-lattice"></div>
<form onsubmit="drawbethe(3,3); return false;">
  <input type="button" value="chain" onclick="drawbethe(8, 2);">
  <input type="button" value="3,3" onclick="drawbethe(3, 3);">
</form>
#+END_EXPORT
```

**Comment by kaushalmodi** [comment]
Thanks for the report. 

You're right. That recent commit would then not export blocks with html backend annotation. 

Let me see if I can allow hugo and html (and md) export blocks (maybe snippets too) to get exported by ox-hugo. 

If not, I'll revert the export block part for now.

**Comment by kaushalmodi** [comment]
@Titan-C Please try out the latest commit.. should be out through Melpa in 2-3 hours.

**Comment by Titan-C** [comment]
Thank you very much. Yes it is working great.
