### ISSUE TITLE
when running in auto-reload mode, URL of modified page is turned to lowercase

### ISSUE THREAD

**Issue by lwiechec** [kaushalmodi/ox-hugo#112]
I am using ox-hugo to generate my work blog which I publish to our company's GitHub Enterprise pages.

For that, in my `config.toml` I have the following:

```
baseURL = "http://github.our.domain/pages/Wiechec/journal/"
```
and in the org file with the blog, the following

```org
#+HUGO_SECTION: pages/Wiechec/journal/post
```

Then I run Hugo in 'navigate to changed page' mode:

```
hugo server -D --navigateToChanged
```

Then the URL that Hugo is navigating to is `http://localhost:1313/pages/wiechec/journal/post/2018-01-04/` and *not* `http://localhost:1313/pages/Wiechec/journal/post/2018-01-04/`.

It is possible that this is not `ox-hugo`'s fault but Hugo's itself; I don't know Hugo enough to verify that...

**Comment by kaushalmodi** [comment]
> It is possible that this is not ox-hugo's fault but Hugo's itself; I don't know Hugo enough to verify that...

`ox-hugo` shouldn't lower case the path.. you can verify by seeing that the casing of the dirs created inside the `content/` dir. It should be `content/pages/Wiechec/journal/post`.

What you are seeing is a Hugo feature.. it auto-lower-cases the whole path. You can confirm that by:

- cd to your hugo site base dir (the one containing the config.toml)
- Do `hugo config | grep disablepathtolower`. Its default value is `false` i.e. it **will** lower case the whole URL.

So try setting `disablePathToLower = true` in your `config.toml`. That will disable this feature.

**Comment by lwiechec** [comment]
thanks! I should have read Hugo docs more closely!
