### ISSUE TITLE
Image hyperlinked to image not working when linked image needs to be copied to static

### ISSUE THREAD

**Issue by eadmund** [kaushalmodi/ox-hugo#124]
So I have a file tree like this:

```
|-blog.org
|-hugo/
|- …
|-images/
|--foo.jpeg
|--bar.jpeg
```

Where `blog.org` looks something like:

```
#+HUGO_BASE_DIR: ./hugo
#+SEQ_TODO: TODO DRAFT DONE
#+PROPERTY: header-args :eval no

#+STARTUP: indent

#+AUTHOR:
* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: post
:END:
** Test images
:PROPERTIES:
:EXPORT_FILE_NAME: image-test
:END:
[[file:images/foo.jpeg][file:images/bar.jpeg]]
```

I would expect from the documents that this would result in `images/foo.jpeg` & `images/bar.jpeg` being copied to `hugo/static/ox-hugo` and something like `[{{<figure src="/ox-hugo/bar.jpeg">}}](/ox-hugo/foo.jpeg)` being in the generated markdown.

Instead, only `bar.jpeg` is copied to `hugo/static/ox-hugo` and the generated markdown is `[{{<figure src="/ox-hugo/bar.jpeg">}}](images/foo.jpeg)`, which is of course a dead link (because there is no file `images/foo.jpeg` anywhere in the generated site).

I've played around with different variants of full paths, relative paths & `file:`, but to no avail.

Here's the generated markdown:

+++
title = "Test images"
draft = false
+++

[{{<figure src="/ox-hugo/bar.jpeg">}}](images/foo.jpeg)

**Comment by kaushalmodi** [comment]
>     [[file:images/foo.jpeg][file:images/bar.jpeg]]

Can you try:

```
[[file:/images/foo.jpeg][file:/images/bar.jpeg]]
```

or even:

```
# The =file:= is actually necessary only in the description portion of the 
# link.. to make a hyperlinked image that links to an image.
[[/images/foo.jpeg][file:/images/bar.jpeg]]
```

.. because I [have a test][1] that tests exactly that ([Markdown output][2] | [Hugo Output][3]).


*Note the forward slashes added at the beginning*

[1]: https://github.com/kaushalmodi/ox-hugo/blame/49fd1e4e0010acafa22c6bdb14fb040fabc33573/test/site/content-org/all-posts.org#L69-L71
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/image-links.md
[3]: https://ox-hugo.scripter.co/test/posts/image-links/#clickable-image-that-opens-the-image--works

**Comment by kaushalmodi** [comment]
May be the issue is that this is a combination of "hyperlinked image" + "image that needs to be copied to static".. investigating.

**Comment by eadmund** [comment]
Certainly.

```
[[file:/images/foo.jpeg][file:/images/bar.jpeg]]
```

becomes:

```
[{{<figure src="/images/bar.jpeg">}}](/images/foo.jpeg)
```

with nothing copied to `hugo/static/images` (in fact, the directory doesn't exist).

```
[[/images/foo.jpeg][/images/bar.jpeg]]
```

becomes:

```
[images/bar.jpeg](/images/foo.jpeg)
```

Again, with nothing copied to `hugo/static/images`.

I did see the test, which is why I was so surprised that it's not working.

Of the non-working alternatives, I prefer the non-absolute paths, because it means that image linking within Org itself (e.g. `C-c C-o`) works.

(as an aside, `ox-hugo` is pretty awesome! I'm still not 100% convinced I like the all-in-one workflow — I suspect that's why relref links to other subtrees doesn't work — but it's definitely nice to have the real Org-mode at my fingertips)

**Comment by kaushalmodi** [comment]
> I'm still not 100% convinced I like the all-in-one workflow — I suspect that's why relref links to other subtrees doesn't work

Yup, that's a "small" price to pay.. that's the [only thing][1] blocking a 1.0 release of this package. But otherwise, subtree-based export gains a lot compared to the file-based flow.. the inheritance of tags, sections, etc. "just works".. you probably [saw this already][2], but that shows how much meta-data is auto-inferred from subtree properties :)

[1]: https://github.com/kaushalmodi/ox-hugo/issues/30
[2]: https://ox-hugo.scripter.co/doc/org-meta-data-to-hugo-front-matter/

**Comment by kaushalmodi** [comment]
@eadmund Sorry, auto-closed this issue by mistake. 

But I have committed a fix. You can try it out from the latest master commit (or wait for it to arrive on Melpa in few hours).

## New test

[Org][1] → [Markdown][2] → [Hugo output][3] 

Relevant Markdown snippet:

```markdown
#### Same image, but hyperlinked to itself {#same-image-but-hyperlinked-to-itself}

[{{<figure src="/ox-hugo/copy-2-of-unicorn-logo.png">}}](/ox-hugo/copy-2-of-unicorn-logo.png)
```

[1]: https://github.com/kaushalmodi/ox-hugo/blame/bf5dbd767b68ec94f7f50922888d57c193e11d28/test/site/content-org/all-posts.org#L115-L116
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/image-links.md
[3]: https://ox-hugo.scripter.co/test/posts/image-links/#same-image-but-hyperlinked-to-itself

**Comment by kaushalmodi** [comment]
Also, ignore the examples I gave earlier.. your original links should now work fine:

```org
[[file:images/foo.jpeg][file:images/bar.jpeg]]
```

**Comment by eadmund** [comment]
The fix seems to work — excellent! Thanks much for the speedy response.

FWIW I think that the ability to link between posts is the single most important outstanding feature: the blog I'm converting uses intra-blog links a _lot_.

**Comment by kaushalmodi** [comment]
>FWIW I think that the ability to link between posts is the single most important outstanding feature: the blog I'm converting uses intra-blog links a lot.

Of course. That is not taken lightly. Also, I am curious to see how you are using the links (more test cases!). Feel free to share the blog source if you have or plan to to make it public. Thanks.
