### ISSUE TITLE
Document shortcodes exporting support

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#126]
There are many ways:

## Recommended (in decreasing order)

1. Using special blocks, but exporting div or other HTML5 tag wrapped HTML ( https://ox-hugo.scripter.co/doc/org-special-blocks/ ).
2. Using special blocks, but exporting in Hugo shortcode syntax (See `HUGO_PAIRED_SHORTCODES`).
3. Using Org macros for unpaired shortcodes (gist, youtube, etc.)

## Not recommended

1. Or.. just putting raw Hugo shortcodes in Org document, probably wrapped in `#+begin_export html` and `#+end_export` - **I wouldn't recommend this.. pollutes the Org document with Hugo syntax too much**.

**Comment by kaushalmodi** [comment]
https://github.com/kaushalmodi/ox-hugo/commit/0150797401693cee51fde03fa07a1f10d36915e9

**Comment by kaushalmodi** [comment]
Document how to use non-pair shortcodes in Org documents **if you really need to**: https://github.com/kaushalmodi/ox-hugo/issues/242#issuecomment-444913361

**Comment by mcdviii** [comment]
Has this been implemented?

I'm looking for a way to export a list of image links, which need to be formatted in HTML so that a jQuery script can format them correctly.

**Comment by kaushalmodi** [comment]
> Has this been implemented?

Yes, it only needs to be documented. The example in my above comment works.

> I'm looking for a way to export a list of image links, which need to be formatted in HTML so that a jQuery script can format them correctly.

Though, it's not clear how that relates to shortcode exports. I am assuming that you have a shortcode that does what you said there?

**Comment by mcdviii** [comment]
>  Though, it's not clear how that relates to shortcode exports. I am assuming that you have a shortcode that does what you said there?
I may be confused, then. I'm simply trying to export my file so that HTML tags get rendered like they normally would in a Hugo markdown file. Perhaps what I'm looking for is different from this issue.

**Comment by mcdviii** [comment]
Will do. Thank you.

**Comment by kaushalmodi** [comment]
Hugo Shortcodes supported is documented on https://ox-hugo.scripter.co/doc/shortcodes/.
