### ISSUE TITLE
Ignore indentation before latex environment blocks

### ISSUE THREAD

**Issue by emacsun** [kaushalmodi/ox-hugo#128]
Hi @kaushalmodi ,

Recently, I want to add some latex equations into my post, such as:

```
\begin{equation}
\label{eq:1}
C = W\log_{2} (1+\mathrm{SNR})
\end{equation}
```

when there are no white space before the first character of the four lines, the ox-hugo works perfect. However when there are white space (auto indent in Org mode) before the first character, ox-hugo will treat the equation as code and convert the fourline literately. 

i.e. 

```
    \begin{equation}
    \label{eq:1}
    C = W\log_{2} (1+\mathrm{SNR})
    \end{equation}
```

will be treated as code. However, 

```
\begin{equation}
\label{eq:1}
C = W\log_{2} (1+\mathrm{SNR})
\end{equation}
```

will be treated as latex equation. The main differences lie in the space before the beginning of each line.

I check the output *.md file and find the difference.

**Comment by kaushalmodi** [comment]
The 2nd and 3rd equation snippets look the exact same. 

Can you please provide a minimum working example of an Org file that shows this issue? Also provide the generated Markdown file.  You can simply commit those files to a test repo, and share that, or upload those to something like a gist or pastebin.

**Comment by kaushalmodi** [comment]
Side note: to create code blocks in GitHub, you use the Markdown syntax:

````
```
my code snippet
```
````

**Comment by emacsun** [comment]
thank you for your instant reply. I will try my best to make my self clear.
the following code (code snippet1 )will be treated as code intead of interpreted as equation C = log2(1+SNR),

code snippet 1:
```
    \begin{equation}
    \label{eq:1}
    C = W\log_{2} (1+\mathrm{SNR})
    \end{equation}
```

the following (code snippet 2) will be treated as equation C=Wlog2(1+SNR)
```
\begin{equation}
\label{eq:1}
C = W\log_{2} (1+\mathrm{SNR})
\end{equation}
```

do you notice the space at the code snippet 1 at the beginning of each line? the space is generated by Org-indent-buffer under headline level 4. org-indent-buffer generate space at the beginning of the code snippet. When I delete the space generated by org-indent-buffer manually, the converted markdown file will treat the code snippet as an equation.

**Comment by kaushalmodi** [comment]
Yes, thank you, understand the problem. I though need to yet replicate it and debug. 

I've never used `org-indent-buffer` as I prevent having indentation white space. Instead I use `org-indent-mode`, which shows the indentation in the display, but doesn't actually insert the actual spaces in the file. 

I'll tag this as bug as soon as I recreate the problem, and then work on the fix.

**Comment by emacsun** [comment]
Bye the way, I found that if you use both `org-indent-mode` and `fci-mode` , there will be an ugly vertical line at the `fill-column` position of you screen.

**Comment by kaushalmodi** [comment]
I wouldn't be surprised :). I stopped using `fci-mode` a long time back because I found it to be very buggy, and had to keep on adding hacks to make it work as I want. Also I found it useful only in prog modes. For Org mode, I simply enable auto-fill-mode.

**Comment by kaushalmodi** [comment]
Marking this as an enhancement because there doesn't seem to be a consensus in the inbuilt exporters if that indentation should be kept or removed:

- `ox-html` retains it. So if you export using C-c C-e h h, you will see the indented equation block verbatim.
- `ox-md` and `ox-ascii` remove that indentation.

As removing the indentation feels the right thing to do, I'll now do the same in `ox-hugo` too, when parsing latex environments.

**Comment by kaushalmodi** [comment]
@emacsun Let me know how this fix works for you. If using melpa, you should get that update in about 2-3 hours.

Test case: https://ox-hugo.scripter.co/test/posts/indented-equations/
