### ISSUE TITLE
Gopher links don't work

### ISSUE THREAD

**Issue by eadmund** [kaushalmodi/ox-hugo#132]
When trying to export an article which includes the text `[[gopher://GOPHERSITE/][some text]]`, I get the error `Unable to resolve link: "gopher://GOPHERSITE/"`.  [RFC 4266](https://tools.ietf.org/html/rfc4266) indicates that this is a legitimate Gopher URL.

(I'm converting an historical blog with lots of old links …)

**Comment by kaushalmodi** [comment]
Can you provide a MWE? I am not aware of gopher protocol. 

- How does it look in Org?
- What should it look like in Markdown (or HTML)?

**Comment by eadmund** [comment]
Gopher was a very old precursor to the web.  Very rarely supported anymore, but there are a few folks still running it (rather surprisingly). Gopher URLs are still real URLs, though, even if a modern web browser doesn't resolve them (a little like [`telnet:`](https://tools.ietf.org/html/rfc4248) or [`news:`](https://tools.ietf.org/html/rfc5538) URLs).

It's just another URL scheme, so `[[gopher://foo.example/][a Gopher site]]` in Org should turn into `[a Gopher site](gopher://foo.example/)` in Markdown and `<a href="gopher://foo.example/">a Gopher site</a>` in HTML.

There's probably a piece of logic trying to figure out if the link content is a URL; it probably assumes that anything beginning with `http://` or `https://` is a URL; it just needs to be more liberal in what it accepts.  If it were _really_ clever, it'd actually use the full URL EBNF language, but that might be more trouble than it's worth.

**Comment by kaushalmodi** [comment]
Yes, the fix for specifically this one should be an easy fix; I'll just add gopher to the list of valid protocols. I believe that the inbuilt exporters (html, md, etc.) should also fail the same way (I could be wrong) because I don't remember seeing gopher anywhere in the source code.

**Comment by kaushalmodi** [comment]
This turned out to be a bit more involved. Something needs to be fixed in Org source.. I yet need to figure out what exactly [[Ref][1]].

[1]: http://lists.gnu.org/r/emacs-orgmode/2018-02/msg00074.html

**Comment by kaushalmodi** [comment]
@eadmund Nicolas on the Org mailing list was very prompt with the reply. Do you want to try adding `gopher` by customizing `org-link-parameters` in your emacs config? Just copy the `"https"` element, and replace `https` with `gopher`. I haven't tried, but things should "just work" then.

**Comment by kaushalmodi** [comment]
@eadmund I've have verified this to work.

```el
(with-eval-after-load 'org
  (defun org-link-gopher-export-link (link desc format)
    "Create export version of LINK and DESC to FORMAT."
    (let ((link (concat "gopher:" link)))
      (cond
       ((eq format 'html)
        (format "<a href=\"%s\">%s</a>" link desc))
       ((eq format 'latex)
        (format "\\href{%s}{%s}" link desc))
       (t                               ;`ascii', `md', `hugo', etc.
        (format "[%s](%s)" desc link)))))
  (org-link-set-parameters "gopher" :export #'org-link-gopher-export-link))
```

As this issue was not related to `ox-hugo', I'll also close this.
