### ISSUE TITLE
LaTeX \\ and \| in ox-blackfriday

### ISSUE THREAD

**Issue by benide** [kaushalmodi/ox-hugo#138]
`\\` should be exported as `\\\\\\`. You can see the problem on line 5021 of `ox-hugo/test/site/content-org/all-posts.org` and how it's exported in equation 1 on https://ox-hugo.scripter.co/test/real-examples/nn-intro/

`\|` should be exported as `\\|`. See line 4830 of `ox-hugo/test/site/content-org/all-posts.org`

I'm absolutely loving ox-hugo! Thanks for all of your hard work!

**Comment by kaushalmodi** [comment]
@benide Thank you for the bug report with suggested fixes too.

Blackfriday has a bug that it doesn't understand if certain part of text is inside LaTeX equation or environment. So we need to escape everything!

> `\|` should be exported as `\\|`

I would have never figured that one out; I don't use LaTeX equations, so TIL that `\|` should render as parallel pipes :)

> I'm absolutely loving ox-hugo! Thanks for all of your hard work!

Glad to hear!

---

Here's the new test that verifies this fix: https://ox-hugo.scripter.co/test/posts/equations-bf-escaping/
