### ISSUE TITLE
package-compute-transaction: Package ‘org-9.0’ is unavailable

### ISSUE THREAD

**Issue by casouri** [kaushalmodi/ox-hugo#144]
When I type `M-x package-install RET ox-hugo RET`
above error appears and prevents me from installing ox-hugo.

My org version is 9.1.4.

**Comment by kaushalmodi** [comment]
Can you try this from fresh emacs session (quit and restart emacs):

- Ensure that Melpa **and** [Org Elpa][1] is added to your `package-archives`.
- `M-x package-list-packages`.
- Search for `ox-hugo`, and once the point is on that row, hit `i` and then `x`.

[1]: https://orgmode.org/elpa.html

**Comment by casouri** [comment]
It's because org-elpa wasn't properly configured. 
Thanks 😄
