### ISSUE TITLE
Support forcing line break with "\\" at EOL

### ISSUE THREAD

**Issue by vinursme** [kaushalmodi/ox-hugo#147]
In orgmode, I can enforce a line break within a paragraph, use ‘\\\\’ at the end of a line.but, i use it within ox-hugo, but it seems doesn't use a line break.

**Comment by kaushalmodi** [comment]
> a line break within a paragraph, use ‘\’ at the end of a line

Only the latex/pdf backend supports that.

For ox-hugo (also ox-md, ox-html, etc.), you can force a line break using something like:

```
foo <br />
bar
```

Does that help?

**Comment by kaushalmodi** [comment]
@vinursme To gage the necessity of that feature.. how often do you need to force a line break like that? Would the `<br />` solution work?

**Comment by vinursme** [comment]
@kaushalmodi yes, thanks very much, u can implement this later, i just feel that  use <br /> is not perfect in orgmode file, thanks for ur help.

**Comment by kaushalmodi** [comment]
This feature is now implemented; [test][1].

[1]: https://ox-hugo.scripter.co/test/posts/force-line-break/
