### ISSUE TITLE
Mailto links don't export properly

### ISSUE THREAD

**Issue by siddharthshekar** [kaushalmodi/ox-hugo#149]
Thanks for the great work on this project! Mailto links in org-mode don't seem to export properly. The following org-mode snippet: `[[mailto:abc@xyz.com][def]]` exports to `[def](abc@xyz.com)`. The correct export code should be `[def](mailto:abc@xyz.com)`.

**Comment by kaushalmodi** [comment]
Hi Siddharth,

Thanks for opening this issue.. the `mailto:` protocol support got ignored as I never used that. It's now added, and here the [test][1] for that.

[1]: https://ox-hugo.scripter.co/test/posts/external-links/#mailto-link-support

**Comment by siddharthshekar** [comment]
Thanks for the quick fix!
