### ISSUE TITLE
[feature request] handling of remote image links

### ISSUE THREAD

**Issue by digizeph** [kaushalmodi/ox-hugo#150]
First, I'd like to thank you for this awesome project!

I have a blog, and I'd like to gradually migrating it to an org files. The problem I have is that I have posts that contains images hosted on imgur, and I couldn't find out a way to export to markdown with the style like `![title](link)`, which will render as inline images.

I'd like to see if this could be added. I can also work on a PR if you think this feature requires more work.

Thanks!

**Comment by kaushalmodi** [comment]
Hello,

Looks like you figured out why it wasn't working for you, and so you closed this issue? :)

In any case, `ox-hugo` supports `![title](link)` type inline inline links.. For anyone else who comes across this thread, I also have tested for those:

- [Org][1] | [Markdown][2] | [HTML][3]

[1]: https://github.com/kaushalmodi/ox-hugo/blame/21a479f5ad7fda38584e97c44b5e4ac08293746d/test/site/content-org/all-posts.org#L130-L164
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/inline-images.md
[3]: https://ox-hugo.scripter.co/test/posts/inline-images/

**Comment by digizeph** [comment]
Hey, thanks for the reply! I found out that for my purpose (just insert a remote image as inline image, alt-text doesn't matter), I could just through in the image link as plain text. It will generate something like this `{{< figure src="IMGUR_LINK" >}}`.

**Comment by kaushalmodi** [comment]
> I found out that for my purpose (just insert a remote image as inline image, alt-text doesn't matter)

Just to get the terms right, the `figure` shortcode gets inserted only if the image is NOT inlined..

See the below examples (both are taken from the Org and Markdown example links in my previous comment):

### Not Inline

Below Org image link lies in its own Org paragraph.

```
[[/images/org-mode-unicorn-logo.png]]
```

That gets exported to Markdown as:

```md
{{< figure src="/images/org-mode-unicorn-logo.png" >}}
```

### Inline

Below image link is in the same Org paragraph as the preceding text.. so it gets inlined.

```
This is an inline non-hyperlinked image without alt text or other
attributes: [[/images/org-mode-unicorn-logo.png]].
```

This exports as:

```md
This is an inline non-hyperlinked image without alt text or other
attributes: ![](/images/org-mode-unicorn-logo.png).
```
