### ISSUE TITLE
Summary splitter (more comment) at end of post content (file or subtree) causes error

### ISSUE THREAD

**Issue by zzamboni** [kaushalmodi/ox-hugo#152]
First of all, I'd like to say THANK YOU for ox-hugo - it has revolutionized how I maintain my Hugo-powered website using org-mode.

I have found a strange behavior in what should be a very uncommon corner case, but here it is anyway: if a post contains a `<!--more-->` tag as its last line, upon export I get the prompt `Buffer test.md modified; kill anyway?`, and then no matter what I respond, I get the error `markdown-syntax-propertize-comments: Wrong type argument: integer-or-marker-p, nil`, and the file is not exported.

**Very easy workaround**: adding some text after the `<!--more-->` line, even if it's just a `\nbsp`, then the export works fine (this is why I think this is an uncommon corner case, in regular use this shouldn't happen).

Here's a short file which reproduces the problem:

```
#+hugo_base_dir: ../

* DONE Test post
CLOSED: [2018-04-05 Thu 14:33]
:PROPERTIES:
:EXPORT_FILE_NAME: test
:END:

Here is some test.

@@html:<!--more-->@@
```

In case you are curious: I came across this because I have a short page in which I want to have the `<!--more-->` tag to influence the generation of the post summary by Hugo (I cannot use the `:summary` custom front matter because in this case I want the summary to include some HTML generated by a custom Hugo shortcode, which would otherwise get stripped out).

Versions: Emacs 25.3.2, Org mode 9.1.8, ox-hugo 20180403.1111 from MELPA

**Comment by kaushalmodi** [comment]
> First of all, I'd like to say THANK YOU for ox-hugo - it has revolutionized how I maintain my Hugo-powered website using org-mode.

Thanks!

> no matter what I respond, I get the error markdown-syntax-propertize-comments: Wrong type argument: integer-or-marker-p, nil, and the file is not exported.

That sounds like a bug. Can you do `M-x toggle-debug-on-error`, then recreate that error. That should throw a backtrace, paste that here. Thanks.

I'll also try to reproduce the problem locally, but the backtrace will immensely help.

**Comment by kaushalmodi** [comment]
And to the question:

> How to insert  tag in a post?

You can simply do:

```
#+hugo: more
```

**Comment by zzamboni** [comment]
Thanks for the quick response! Here's the backtrace:
https://gist.github.com/zzamboni/d4cab2c2d26aa981a9094d60a0c0551e

Thanks for the tip about the `more` tag! Much cleaner that way. It still triggers the same error though :)

**Comment by kaushalmodi** [comment]
OK, I was able to reproduce this issue even with:

```
*** Summary Splitter at EOF                                             :eof:
:PROPERTIES:
:EXPORT_FILE_NAME: summary-splitter-at-eof
:END:
Here is the summary.
#+hugo: more
```

I'll take a look by the end of today.

**Comment by kaushalmodi** [comment]
Closing this issue as it's not related to `ox-hugo`, and it's being tracked in `markdown-mode` repo at https://github.com/jrblevin/markdown-mode/issues/327.
