### ISSUE TITLE
Escaping Javascript multiplications

### ISSUE THREAD

**Issue by amca01** [kaushalmodi/ox-hugo#154]
I'm exploring using the graphics package [JSXGraph](https://jsxgraph.uni-bayreuth.de/wp/index.html); I can do this by writing all the Javascript code inside a `<div>`, `</div>` block: see https://numbersandshapes.net/blog/post/exploring_jsxgraph/ for an example.

However, there is a problem with multiplication: code such as `2*x` will be turned into the corresponding md file as `2\*x`.  I can get round this by using `x/0.5` instead, but clearly I'd rather just use the multiplication symbol.  How can I prevent ox-hugo from turning a multiplication symbol `*` into `\*`?  Thank you!

**Comment by kaushalmodi** [comment]
Can you share the Org source?

This seems to be a tricky issue, but I'll try to tackle it. But I can understand this problem better once you give a sample of the Org source. 

The tricky part would be figuring out which part of the Org post should be escaped and which part should be not.

**Comment by amca01** [comment]
Here's a micro example:

    <div> 
    <script type="text/javascript">
    var a = 3;
    var b = 2*a;
    </script>
    </div>

After exporting this from my org file to a Hugo md file, the only thing that has changed is that the fourth line becomes

    var b = 2\*a;

Thanks for looking into this!

**Comment by kaushalmodi** [comment]
I haven't tried.. but can you wrap that in `#+begin_export html` and `#+end_export` (yes, `html`)?

**Comment by amca01** [comment]
Hey - that works!  Thank you!

**Comment by kaushalmodi** [comment]
Cool! Yes, it's impossible for the ox-hugo or ox-md exporter to know if a stray asterisk needs to be escaped or not. 

So the best way is to wrap it in those begin/end that tells Org that "Hey, export that portion using the HTML exporter.".
