### ISSUE TITLE
Need a bit of help with sections and pages

### ISSUE THREAD

**Issue by amca01** [kaushalmodi/ox-hugo#156]
I now have "basic" hugo and ox-hugo working nicely.  And I can write up and publish new posts with delightful ease - thanks to all the people who so kindly helped me.

But what I want to do now is to import all my old blog posts from my wordpress site into the hugo blog, but under a new section, called say: "Old Posts".  I can set up a menu item for this in my `config.toml` and indeed it shows up fine, but I don't seem to be able to populate this page with the posts I want.

Here's my experiment so far:

```
* Old Posts
  :PROPERTIES:
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nocomment true :nodate true :nopaging true :noread true
  :EXPORT_HUGO_SECTION: oldposts
  :EXPORT_HUGO_WEIGHT: auto
  :END:
** Old Posts
  :PROPERTIES:
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nocomment true :nodate true :nopaging true :noread true
  :EXPORT_FILE_MENU: :menu "main"
  :EXPORT_FILE_NAME: _index
  :EXPORT_HUGO_WEIGHT: auto
  :END:
My old blog, exported from Wordpress
** Post 1
  :PROPERTIES:
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nocomment true :nodate true :nopaging true :noread true
  :EXPORT_FILE_NAME: post_1
  :EXPORT_HUGO_WEIGHT: auto
  :END:
Just to see how it works
** Post 2
  :PROPERTIES:
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nocomment true :nodate true :nopaging true :noread true
  :EXPORT_FILE_NAME: post_2
  :EXPORT_HUGO_WEIGHT: auto
  :END:
and another one, for experiment.
```
My `config.toml` contains:

```
[[menu.main]]
	name = "Old Posts"
	pre = "<i class='fa fa-wordpress fa-fw'></i>"
	weight = 7
	identifier = "oldposts"
	url = "/oldposts/"
```
Clearly something is not quite right: all the material is exported, but none of it shows in the browser: `localhost:1313/oldposts/` is a blank page.  If anybody is able to, at a glance, tell me what I'm doing wrong, I'd be very happy!  Thanks very much.

**Comment by kaushalmodi** [comment]
> all the material is exported, but none of it shows in the browser: localhost:1313/oldposts/ is a blank page.

If everything is getting exported, then that's what `ox-hugo`'s job is limited to.

The issue could be related to your theme. But it's difficult to say that for sure. The best way would be to share the site source. Can you commit the above changes including the generated markdown files to a branch in your repo and share that (including the theme, etc. so that I can reproduce the issue locally)?

**Comment by amca01** [comment]
Thanks as always!  I've pushed everything to the github site https://github.com/amca01/whats_this But as you say it might be a theme issue (Blackburn)... I'll check that out too.  However, if this is a Hugo and not an ox-hugo issue, please don't waste your time: just close off this thread.

**Comment by amca01** [comment]
No - it was a theme issue.  Somebody had already raised this issue in the github page of the theme, so I followed the advice there.  Sorry for wasting your time!

Consider this issue closed.

**Comment by kaushalmodi** [comment]
Thanks for the update. Yes, as long as the Markdown is getting created with the content and front-matter you expect, `ox-hugo` is good. 

> Sorry for wasting your time!

No problem.
