### ISSUE TITLE
Handle #+RESULTS

### ISSUE THREAD

**Issue by eadmund** [kaushalmodi/ox-hugo#158]
E.g.:

    #+RESULTS:
    : foo
    : bar

Right now this is just ignored entirely.

**Comment by kaushalmodi** [comment]
I'm pretty confident, that those export :)

- [Org][1] | [Markdown][2] | [HTML][3]

Can you provide a complete Org file that shows the issue? You are probably not exporting the results by default? In the above example, I have `:exports both` in the default header args. 

See [Org Manual: Exporting code blocks][4] for more info.


[1]: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/raw/master/content-org/notes/string-fns-nim-vs-python.org
[2]: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/raw/master/content/notes/string-fns-nim-vs-python.md
[3]: https://scripter.co/notes/string-fns-nim-vs-python/
[4]: https://orgmode.org/manual/Exporting-code-blocks.html

**Comment by eadmund** [comment]
I _believe_ that's different. `:exports both` or `:exports both` actually _runs_ the code in the block at export time; a `#+RESULTS` block is created with `org-babel-execute-src-block`. I can't actually find documentation on the Org-babel site about what should be done with a `#+RESULTS` block, or if it's only there for a human editor of the org file to begin with.

    #+HUGO_BASE_DIR: .
    * Test
    :PROPERTIES:
    :EXPORT_FILE_NAME: test
    :EXPORT_DATE: 2018-04-29T21:14:47-0400
    :END:
    This is a test.
    
    #+BEGIN_SRC lisp
    (+ 1 2)
    #+END_SRC
    
    #+RESULTS:
    : 4

This will export a Markdown file with the following (note the actual result of the evaluation, rather than the value in the `#+RESULTS` block):

    +++
    title = "Test"
    author = ["Robert A. Uhl"]
    date = 2018-04-29T00:00:00-04:00
    draft = false
    +++
    
    This is a test.
    
    ```lisp
    (+ 1 2)
    ```
    
    ```text
    3
    ```

**Comment by kaushalmodi** [comment]
> :exports both or :exports both actually runs the code in the block at export time;

You can prevent that by adding `:eval no` (to never evaluate those src blocks) or `:eval never-export` (to not evaluate those only during exports).

> This will export a Markdown file with the following (note the actual result of the evaluation, rather than the value in the #+RESULTS block):

That's correct; it's the default behavior, and not something that `ox-hugo` controls. `ox-hugo` just controls the "presentation" of those results blocks i.e. wraps them in ` ```text .. ``` `.

**Comment by eadmund** [comment]
Well, nuts — and I _did_ even read the docs! Learn something new every day. Sorry about that.

**Comment by kaushalmodi** [comment]
No problem. Glad I could help. Publishing src blocks and their results is one of the many reasons why I got started on `ox-hugo`. I like taking "literate programming" notes. With time, they will all end up here: https://scripter.co/notes/ :)
