### ISSUE TITLE
Wrapping various headlines in a <div> or <section>

### ISSUE THREAD

**Issue by rolojf** [kaushalmodi/ox-hugo#160]
Turns out that:
>+begin_section
> **` My important heading 
>text` text
>** Another heading
>some other text like lorem...
>-end_section

It doesn't work.  as far as I know. In the manual of org-mode we can read:

> 12.9.3 ... Special blocks cannot have headlines.  For the HTML exporter to wrap the headline and
its contents in '<section> ’ or '<article>’ tags, set the HTML_CONTAINER property for the headline.

Besides exporting directly html code with @@ or other form, how can I wrap these headlines in one div or section?

**Comment by kaushalmodi** [comment]
Hello,

Yes, that's as per the spec of how Org Special blocks work as you found out. 

The only way that *can probably* work right away is:

```
#+html: <section>
#+html: <section></section>

** My important heading text text
** Another heading
some other text like lorem...

#+html: </section>
```

- The empty section inserted above is a hack for Blackfriday. The exported HTML will still have that empty section, but the whole thing should render fine in the browser. 

I haven't checked if this works. Let me know if it does. 

Thanks.

**Comment by rolojf** [comment]
It worked. 

Tried different things. I will stick with this (it worked):

> #+html: <p><section></p>

Less typing is better.

Thanks

**Comment by kaushalmodi** [comment]
@rolojf Glad that you got this working. I have added a test case for this, just in case..

- [Org][1] | [Markdown][2] | [HTML][3]

[1]: https://github.com/kaushalmodi/ox-hugo/blame/58a4aef012f195ed56ef5edf5b8e749c834d7dc9/test/site/content-org/all-posts.org#L2007-L2053
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/wrapping-org-headings-in-html-tags.md
[3]: https://ox-hugo.scripter.co/test/posts/wrapping-org-headings-in-html-tags/
