### ISSUE TITLE
Add support for Org coderef

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#162]
https://orgmode.org/manual/Literal-Examples.html

---

From https://github.com/kaushalmodi/ox-hugo/issues/343#issue-594399355:

In HTML, hovering the mouse over such a link`[[(sc)]]` remote-highlights the corresponding code line

### Example Org File

```org
#+BEGIN_SRC emacs-lisp -n -r
  (save-excursion                 (ref:sc)
     (goto-char (point-min))      (ref:jump)
#+END_SRC
```
In line `[[(sc)]]` we remember the current position. `[[(jump)][Line (jump)]]`
jumps to point-min.

---

Code snippet form `ox-html` -> `org-html-do-format-code`:

```el
     (lambda (loc line-num ref)
       (setq loc
	     (concat
	      ;; Add line number, if needed.
	      (when num-start
		(format "<span class=\"linenr\">%s</span>"
			(format num-fmt line-num)))
	      ;; Transcoded src line.
	      (if wrap-lines
		  (format "<code%s>%s</code>"
			  (if num-start
                              (format " data-ox-html-linenr=\"%s\"" line-num)
                            "")
			  loc)
		loc)
	      ;; Add label, if needed.
	      (when (and ref retain-labels) (format " (%s)" ref))))
       ;; Mark transcoded line as an anchor, if needed.
       (if (not ref) loc
	 (format "<span id=\"coderef-%s\" class=\"coderef-off\">%s</span>"
		 ref loc)))
```

---

Code snippet from `ox-html` -> `org-html-link`:

```el
     ;; Coderef: replace link with the reference name or the
     ;; equivalent line number.
     ((string= type "coderef")
      (let ((fragment (concat "coderef-" (org-html-encode-plain-text path))))
	(format "<a href=\"#%s\" %s%s>%s</a>"
		fragment
		(format "class=\"coderef\" onmouseover=\"CodeHighlightOn(this, \
'%s');\" onmouseout=\"CodeHighlightOff(this, '%s');\""
			fragment fragment)
		attributes
		(format (org-export-get-coderef-format path desc)
			(org-export-resolve-coderef path info)))))
```

**Comment by kaushalmodi** [comment]
This can probably be implemented once https://github.com/alecthomas/chroma/issues/132 is resolved (hopefully with https://github.com/alecthomas/chroma/pull/203).

**Comment by staticaland** [comment]
https://gohugo.io/content-management/syntax-highlighting/#highlight-shortcode mentions `anchorlinenos` and `lineanchors`, so maybe this is a possibility now.

See https://github.com/gohugoio/hugo/issues/7622 and https://github.com/gohugoio/hugo/pull/7674/files

**Comment by kaushalmodi** [comment]
Note to self: Hugo v0.75.0 or newer will be needed for the `anchorlinenos` feature: https://github.com/gohugoio/hugo/commit/fb0f2cc718a54fd0774a0367e0a60718b5731de5

**Comment by kaushalmodi** [comment]
This will now export with code refs links once https://github.com/kaushalmodi/ox-hugo/pull/525 is merged:

```org
#+begin_src emacs-lisp 
(save-excursion                 (ref:sc)
   (goto-char (point-min))      (ref:jump)
#+end_src

In line [[(sc)]] we remember the current position. [[(jump)][Line (jump)]] jumps to
~point-min~.
```

**Comment by kaushalmodi** [comment]
- Update in the manual: https://ox-hugo.scripter.co/doc/source-blocks/#code-references
- Test case: https://ox-hugo.scripter.co/test/posts/coderef/
