### ISSUE TITLE
allow a null hugo-section value for _index.md homepage?

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#164]
Hugo allows [a special sectionless "home page"](https://gohugo.io/templates/homepage/#add-content-and-front-matter-to-the-homepage) to be created as `content/_index.md`.  Is it currently possible to export to this page using ox-hugo? Right now it looks to me as though ox-hugo will error out if the section is set to nil, which would have to happen (the post would also need to be titled "_index", I think)

Thanks for all your work on this over the last year or so, Kaushall -- I'm excited to get familiar with all of your recent improvements.

**Comment by kaushalmodi** [comment]
> Hugo allows a special sectionless "home page" to be created as content/_index.md. Is it currently possible to export to this page using ox-hugo? 

Yes!! :)

> Right now it looks to me as though ox-hugo will error out if the section is set to nil, which would have to happen (the post would also need to be titled "_index", I think)

Try this:

```org
* My home page
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:EXPORT_HUGO_BUNDLE: /
:EXPORT_FILE_NAME: _index
:END:
```

I actually have a [test case for this][1], which exports to [this][2].


> Thanks for all your work on this over the last year or so, Kaushall -- I'm excited to get familiar with all of your recent improvements.

Awesome! Looking forward to bug reports! :D

[1]: https://gitlab.com/kaushalmodi/hugo-sandbox/blob/7f19da52b8cc6a0d18411edfb39dd39cef5cbdbc/content-org/sandbox.org#L117-122
[2]: https://hugo-sandbox.netlify.com/

**Comment by kaushalmodi** [comment]
I just tested that empty sections behave the same way too (added new tests for that).

So this will work the same way:

**Comment by kaushalmodi** [comment]
@titaniumbones Feel free to reopen this issue if I misunderstood and the above suggested solution didn't work for you, and definitely please do that if any Org syntax causes ox-hugo export to generate an error back-trace.
