### ISSUE TITLE
Special handling of timestamps (dates) in text

### ISSUE THREAD

**Issue by dschrempf** [kaushalmodi/ox-hugo#168]
Hi,

I wanted to thank you very much for working on this project.

I have a short question. Sometimes I use timestamps in the text (in the blog entry and not the front matter), e.g., to document when I did what. With classical Org Mode HTML export, I used a style sheet to properly style these timestamps but I cannot find a canonical way to do that with `ox-hugo`. Did I just miss how this can be done, or is it not yet possible? It would be enough to wrap the timestamp into a HTML class or something, but I don't know if this is possible with `blackfriday`...

Thanks for your help,
Dominik

Edit: I just saw that the timestamps are actually wrapped in `timestamp-wrapper`, so this question is probably obsolete, thanks!

**Comment by kaushalmodi** [comment]
@dschrempf btw, if you have the Org source of your site public somewhere, you can add yourself [here via a PR][1], or just send me the links to your Org source and website.

[1]: https://ox-hugo.scripter.co/doc/examples/
