### ISSUE TITLE
Better support for html attributes

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#17]
We will often want to add classes and other HTML attributes to HTML nodes like images and possibly headlines, etc, using the org `:HTML_*:` syntax.  Some markdown parsers like `kramdown` support this, but `blackfriday` does not.  One workaround would be to call out to the ox-html exporter whenever an HTML attriute is detected in an org element.  THis seems kind of arduous.  Another, very partial, solution would be to support the standard Hugo figure shortcode, which supports several attributes.  There might also be a better, more general solution I haven't figured out.  

There's some discussion of this on Github: 
- https://github.com/russross/blackfriday/issues/364
- https://github.com/russross/blackfriday/issues/218

**Comment by titaniumbones** [comment]
Another, more difficult option would be to export directly to mmark, which supports a much broader set of markup.  We'd have to write a much more extensive exporter, though (and since mmark is an extension of blackfriday, we'd have a VERY long backend derivation chain: `html --> md --> blackfriday --> mmark --> hugo` !). Not bothering iwth this for now but the ability to use atytributes, **especially** classes, would make the exporter much more powerful.

**Comment by titaniumbones** [comment]
mmark syntax document: https://github.com/miekg/mmark/wiki/Syntax

**Comment by kaushalmodi** [comment]
I haven't yet come across `mmark` in my documentation and blogging. Opening another issue to track support for that ( https://github.com/kaushalmodi/ox-hugo/issues/18 ).

**Comment by kaushalmodi** [comment]
> We will often want to add classes and other HTML attributes to HTML nodes like images and possibly headlines, etc, using the org :HTML_*: syntax.

Let's start adding files to the `tests/org` and `tests/md-golden` directories. We will figure out later how to do the auto-checking. But for now, we can treat this as "spec-generation" for this project :)

So if `tests/org/foo.org` should export to `tests/md-golden/foo/title1.md` and `tests/md-golden/foo/title2.md` (you can completely hand-code or tweak that `foo.md`), check those three files in.

I hope that makes sense.

**Comment by titaniumbones** [comment]
What do you think we should do with a snippet like this:

```org-mode
#+ATTR_HTML: :class inset
[[file:Images/wpid-future-history-small.jpg]]
Why we should write history, why everyone should do it, and why that means we need the Web.  Hacker cultures, collaborative learning, knowledge sharing, non-expert culture. And a few words about the world's third-tallest mountain.  
```
I personally have a lot of legacy code like this -- at present I export to wordpress and use the assigned classes to control behaviour of exported images in a wordpress theme.  I would like to be able to do something similar in Hugo.  

The easiest option I see is to add a check for HTML attribute lines in the exporter, and any such values are non-nil, to use the relevant `org-html` function instead of the `org-md` function.  Then as we learn more about Hugo and Blackfriday, we can chip away at the HTML bits over time.

Downside is we would likely have to write a lot of repetitive code in `ox-hugo` since html attributes can be present in many kinds of element.s

**Comment by kaushalmodi** [comment]
> What do you think we should do with a snippet like this:
>
>     #+ATTR_HTML: :class inset
>     [[file:Images/wpid-future-history-small.jpg]]
>
> I personally have a lot of legacy code like this -- at present I export to wordpress and use the assigned classes to control behaviour of exported images in a wordpress theme. I would like to be able to do something similar in Hugo.

I haven't yet needed to use `#+ATTR_HTML`, so I have no comments.

> The easiest option I see is to add a check for HTML attribute lines in the exporter, and any such values are non-nil, to use the relevant org-html function instead of the org-md function. 

That seems to make sense for now. It looks like a big undertaking.

> Then as we learn more about Hugo and Blackfriday, we can chip away at the HTML bits over time.

Yes

**Comment by kaushalmodi** [comment]
Looking at this, it might even be easier to support shortcodes by simply wrapping them in 

```
#+BEGIN_EXPORT md
< .. >
#+END_EXPORT
```

( https://github.com/kaushalmodi/ox-hugo/issues/4 )

**Comment by titaniumbones** [comment]
hmm. I'm not sure that's the best solution. As I see the problem, it's "what's the greatest extent to which we can support the full range of org-mode features in an exported Hugo document?"  HTML class attributes are a significant piece of the org toolkit, and they're supported e.g. by the unofficial wordpress exporter. So I think we should try to support the natural org syntax for as many features as possible, in a way that is compatible with other html-based exporters like ox-reveal and org2blog (those are the ones I used in the past, but of course there are others).  

As I see it, the point is that the original document should be as org-y as possible, and it should be trivial to port a site from hugo to (say) jekyll or something else. I think adding big chunks of `md` code through a document makes that harder.

**Comment by kaushalmodi** [comment]
> the point is that the original document should be as org-y as possible

That's my aim too. Thanks for pushing to work towards that. So let's take the "plan b" to use shortcodes in "md" export blocks completely off the table.

**Comment by titaniumbones** [comment]
here's an initial attempt to do a very dumb check for `:html_attr` and, if it's non-nil, send the link back to html for processing (instead of producing md output). 

I also try to copy image files and rewrite image file names to the site root `/static/images/etc`. However, org-html-link will rewrite these links as `file:///static/images/etc` (line 2943 of my somewhat dated `ox-html.el`). I'm not sure what to do about this. Basically, this seems like a bad idea for org to be doing, but we can't touch that code. We could include the whole long function as something like `org-hugo-htmlize-link` in `ox-hugo.el`, modify it lightly, and call out to it, but that seems messy and a maintenance nightmare.  ideas?

here is my ugly ufnction, with osme repetitive bits that should be cleaned up:

```emacs-lisp
(defun org-hugo-link (link contents info)
  "Convert LINK to Markdown format.

CONTENTS is the link's description.
INFO is a plist used as a communication channel.

Unlike `org-md-link', this function will also copy local images
and rewrite link paths to make blogging more seamless."
  (let* ((link-org-files-as-md
	 (lambda (raw-path)
           ;; Treat links to `file.org' as links to `file.md'.
           (if (string= ".org" (downcase (file-name-extension raw-path ".")))
               (concat (file-name-sans-extension raw-path) ".md")
             raw-path)))
	(type (org-element-property :type link))
        (parent (org-export-get-parent link))
        (attr (org-export-read-attribute :attr_html parent)))
    (message "[ox-hugo DBG] link filename is : %s" (expand-file-name (plist-get (car (cdr link)) :path)))
    (message "[ox-hugo DBG] link type is %s" type)
    ;;(message "[ox-hugo DBG] modified link is %s " (org-element-put-property link :path "hello" ))
    ;;(message "[ox-hugo DBG] link path is %s" (plist-get (car (cdr  link)) :path))
    (message "[ox-hugo DBG] attribute is:  %s" (org-export-read-attribute :attr_html parent))
    (if attr
        (if (string= type "file")
            (org-html-link
             (org-element-put-property link :path
                                       (org-hugo--attachment-rewrite
                                        (org-element-property :path link) info))
             contents info)
          (org-html-link link contents info))
      (cond
       ;; Link type is handled by a special function.
       ((org-export-custom-protocol-maybe link contents 'md))
       ((member type '("custom-id" "id" "fuzzy"))
        (let ((destination (if (string= type "fuzzy")
                               (org-export-resolve-fuzzy-link link info)
                             (org-export-resolve-id-link link info))))
	  (pcase (org-element-type destination)
            (`plain-text			;External file
             (let ((path (funcall link-org-files-as-md destination)))
               (if (not contents) (format "<%s>" path)
                 (format "[%s](%s)" contents path))))
            (`headline
             (format
              "[%s](#%s)"
              ;; Description
              (cond ((org-string-nw-p contents))
                    ((org-export-numbered-headline-p destination info)
                     (mapconcat #'number-to-string
                                (org-export-get-headline-number destination info)
                                "."))
                    (t (org-export-data (org-element-property :title destination)
                                        info)))
              ;; Reference
              (or (org-element-property :CUSTOM_ID destination)
		  (org-export-get-reference destination info))))
            (_
             (let ((description
                    (or (org-string-nw-p contents)
                        (let ((number (org-export-get-ordinal destination info)))
			  (cond
			   ((not number) nil)
			   ((atom number) (number-to-string number))
			   (t (mapconcat #'number-to-string number ".")))))))
               (when description
                 (format "[%s](#%s)"
                         description
                         (org-export-get-reference destination info))))))))
       ((org-export-inline-image-p link org-html-inline-image-rules)
        (message "org-hugo-link processing an image %s" contents)

        (let ((path (org-hugo--attachment-rewrite
                     (let ((raw-path (org-element-property :path link)))
                       (if (not (file-name-absolute-p raw-path)) raw-path
                         (expand-file-name raw-path)))
                     info))
              (caption (org-export-data
                        (org-export-get-caption
                         (org-export-get-parent-element link))
                        info)))
	  (format "![img](%s)"
		  (if (not (org-string-nw-p caption)) path
                    (format "%s \"%s\"" path caption)))))
       ((string= type "coderef")
        (let ((ref (org-element-property :path link)))
	  (format (org-export-get-coderef-format ref contents)
		  (org-export-resolve-coderef ref info))))
       ((equal type "radio") contents)
       (t (let* ((raw-path (org-element-property :path link))
                 (path
		  (cond
		   ((member type '("http" "https" "ftp"))
                    (concat type ":" raw-path))
		   ((string= type "file")
                    (org-hugo--attachment-rewrite
                     (org-export-file-uri
                      (funcall link-org-files-as-md raw-path))
                     info))
		   (t raw-path)))
                 )
            (if (not contents) (format "<%s>" path)
              (format "[%s](%s)" contents path)
              )))))))
```

**Comment by titaniumbones** [comment]
ok, wait -- I'm sorry for the noise -- here is a much simpler change that only supports the hugo built-in figure shortcode, which supports a much smaller set of html attributes. What do you think? the change comes after `org-export-inline-image-p` in the code below:

```emacs-lisp
(defun org-hugo-link (link contents info)
  "Convert LINK to Markdown format.

CONTENTS is the link's description.
INFO is a plist used as a communication channel.

Unlike `org-md-link', this function will also copy local images
and rewrite link paths to make blogging more seamless."
  (let ((link-org-files-as-md
	 (lambda (raw-path)
           ;; Treat links to `file.org' as links to `file.md'.
           (if (string= ".org" (downcase (file-name-extension raw-path ".")))
               (concat (file-name-sans-extension raw-path) ".md")
             raw-path)))
	(type (org-element-property :type link)))
    (message "[ox-hugo DBG] link filename is : %s" (expand-file-name (plist-get (car (cdr link)) :path)))
    (message "[ox-hugo DBG] link type is %s" type)
    (message "[ox-hugo DBG] link ")
    (cond
     ;; Link type is handled by a special function.
     ((org-export-custom-protocol-maybe link contents 'md))
     ((member type '("custom-id" "id" "fuzzy"))
      (let ((destination (if (string= type "fuzzy")
                             (org-export-resolve-fuzzy-link link info)
                           (org-export-resolve-id-link link info))))
	(pcase (org-element-type destination)
          (`plain-text			;External file
           (let ((path (funcall link-org-files-as-md destination)))
             (if (not contents) (format "<%s>" path)
               (format "[%s](%s)" contents path))))
          (`headline
           (format
            "[%s](#%s)"
            ;; Description
            (cond ((org-string-nw-p contents))
                  ((org-export-numbered-headline-p destination info)
                   (mapconcat #'number-to-string
                              (org-export-get-headline-number destination info)
                              "."))
                  (t (org-export-data (org-element-property :title destination)
                                      info)))
            ;; Reference
            (or (org-element-property :CUSTOM_ID destination)
		(org-export-get-reference destination info))))
          (_
           (let ((description
                  (or (org-string-nw-p contents)
                      (let ((number (org-export-get-ordinal destination info)))
			(cond
			 ((not number) nil)
			 ((atom number) (number-to-string number))
			 (t (mapconcat #'number-to-string number ".")))))))
             (when description
               (format "[%s](#%s)"
                       description
                       (org-export-get-reference destination info))))))))
     ((org-export-inline-image-p link org-html-inline-image-rules)
      (message "org-hugo-link processing an image %s" contents)

      (let* ((path (org-hugo--attachment-rewrite
                   (let ((raw-path (org-element-property :path link)))
                     (if (not (file-name-absolute-p raw-path)) raw-path
                       (expand-file-name raw-path)))
                   info))
            (caption (org-export-data
                      (org-export-get-caption
                       (org-export-get-parent-element link))
                      info))
            (parent (org-export-get-parent link))
            (attr (org-export-read-attribute :attr_html parent))
            (class (plist-get attr :class)))
	(format "{{figure src=\"%s\" caption=\"%s\" class=\"%s\"}}"
                path caption class
		)))
     ((string= type "coderef")
      (let ((ref (org-element-property :path link)))
	(format (org-export-get-coderef-format ref contents)
		(org-export-resolve-coderef ref info))))
     ((equal type "radio") contents)
     (t (let* ((raw-path (org-element-property :path link))
               (path
		(cond
		 ((member type '("http" "https" "ftp"))
                  (concat type ":" raw-path))
		 ((string= type "file")
                  (org-hugo--attachment-rewrite
                   (org-export-file-uri
                    (funcall link-org-files-as-md raw-path))
                   info))
		 (t raw-path))))
          (if (not contents) (format "<%s>" path)
            (format "[%s](%s)" contents path)))))))
```

**Comment by kaushalmodi** [comment]
> ok, wait -- I'm sorry for the noise 

No need to be sorry, the SNR (signal to noise ratio is good :))

> -- here is a much simpler change that only supports the hugo built-in figure shortcode, which supports a much smaller set of html attributes. What do you think? 

It's an elegant solution. I have merged it and also updated the example site. Please have a look.

Thank you.

**Comment by kaushalmodi** [comment]
@titaniumbones You have already added support for supporting `ATTR_HTML` to specify the class for inserted images.

What this issue mainly for that? If so, this issue can be closed.

If not, we need more details on what else needs to be supported.

**Comment by titaniumbones** [comment]
WHen I use `ATTR_HTML`, it's almost always for images. So my use case is mostly covered. But I wonder if we should try to support it wherever org uses it? 

I'd add the enhancement or wishlist labels to the issue if we keep it. And I can rewrite the issue text to make it clearer.

**Comment by kaushalmodi** [comment]
> But I wonder if we should try to support it wherever org uses it?

I have never user `ATTR_HTML`. So let's see what kind of support requests turn up.

**Comment by kaushalmodi** [comment]
Now all parameters of the Hugo figure shortcode are supported. I believe this issue can be closed now.
