### ISSUE TITLE
citations with pandoc/pandoc-citeproc

### ISSUE THREAD

**Issue by mclearc** [kaushalmodi/ox-hugo#175]
Great package - thanks for all your work! I was wondering if there is any way to get ox-hugo to leverage pandoc/pandoc-citeproc so that pandoc's use of [citations](http://pandoc.org/MANUAL.html#citations) and citation keys could be utilized? Ideally, it might involve something like an option to call pandoc-citeproc to convert citation keys in the subtree to full citations in the markdown. If I knew any elisp I would help, but unfortunately....

**Comment by kaushalmodi** [comment]
Hello!

I haven't used pandoc, but I am not familiar with the citations stuff. 

This is probably out of the scope of ox-hugo, but let's see if we can find a solution to this. 

- What does a pandoc citation look like in Org mode?
- How do you expect it to eventually convert to in Markdown? Note that the end product of ox-hugo is Markdown format **that Hugo/Blackfriday can parse**.

It's possible that there are some Elisp packages out there that do the pandoc citation parsing you want.. I would guess that `ox-pandoc` probably does this. So let's find out if that's the case.

If that's the case, I can probably add a hook in ox-hugo that you can customize to call that pandoc processing function. 

I am also copying @kawabata, the author of [`ox-pandoc`][1], to see if they can provide some insight here. 

There are lots of "if"s and unknowns involved.. let's see where we get :)

[1]: https://github.com/kawabata/ox-pandoc

**Comment by mclearc** [comment]
Thanks - citations look like this `[@citekey1; @citekey2]`. `ox-pandoc` would certainly be able to parse the citations, so a simple hook would be perfect.

**Comment by kaushalmodi** [comment]
@mclearc Sorry, but it's not yet clear to me. I'll need a comprehensive example in order to implement this and test it. That example will eventually make into the ox-hugo test suite. 

- Please paste a minimal Org file that contains that citation and should also export as a post. 
- You will also probably need to define the citations somewhere.. (what is citekey1?, citekey2?)
- Assuming that ox-hugo successfully exports that Org file, what would the final Markdown file look like? (Include the whole valid Markdown file, including all the Hugo meta data)

**Comment by kaushalmodi** [comment]
Thanks for those examples. 

Unfortunately, supporting this seems to be a lot more involved. You can either use `ox-pandoc` or `ox-hugo` to generate the Markdown, but not both.

How the exporter works is that it passes each Org element through the user-specified exporter. So an Org bold element `*foo*` will become `**foo**` when passed through `ox-hugo`, `ox-md`, etc., but instead become `<b>foo</b>` when passed through `ox-html` exporter.

AFAIK, Org doesn't have a special element for syntax like `@loncar2016`. May be I just do search/replace of `@something` with the citation based on some internal function in `ox-pandoc`. But that sounds too risky, and I'd need to do some research on `ox-pandoc` + `pandoc`.

Also looks like you need support for `#+pandoc_*` options, so that adds yet another layer of complication.

I will leave this issue open hoping that someone using `ox-pandoc` + `ox-hugo` has a good idea on how to integrate this feature.

I have not used it myself, but have heard a lot about [`org-ref`][1], though it is currently broken for markdown exporter backends (https://github.com/jkitchin/org-ref/issues/558).

[1]: https://github.com/jkitchin/org-ref

**Comment by kaushalmodi** [comment]
For reference, here are the contents of that dropbox link:

## Org

```org
#+TITLE: Org Pandoc Citation Test Example
#+DATE: July 14, 2018
#+OPTIONS: author:nil
#+BIBLIOGRAPHY: example.bib
#+PANDOC_EXTENSIONS: markdown-citations
#+PANDOC_OPTIONS: atx-headers:t
#+NOCITE: @giovanelli2016; @eilan2016

* Test Header

Here is a test example file with an in-text citation where someone important
says something important (e.g. @loncar2016). And here is another bit of
blah with a footnote citation.[fn:1]

Note that the setting =PANDOC_OPTIONS= allows one to pass command line settings
to pandoc via =ox-pandoc=. In this case, the setting passed converts citations
into markdown.

Note also the =NOCITE= comment in the header, which allows citations to appear
in the references section that have not actually appeared in the body of the
text.

[fn:1] See [@thompson2016].


* References
:PROPERTIES:
:UNNUMBERED:
:END:
```

## Markdown

```md
+++
title = "Org Pandoc Citation Test Example"
draft = false
author = false
toc = false
+++

# Test Header

Here is a test example file with an in-text citation where someone
important says something important (e.g. Loncar (2016)). And here
is another bit of blah with a footnote citation.[^1]

Note that the setting `PANDOC_OPTIONS` allows one to pass command line
settings to pandoc via `ox-pandoc`. In this case, the setting passed
converts citations into markdown.

Note also the `NOCITE` comment in the header, which allows citations to
appear in the references section that have not actually appeared in the
body of the text.

# References {#references .unnumbered}

Eilan, Naomi. 2016. "You Me and the World." *Analysis* 76 (3): 311--24.

Giovanelli, Marco. 2016. "\"\...But I Still Can't Get Rid of a Sense of
Artificiality\" the Reichenbach--Einstein Debate on the Geometrization
of the Electromagnetic Field." *Studies in History and Philosophy of
Science* 54: 35--51.

Loncar, Samuel. 2016. "Why Listen to Philosophers? A Constructive
Critique of Disciplinary Philosophy." *Metaphilosophy* 47 (1): 3--25.

Thompson, Morgan, Toni Adleberg, Sam Sims, and Eddy Nahmias. 2016. "Why
Do Women Leave Philosophy? Surveying Students at the Introductory
Level."

[^1]: See (Thompson et al. 2016).
```

## Bib

```bib
@article{giovanelli2016,
  title = {"...{{But I}} Still Can't Get Rid of a Sense of Artificiality" {{The Reichenbach}}–{{Einstein}} Debate on the Geometrization of the Electromagnetic Field},
  volume = {54},
  journaltitle = {Studies in History and Philosophy of Science},
  date = {2016},
  pages = {35--51},
  keywords = {Einstein,physics,science},
  author = {Giovanelli, Marco},
  file = {/Users/roambot/Dropbox/Work/MasterLib/giovanelli2016_the_reichenbach–einstein_debate.pdf}
}

@article{eilan2016,
  title = {You {{Me}} and the {{World}}},
  volume = {76},
  number = {3},
  journaltitle = {Analysis},
  date = {2016},
  pages = {311--324},
  author = {Eilan, Naomi},
  file = {/Users/roambot/Dropbox/Work/MasterLib/eilan2016_you_me_and_the_world.pdf}
}

@article{loncar2016,
  title = {Why {{Listen}} to {{Philosophers}}? {{A Constructive Critique}} of {{Disciplinary Philosophy}}},
  volume = {47},
  number = {1},
  journaltitle = {Metaphilosophy},
  date = {2016},
  pages = {3--25},
  author = {Loncar, Samuel},
  file = {/Users/roambot/Dropbox/Work/MasterLib/loncar2016_why_listen_to_philosophers.pdf}
}

@article{thompson2016,
  title = {Why {{Do Women Leave Philosophy}}? {{Surveying Students}} at the {{Introductory Level}}},
  abstract = {Abstract Although recent research suggests that women are underrepresented in philosophy after initial philosophy courses, there have been relatively few empirical investigations into the factors that lead to this early drop-off in women's representation. In this paper, we.},
  date = {2016},
  author = {Thompson, Morgan and Adleberg, Toni and Sims, Sam and Nahmias, Eddy},
  file = {/Users/roambot/Dropbox/Work/MasterLib/thompson2016_why_do_women_leave_philosophy.pdf}
}

@article{fricker2016,
  title = {What's the {{Point}} of {{Blame}}? {{A Paradigm Based Explanation}}: {{What}}'s the {{Point}} of {{Blame}}},
  volume = {50},
  number = {1},
  journaltitle = {Noûs},
  date = {2016},
  pages = {165--183},
  author = {Fricker, Miranda},
  file = {/Users/roambot/Dropbox/Work/MasterLib/fricker2016_what's_the_point_of_blame.pdf}
}
```

**Comment by mclearc** [comment]
Thanks for looking into this. I'll post any useful workarounds/workflows here if I think of them.

**Comment by kaushalmodi** [comment]
Thanks. Yesterday, I spent some time tinkering with this. I thought I almost got it, and am faced by a frustrating outcome ([Details on the issue I posted on Pandoc Google Groups][1]).

[1]: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/pandoc-discuss/yDOzeAiNQ_U

**Comment by kaushalmodi** [comment]
@mclearc Question: How did you end up with that Markdown file in https://github.com/kaushalmodi/ox-hugo/issues/175#issuecomment-405721433? 

Did you start with the Org file you posted, and end up with Markdown file through a pandoc command, or a particular ox-pandoc export? If so, what was that pandoc command or ox-pandoc export binding (C-c C-e p ? ?)?

Or did you first export and then manually tweak that Markdown file?

**Comment by mclearc** [comment]
I first exported then manually tweaked. It dawned on me that Hugo reads yaml front matter so I didn't even really need to produce a toml section. As for the command I used, it was just some version of `org-pandoc-export-to-markdown`.  I think the trick is going to be retaining the footnote links while converting the citations. If I come up with a winning combo I'll let you know.

**Comment by mclearc** [comment]
Here's what straight exporting to markdown (i.e. `org-pandoc-export-to-markdown`) with the following options in the org file gets you:

Options: 
```org
#+OPTIONS: author:nil
#+BIBLIOGRAPHY: example.bib
#+PANDOC_EXTENSIONS: markdown-citations 
#+PANDOC_OPTIONS: atx-headers:t
#+NOCITE: @giovanelli2016; @eilan2016
```

This actually seems pretty close to what you were looking for.. 


```markdown
---
bibliography: 'example.bib'
date: 'July 14, 2018'
nocite:
- '@giovanelli2016; @eilan2016'
pandoc_extensions: 'markdown-citations'
pandoc_options: 'atx-headers:t'
title: Org Pandoc Citation Test Example
---

# Test Header

Here is a test example file with an in-text citation where someone
important says something important (e.g. Loncar (2016)). And here is
another bit of blah with a footnote citation.[^1]

Note that the setting `PANDOC_OPTIONS` allows one to pass command line
settings to pandoc via `ox-pandoc`. In this case, the setting passed
converts citations into markdown.

Note also the `NOCITE` comment in the header, which allows citations to
appear in the references section that have not actually appeared in the
body of the text.

# References {#references .unnumbered}

::: {#refs .references}
::: {#ref-eilan2016}
Eilan, Naomi. 2016. "You Me and the World." *Analysis* 76 (3): 311--24.
:::

::: {#ref-giovanelli2016}
Giovanelli, Marco. 2016. "\"\...But I Still Can't Get Rid of a Sense of
Artificiality\" the Reichenbach--Einstein Debate on the Geometrization
of the Electromagnetic Field." *Studies in History and Philosophy of
Science* 54: 35--51.
:::

::: {#ref-loncar2016}
Loncar, Samuel. 2016. "Why Listen to Philosophers? A Constructive
Critique of Disciplinary Philosophy." *Metaphilosophy* 47 (1): 3--25.
:::

::: {#ref-thompson2016}
Thompson, Morgan, Toni Adleberg, Sam Sims, and Eddy Nahmias. 2016. "Why
Do Women Leave Philosophy? Surveying Students at the Introductory
Level."
:::
:::

[^1]: See (Thompson et al. 2016).
```

**Comment by kaushalmodi** [comment]
Great! `markdown-citations` was the key!

Try this:


```
#+hugo_base_dir: .

#+title: Org Pandoc Citation Test Example

#+export_file_name: org-citation-example-source

#+hugo_front_matter_format: yaml
#+hugo_custom_front_matter: :bibliography "example.bib"
#+hugo_custom_front_matter: :nocite "@giovanelli2016, @eilan2016"

* Test Header
Here is a test example file with an in-text citation where someone
important says something important (e.g. @loncar2016). And here is
another bit of blah with a footnote citation.[fn:1]
* References
:PROPERTIES:
:UNNUMBERED:
:END:
* COMMENT
** STEP 1: Convert this Org file to Markdown
- Use ~ox-hugo~. Do ~C-c C-e H H~ to export this ~content/posts/org-citation-example-source.md~.
- Symlink that file to ~org-citation-example-source.md~ in the current directory.
- Place the ~example.bib~ in the current directory too.
** STEP 2: Parse the citation annotation in the exported Markdown using Pandoc
*** Exporting to *markdown* output format
#+begin_example
pandoc --filter pandoc-citeproc -f markdown -i org-citation-example-source.md -t markdown-citations -o org-citation-example-md.md --atx-headers --standalone
#+end_example
* Footnotes
[fn:1] See [@thompson2016].
```

Instructions are in STEP 1 and STEP 2.

**Comment by kaushalmodi** [comment]
If this works, I need to work on these to make it work with `C-c C-e H H` in one step:

- [ ] Recognize `#+bibliography:` and auto-set the `bibliography` YAML front-matter.
- [ ] Call that `pandoc` command post-ox-hugo export. **No need for `ox-pandoc` dependency** because there seems to be just *one right way* to do this.
- [ ] Remove those `:::` chars added by pandoc in the references.

What you lose:

- The CUSTOM_ID that you set in the Org file for the section headings.
- Footnote style is overridden by pandoc, but that should work too.
- Not sure if any Blackfriday-specific fixes done in ox-hugo exported markdown get overridden by Pandoc.

**Comment by mclearc** [comment]
Yeah - those steps work for me. Though you'd then need to presumably move the pandoc converted file to the right directory and delete the symlink? Here's the output:

```markdown

---
author:
- Colin McLear
bibliography: 'example.bib'
draft: False
nocite: '@giovanelli2016, @eilan2016'
title: Org Pandoc Citation Test Example
---

## Test Header

Here is a test example file with an in-text citation where someone
important says something important (e.g. Loncar (2016)). And here is
another bit of blah with a footnote citation.[^1]

## References

## Footnotes {#footnotes .unnumbered}

::: {#refs .references}
::: {#ref-eilan2016}
Eilan, Naomi. 2016. "You Me and the World." *Analysis* 76 (3): 311--24.
:::

::: {#ref-giovanelli2016}
Giovanelli, Marco. 2016. "\"\...But I Still Can't Get Rid of a Sense of
Artificiality\" the Reichenbach--Einstein Debate on the Geometrization
of the Electromagnetic Field." *Studies in History and Philosophy of
Science* 54: 35--51.
:::

::: {#ref-loncar2016}
Loncar, Samuel. 2016. "Why Listen to Philosophers? A Constructive
Critique of Disciplinary Philosophy." *Metaphilosophy* 47 (1): 3--25.
:::

::: {#ref-thompson2016}
Thompson, Morgan, Toni Adleberg, Sam Sims, and Eddy Nahmias. 2016. "Why
Do Women Leave Philosophy? Surveying Students at the Introductory
Level."
:::
:::

[^1]: See (Thompson et al. 2016).
```

**Comment by kaushalmodi** [comment]
> Though you'd then need to presumably move the pandoc converted file to the right directory and delete the symlink? 

The copying/symlinking is needed only in the current "prototype" :) See my checklist in https://github.com/kaushalmodi/ox-hugo/issues/175#issuecomment-405987796.

**Comment by kaushalmodi** [comment]
Interesting! Pandoc removed only the redundant heading ID's.

### Before pandoc run

```md
...
## Test Header {#test-header}

Here is a test example file with an in-text citation where someone
important says something important (e.g. @loncar2016). And here is
another bit of blah with a footnote citation.[^fn:1]

See [Some section](#abc).


## Some section {#abc}
...
```

### After pandoc run

```md
...
## Test Header

Here is a test example file with an in-text citation where someone
important says something important (e.g. Loncar (2016)). And here is
another bit of blah with a footnote citation.[^1]

See [Some section](#abc).

## Some section {#abc}
...
```

So the CUSTOM_ID's are unharmed!

**Comment by kaushalmodi** [comment]
@mclearc Just one note.. I see that your markdown output has `## Footnotes {#footnotes .unnumbered}`. I wonder why that is because it is not seen in my ox-hugo exports. May be we can resolve that in a separate issue once this one is resolved.

**Comment by mclearc** [comment]
hmm – not sure if that is something to do with my export settings or not but seems like it must be if you're not seeing it. I'll try and test it later today.

**Comment by kaushalmodi** [comment]
> not sure if that is something to do with my export settings

Probably not.. but you probably tweaked the `org-footnote-section` variable? Mine is set to the default value `"Footnotes"`.

**Comment by mclearc** [comment]
yeah - it is currently set to `nil` - I like to keep footnotes with their sections. So setting `org-footnote-section` to `t` probably avoids the issue.

**Comment by kaushalmodi** [comment]
@mclearc I thought this implementation would be solid (working on https://github.com/kaushalmodi/ox-hugo/tree/pandoc-citeproc-support).. but found a show stopper.. Pandoc is transforming the ox-hugo generated Hugo/Blackfriday compatible tables into something else.

So this feature has a big caveat: **You cannot use Org tables in your posts with Pandoc citation parsing enabled.**

**Comment by kaushalmodi** [comment]
@mclearc Do you want to try out `ox-hugo` from [`pandoc-citeproc-support`][1] branch?

I believe it is almost good to go except for the caveat:

- Org tables won't export correctly as Pandoc messes them up.

You also don't need to set the front-matter format to YAML; keeping with TOML would work.

- [Org][2] | [Markdown][3]

[1]: https://github.com/kaushalmodi/ox-hugo/commits/pandoc-citeproc-support
[2]: https://github.com/kaushalmodi/ox-hugo/blame/pandoc-citeproc-support/test/site/content-org/all-posts.org#L4594-L4625
[3]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/pandoc-citeproc-support/test/site/content/posts/citations-example-toml.md

**Comment by mclearc** [comment]
Thanks for your work. I'll give a look and report back. I don't use tables very often, so the lack of conversion there won't be an issue for me.

**Comment by kaushalmodi** [comment]
@mclearc And the final known issue about tables is also now solved! :D

Please update that branch and stress-test it!

Example Org:

```org
* Pandoc Citations                                         :pandoc:citations:
:PROPERTIES:
:EXPORT_HUGO_PANDOC_CITATIONS: t
:EXPORT_BIBLIOGRAPHY: bib/bib1.bib, bib/bib2.bib
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :nocite '(@giovanelli2016 @eilan2016)
:EXPORT_HUGO_PAIRED_SHORTCODES: %mdshortcode myshortcode
:END:
** Citations Example (TOML)                                            :toml:
:PROPERTIES:
:EXPORT_FILE_NAME: citations-example-toml
:END:
#+begin_description
Test the parsing of Pandoc Citations, while also testing that ox-hugo
exported Markdown doesn't get broken -- TOML front-matter.
#+end_description
{{{oxhugoissue(175)}}}
*** Section 1
Here is a test example file with an in-text citation where someone
important says something important (e.g. @loncar2016). And here is
another bit of blah with a footnote citation.[fn:5]

See [[#citation-example-section-2]].
*** Section 2
:PROPERTIES:
:CUSTOM_ID: citation-example-section-2
:END:
Content in section 2.
*** Testing random Hugo shortcode
#+begin_mdshortcode
Text containing *Markdown*
#+end_mdshortcode
Some text.
#+begin_myshortcode
Text not containing *Markdown*
#+end_myshortcode
*** Testing tables
|----------+----------+----------|
| Header 1 | Header 2 | Header 3 |
|----------+----------+----------|
| a        | b        | c        |
| d        | e        | f        |
|----------+----------+----------|
```

With the .bib files in place, all you should need to do is `C-c C-e H H`.

**Comment by mclearc** [comment]
From what I can see this works great! The only issue I've seen is if a page happens not to have citations, but has `:EXPORT_HUGO_PANDOC_CITATIONS: t` the entire set of metadata dissapears. Probably won't often be an issue, but if you happen to have subtree without citations it might be a little weird. But thanks for the work! 🎊

**Comment by kaushalmodi** [comment]
> The only issue I've seen is if a page happens not to have citations, but has :EXPORT_HUGO_PANDOC_CITATIONS: t the entire set of metadata dissapears.

Interesting! I happen to have had thought of that exact use case few minutes back and already [fixed it][1] :D Do you want to update that branch and retry?

[1]: https://github.com/kaushalmodi/ox-hugo/commit/cb2558b65a624e0c6794044c44565314524385af

**Comment by mclearc** [comment]
Looks fixed! 😄

**Comment by kaushalmodi** [comment]
This issue got auto-closed. Feel free to re-open it if you face any issues.

The pandoc test branch has now been merged into master. So you will get this update via the next Melpa update too.

**Comment by kaushalmodi** [comment]
[Pandoc Citations][1] -- `ox-hugo` Documentation

[1]: https://ox-hugo.scripter.co/doc/pandoc-citations/
