### ISSUE TITLE
Setting a slug explicitly

### ISSUE THREAD

**Issue by akirak** [kaushalmodi/ox-hugo#176]
Hello, thanks for your recent update on the draft states in ox-hugo. It has made things simple. 

Is there a way to set the slug of a post produced by ox-hugo? If not, you should provide this feature via a property like `hugo_export_slug` (in upper case). This feature is vital, because without a slug, the URL of a post changes after its title is changed.

**Comment by kaushalmodi** [comment]
All Hugo front-matter AFAIK are supported. May be it's just the typo? Try `#+hugo_slug` **keyword** or `:EXPORT_HUGO_SLUG:` **property** in subtree. Search for "hugo_slug" in the [ox-hugo test case][1].

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/all-posts.org

**Comment by akirak** [comment]
Thanks.
