### ISSUE TITLE
Support Org > mmark 

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#18]
`mmark` is supported in Hugo since v0.15 [[Release Notes][1]].

I haven't yet used `mmark`. 

Also given the popularity of [`mmark`][2] (162 stars as of today) vs [`blackfriday`][3] (2470 stars), marking it as a *wishlist* item. So it won't be implemented unless someone jumps in to help develop the support.

- [`mmark` Syntax][4]

[1]: https://github.com/gohugoio/hugo/releases/tag/v0.15
[2]: https://github.com/miekg/mmark
[3]: https://github.com/russross/blackfriday
[4]: https://github.com/miekg/mmark/wiki/Syntax

**Comment by titaniumbones** [comment]
(of course, the other wishlist item might be to just learn Go and implement the appropriate feature support in Googrgeous...).

**Comment by kaushalmodi** [comment]
As of today, `ox-hugo` has grown into a blend of Markdown + HTML exporter that exports files that can be understood by probably all Markdown parsers. I don't see a point keeping this *wishlist* issue open. 

If there's a `mmark` feature that `ox-hugo` doesn't yet support, then a separate issue for each of those features can be opened.
