### ISSUE TITLE
ox-hugo:export - Always exports the author's name as an array 

### ISSUE THREAD

**Issue by sus007** [kaushalmodi/ox-hugo#180]
> #### As the title says it all. Every time I export my org, it gets the author attribute as an **`array`** instead of a normal **`string`** and hence triggers casting error while serving the hugo locally. 

**`error calling safeHTML: unable to cast []string{"MY NAME"} of type []string to string
`**

Could you point me somewhere to fix this minor issue ?

**Comment by kaushalmodi** [comment]
Does this help? https://ox-hugo.scripter.co/doc/author/

**Comment by kaushalmodi** [comment]
@sus007 If you already visited the Author documentation link I pasted earlier, visit it again; I have made that documentation more thorough now. Let me know if you still have questions.

**Comment by sus007** [comment]
I'll make sure to raise another issue should I encounter another problem. Thank you for this awesome tool :nerd_face:
