### ISSUE TITLE
Automatic generation of _index.md when using nested sections

### ISSUE THREAD

**Issue by StevenTammen** [kaushalmodi/ox-hugo#186]
I was pleasantly surprised to see that ox-hugo transparently handles nested sections during export. 

For example, a post at `hugo-dir/org-content/posts/post1.org` might have the following information:

```
#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: posts
```

and get exported to `hugo-dir/content/posts/post1.md`.

But if we wanted to have a post in a nested section, we might have something instead like `hugo-dir/org-content/posts/nested-section/post1.org` with

```
#+HUGO_BASE_DIR: ../../../
#+HUGO_SECTION: posts/nested-section
```

which will correctly get exported to `hugo-dir/content/posts/nested-section/post1.md`.

------------------------------------

Now, for Hugo to correctly handle [branch bundles](https://gohugo.io/content-management/page-bundles/#branch-bundles), it needs an `_index.md` file defined in the nested directories used for export (i.e., the `content` versions not the `org-content` versions). Leaving this file blank works fine; custom front-matter can be defined in it for the list pages that Hugo automatically generates. But it has to exist for the nested section to work properly.

I think a good enhancement to ox-hugo would be to automatically generate a blank _index.md file when an Org file is exported to a nested section, if it does not already exist.

------------------------------------

If the current implementation works something like the following:

```
create .md file at HUGO_BASE_DIR/content/HUGO_SECTION/filename.md
```

then the enhanced version could look something like

```
create .md file at HUGO_BASE_DIR/content/HUGO_SECTION/filename.md

if ( (HUGO_SECTION contains one or more /'s) and (_index.md does not exist in HUGO_BASE_DIR/content/HUGO_SECTION/))
        create blank file in this directory called _index.md
```

Thoughts?

**Comment by kaushalmodi** [comment]
I wouldn't risk automatically creating any file. What if the user wants a branch bundle instead of a leaf bundle?

How about this?:

```
#+hugo_section: foo/bar/
#+hugo_bundle: zoo
#+export_file_name: _index
```

This would create `content/foo/bar/zoo/_index.md` (branch bundle). If user wants a leaf bundle, they would just replace `_index` with `index`. 

Does that work for your use case?

**Comment by StevenTammen** [comment]
Yeah, that works fine. I see what you mean about branch bundles vs. leaf bundles. There would have to be some way to select between leaf, branch, or none (if the file is part of a root section).

The reason I asked about this is because it is easy to forget to create an _index file to begin with, and if you don't create one, the nested section will not function properly. The idea behind having it get transparently added on export was to make sure it is always present in the directory Hugo is publishing from.

This is easy enough to do manually, so it's not a big deal, but it's just one more thing to remember.

**Comment by kaushalmodi** [comment]
> The reason I asked about this is because it is easy to forget to create an _index file to begin with

Branch bundles are not mandatory. You would need branch bundles only if your want a landing page for a section, want to specify some front-matter, etc.

> The idea behind having it get transparently added on export was to make sure it is always present in the directory Hugo is publishing from.

Ox-hugo cannot impose any web site structure style. It just creates as instructed :)

> just one more thing to remember.

As you use this more, this won't be an issue. Trust me. 

---

Btw, you might also like going through my blog post on [branch vs leaf bundles][1]. It happens that I sort of coined the branch bundle vs leaf bundle terms for the documentation. Earlier they were being referred to as "directory with _index" vs "directory with index".

Later I ported part of my blog post to the official Hugo docs on Page Bundles :)

[1]: https://scripter.co/hugo-leaf-and-branch-bundles/
