### ISSUE TITLE
ox-hugo export : Exports `keyword` as \`keyword`\

### ISSUE THREAD

**Issue by sus007** [kaushalmodi/ox-hugo#187]
Whenever I want to include a keyword in between a normal paragraph by using backticks(`),

>  **Eg: `const, static`, etc,**

 I get **backticks enclosed within backslashes** in the outputted markdown,  which results to unintentional rendering in the final webpage. Is there any way to avoid this conversion ?

**Comment by kaushalmodi** [comment]
Not sure if I am understanding this right.. the backtick sytnax is Markdown. In Org you would do either `Eg: =const=, =static=, etc` or `Eg: ~const~, ~static~, etc`.

If you use a backtick in Org, it's assumed that you want to export a literal `` ` ``, and so that gets escaped.

**Comment by sus007** [comment]
Ex-Vimmer/Emacs Newbie here, sorry for your trouble. :smile:

**Comment by kaushalmodi** [comment]
No problem, such questions are welcome :). Welcome to Emacs and Org mode.
