### ISSUE TITLE
Listing posts in home page

### ISSUE THREAD

**Issue by JuanPabloMF** [kaushalmodi/ox-hugo#188]
This is a followup from a conversation started in the emacs subreddit.
https://www.reddit.com/r/emacs/comments/95pxau/oxhugo_beginner_question_how_do_i_get_my_home/

So I am using the ghostwriter template, and I want to get my posts listed in my homepage. I am an absolute Hugo beginner so my question might need a tweak in the Hugo configs, instead of my org file, but first I wanted to check that everything is fine from the org file side.

I created a repo to share all of my settings:
https://bitbucket.org/juanpablomf/blog/src/master/

This is what I get in my home:

![screenshot from 2018-08-13 14-54-20](https://user-images.githubusercontent.com/4017397/44048932-240f82d0-9f09-11e8-8fc5-68673f84885b.png)

And this in /posts:

![screenshot from 2018-08-13 14-55-02](https://user-images.githubusercontent.com/4017397/44048871-03bb9cf8-9f09-11e8-85fa-d717d8276883.png)

I have tried a few ways to get the listing in the home but is not getting it. Any ideas?

**Comment by kaushalmodi** [comment]
> but first I wanted to check that everything is fine from the org file side.

Yes. All looks good from Org side. It is the theme's issue.

You can fix the theme locally by making this change:

```diff
diff --git a/layouts/index.html b/layouts/index.html
index 70190f9..119ae94 100644
--- a/layouts/index.html
+++ b/layouts/index.html
@@ -4,7 +4,7 @@
     {{ partial "intro.html" . }}
 
     <ol class="post-list">
-        {{ $pag := .Paginate (where .Data.Pages "Type" "post") }}
+        {{ $pag := .Paginate (where .Pages "Type" "in" .Site.Params.mainSections) }}
         {{ range $pag.Pages }}
             {{ partial "post-stub.html" . }}
         {{ end }}
```

After that, I get:

![image](https://user-images.githubusercontent.com/3578197/44051070-d67c3470-9f06-11e8-82e7-adb7e9b3e35e.png)


See https://github.com/jbub/ghostwriter/issues/60. I'm closing this issue here.

**Comment by kaushalmodi** [comment]
As an aside, the theme shouldn't be printing the date if it is not set (which it does in this case.. printing "Jan 1, 0001" which is not useful). You should open that issue on that theme's repo.

**Comment by JuanPabloMF** [comment]
When making the change I am getting the following log error (after hugo server -D):

ERROR: 2018/08/13 16:45:53 template.go:350: template: theme/partials/post-footer.html:7: function "relLangURL" not defined
ERROR: 2018/08/13 16:45:53 template.go:350: template: theme/partials/post-header.html:7: function "default" not defined
ERROR: 2018/08/13 16:45:53 template.go:350: template: theme/partials/post-stub.html:4: function "default" not defined
ERROR: 2018/08/13 16:45:53 template.go:119: html/template: "theme/partials/post-footer.html" is an incomplete template in theme/partials/post-footer.html
ERROR: 2018/08/13 16:45:53 general.go:222: Error while rendering homepage: template: theme/index.html:7:36: executing "theme/index.html" at <.Pages>: Pages is not a field of struct type *hugolib.Node

**Comment by kaushalmodi** [comment]
What's you Hugo version? I am testing this on Hugo v0.47-DEV. So I'd suggest that you use Hugo v0.46.

**Comment by JuanPabloMF** [comment]
I had an old version of Hugo running, with 0.46 it works perfect. Thanks!!
