### ISSUE TITLE
Allow replacing `ipython` "language" in src blocks with "python3" so that Chroma highlighting works

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#189]
Tweak `org-hugo-src-block` function to replace the "ipython" lang with "python3".

May be introduce a defcustom for this.

/cc @JuanPabloMF

---

[Ref][1]

[1]: https://gitter.im/KaushalModi/Lobby?at=5b72013a637ee66082e77862

**Comment by kaushalmodi** [comment]
https://github.com/alecthomas/chroma/issues/164

**Comment by jkitchin** [comment]
Is there a way to define aliases for languages? I recently started using emacs-jupyter, and that is how the src-blocks are named. They aren't syntax highlighted as Python blocks with ox-hugo though.
