### ISSUE TITLE
Conditional styling of <figure> for images

### ISSUE THREAD

**Issue by StevenTammen** [kaushalmodi/ox-hugo#192]
Earlier today I added some CSS for the `<figure>` tag so that I could add captions to images that would look nice:

```
figure {
  text-align: center;
  font-size: smaller;
  text-indent: 0;
  border: thin silver solid;
  margin: 0.5em;
  padding: 0.5em;
}
```

This adds a border to group captions with their images (so that it is easy to tell which caption goes with what image, if you have a group of captioned images). For a real-world example, see the pictures towards the bottom of [this page](https://www.steventammen.com/pages/pencil-leads/) on my site.

I am creating image links according to the instructions on <https://ox-hugo.scripter.co/test/posts/image-links/>. So things like 

`[[/path/to/img/in/static][file:/path/to/img/in/static]]`, or

`[[https://blah.com/img.png][file:/path/to/img/in/static]]`.

(I'm serving "external" images from my own static directory for speed: Netlify's CDN that I am using is quite fast).

--------------------

The problem is that the CSS I apply to the `<figure>` tag gets applied to *all* the images across my site. For example, the graphics in [this blog post of mine](https://www.steventammen.com/posts/initial-greek-survey-analysis/) get the border even though they don't have any caption.

Since [CSS does not have parent selectors at present](https://stackoverflow.com/questions/2326499/apply-css-styles-to-an-element-depending-on-its-child-elements#2326571), I cannot simply choose to conditionally style `<figure>` elements that contain `<figcaption>` elements. It's not too hard to get the behavior I'm looking for with jQuery (based on what I've read -- I don't actually have any experience with Javascript), but it does slow down pages, and seems needless to me.

Here's what I would propose: to have ox-hugo add a class to the generated `<figure>` elements to allow for different styling for images with captions and images without captions.

So, for example,

```
#+CAPTION: Some caption
[[/path/to/img/in/static][file:/path/to/img/in/static]]
```

would export to

```
{{< figure class="captioned-image" ... >}}
```

While 

```
[[/path/to/img/in/static][file:/path/to/img/in/static]]
```

(an inlined-image without a caption) would just export to

```
{{< figure ... >}}
```

This should work fine since [Hugo's figure shortcode supports the class attribute](https://gohugo.io/content-management/shortcodes/#figure).

--------------------

What do you think? 

If this is not too hard, I think it would be beneficial for ox-hugo to also support generalized image CSS classes in case you want to style some uncaptioned images differently without using HTML directly. Perhaps something like

```
#+IMAGE_CLASS bordered-image
[[/path/to/img/in/static][file:/path/to/img/in/static]]
```

exporting to

```
{{< figure class="bordered-image" ... >}}
```

**Comment by kaushalmodi** [comment]
> Here's what I would propose: to have ox-hugo add a class to the generated <figure> elements to allow for different styling for images with captions and images without captions.

As you would have noticed, `ox-hugo` does not insert raw `<figure>` HTML in the exported Markdown. It just inserts the Hugo `figure` shortcode. While I don't like exporting Hugo shortcodes in general, it actually helps in this case as you can customize that shortcode to convert to any HTML you like. 

That means that you can detect if the `caption` parameter of the `figure` shortcode is present, and if so insert the extra class. If you like, you can use the [`ox-hugo` doc site custom `figure` shortcode][1] as a starting point to add your customization. If you need help with that, come over to [Hugo Discourse forum][2].  

> If this is not too hard, I think it would be beneficial for ox-hugo to also support generalized image CSS classes in case you want to style some uncaptioned images differently without using HTML directly. Perhaps something like

That's already possible! :D

Example from one of the tests ([this one][3]):

```org
#+attr_html: :class inset
[[/images/org-mode-unicorn-logo.png]]
```

exports to:

```md
{{< figure src="/images/org-mode-unicorn-logo.png" class="inset" >}}
```

[1]: https://github.com/kaushalmodi/hugo-onyx-theme/blob/2ce7808e6a387e6d1aab36f0984df606d9a060b4/layouts/shortcodes/figure.html
[2]: https://discourse.gohugo.io/
[3]: https://ox-hugo.scripter.co/test/posts/figure-shortcode-and-attr-html/

**Comment by StevenTammen** [comment]
I'll take a look at this more in a couple days. My college work is front-loaded towards the beginning of weeks, which means I'm pretty busy from like Sunday-Wednesday. Some comments now, though:

1) I think you understand now. Having the option to automatically add the "caption class" to the Hugo shortcodes wouldn't mean it would have to be turned on by default. But I don't see a great deal of harm in using the class even without custom styling defined immediately.

I can try to implement this in a custom shortcode if you want. But I haven't done any complicated template scripting for Hugo before, so it might be a while.

2) I might be misunderstanding you, but couldn't you use Hugo's [{{% shortcode %}} syntax](https://gohugo.io/content-management/shortcodes/#shortcodes-with-markdown) to render markup Hugo shortcodes? Rather than the {{< shortcode >}} syntax?

I seem to have a problem within Org mode itself not allowing markup in captions. For example, I was trying to link to image sources in my captions (just normal Org links), but the links were not working, nor things like /italics/. I guess Org mode captions can't contain any markup? Seems unnecessarily restrictive. Is this an Org mode thing?

**Comment by kaushalmodi** [comment]
> Having the option to automatically add the "caption class" to the Hugo shortcodes wouldn't mean it would have to be turned on by default.

It's just that it would complicate the code a bit.. I need to then address/test situations where the figures have captions **and** `#+attr_html: :class foo` is specified by the user.

> I might be misunderstanding you, but couldn't you use Hugo's `{{% shortcode %}}` syntax to render markup Hugo shortcodes? Rather than the `{{< shortcode >}}` syntax?

Both work and they have different meanings to Hugo. It's yet an undocumented feature, but you can have Org Special Blocks convert to Hugo shortcodes. See:
- https://ox-hugo.scripter.co/test/posts/paired-shortcodes-special-blocks-no-arguments/
- https://ox-hugo.scripter.co/test/posts/paired-shortcodes-special-blocks-no-arguments/
- https://github.com/kaushalmodi/ox-hugo/issues/119, https://github.com/kaushalmodi/ox-hugo/issues/126

> I seem to have a problem within Org mode itself not allowing markup in captions.

That's a known issue with the inbuild `figure` shortcode in Hugo. See https://github.com/kaushalmodi/ox-hugo/issues/136. The workaround is to use [my custom `figure` shortcode][1].

>  I guess Org mode captions can't contain any markup? Seems unnecessarily restrictive. Is this an Org mode thing?

Nope, they can :)

[1]: https://github.com/kaushalmodi/hugo-onyx-theme/blob/2ce7808e6a387e6d1aab36f0984df606d9a060b4/layouts/shortcodes/figure.html

**Comment by StevenTammen** [comment]
Sorry for the delay on this.

I got what I wanted working by modifying the shortcode as you suggested. You can see [the commit](https://github.com/StevenTammen/steventammen.com/commit/fb6c68120485700aa487ed7ebce61f59480c6ebe) if you like. All I did compared to your shortcode was add a line within the definition of the opening `<figure>` tag.

On Org captions, let me show what I mean with pictures. It could be something related to my Spacemacs configuration (...?), but Org mode itself is not "recognizing" the markup (displaying links rather than leaving the bracket markup, applying styling to `/italic/` and `*bold*` text, etc.). For example:

![image](https://user-images.githubusercontent.com/14948260/45246863-c18dba00-b2d1-11e8-8f5b-1a1cef261629.png)

As you can see, Org mode isn't recognizing the markup in the caption. It gets exported fine though.

![image](https://user-images.githubusercontent.com/14948260/45246932-13cedb00-b2d2-11e8-8aae-aa8c9d41f363.png)

I'm guessing this isn't related to ox-hugo at all, but this is what I was talking about.

Thanks for your help!

**Comment by kaushalmodi** [comment]
I see.

Yes, that has nothing to do with ox-hugo. Ox-hugo is not a major mode (like Org mode). So it cannot affect how stuff looks in the Emacs windows. It's just an Org exporter, so its job is to just transform Org to the exported format. 

Glad to see that you got the intended results in the final HTML. 

About the bold/italics not *rendering* in the Org mode buffer, it has to do with the font lock setting in Org mode. There are so many overlapping font locks there that such corner cases get left out. 

The font locking rules probably ignore bold/italics/etc in captions as it's setting the font lock just for captions. 

Though, as you saw, this affects only the visuals, not the exported file. 

You can report this to the Org mode mailing list. It's possible that someone has already fixed this in their config, and they can share their solution, or even Nicolas Goaziou may directly fix it in Org mode :)

**Comment by kaushalmodi** [comment]
@StevenTammen OK then, I am closing this issue as it's just cosmetics, and has to do with font locking in Org mode.
