### ISSUE TITLE
table syntax in Hugo differs from vanilla md and gfm

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#2]
- vanilla markdown has now table syntax
- gfm table syntax is 
```gfm
| Heading| Column2|
|----------|----------|
| content | content |
```

in Hugo's Blackfriday parser, table syntax is
```
 Heading| Column2
----------/---------
 content | content 
```

So probably ox-hugo needs to supply its own table parser.

**Comment by kaushalmodi** [comment]
I am using [this][1] (see comments at the end) for tables in Hugo. Will need to make the exporter do the same. 

[1]: https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-markdown.el

**Comment by titaniumbones** [comment]
wouldn't the simplest solution be to just use a standard exporter function that writes the table properly in the first place?

It's too bad that blackfriday requires a table header! I guess there's nothing we can do about that though.

**Comment by titaniumbones** [comment]
Made some progress via the gfm table exporter in https://github.com/kaushalmodi/ox-hugo/pull/8, but syntax of the horizontal rule between table header and body is imperfect, and blackfriday doesn't recognize the output as a table.

**Comment by kaushalmodi** [comment]
Table support is added and tested. Closing this issue.
