### ISSUE TITLE
Auto-generate the config.toml

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#20]
- [ ] If a `config.toml` does not exist, auto-generate it from a template.
- [ ] Option to auto-generate the `config.toml` during each export, basically user will not be allowed to manually update the `config.toml`. All `config.toml` options need to be parsed somehow from the source Org file.

**Comment by titaniumbones** [comment]
hmm, if we do that , then there should be a way to specify additional config options.  This would get one closer to automating the construction of a whole hugo site directly from org.

**Comment by kaushalmodi** [comment]
After having this issue being left open for over a year, and given thought to it, this really falls outside the realm of `ox-hugo`, so closing it.
