### ISSUE TITLE
Read :LOGBOOK: drawer for metadata and modification timestamps

### ISSUE THREAD

**Issue by alphapapa** [kaushalmodi/ox-hugo#203]
Hi Kaushal,

Reading about ox-hugo again, and thinking about giving it a try, I thought I would post this idea that I was thinking about last night, which I'd like to have in my "ideal" Org blogging engine:

I'd like the `:LOGBOOK:` drawer to act as a log of changes for each post.  e.g. if I updated a post that was already published, I could use `org-add-log-note` (`C-c C-z`) to make a note, like "Updated link and corrected typos."  Then when I republished or reexported the blog, the note from the logbook would be put in the HTML in the appropriate place, and the last-modified timestamp would be taken from the most recent logbook entry.

Also, quick question: Is it possible to set up ox-hugo so that only posts with a certain to-do keyword are published?  The workflow I was thinking of was to have `TODO` entries be ideas for posts, another keyword for drafts, and a `PUBLISHED` keyword (configured as a "done" keyword in Org) for posts I want to be published.

Thanks.

**Comment by kaushalmodi** [comment]
I like the LOGBOOK feature, and probably something that I would use too. 

A long time back, I tried using the log book but it never worked for me.. I couldn't get the TODO/DONE state changes to log in the LOGBOOK drawer. And as it wasn't a pressing matter, I didn't did into what I should need to set in my config to make that work. 

In addition to changelog recording, I would also like to get the TODO state transitions recorded in there.

> Is it possible to set up ox-hugo so that only posts with a certain to-do keyword are published?

Yes, sort of. 

You can have posts without DONE state to not get published by Hugo (but they still will be exported with the draft front-matter set to true. Hugo doesn't publish such posts by default.)

Just mark all posts to be drafts by default by putting `#+hugo_draft: true` at the top of the Org file. Then only the posts marked DONE will have the draft set to **false** and thus will be published https://github.com/kaushalmodi/ox-hugo/issues/171#issuecomment-403792998).

**Comment by kaushalmodi** [comment]
@alphapapa I need to may be set some defcustoms to get notes going **into** LOGBOOK drawer?

In a plain heading, doing `C-c C-z` and typing "Test note." gives:

```org
* Taking notes
- Note taken on [2018-09-06 Thu 10:18] \\
  Test note.
```

So I need to put a hack to interpret a list item beginning with "Note taken on " as something special.

**Comment by kaushalmodi** [comment]
OK, I needed `#+startup: logdrawer` and `C-c C-z` (`org-add-note`) does this:

```
* Notes in LOGBOOK
:LOGBOOK:
- Note taken on [2018-09-06 Thu 10:38] \\
  New note.
:END:
```

**Comment by kaushalmodi** [comment]
@takaxp Thanks. I read about `@` too, though not sure if I will use it. It would be too *prompty* for me when marking posts as DONE (or PUBLISHED).

*PS: `ox-hugo` hasn't hard-coded the DONE keyword. So `#+seq_todo: TODO(!) PUBLISHED(@/!)` will also work.*

**Comment by kaushalmodi** [comment]
@alphapapa Would you like to make this a reality? 

I have just added tests marked as `noexport` for now: https://github.com/kaushalmodi/ox-hugo/commit/fad9c3dfeba492a45ef72d952982295861af352e

**Comment by kaushalmodi** [comment]
Some initial work in https://github.com/kaushalmodi/ox-hugo/tree/logbook.

**Comment by alphapapa** [comment]
Hi Kaushal,

> Would you like to make this a reality?

Well, I don't actually use Hugo (yet?), and I don't have much experience with org-export code, so I probably won't be contributing any patches--at least, not unless I actually start using this.  :)  I just wanted to toss the idea out there in case you thought it was worth doing, because it's a feature I would like to use myself.

Thanks.

**Comment by kaushalmodi** [comment]
@alphapapa 

> Well, I don't actually use Hugo (yet?)

Got it. :)

I thought you would be a good candidate as I was stumbling through this initial commit for parsing logbook: https://github.com/kaushalmodi/ox-hugo/commit/7872a01cfeb8f8de315df47e298cb39196c3af9b#diff-83e8d96285fece9af7ae40f921c15f3cR1596 .. `org-element-map` and stuff.

In any case, thanks for suggesting logbook notes.. I think I can use those to replace my "update" Org macros: 
![image](https://user-images.githubusercontent.com/3578197/45217631-d71fc700-b272-11e8-8b3a-fa48b2101fa9.png)

**Comment by alphapapa** [comment]
> I thought you would be a good candidate as I was stumbling through this initial commit for parsing logbook: 7872a01 .. org-element-map and stuff.

Maybe so!  I actually found that code very interesting, how you used 4 lambdas nested with `org-element-map`.  I haven't seen it used that way before.  At first I was surprised, but then I realized that it makes sense.  (I feel like it's begging for some kind of org-element-recursive-map macro, though...)  I've tried to write code making heavy use of org-element-map before, but I've never gotten the hang of it.  Something about the structure of the parsed elements confuses me.  Sometimes I wonder if it ought to use structs to help, if it would.

> In any case, thanks for suggesting logbook notes.. I think I can use those to replace my "update" Org macros: 

Yep, that's exactly what I was thinking it would be useful for!

**Comment by kaushalmodi** [comment]
@alphapapa It's close to 4 years and this is now finally implemented 😁.

Now `ox-hugo` is able to parse `date` and `lastmod` frontmatter fields for Hugo from the TODO state transitions in the LOGBOOK drawer and notes from there get exported to `logbook.<..>.notes` frontmatter. 

Check out the commit diff of https://github.com/kaushalmodi/ox-hugo/pull/504 for details if interested. I have tested out this feature on my site and it seems to work well 😃. I'd welcome any critical feedback on elisp coding (based on that PR diff) from you. 

### Documentation

https://ox-hugo.scripter.co/doc/drawers/

### Example usage

[scripter.co commit # cae86abc](https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/-/commit/cae86abc0bdf6c9c2ceda1e249453f1642038cdc)

**Comment by alphapapa** [comment]
@kaushalmodi I just happened to look at my GitHub notifications today (which I haven't been doing regularly for a while now).  Cool!  :)  The only feedback I have on the Elisp would be to consider using `cl-labels` to name the functions used in the nested `org-element-map` calls, rather than using nested lambdas.  It *could* make the code more readable and less nested, but that's largely a matter of taste.

I'm always impressed by how thoroughly your projects are written and tested.  Nicely done!

**Comment by kaushalmodi** [comment]
@alphapapa Thanks for your feedback and the idea of using `cl-labels`. I attempted something in https://github.com/kaushalmodi/ox-hugo/pull/637. It makes the nested `org-element-map` more readable, but I couldn't figure out if I could use a recursive `cl-labels` defined function there.

But you are right; breaking out the code from the inner most `org-element-map` to a separate function made things more readable 😃.

**Comment by alphapapa** [comment]
> but I couldn't figure out if I could use a recursive cl-labels defined function there.

I'm not sure what you mean, but you should be able to use `labels`-defined functions instead of the nested lambdas...if you want to, anyway.  :)  With that change, it's already much more understandable, I think.

**Comment by kaushalmodi** [comment]
> but you should be able to use labels-defined functions instead of the nested lambdas...

Hmm.. I couldn't still figure that out.

> if you want to, anyway. :) 

I want to at least see what using `cl-labels` instead of nested `org-element-map` would look like... but I'm hitting a wall here.

> With that change, it's already much more understandable, I think.

Cool. I'll just commit what I have for now. Thanks!

**Comment by alphapapa** [comment]
Each lambda would be pulled out into a named `labels` function.  In a way, it could be less clear, because the structure wouldn't be visually apparent--each function would call another one by name rather than having its body nested within it.  But if the names are carefully chosen, it could make the code more composable and readable.

**Comment by kaushalmodi** [comment]
@alphapapa I understood (or probably not) the concept, but I don't understand how I can shrink this piece of code:

```el
(org-element-map drawer 'plain-list
  (lambda (lst)
    (org-element-map lst 'item
      (lambda (item)
        (org-element-map item 'paragraph
          (lambda (para)
            (org-hugo--parse-logbook-entry para parent-heading-title info))
          nil :first-match)))) 
  nil :first-match)
```

#### First lambda

```el
(lambda (lst)
    (org-element-map lst 'item
      (lambda (item)
        (org-element-map item 'paragraph
          (lambda (para)
            (org-hugo--parse-logbook-entry para parent-heading-title info))
          nil :first-match))))
```

#### Second lambda

```el
(lambda (item)
        (org-element-map item 'paragraph
          (lambda (para)
            (org-hugo--parse-logbook-entry para parent-heading-title info))
          nil :first-match))
```

### Third lambda

```el
(lambda (para)
            (org-hugo--parse-logbook-entry para parent-heading-title info))
```

If I were to create a `cl-lambda` for each, I would end up with 

```el
(org-element-map drawer 'plain-list
  #'fn-to-apply-on-list-element ;a cl-label identifier that accepts one arg
  nil :first-match)
```

and then I will need a separate cl-label for each of the other 2 lambdas, right?

I was trying to figure out how to use just one cl-label in a recursive fashion ..

**Comment by alphapapa** [comment]
Well, maybe I'm missing something, in which case I'd be wasting your time, but I was thinking of something like this:
```el
(let ((parent-heading-title)
      (info))
  (cl-labels ((one (lst)
                   (org-element-map lst 'item
                     #'two))
              (two (item)
                   (org-element-map item 'paragraph
                     #'three nil :first-match))
              (three (para)
                     (org-hugo--parse-logbook-entry para parent-heading-title info)))
    (org-element-map drawer 'plain-list #'one nil :first-match)))
```
