### ISSUE TITLE
Moving a post into draft form, deleting it from blog?

### ISSUE THREAD

**Issue by amca01** [kaushalmodi/ox-hugo#207]
I have just got back to my blog after several months being too busy even to think about it.  In haste I whipped up a post and published it long before it was ready.  How do I take a published post out of the hugo site, and ensure that it's listed as draft - so not to be published until I'm sure it's ready?

**Comment by kaushalmodi** [comment]
To delete the post, you will need to do it manually. 

To change it to draft, set `#+hugo_draft: true` at the top of the file for per-file export flow. 

For per-subtree export flow, set the Org TODO state to TODO (or DRAFT if you have configured DRAFT as a "TODO" state too).

**Comment by amca01** [comment]
So sorry not to have responded earlier (work is CRAZY) - what I did was simply delete that post.  I now have an environment set up in a docker container that works fine: I can develop on my laptop, using ox-hugo, and when the post looks lovely, I can simply move it to the container using a script with rsync.  The trick is not to rsync before I'm ready!  

Thank you very much.

**Comment by kaushalmodi** [comment]
OK, thanks for the update. I'm closing this issue then.
