### ISSUE TITLE
Export happens even when EXPORT_FILE_NAME is empty

### ISSUE THREAD

**Issue by takaxp** [kaushalmodi/ox-hugo#211]
Hi!

When I use the latest ox-hugo with `ox-hugo-auto-export` and `auto-save-buffers.el`, unexpected files were exported during writing a new post in an org file.

For example, my org file is organized as:

```org
* 2018
:PROPERTIES:
:EXPORT_HUGO_SECTION: 2018
:END:
** DONE post1
   CLOSED: [2018-09-15 Sat 00:35]
:PROPERTIES:
:EXPORT_FILE_NAME: 0915-pasta-puttanesca
:EXPORT_HUGO_TAGS: "pasta" "tomato"
:CREATED:  [2018-09-25 Tue 00:35]
:END:
```

Then I create a new post via org-capture, the file will be the following and automatically saved by `auto-save-buffer.el`.

```org
* 2018
:PROPERTIES:
:EXPORT_HUGO_SECTION: 2018
:END:
** DONE post1
   CLOSED: [2018-09-15 Sat 00:35]
:PROPERTIES:
:EXPORT_FILE_NAME: 0915-pasta-puttanesca
:EXPORT_HUGO_TAGS: "pasta" "tomato"
:CREATED:  [2018-09-25 Tue 00:35]
:END:
** TODO post2
:PROPERTIES:
:EXPORT_FILE_NAME:
:EXPORT_HUGO_TAGS: 
:CREATED:  [2018-09-26 Wed 15:45]
:END:
```

In this case, the second post will be immediately exported as `2018/.md` because `org-hugo--parse-draft-state` always return `t`. Moreover, `2018/a-new-.md` could be exported during thinking the blog title because `auto-save-buffers.el` will be activated after going by an idle time, e.g. 1.5[s].

My proposal is refining the behavior of `org-hugo--parse-draft-state`. The function should return `t` only when the org state is `DRAFT` or specifying `HUGO_DRAFT` in the post.

Something like this:
```lisp
(if (member (org-entry-get (point) "TODO") org-done-keywords)
    nil
  (progn
    (if (string= "DRAFT" (org-entry-get (point) "TODO"))
        t
      nil)))
```

**Comment by kaushalmodi** [comment]
> Then I create a new post via org-capture, the file will be the following and automatically saved by auto-save-buffer.el.

Also, you will not face this bug if you derive your Org capture template from the ox-hugo documentation. I use `org-hugo-slug` to derive the export file name from the title (and I always type the title at the capture prompt).

**Comment by takaxp** [comment]
Yep. But I didn't follow the template that you mentioned, and sometime I decide the title after `C-c C-c` or `C-u C-c C-c` for org-capture :)
So, I'll customize my config for `auto-save-buffers.el` to prevent auto saving if the cursor on the same line of `EXPORT_FILE_NAME` :)

**Comment by kaushalmodi** [comment]
Unrelated question: I am curious why you are using EXPORT_HUGO_TAGS instead of the normal Org tags. 

If you use Org tags, you can "collect" tags from the parent hierarchy too.

```
* Cooking posts :cooking:
** Pasta recipes :pasta:
*** Pasta Puttanesca :tomato:
:PROPERTIES: 
:EXPORT_FILE_NAME: 0915-pasta-puttanesca :END:
This post has all 3 tags: cooking, pasta, tomato
```

**Comment by takaxp** [comment]
That's interesting. But I want to keep my all posts in the second level of org headings. In order to that, if I put all tags to the headings, the headings will be messed up. Since I want to keep the heading line clean and simple, I usually put only one category to the heading line like `@cooking` and put multiple tags in `EXPORT_HUGO_TAGS` :)

**Comment by kaushalmodi** [comment]
> sometime I decide the title after C-c C-c or C-u C-c C-c for org-capture

Hmm, that first C-c C-E after capture shouldn't have caused the export in any case. I'll investigate.

**Comment by takaxp** [comment]
Here is a demo.

![untitled](https://user-images.githubusercontent.com/136673/46078250-914d8300-c1ce-11e8-92b7-6b65db1d6619.gif)

**Comment by kaushalmodi** [comment]
@takaxp OK, after that last commit, now at least the ".md" files won't export. If you attempt to export, you will get:

> FILENAME.org: Point is not in a valid Hugo post subtree; move to one and try again

So that was part 1 of the problem.

Let's resolve the part 2 of the problem (why C-c C-c attempts to export in Org Capture) in https://github.com/kaushalmodi/ox-hugo/issues/212.

Thanks for reporting such issues!
