### ISSUE TITLE
HUGO_SECTION Org keyword vs subtree property

### ISSUE THREAD

**Issue by cro** [kaushalmodi/ox-hugo#214]
Apologies, I searched the docs and I can't find an answer to my question.

The ox-hugo docs imply that the preferred workflow is to export many subtrees from a single org file.  Is there a way to specify which HUGO_SECTION a subtree belongs in?  I guessed that you could put HUGO_SECTION in the property drawer of a subtree, but this doesn't seem to work. Is there another way?

**Comment by kaushalmodi** [comment]
> I guessed that you could put HUGO_SECTION in the property drawer of a subtree, but this doesn't seem to work.

Just making sure.. are you using the "EXPORT_" prefix? That's just how subtree exports work in Org mode. When the properties are in subtrees, they need the "EXPORT_" prefix. 

Let me know if you need examples (you can even grep for EXPORT_HUGO_SECTION in this entire repo for many examples).

**Comment by cro** [comment]
That was the missing piece--I didn't connect that I could put `EXPORT_` in front of the properties.  Thank you very much!
