### ISSUE TITLE
images are not rendered to html

### ISSUE THREAD

**Issue by jarss** [kaushalmodi/ox-hugo#219]
Hi, 

When using Org with inline images, images links are not created. 

I use org-mode's C-u C-c C-l to create a link to the png file. in org-mode, I see the link [[file:<path to file>]]. When publishing wiht Ox-Hugo however (C-e C-H -C-H), the rendered .md creates a link to the root of the site, not the /static folder. If I place the image in the root, same issue, even though now the path is correct. In both cases a broken image link symbol is shown. 

The path to the repository is https://github.com/jarss/TAONAW

**Comment by kaushalmodi** [comment]
You happen to have hit a jackpot :)

You uncovered probably the only major Hugo bug that I still face, but luckily that `figure` shortcode workaround is possible.

This doesn't happen for normal ~https://www.foo.com/~ domains. But your domain has a subdir in BaseURL: ~https://www.foo.com/SUBDIR/~. So this issue happens. But with that PR, that issue will be fixed.

This is not an ox-hugo issue.

**Comment by jarss** [comment]
Ohh! What do I get? What do I get??

I guess I can include image the "regular" Hugo way, once I figure that one out. I'm not sure why it doesn't work if the path in the .md file is correct.

**Comment by kaushalmodi** [comment]
> path in the .md file is correct.

The path in the .md file becomes `/image.png`. The forward slash means the domain root, which happens to be `https://jarss.github.io/` in your case. 

As the image is not present there, you don't see it. 

The custom figure shortcode prevents image URLs from being relative links like that, and instead prefixes all the image links with the BaseURL set in your site config. 

I hope that makes sense.

**Comment by kaushalmodi** [comment]
>  I can include image the "regular" Hugo way, 

This *is* the regular Hugo way. 

The issue surfaces because you are using a BaseURL with a subdir. 

Not sure if your know, but if the rename your site repo to literally **jarss.github.io**, your site will deploy on https://jarss.github.io/ directly, and then you don't need to use that figure code. 

To test out that, simply change your BaseURL to https://www.example.com, **don't commit that**. But then kill and restart Hugo server, and you will see the images show up fine, without that custom figure shortcode.

**Comment by jarss** [comment]
Hmmm. I think I get it - the root of the site is different than the root Hugo thinks the site is on because I use pages on GitHub. Still, not sure why this happens locally as well. Some possible workarounds: 
1. edit the html files themselves to reflect the path as it is on the site. This will need to happen each time I build the site
2. point to another location altogether (store images elsewhere), this works in org, doesn't require extra editing, and will keep working
3. maybe use the [figure shortcode](https://gohugo.io/content-management/shortcodes/#figure), still need to read about that to make sure I get how to use it. Also need to read up what you posted above.

**Comment by kaushalmodi** [comment]
> Here are the details of what I had to do:

Yes, I did just that in that PR. (Did you look at the diff of that PR?)

> Did you say the next Hugo version will support this? I assumed I wouldn't need to remove figure.html.

No, I don't think Hugo will update the internal figure shortcode to use this version that auto-prepends the BaseURL. 

I might move this shortcode to a Hugo theme component. Then people won't need to manually update it; they'd just update that theme component. 

You can close this issue once you deploy your site with the images successfully.

**Comment by jarss** [comment]
I don't know what PR is   >.>  (sorry, still new to all of this!) 

This is a big issue (I think) if people use docs in Github etc... but I don't know how widespread this is.

**Comment by kaushalmodi** [comment]
@jarss oh boy! I thought you would have received an email or a notification or something when I sent you this PR (pull request) yesterday: https://github.com/jarss/TAONAW/pull/1/files.

**Comment by jarss** [comment]
Oh I see. 

I probably did but I'm pretty bad at checking my email for these things. a PR makes sense here (in GitHub) but I wouldn't know to look for it because I am just now learning how this works xD

Oh well. Glad I figured out how to use what you said. I sense there's a blog post coming in the near future about my beginnings with Hugo...
