### ISSUE TITLE
Advice on hugo slideshow with audio from ox-hugo

### ISSUE THREAD

**Issue by tsdye** [kaushalmodi/ox-hugo#220]
Aloha Kaushal,

I'd like to migrate several slideshows with audio to hugo-generated web pages so my students can view them on their devices more easily.  The source file is an Org mode document that I currently export to pdf.  I made a custom link for the audio clips that embeds them in the pdf file.

Two questions:

1) Do you have an example of an audio link that ox-hugo will export, along with any necessary front-matter setup?  I see that ox-hugo has audio support, but it isn't clear to me how to use it.

2) Can you recommend a hugo theme that supports audio and would be suitable for an academic-looking slideshow?  Any advice on how I might approach this would be appreciated.

All the best,
Tom

**Comment by tsdye** [comment]
Aloha Kaushal,

Thanks for the advice and information.  Helpful, as usual.

Following, please find the custom audio link I've been using for pdf export.  You can see it in action by downloading [this large file](http://www.tsdye2.com/anth_464_spring_2018/anth-464-archaeology.pdf) and opening it in Adobe Acrobat.  This setup has worked OK for a few years,  but every semester a few students struggle with the fact that the pdf file opens in the browser, which won't play the audio.  A responsive html presentation seems to be what the students want; many of them prefer looking at their phones instead of sitting at a computer.

The audio clips I'm using are saved in mp3 format.

Let me know if you have questions.

All the best,
Tom

*** Audio link                                                     :noexport:
The audio link is set up to export an invisible audio link into a pdf
file for viewing with Adobe Acrobat (doesn't work in Skim).  It is set
up to playback the audio file in the link when the pdf page is first
visible, starting always from the beginning.  There are no controls
for playback.

A playback window shows progress.  It appears at the top right corner
of the slide.

Its typical use is at the beginning or end of a slide.

The link assumes: (add-to-list 'org-latex-packages-alist '("" "media9"))

```
#+name: audio-link
#+header: :results silent :exports none
#+begin_src emacs-lisp
(org-add-link-type
 "audio" nil
 (lambda (path desc format)
   (cond
     ((eq format 'latex)
      (format "\\includemedia[
  addresource=%s,
  width=1cm,
  height=\\baselineskip,
  transparent,
  windowed=@tr,
  activate=pagevisible,
  noplaybutton,
  flashvars={
    source=%s
   &autoPlay=true
  },
]{}{APlayer.swf}" path path)))))
#+end_src


```

**Comment by kaushalmodi** [comment]
@tsdye I was revisiting the ox-hugo code that created audio front-matter and I noticed that it was inconsistent with the videos and images front-matter.

The latter two are lists, while audio was not a list.

In https://github.com/kaushalmodi/ox-hugo/commit/c0f3ec57f4c3e500684933baa9a27b18752940df, I have made the `audio` front-matter a list too.

**Comment by kaushalmodi** [comment]
@tsdye Well, soon after I committed that, I realized why I had decided to keep `audio` a non-list :). See the commit message in https://github.com/kaushalmodi/ox-hugo/commit/2ee6036d632cb76f0e270b29005ab00c4a5804aa.

**Comment by kaushalmodi** [comment]
@tsdye I don't know JS, so I pulled up something very basic from https://www.w3schools.com/jsref/met_audio_pause.asp and created a basic audio playing page in my sandbox repo ([see this commit](https://gitlab.com/kaushalmodi/hugo-sandbox/commit/9fc40208b8ad27a28b9996d1c101440f1cc4e0da) - That commit has all the elements needed to build that page).

Here's the generated page: https://hugo-sandbox.netlify.com/posts/audio-widget-1/.

**Comment by tsdye** [comment]
@kaushalmodi This is super helpful.  Thanks!
