### ISSUE TITLE
null string in tags

### ISSUE THREAD

**Issue by takaxp** [kaushalmodi/ox-hugo#221]
Hi.

I just find that null string tags are exported to markdowns. Is this intended?

![screen shot 2018-10-08 at 16 13 20](https://user-images.githubusercontent.com/136673/46595790-16ad2d80-cb15-11e8-8f2e-59028d38c08c.png)

**Comment by kaushalmodi** [comment]
Yes, this is a bug. Though, I am curious, how did you end up with this bug? Why set empty strings for tags? :)

**Comment by takaxp** [comment]
I just put `""` into `EXPORT_HUGO_TAGS` :)

```
:EXPORT_HUGO_TAGS: "" "hoge"
```

It was happened accidentally while refactoring my tags, but the post was also exported by the auto-exporter. After publishing my new posts including the pot with null tag, then I realized it an empty tag was appeared in the tag could in my Hugo blog.

**Comment by kaushalmodi** [comment]
@takaxp The fix was easy. I think most of your bug reports got resolved by using just `org-string-nw-p` :P You are really good at finding those corner cases! 👍

**Comment by takaxp** [comment]
Interesting, and thanks! 👍

**Comment by kaushalmodi** [comment]
@takaxp Actually I am thinking of reverting that commit and instead throw a user-error if "" tag is found.

I don't see a reason to commit "" to the source Org files permanently. As you said, they happened by mistake, and should be fixed.

That commit just masked the user mistake. But by making this an error, that can be fixed.

**Comment by takaxp** [comment]
That's good idea. For me, `user-error` will be able to provide kind suggestion.

**Comment by kaushalmodi** [comment]
Thanks for the quick response, I'll make the user-error display the name of the front-matter having empty string element.

**Comment by takaxp** [comment]
That's very useful because actually it took some time to find the entry with null field. So if the `user-error` provides information about the mistakes, that's really useful.

**Comment by kaushalmodi** [comment]
@takaxp OK, let me know how it goes after updating to the latest master.

**Comment by takaxp** [comment]
Verified. Works well. Thank you so much :)
