### ISSUE TITLE
Can't find .dir-locals.el to auto export on save

### ISSUE THREAD

**Issue by jarss** [kaushalmodi/ox-hugo#223]
Following the [documents on Set org-hugo-auto-export-on-save](https://ox-hugo.scripter.co/doc/auto-export-on-saving/#step-2-set-org-hugo-auto-export-on-save), it says to set up .dir-locals.el but... I can't find this file. 

My content org file is in the root of the file (I push it to git with each update, I think this is quite cool). So "If you have the Org file directly in the project root or in the same directory as the .dir-locals.el, add this in that file instead:" but... I can't find this file. I looked around my site and I don't see it. I guess I could just create it, but I'm not sure if this is something I'm supposed to have and the fact that I don't have it signals other issues? 

My init does include (require 'ox-hugo-auto-export).

**Comment by jarss** [comment]
So, just create the file and dump ((org-mode . ((org-hugo-auto-export-on-save . t)))) into it..? Don't I need to create some definitions first or anything? I don't think this is working. 

Reading through the link, this is above my head (many parts of the emacs manual are still). I will revisit it a later date.

**Comment by kaushalmodi** [comment]
I had even added this as part of the PR I had sent for your site. But I believe you still haven't looked at it. 

See this commit in that PR: https://github.com/jarss/TAONAW/commit/599765f66949324db77922e1ee5a7b4023ad7c48

**Comment by kaushalmodi** [comment]
So to summarize, you need to **require** the auto export package as shown in https://ox-hugo.scripter.co/doc/auto-export-on-saving/#step-1-require-ox-hugo-auto-export-package, and add the .dir-locals.el. 

If that doesn't work, restart Emacs (it's easier than ensuring that everything is evaluated).

**Comment by jarss** [comment]
OK, so I here's what's in my setting.org (I use babel): 

```
#+BEGIN_SRC emacs-lisp
(with-eval-after-load 'ox
 (require 'ox-hugo))
 (require 'ox-hugo-auto-export) ;If you want the auto-exporting on file saves
#+END_SRC

```
I restarted Emacs, have  .dir-locals.el in the root of the site as you saw, and yes that line is in there... so now I'm saving a line of text I added to the latest post in my .org file, looking at the Hugo local server... nothing. Is something wrong with the setup, or maybe I'm not getting what this is supposed to do exactly?

**Comment by kaushalmodi** [comment]
I noted in your last commit that you missing a dot prefix to that .dir-locals.el file. To have it saved and committed as "dir-locals.el", not ".dir-locals.el". 

(I you are not receiving emails for such messages/comments related to GitHub commits and PRs, may be you should enable them.)

If you are on Windows, look up on if anything special needs to be done to preserve a dot in beginning of a file name.

**Comment by jarss** [comment]
ah. Yep. that was it >.>

I possibly have a bit of dyslexia (serious) where I can miss things like that. You can tell me there's a typo in a word and I'll look at it 5 times and won't see it. 

I get the emails, but I don't always log in. I set up a protonmail account and it's great to be a bit away from Google, but it's not as good when you want to get notifications and don't have the tab open. Need to get in the habit. 

Thanks for helping me with this one as well :)
