### ISSUE TITLE
support hindsite

### ISSUE THREAD

**Issue by reuleaux** [kaushalmodi/ox-hugo#229]
I came across hindsite, kind of a simpler hugo, cf.
  https://github.com/srackham/hindsite
which builds upon blackfriday as well, and thus I thought, that ox-hugo could
be a fit for hindsite as well: this has worked for me with some minor issues, cf my workaround:
 https://github.com/srackham/hindsite/issues/1
but maybe ox-hugo could support hindsite out of the box in the future ?

**Comment by kaushalmodi** [comment]
Sorry, I cannot make the suggested changes to date and author to fit hindsite implementation.

You already received my my detailed reply at https://github.com/srackham/hindsite/issues/1#issuecomment-434164900, but linking it here just for back reference.

You might find these useful to make hindsite-friendly exports:
- https://ox-hugo.scripter.co/doc/custom-front-matter/
- https://ox-hugo.scripter.co/doc/author/
- https://ox-hugo.scripter.co/doc/source-blocks/#code-fences (The source block exports should also work for hindsite as long as you do not use the Org mode `+n` / `-n` src block header switches or the `:hl_lines` ox-hugo-specific feature).

**Comment by kaushalmodi** [comment]
@reuleaux 

So it looks like you will not need the date format workaround once hindsite supports TOML date types in front-matter (right now, hindsite treats dates as strings and so you need to add those quotes in that workaround).

About the author issue, doing the suggested in https://ox-hugo.scripter.co/doc/author/#forcing-author-to-be-a-string--alternative might prove to be much simple than the elisp hack you are doing.

Let me know how they work.

**Comment by kaushalmodi** [comment]
You already had the `date` working for hindsite by setting `org-hugo-date-format`.

I hope it's safe to assume that you got the author working as well, by using the "forcing author to be a string" workaround I linked above.

Closing this issue.
