### ISSUE TITLE
Single subtree exports with wrong file name

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#23]
Single subtree exports should name the `.md` file based on the exported headline. But instead it takes the source Org file name.

If I have a `foo.org` with a subtree with heading *Post 1*, the exported file should be named something like `post_1.md`, **not** `foo.md`.

Do `C-c C-e H H` to export only the current subtree.

**Comment by titaniumbones** [comment]
This is a more general problem with the org exporter. We can do a check for the "EXPORT_FILE_NAME" property before export, and if it doesn't exist, generate it from the heading.  

Best practice, though, is to use that property directly.   So maybe we should actually set the property *in the org file itself* if it doesn't exist.

**Comment by kaushalmodi** [comment]
> So maybe we should actually set the property in the org file itself if it doesn't exist.

Thanks. Looks like that's the way to go.

We can have an interactive function to create a new subtree (may be pair that with org capture) and few properties are added automatically:

- EXPORT_DATE
- EXPORT_FILE_NAME
- EXPORT_DRAFT (or EXPORT_HUGO_DRAFT) set to "false"
- EXPORT_SLUG (may be)

This can be a defcustom.

**Comment by titaniumbones** [comment]
Wait, don't we want to preserve the existing subtree and just set those property values? if we create a new subtree, then we're duplicating the org source, which sounds messy to me.

**Comment by kaushalmodi** [comment]
Hmm, there is some confusion.

See [this example][1]. In there "Overriding default tags" and "Specifying additional tags" are two separate posts in separate subtrees. So each subtree will need unique values of date, file name, draft, slug, etc. (basically all Hugo front matter variables).

So my suggestion was that when a new blog post drafting begins, a new subtree/heading be created with certain front matter vars (like date, file name, draft, slug) auto-populated based on a defcustom.

User interaction:

1. Calls interactive function to write a new blog post.
2. Minibuffer prompts user to type the blog post title.
3. A new subtree is created with the heading set to that title.
    - That title helps generate the file name and slug (replace symbols with spaces, spaces with hyphens, etc.) --[example][2]
    - Sets the *draft* status by default (if specified in the defcustom)
    - Sets the *date* as per [this precedence][3].

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/tests/org/tags-and-keywords/tags-and-keywords.org
[2]: https://gist.github.com/kaushalmodi/af385e18b50cf665cd93d4b7f167302d#file-hugo_new_post-sh-L83-L98
[3]: https://github.com/kaushalmodi/ox-hugo/blob/3e58ef9f5b86a02bf784c197d1fdded0718cdecf/ox-hugo.el#L266-L271

**Comment by kaushalmodi** [comment]
This is sort of implemented in https://github.com/kaushalmodi/ox-hugo/commit/e8566709b15257357b40e6899975b1058e08520c with a new interactive function `org-hugo-export-current-subtree`.  That will export only the current or parent subtree which first matches the condition that an EXPORT_FILE_NAME property be present.

**Comment by kaushalmodi** [comment]
This got fixed a while back after we started using EXPORT_FILE_NAME.
