### ISSUE TITLE
Tables with merged cells and partial lines?

### ISSUE THREAD

**Issue by amca01** [kaushalmodi/ox-hugo#230]
Is it possible, either in markdown or in ox-hugo, to create a table which includes merged cells (like the html `colspan`) and lines that only go under some of the cells?  What I'm after is something like this:

                           Demands
                    100  100  100  100  100
                   -------------------------
              100 | 100  100  100  100  100 
     Supplies 100 | 100  100  100  100  100
              100 | 100  100  100  100  100

(The numbers are just place fillers here.) But you see what I want: the term "Demands" spans the last 5 columns, and so does the line underneath them.  Can I get an affect like this with ox-hugo?  I know I can get it with html (or plain text as here), but I was hoping there'd be an easier way.  Thanks!

**Comment by kaushalmodi** [comment]
Hello,

What you want can be best done using direct HTML tables, or may be some CSS tricks too. 

Org mode has support for [column grouping][0] (merging) only, but not row merging. Though, I believe, that only ox-html can do that. 

Blackfriday Markdown (used by Hugo) supports none of them. So I have limited the table features only to those supported by Blackfriday. 

Unfortunately, HTML tables might be the only way to go to get true merged cells. 

[0]: https://orgmode.org/manual/Column-groups.html#Column-groups

**Comment by amca01** [comment]
Thank you very much - that's fine; I'm happy to use html if I have to.  I've also tried with MathJax, but unfortunately MathJax doesn't support all of LaTeX array/tabular features (such as "multicolumn" for merged cells).  Thanks again!

**Comment by kaushalmodi** [comment]
If you haven't already, check out some exampkea of table styling that you can do with ox-hugo here: https://ox-hugo.scripter.co/doc/table-styling/.

**Comment by amca01** [comment]
I'll look at those examples with more detail - thanks!

**Comment by kaushalmodi** [comment]
@amca01 As the inability to have merged cells is gated by Org syntax and what Blackfriday allows, I'll close this issue.

Looks like HTML/CSS is the only resort in this case.
