### ISSUE TITLE
Question about linking to figures and tables

### ISSUE THREAD

**Issue by FelixBrendel** [kaushalmodi/ox-hugo#233]
Hello again,

I have a question regarding referencing images or tables that have the `#+name: <name>` property set.

I can then reference these figures using `[[<name>]]`. Doing this will insert the figure / table number as a clickable link. This works with HTML and latex as well, and should not be news. 

When exported to latex the link will be turned into a `\ref{}` and usually I change this in the latexheader to actually call `\autoref{}` which not only inserts the number as a link but also the name of the type that you are referencing. 

So for example when referencing a table called `table_ref` by using the org link `[[tab_ref]]` it will appear in the pdf as `Table n` depending on the actual number.

Now I want to ask if there is a way to have a similar effect in ox-hugos export.

Just `[[table_ref]]` will be transformed into `[1](#table-1)` And if I have a named link `[table_ref][name]` then the number will not be generated at all.

Do you think there is a way to archive what I am looking for?

**Comment by kaushalmodi** [comment]
Hello,

I believe I already have implemented (maybe partially) what you are looking for? 

It will be clearer if you can present the **expected** Markdown snippets. 

If you haven't already, look at this test: https://ox-hugo.scripter.co/test/posts/links-to-tables/. The links to tables translate to table numbers.

**Comment by kaushalmodi** [comment]
.. and you will find similar tests for figures and source blocks too.

**Comment by kaushalmodi** [comment]
Ah OK, I stayed away from the type insertion because I played with it and couldn't find a consistent way that could always work. 

Example:

- Problem of capitalizing the type or not. 
- Call it "code snippet" vs "listing" vs ??
- Call it "figure" vs "image" vs ??

So I just left that out. User can write such links as:

- `Table [[tab__refa]]`
- `[[tab__refa][above table]]`

>but can I inject additional text into the link and also have the automatic numbering in there?

Let me think of a good way to do that.

**Comment by FelixBrendel** [comment]
The way autoref for latex does this is by always capitalizing the type and it has a default name for every type but that can be customized (for example for different languages). 

What do you think of the idea of of being able to toggle type insertion with something like `#+hugo_auto_insert_types: t` and setting the inserted names with something like `#+hugo_type_name_table: Tabelle`?

**Comment by FelixBrendel** [comment]
If one would want to make a contribution reagarding this issue, could you point to the relevant code or some information about the code structure? (This feature would be really nice to have for me, but I am not the best lisp hacker. However I want to try anyways xD)

**Comment by kaushalmodi** [comment]
The change needs to go in this section:

https://github.com/kaushalmodi/ox-hugo/blob/99e77158bfab545dfd1a3d71cfd2698195a65653/ox-hugo.el#L1971-L1989

If a defcustom `org-hugo-link-desc-insert-type` is set (default is nil), insert the type (no need for the `#+hugo_..` keyword as this would be something that a user would want to user in all of their sites or none. And in case they want to change that for only few sites, they can do that in .dir-locals.el. (I had created just this defcustom in a WIP branch: https://github.com/kaushalmodi/ox-hugo/commit/53e7c837cc8189d2a43f02f06a58f23c6ac88209).

In addition create an ox-hugo internal defvar that's an alist that maps Org elements to the type strings. `src-block` -> "Code Snippet", `table` -> "Table", `figure` -> "Figure". As an extra step, use `org-html--translate` (yes, HTML) to translate those to user local language. See https://github.com/kaushalmodi/ox-hugo/blob/99e77158bfab545dfd1a3d71cfd2698195a65653/ox-hugo.el#L2025 for example of that.

As this feature needs a couple of pieces to be put in place to be complete, I haven't yet got to that.

Thanks for offering the help. Start with using that defcustom I linked above, and gradually make it more generic:

1. First hard-code the type strings in that section I linked above, using that defcustom
2. Then add that alist `defvar` (I do not want to make that a defcustom), and get values from that alist to replace the hard-coded values.
3. Next use the `org-html--translate` returned string if any.
4. Don't forget to add tests.

**Comment by kaushalmodi** [comment]
@FelixBrendel But before you start spending any time on this, it's necessary to assign your copyright to FSF. See the top 2 links on https://ox-hugo.scripter.co/doc/contributing-guide/.

Some day, when that that internal linking issue get resolved, I plan to submit this package to GNU Elpa. *I am not yet doing that as I finding ox-hugo a bit incomplete without that.*

**Comment by kaushalmodi** [comment]
@FelixBrendel I might actually have this implemented in few hrs.

**Comment by FelixBrendel** [comment]
Wow great effort! Then I will wait and see where I can be helpful!

**Comment by kaushalmodi** [comment]
@FelixBrendel Done. Major work was organizing the tests so that I am not adding redundant text for tests with `org-hugo-link-desc-insert-type` = `nil` (default) and `org-hugo-link-desc-insert-type` = `t`. 

See https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/single-posts/links-to-org-elements.org where I set this at the bottom of the file:

```
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# org-hugo-link-desc-insert-type: t
# End:
```

The issue got auto-closed as I linked a commit to "Fix" this, but feel free to comment further in this same thread.

**Comment by FelixBrendel** [comment]
That is absolutely awesome! Thank you so much for yourhard work!!
I read your code and it seems you introduced org-blackfriday--org-element-string to give names to the elemens, could you give a quick example how one could change them on a per document basis?
Thank you again!

**Comment by kaushalmodi** [comment]
> could you give a quick example how one could change them on a per document basis?

You can set `org-blackfriday--org-element-string` in .dir-locals.el in that doc directory. But as I don't expect folks to change this too frequently, I haven't made that a defcustom, and so I haven't marked that as a safe local variable too.

So the first time that .dir-locals.el gets evaluated, you'll get a prompt if you want to mark it as safe, hit `!` in that prompt to save that preference.

If you are not aware of .dir-locals.el, see https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html.

**Comment by kaushalmodi** [comment]
btw if you want to set the table string as "Tabelle" (based on your earlier comment) instead of "Table", just set `#+language: de` at the top of your Org file .. It should get auto-translated.

**Comment by kaushalmodi** [comment]
> It should get auto-translated.

Confirmed!

I just added `#+language: de` at the top of the test Org file, and this was the diff in the exported file: https://ptpb.pw/09qT/diff.

**Comment by kaushalmodi** [comment]
There is not approval process. The update should be published by Melpa in an hour or so.

**Comment by kaushalmodi** [comment]
I have updated that test: https://ox-hugo.scripter.co/test/singles/links-to-org-elements/ 😄

**Comment by FelixBrendel** [comment]
Some random german in the docs, yay! 😊 Thank you again for your work!
