### ISSUE TITLE
Q: How to link files like executables in a post?

### ISSUE THREAD

**Issue by Compro-Prasad** [kaushalmodi/ox-hugo#235]
Like images I want to link executables. How can I do it?

**Comment by kaushalmodi** [comment]
I hadn't yet seen a use case of committing executables to git repos! This is the first time. 

If your executables have an extension, org-hugo-external-file-extensions-allowed-for-copying` would help. 

Can you give a specific use case?

**Comment by Compro-Prasad** [comment]
I am writing a post for CTF solution. It isn't necessary though. Just wanted a way to do it and it works. Thanks!
