### ISSUE TITLE
How to add arbitrary code?

### ISSUE THREAD

**Issue by fkgruber** [kaushalmodi/ox-hugo#237]
Hi
I would like to add arbitrary html/javascript code. Is there any easy way to accomplish this?

Specifically I would like to add this code to generate a photo album as generated from:
http://nano.gallery/builder2.html

For example this could look like:
```
<!-- nanogallery2 portable - http://nano.gallery -->
<div id="ngy2p" data-nanogallery2-portable='{"itemsBaseURL":"http://nanogallery2.nanostudio.org/samples/","thumbnailWidth":"200","thumbnailAlignment":"center"}'>nanogallery2
  <a href="berlin1.jpg" data-ngthumb="berlin1t.jpg" data-ngdesc="">Berlin 1</a>
  <a href="berlin2.jpg" data-ngthumb="berlin2t.jpg" data-ngdesc="">Berlin 2</a>
  <a href="berlin3.jpg" data-ngthumb="berlin3t.jpg" data-ngdesc="">Berlin 3</a>
</div>
<script> var st = document.createElement('script'); st.type = 'text/javascript'; st.src = '//nano.gallery/portable.php?k=m&u='+encodeURI(window.location.href); document.getElementsByTagName('head')[0].appendChild(st); </script>
<noscript>Please enable javascript to view the <a href="//nano.gallery">gallery powered by nanogallery2.</a></noscript>
<!-- end nanogallery2 -->
```

I tried the EXPORT_HTML block but that didn't seem to work. 

What is the right way to do this? 

thanks
FKG

**Comment by kaushalmodi** [comment]
> I tried the EXPORT_HTML block but that didn't seem to work.

That's incorrect syntax. Use `#+begin_export html` .. `#+end_export` instead.

Example: https://ox-hugo.scripter.co/test/posts/export_block_html/

---

I'm traveling (for another 2 weeks). So my responses would be delayed.

**Comment by kaushalmodi** [comment]
I'd like to know if you were able to resolve this issue by using the correct syntax. But it has been more than 2 weeks, and no response. So I am closing this issue.

Feel free to comment further in this thread even if it is closed.
