### ISSUE TITLE
The top-most Markdown heading level in a post should be level-2

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#24]
Always translate level N Org headline to level N+1 Markdown headline because Markdown level 1 headline and HTML title both get the HTML \<h1\> tag, and we do not want the top-most heading of a post to look the exact same as the post's title.

So, within a post, `* Heading 1` should translate to `## Heading 1` in Markdown.

**Comment by kaushalmodi** [comment]
This is now supported with:

```
#+OPTIONS: loffset:1
````

With that,

```
* Heading 1
```

will translate to

```
## Heading 1
```

**Comment by titaniumbones** [comment]
should this be` hugo-loffset`, to indicate that it's hugo-specific?

**Comment by kaushalmodi** [comment]
I thought about that, but then didn't seem necessary to make that name longer. Here's why:

- "loffset" is anyways a weird looking string. I really doubt it will cause conflict with a future exporter backend.
- I might integrate this into ox-md.el. Even then we would be fine; no conflict. 
- If someone has "#+OPTIONS: loffset:1" in their Org file, and they are not exporting to Hugo, I think it won't complain. 

What do you think?

(Also, do you think you'd use this? Or keep the default offset of 0? Probably it's just my OCD to have this feature :))

**Comment by kaushalmodi** [comment]
@titaniumbones I was thinking more on this.. thinking of removing "loffset" OPTION altogether and keeping just HUGO_LEVEL_OFFSET. 

In addition, also planning to set the default value of HUGO_LEVEL_OFFSET to 1. 

Do you have any objection?

**Comment by kaushalmodi** [comment]
@titaniumbones I have gone ahead and removed support for `loffset` from `#+OPTIONS`. Also the default value of `HUGO_LEVEL_OFFSET` is now `1`. If you like, you can go back to the previous 0 offset by adding below to the Org file:

```
#+HUGO_LEVEL_OFFSET: 0
```

**Comment by shimmy1996** [comment]
It seems that the exported `HUGO_LEVEL_OFFSET` option from org is by default a string and this would cause problems with loffset. Here's a quick hack I pieced together but there may be better ways:
```
(car (read-from-string (plist-get info :hugo-level-offset))))
```

**Comment by kaushalmodi** [comment]
@shimmy1996 Hello! Can you please post a minimal working example that reproduces the problem? I'll have a look at that and fix it when I get to a computer.

**Comment by shimmy1996** [comment]
@kaushalmodi Sure thing, here's a short repro:
```
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: ./
#+HUGO_LEVEL_OFFSET: 0

* Homepage
:PROPERTIES:
:EXPORT_FILE_NAME: _index.md
:EXPORT_TITLE: Home
:END:

** Hello World!

Hello!
```
Directly exporting the subtree or exporting all subtrees will get the following error:
```
Wrong type argument: number-or-marker-p, "0"
```
Which I think is caused by the exported option `HUGO_LEVEL_OFFSET` being a string instead of a number.
