### ISSUE TITLE
Shortcodes for a gallery?

### ISSUE THREAD

**Issue by amca01** [kaushalmodi/ox-hugo#242]
I'm trying to incorporate a gallery into one of my pages: I simply want all images in a directory to be displayed as thumbnails, from which a full size image can be chosen by selecting its thumbnail.

I'm experimenting with [hugo-easy-gallery](https://github.com/liwenyip/hugo-easy-gallery) which advises the syntax

    {{< gallery dir="/image_dir/" />}}

which doesn't work in ox-hugo, as the two slashes around `image_dir` are interpreted as italic.  The syntax

    {{< gallery dir="/image_dir" >}}

sort of works, except that (a) not all image thumbnails are shown, (b) some of the thumbnail orientations are wrong (but the corresponding image is correct), (c) the thumbnails are rectangular instead of square.

I don't know if this is a hugo issue, an ox-hugo issue, a hugo-easy-gallery issue, or a Blackburn theme issue.  But I'd like to be able to easily and simply display a directory of images.

I've entered the shortcode above directly into my org file: no surround fencing, such as of `#+begin_something` and `#+end_something`.  Anyway, any advice on how to set up a gallery of images from a directory would be welcome.  Thanks!

**Comment by kaushalmodi** [comment]
While most shortcodes work with ox-hugo, it cannot be guaranteed that they will always work, because Org mode doesn't identify the shortcodes as something special. 

So what you are seeing is bound to happen. 

Can you try converting your shortcode to an Org macro? That way, you will also make your Org document "more pure" Org :)

**Comment by amca01** [comment]
Thank you - well, that would require an expertise that I don't currently have.  But is there a better "org-friendly" way of making a gallery from a directory?  I could probably simply use a JavaScript gallery creator, and there are plenty of those!

**Comment by titaniumbones** [comment]
@amca01 while I love @kaushalmodi 's suggestion and i will use it myself, I doubt that it will solve your problem.  The gallery shortcode generates the list of files using a very straightforward readDir` command: https://github.com/liwenyip/hugo-easy-gallery/blob/master/layouts/shortcodes/gallery.html#L10 . The final slash is unlikely to change the output of that command.

 perhaps you could try manually adding a markdown file containing the shortcode to the hugo site (so, including that file outside of the org-hugo  export process). If it works, hen you know the problem is with org export; but I bet it is somewhere else in the stack.

**Comment by kaushalmodi** [comment]
I am traveling right now. Let me see if I can find a solution next week.

**Comment by amca01** [comment]
Thank you both... I'm also experimenting with static gallery generators, of which [sitelen-mute](https://github.com/kensanata/sitelen-mute) and [sigal](https://github.com/saimn/sigal) are two.  Currently I'm trying to get sitelen-mute to work; if that fails I'll give sigal a try.  For my purposes this may turn out to be better than wrestling with shortcodes.

**Comment by kaushalmodi** [comment]
@amca01 How about this?

Define a macro called gallery like this at the top of your Org document:

```org
#+macro: gallery @@html:{{< gallery dir="$1" />}}@@
```

The `@@html: .. @@` piece is critical.. Org needs to retain that as an "HTML" snippet and not parse that as Org or Markdown.

And then use that macro as `{{{gallery(/image_dir/)}}}` in that same Org document.

You should see that macro get exported as below in the Markdown file:

```md
{{< gallery dir="/image_dir/" />}}
```

**Comment by kaushalmodi** [comment]
@amca01 Scratch that; you could just do the below instead :D

```org
#+html: {{< gallery dir="/image_dir/" />}}
```

**Comment by titaniumbones** [comment]
wouldn't it be ok also to just pass the html directly form the text
(because probably one will only use the macro once or twice and not that
much typing is saved by adding that extra layer of complexity):

```org
* my fascinating post

I went on vacation and lucky you, you get to see all my pictures.

@@html:{{< gallery dir="/images/some/dir" >}}@@
```


Kaushal Modi <notifications@github.com> writes:

> @amca01 How about this?
>
> Define a macro called gallery like this at the top of your Org document:
>
> #+macro: gallery @@html:{{< gallery dir="$1" />}}@@
>
> The @@html: .. @@ piece is critical.. Org needs to retain that as an "HTML" snippet and not parse that as Org or Markdown.
>
> And then use that macro as {{{gallery(/image_dir/)}}} in that same Org document.
>
> You should see that macro get exported as below in the Markdown file:
>
> {{< gallery dir="/image_dir/" />}}
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by kaushalmodi** [comment]
> wouldn't it be ok also to just pass the html directly form the text

Yes, that's what I later suggest in https://github.com/kaushalmodi/ox-hugo/issues/242#issuecomment-444919381 :)

I, at times, get carried away making something work even if that's the more complex way.

**Comment by amca01** [comment]
Something else to try  - thank you all!

Meanwhile, I have discovered that sitelen-mute in fact works very well.

**Comment by faaafo** [comment]
@amca01 I need to implement a photo gallery in my ox-hugo  :heart: powered blog as well, how did you end up on this topic?
