### ISSUE TITLE
Suggestion: Enable export of todo keywords to <li> heading items 

### ISSUE THREAD

**Issue by DynamicMetaFlow** [kaushalmodi/ox-hugo#250]
Greetings! Thank you for creating ox-hugo! It's been immensely helpful and I intend to use it to document my learning process. 

At the moment one of my projects is to create a public agenda of what I'm working on so I can share it with friends.

One of the stumbling blocks that I'm running in to is that once the heading reaches a certain level the TODO/DONE keywords when exporting from org to markdown does not included the 

`<span class="org-todo todo TODO">TODO</span> `

I was reviewing the functions in ox-hugo.el, particularly (defun org-hugo-headline) and doing my best to figure out how this could be done but to no avail.

I was wondering if it would be at all possible that when using list items that TODO/DONE keywords can also be exported to markdown.

Thank you for your time and consideration!

**Comment by kaushalmodi** [comment]
I read in hurry. You mentioned that:

> One of the stumbling blocks that I'm running in to is that **once the heading reaches a certain level** the TODO/DONE keywords

I think there are two limits.. try bumping the Org-inbuilt heading limit using, I think, `#+options: h:6`.  

The hard limit is the Markdown heading limit of h6, as I think that HTML doesn't go deeper than h6. 

If you share a minimal working example showing that problem, I can have a look in detail once I'm back from my trip (Jan first week).

**Comment by kaushalmodi** [comment]
@DynamicMetaFlow This is now implemented in https://github.com/kaushalmodi/ox-hugo/commit/47d8dd1ac4bb6524a9bb2290123a63d5cf8d758b.

You can get the latest ox-hugo.el from the master branch or wait for the next ox-hugo update on Melpa. Let me know if this issue can be closed (or you can close it too).

**Comment by DynamicMetaFlow** [comment]
@kaushalmodi 
Thank you so much! I really appreciate it. I updated ox-hugo on Melpa and everything works as expected with the TODO tags!
