### ISSUE TITLE
Support inlining SVG - Really useful with PlantUML generated SVGs with hyperlinks

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#253]
For the hyperlinks to work in SVGs, they need to be inlined, and not be in the `img` tag.

- https://alligator.io/svg/hyperlinks-svg/
- http://plantuml.com/svg

```
@startuml
skinparam svgLinkTarget _parent
start
:[[http://plantuml.com]];
stop
@enduml
```

**Comment by iT-Boyer** [comment]
An error occurred while exporting ~@startmindmap @endmindmap~ by org mode
https://github.com/plantuml/plantuml/issues/620#issue-963159710
