### ISSUE TITLE
Latex \{ not escaped

### ISSUE THREAD

**Issue by jethrokuan** [kaushalmodi/ox-hugo#258]
## Actual Behavior

Equations containing `\{\}` or `\left\{\right\}` are not escaped to `\\{\\}` in the exported markdown. This causes hugo's markdown engine to produce `{}` and `\left{\right}`, which are invalid latex math formats.

## Expected Behavior

Expect `\{\}` to be escaped to `\\{\\}`

## How to Reproduce the Issue

Create an org file containing:

```
\begin{equation}
  \phi_j(x) = \mathrm{exp}\left\{ - \frac{(x - \mu_j)^2}{2s^2} \right\}
\end{equation}
```

Result:

![image](https://user-images.githubusercontent.com/1667473/52423991-0ee9ae00-2b34-11e9-92d3-2710dc0e62ab.png)

Expecting:

```
\begin{equation}
  \phi_j(x) = \mathrm{exp}\left\\{ - \frac{(x - \mu\_j)^2}{2s^2} \right\\}
\end{equation}
```

which produces:

![image](https://user-images.githubusercontent.com/1667473/52424029-26c13200-2b34-11e9-995a-ea33861a6f45.png)

## Ox-Hugo Debug Information

* Debug information for =ox-hugo=
** Emacs Version
#+begin_example
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.2)
 of 2019-01-30
#+end_example
** Org Version
#+begin_example
Org mode version 9.2 (9.2-elpa @ /nix/store/l77926g0jh1c3xgivhhmrzs0injs8ycd-emacs-packages-deps/share/emacs/site-lisp/elpa/org-20181230/)
#+end_example
** Hugo Version
#+begin_example
=hugo= binary not found in PATH
#+end_example
*** Org =load-path= shadows
*Warning*: Possible mixed installation of Org
#+begin_example

-- redacted because it was really long --
Study the output of =M-x list-load-path-shadows=.
** =ox-hugo= defcustoms
|org-hugo-section                                      |"posts"|
|org-hugo-use-code-for-kbd                             |nil|
|org-hugo-preserve-filling                             |t|
|org-hugo-delete-trailing-ws                           |t|
|org-hugo-prefer-hyphen-in-tags                        |t|
|org-hugo-allow-spaces-in-tags                         |t|
|org-hugo-tag-processing-functions                     |(org-hugo--tag-processing-fn-replace-with-spaces-maybe org-hugo--tag-processing-fn-replace-with-hyphens-maybe)|
|org-hugo-auto-set-lastmod                             |t|
|org-hugo-export-with-toc                              |nil|
|org-hugo-export-with-section-numbers                  |nil|
|org-hugo-front-matter-format                          |"toml"|
|org-hugo-default-static-subdirectory-for-externals    |"ox-hugo"|
|org-hugo-external-file-extensions-allowed-for-copying |("jpg" "jpeg" "tiff" "png" "svg" "gif" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")|
|org-hugo-date-format                                  |"%Y-%m-%dT%T%z"|
|org-hugo-paired-shortcodes                            |""|
|org-hugo-langs-no-descr-in-code-fences                |nil|
|org-hugo-suppress-lastmod-period                      |0.0|
|org-hugo-front-matter-format                          |"toml"|

**Comment by kaushalmodi** [comment]
Thanks for reporting this issue. I wouldn't have discovered this as I don't use equations :)

The issue is auto-closed based on that commit that fixed this. But feel free to comment further on whether the fix worked for you or not.

**Comment by jethrokuan** [comment]
Can confirm the patch works!
