### ISSUE TITLE
How can I affect the sort order of posts?

### ISSUE THREAD

**Issue by jave** [kaushalmodi/ox-hugo#262]
Hello,

I'm trying to use ox-hug with the Story theme.

Is it possible to affect the sorting order of posts by some other means than the date?
Preferably I would like the order of the entry in the org file to affect the order of posts in the output.

/Joakim

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by jave** [comment]
okay, I found I can something like:

 :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :image /ox-hugo/hierogram.svg :weight -1001

**Comment by kaushalmodi** [comment]
Try `#+hugo_weight: auto` at the very top of the Org file, and then `C-c C-e H A`.

**Comment by kaushalmodi** [comment]
I need to document the weight setting support in ox-hugo: https://github.com/kaushalmodi/ox-hugo/issues/261

**Comment by jave** [comment]
I guess it would be nice to do something like:
 :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :image /ox-hugo/idea_guy.svg :weight {{{n}}}                                                                                                                                   
 
that is, using the {{{n}}} counter macros syntax. But macros dont seem to expand in this context.

**Comment by kaushalmodi** [comment]
> :weight {{{n}}}

Yes, looks like I need to reevaluate how to auto-calculate weights. 

For now, `#+hugo_weight: auto` mostly works like what you suggested. Give it a try and let me know what exactly didn't work for you in the current auto weight setting logic.

**Comment by jave** [comment]
@kaushalmodi thanks! I didn'nt notice your comment before commenting :)

hugo_weight seems to do what I want, thanks!

as you write in #261 it would be nice with some documentation, like how is the weight calculated, when do you need to regenerate all the posts, etc.
