### ISSUE TITLE
[feature request] support export to hugo-academic slides

### ISSUE THREAD

**Issue by showgood** [kaushalmodi/ox-hugo#263]
Hugo theme academic support slides in markdown and use reveal.js to render it. It would be great if ox-hugo can export org file to such markdown format. An example of that markdown is from academic website: https://raw.githubusercontent.com/gcushen/hugo-academic/master/exampleSite/content/slides/example-slides.md

**Comment by kaushalmodi** [comment]
Hello, is there a specific part of that Markdown file that doesn't get exported from Org mode. 

I just quickly glanced through it, and it looks like normal Markdown. 

Example: `-----` in Org mode would export to `---` in Markdown and so on.

**Comment by showgood** [comment]
I couldn't generate the front-matter with ox-hugo no matter what I tried:

+++
title = "Slides"

[slides]
# Choose a theme from https://github.com/hakimel/reveal.js#theming
theme = "black"
+++

Another thing is it would be very helpful if ox-hugo can generate those --- as separation between headlines automatically to save some manual work.

**Comment by kaushalmodi** [comment]
> I couldn't generate the front-matter with ox-hugo no matter what I tried:

>     +++
>     title = "Slides"
>     
>     [slides]
>     # Choose a theme from https://github.com/hakimel/reveal.js#theming
>     theme = "black"
>     +++

See the syntax for map-type custom front matter: https://ox-hugo.scripter.co/doc/custom-front-matter/#maps-of-single-and-list-values

To get the above, you would write:

```
* Slides
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :slides '((theme . "black"))
```

> Another thing is it would be very helpful if ox-hugo can generate those --- as separation between headlines automatically to save some manual work.

Automatically adding `---` would be a very niche requirement for Markdown specific to reveal.js. More importantly, it wouldn't be possible to accurate guess when the user meant to add the slide breaker `---`. For example: What if the user intended to add multiple nested headings in the same slide?

So it's best to have the user type `-----` in Org just as they would need to type `---` in Markdown for the slides.

**Comment by kaushalmodi** [comment]
You can find more examples for custom map-type front-matter in ox-hugo test suite from this search: https://ox-hugo.scripter.co/test/tags/custom-fm

**Comment by showgood** [comment]
I see, got it working, thanks!
