### ISSUE TITLE
Does ox-hugo honor :exclude-tags ?

### ISSUE THREAD

**Issue by fpopineau** [kaushalmodi/ox-hugo#265]
I wanted to use this trick to exclude some sections from export:
```
(defun fp-export-exclude-nobackend-function (settings backend)
  (let ((nobackend (concat "no" (symbol-name backend))))
    (setq settings
          (plist-put settings :exclude-tags
                     (cons nobackend (plist-get settings :exclude-tags))))
    settings))

(add-to-list 'org-export-filter-options-functions #'fp-export-exclude-nobackend-function)
```

It is supposed to add a "nohugo" tag to :exclude-tags dynamically.
It does not seem to have any effect.
Any idea what could go wrong here ?

Thanks in advance,

Fabrice

**Comment by kaushalmodi** [comment]
Hello, I'll have a look at this after a month (busy with personal stuff and a long trip). 

This definitely is an interesting way to dynamically add exclude tags. 

ox-hugo does support exclude tags; I have few tests for them. So I'll see what's going on here.

**Comment by kaushalmodi** [comment]
> It is supposed to add a "nohugo" tag to :exclude-tags dynamically.

I think that it still works at the same level with the other exporters.

Here's an example that I used with your code.

## Org file

```org
#+hugo_base_dir: .
#+hugo_section: .

* post 1
:PROPERTIES:
:EXPORT_FILE_NAME: post1
:END:
** heading 1.1                                                      :noascii:
Not exported to ascii.
** heading 1.2                                                       :nohugo:
Not exported to hugo.
```

## Export to ascii using `C-c C-e t A`

```txt
Kaushal Modi


Table of Contents
_________________

1. post 1
.. 1. heading 1.2                                               :nohugo:





1 post 1
========

1.1 heading 1.2                                                 :nohugo:
~~~~~~~~~~~~~~~

  Not exported to hugo.
```

## Export to hugo using `C-c C-e H H`

```md
+++
title = "post 1"
author = ["Kaushal Modi"]
draft = false
+++

## heading 1.1 {#heading-1-dot-1}

Not exported to ascii.
```

---

So the dynamic exclude tags work for headings within an export.

But if you want to use those dynamic exports to be effective for subtree-based exports, it behaves the same way (doesn't work) for other exports too.

Example: If the point is under heading 1.1, and you do `C-c C-e C-s t A`, you get:

```
                             ______________

                              HEADING 1.1

                              Kaushal Modi
                             ______________


Table of Contents
_________________




Not exported to ascii.
```

---

The exclusion of posts works if I set `org-export-exclude-tags`.

Though .. not when I set the `#+exclude_tags:` keywords .. for any exporter. So I need to investigate this when I get time.

**Comment by kaushalmodi** [comment]
@fpopineau While the tweak to `org-export-filter-options-functions` tweak as in your first post doesn't work (because of how it's designed to be used in `ox.el`), this now works:

```org
#+hugo_base_dir: .
#+hugo_section: .
#+exclude_tags: nonono

* post 1
:PROPERTIES:
:EXPORT_FILE_NAME: post1
:END:
** heading 1.1                                                      :noascii:
Not exported to ascii.
** heading 1.2                                                       :nohugo:
Not exported to hugo.
* post 2                                                             :nonono:
:PROPERTIES:
:EXPORT_FILE_NAME: post2
:END:
This post must not be exported..
```

The thing is that `org-export-filter-options-functions` is effective only for tags of subtrees within an export *scope*.

**Comment by fpopineau** [comment]
Thanks a lot Kaushal !
You investigated this much faster than I could have.

And this helps a lot. It allows to keep some kind of latex->pdf document
for example in the same tree that is exported by ox-hugo.

Regards,

Le lun. 18 mars 2019 à 06:04, Kaushal Modi <notifications@github.com> a
écrit :

**Comment by kaushalmodi** [comment]
@fpopineau I believe it's safe to close this issue. Let me know if it was otherwise and I'll reopen it.
