### ISSUE TITLE
Exporting without evaluation (file setting)

### ISSUE THREAD

**Issue by shrysr** [kaushalmodi/ox-hugo#266]
I would appreciate advice in resolving the problem outlined below. It is not only speciific to ox-hugo,  but exporting in general. 

## Actual Behavior
This is regarding a file specific setting to not evaluate the blocks prior to export. However, each code block is evaluated when exported. 

I've tried including `# -*- org-export-babel-evaluate: nil -*-` as the first line of the file. 

While the method outlined in #158 is fine for some source blocks, I'm looking for a file specific setting. 

Note: The behavior is the same for other exports as well (markdown / txt etc).

## Expected Behavior
To export the source blocks without evaluation. 

## How to Reproduce the Issue
Export to file (hugo compatible markdown or any other export)

### Example text File 
note: github does not let me attach org files. 
[test1.txt](https://github.com/kaushalmodi/ox-hugo/files/3019220/test1.txt)

**Comment by kaushalmodi** [comment]
> This is regarding a file specific setting to not evaluate the blocks prior to export.

I haven't tried but you probably need to use `#+bind: .. ` **and** enable the evaluation of bind keyword variables (don't recall to that variable; you'd have to look up the manual). 

I add this to the top of my Org files (via a common setup file to be used with `#+setupfile:`) instead:

```
#+property: header-args :eval never-export
```

**Comment by kaushalmodi** [comment]
I am not at my PC yet (travelling for few weeks now), and thus the brevity. I'll get to trying your example in a week.

**Comment by kaushalmodi** [comment]
@shrysr Sorry, this issue got lost in the weeds.

I tried out your example, and I noticed that you had this as the first line:

```
# -**- org-export-babel-evaluate: nil -**-
```

instead of:

```
# -*- org-export-babel-evaluate: nil -*-
```

I do have have R on my system, but I tried this:

```org
# -*- org-export-babel-evaluate: nil -*-
#+toc: t
#+hugo_base_dir: ./hugo_temp
#+hugo_section: docs
#+hugo_auto_set_lastmod: t
#+author: Shreyas Ragavan
#+hugo_tags: R Data-science
#+hugo_categories: R Data-Science
#+hugo_menu: :menu "docs" :weight 2001
#+hugo_custom_front_matter: :linktitle R Notes :parent Programming :toc true
#+hugo_draft: false

#+TITLE: R notes and snippets
#+SUBTITLE: Notes, snippets and packages in R for ready reference.

* =promptData()= : generate shell documentation of dataset
:PROPERTIES:
:CREATED: [2019-03-25 Mon 09:43]
:ID:       826c6fb2-0788-42c0-8dd1-d813233fccec
:End:

If the filename argument is given as "NA", the output will provide lists of the information. If no filename is specified, then an .Rd file will be created in the same working directory.

#+BEGIN_SRC sh :export code
ls
#+END_SRC
```

With that, I see this on export:

```
[ox-hugo] Exporting ‘R notes and snippets’ (foo.org)
Saving file /home/kmodi/temp/hugo_temp/content/docs/foo.md...
Wrote /home/kmodi/temp/hugo_temp/content/docs/foo.md
```

If I remove that first line, I see (notice that now we get "org-babel-exp process sh at position 798..."):

```
[ox-hugo] Exporting ‘R notes and snippets’ (foo.org)
org-babel-exp process sh at position 798...
Saving file /home/kmodi/temp/hugo_temp/content/docs/foo.md...
Wrote /home/kmodi/temp/hugo_temp/content/docs/foo.md
```

So it looks like it's working as expected... you probably just had `-**-` instead of `-*-`?

**Comment by kaushalmodi** [comment]
Here's a minimal example:

```
#+hugo_base_dir: ./hugo_temp

#+property: header-args :eval never-export

#+title: Example of not evaluating when exporting

#+begin_src sh :exports both
date
#+end_src
```

When I export this, I get this in the \*Messages\* buffer:

```
[ox-hugo] Exporting ‘Example of not evaluating when exporting’ (foo.org)
org-babel-exp process sh at position 126...
Evaluation of this sh code block is disabled.
Saving file /home/kmodi/temp/hugo_temp/content/posts/foo.md...
Wrote /home/kmodi/temp/hugo_temp/content/posts/foo.md
```

and this in the exported Md:

````md
+++
title = "Example of not evaluating when exporting"
author = ["Kaushal Modi"]
draft = false
+++

```sh
date
```
````

If I remove `#+property: header-args :eval never-export`, I get prompted if that sh block should be evaluated, and I see these in \*Messages\* and the exported Md:

```
[ox-hugo] Exporting ‘Example of not evaluating when exporting’ (foo.org)
org-babel-exp process sh at position 128...
Evaluate this sh code block on your system? (y or n) y
executing Sh code block...
Wrote /tmp/babel-QeX9gH/ob-input-Cv9taL
Code block evaluation complete.
Saving file /home/kmodi/temp/hugo_temp/content/posts/foo.md...
Wrote /home/kmodi/temp/hugo_temp/content/posts/foo.md
```

````md
+++
title = "Example of not evaluating when exporting"
author = ["Kaushal Modi"]
draft = false
+++

```sh
date
```

```text
Mon Sep  9 09:26:54 EDT 2019
```
````

**Comment by kaushalmodi** [comment]
@shrysr  Probably unrelated .. I see that you have `:export` instead of `:exports` (that extra "s") in your example:

```
# ...

#+BEGIN_SRC R :session :export code
promptData(sunspots, filename = NA)
#+END_SRC

# ...
```

See `C-h i g (org) Exporting Code Blocks`.

**Comment by kaushalmodi** [comment]
I just remembered that you are not using Hugo :). So closing this issue. Feel free to open another issue if you stumble across this in future.
