### ISSUE TITLE
How to set property :EXPORT_DATE: implicitly the same as :date:?

### ISSUE THREAD

**Issue by priyadarshan** [kaushalmodi/ox-hugo#268]
I just came to know about ox-hugo, and I am so glad it exists. It is awesome! Finally I can manage my site from one org file.

I have a few questions, I could not find answers to in the documentation.

If it is all rigth I will open one issue per question, but I could also consolidate all in this one if that is better.

I have already a file with several hundreds subtrees, using the `:date:` property to mark when that unit was written. I would like to use that property as an alias for `:EXPORT_DATE:`, so that I do not have to add an additional property, and I can keep the already burgeoning PROPERTY block cleaner.

How can I set property :EXPORT_DATE: so it is implicitly the same as `:date:`?

For example, at export time, `:date: 2019-04-09` would be used as `:EXPORT_DATE: 2019-04-09`.

It seems that is possible with the ["file" workflow](https://ox-hugo.scripter.co/doc/org-meta-data-to-hugo-front-matter/#for-file-based-exports) where TOML frontmatter date is takend from `#+date: 2017-07-24`?

Thank you for ox-hugo!

**Comment by kaushalmodi** [comment]
@priyadarshan Hello! Hopefully this package does what you expect and more :)

I stick to the internal Org implementation when it comes to things like these.

From https://orgmode.org/manual/Export-settings.html:

> When exporting sub-trees, special node properties in them can override the above keywords. They are special because they have an ‘EXPORT_’ prefix. For example, ‘DATE’ and ‘EXPORT_FILE_NAME’ keywords become, respectively, ‘EXPORT_DATE’ and ‘EXPORT_FILE_NAME’. Except for ‘SETUPFILE’, all other keywords listed above have an ‘EXPORT_’ equivalent. 

So, I'd rather just keep the `#+date` and `:EXPORT_DATE:` support as I have now. I can technically add support for `:date:`, but that would mean that `ox-hugo` would need to parse for those special properties .. right now, the `:EXPORT_DATE:` is auto-parsed by the underlying ox.el.

---

> I have already a file with several hundreds subtrees, using the :date: property to mark when that unit was written. I would like to use that property as an alias for :EXPORT_DATE:

May I suggest using a simple `sed` command to replace `:date:` with `:EXPORT_DATE:`?

**Comment by priyadarshan** [comment]
I understand, thank you for quoting the org manual. I though of doing a search and replace, but `:EXPORT_DATE:` has a different semantic meaning that `:date:`, and I wanted to keep the latter. I think I will first experiment with the `TODO` state workflow, too.

Thank you so much for the thorough and lighting-fast replies.

I am closing this now, and perhaps opening it again in the future.

**Comment by kaushalmodi** [comment]
> :EXPORT_DATE: has a different semantic meaning that `:date:`

What is your semantic meaning for `:date:`?

**Comment by kaushalmodi** [comment]
Note that `ox-hugo` also supports `:EXPORT_HUGO_PUBLISHDATE:` (in case that fits your `:date:` meaning better).

**Comment by priyadarshan** [comment]
Although it may happen I sort subtrees based on other properties, the state I prefer my (monolithic) org file to be in is to have all entries sorted by date of initial writing (newest on top). So, to me, `:date:` means "Date when this subtree was initially written.`

Thank you for pointing to `:EXPORT_HUGO_PUBLISHDATE:`!
