### ISSUE TITLE
How to set :EXPORT_HUGO_BUNDLE: to the sanitised title?

### ISSUE THREAD

**Issue by priyadarshan** [kaushalmodi/ox-hugo#269]
I love being able to use Page Bundles. As I said in my previous issue, I have several hundereds subtrees, and I would like to avoid manually entering `:EXPORT_HUGO_BUNDLE:`.

How could one automatically set property `:EXPORT_HUGO_BUNDLE:` to the sanitised title?

For example, If title would be

```
*** Installing illumos: tutorial
```

`:EXPORT_HUGO_BUNDLE:` would be implicitly set to

`:EXPORT_HUGO_BUNDLE: installing-illumos-tutorial`?

**Comment by kaushalmodi** [comment]
I use Org Capture to populate the `:EXPORT_FILE_NAME:`  which becomes `:EXPORT_HUGO_BUNDLE:` for bundles (and the file name becomes either `index` or `_index`).

So in my Capture template, I use `org-hugo-slug` to *sanitize* those names off the subtree heading.

See [that snippet here in the `ox-hugo` docs][1].

---

You can choose to not use Org Capture, but install call `org-hugo-slug` using your custom Elisp to sanitize the `:EXPORT_HUGO_BUNDLE:` property.


[1]: https://ox-hugo.scripter.co/doc/org-capture-setup/#org-capture-template-page-bundle

**Comment by priyadarshan** [comment]
Thank you for pointing to `org-hugo-slug`, that is what I was looking for, I will try to adapt it to my need.

It would be nice to be able to have a setting that allows one to specify that function as way to populate `:EXPORT_FILE_NAME:` or `:EXPORT_HUGO_BUNDLE:`, if not already explicitly set already. It may be a bit off the plan for `ox-hugo`, though.

By the way, congratulations on the documentation, is is remarkable, and a joy to read.

**Comment by kaushalmodi** [comment]
> It would be nice to be able to have a setting that allows one to specify that function as way to populate :EXPORT_FILE_NAME: or :EXPORT_HUGO_BUNDLE:, if not already explicitly set already.

Yes, those would fit more in user-config domain. While they wouldn't fit in ox-hugo itself, I'd happily accept documentation PR for example user config for those (just as I have the Org Capture examples).

> congratulations on the documentation, is is remarkable, and a joy to read.

Thanks! As you would have guessed the documentation is ox-hugo's dog-food .. I just commit the Org files, ox-hugo converts them to Markdown and then Hugo converts those to HTML, all on Netlify servers 😎

**Comment by priyadarshan** [comment]
Wonderful. elisp programming is a bit above my head right now. I will try to concot something, and if worthy enough I will do a PR. 

I find ox-hugo exemplary in clarity, thoroughness and "dog-fooding" :)

Thank you again, I am closing this for now.

**Comment by priyadarshan** [comment]
Ah, it is perfect. You know, ox-hugo is so nice it makes me giddy with happiness.
