### ISSUE TITLE
How to set `:EXPORT_FILE_NAME: index` to a whole file?

### ISSUE THREAD

**Issue by priyadarshan** [kaushalmodi/ox-hugo#270]
I am aware of #123, but I believe this case is not covered there.

I would like to have `:EXPORT_FILE_NAME: index` applied to a whole file.

I tried by having

```
#+EXPORT_FILE_NAME: index
```

at the beginning of org file with no success. When I try to export a subtree without that property set, I get `Point is not in a valid Hugo post subtree; move to one and try again`.

Would it be possible to have property `:EXPORT_FILE_NAME:` inheritable like others?

**Comment by kaushalmodi** [comment]
> I would like to have :EXPORT_FILE_NAME: index applied to a whole file.

That won't be possible as the `:EXPORT_FILE_NAME:` property is **the** indicator I use to mark a post sub-tree (that allows me to have post subtrees at any indentation level).

Using Org Capture might streamline your post creation flow that auto-inserts `:EXPORT_FILE_NAME:` and other properties that you use commonly.

**Comment by priyadarshan** [comment]
I understand, thank you for the quick replies!

**Comment by kaushalmodi** [comment]
@priyadarshan Cool, you can leave the issues open if you'd like to have further discussion on the topic, if something I suggested doesn't make sense, etc. Else, please close them. *I prefer to have the issue originators close the issues themselves.*

**Comment by priyadarshan** [comment]
I see, thank you for clarifying. I usually leave issue open so the mainatiner can decide if/when to use it. I am closing this now on my side.

**Comment by kaushalmodi** [comment]
> I usually leave issue open so the maintainer can decide if/when to use it. 

This particular topic is completely against the ox-hugo design philosophy. I rely on the users to explicitly set the EXPORT_FILE_NAME so that ox-hugo knows what subtree is the post. 

You can search for EXPORT_FILE_NAME on https://ox-hugo.scripter.co/doc/usage/.

**Comment by priyadarshan** [comment]
Thanks again for clarifying, it makes sense. I did read all the documentation before opening the issues, but it is good to now the philosopy behind such a nice program, too.
