### ISSUE TITLE
revisiting headline container div/sections

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#271]
**not a bug report!** 

## Actual Behavior
Currently, IIUC ox-hugo exports to blackfriday MD, which generates relatively minimal HTML

## Improved Behavior?

By default, org-mode HTML export adds container elements to each subtree. This allows CSS to address the subtree with e.g. `div.outline-3 {background-color: lightcoral; border: black solid 1px;}`. This can be a big help in long documents whose parts ought to be set off from each other with some visual cue. 

A somewhat clumsy workaround is described in #160. This is fine if the enclosing element is only desired in rare cases, but is frustrating and inefficient for general use.

## Proposed Solution
It would be nice to have the option to replicate this in ox-hugo, maybe with a `defcustom` to turn the new behaviour on. 

I guess this would be done in `org-hugo-headline`, probably by adding html directly to the markdown file (?). How hard does this sound to you @kaushalmodi? I can take a crack at it maybe in the next few days, but if you can give me some guidance I would of course appreciate it! Thanks,
matt

**Comment by kaushalmodi** [comment]
> I guess this would be done in org-hugo-headline, 

It probably wouldn't be `org-hugo-headline` because that processes just the headline, and not the whole section under it. 



> probably by adding html directly to the markdown file (?). 

Yes, that would be the only way. 

> How hard does this sound to you @kaushalmodi?

As ox-html already does it, I'd guess that it should be easy. 

> I can take a crack at it maybe in the next few days, but if you can give me some guidance ..

Sure, I'll accept a PR. If you haven't already check out the [`HTML_CONTAINER_CLASS`][1] subtree property. As ox-hugo indirectly extends from ox-html, that might just work right out of box (I haven't tried), and if not, then looking at ox-html code should help port the `HTML_CONTAINER_CLASS` support to ox-hugo. 

[1]: https://orgmode.org/manual/CSS-support.html

**Comment by titaniumbones** [comment]
Hi Kaushal,

So, I took a look at the ox-html code and in fact they do wrap the
subtrees in sections in org-html-headline, because that function has
access to `contents`, which is a parsed description of the full subtree.

So it looks like the easiest fix for getting the html in there is just a
1 or 2 line fix around line 1781, e.g. (will need some finessing):

```emacs-lisp
(concat "<section class=\"outline-container\">\n" (org-hugo--headline-title style level loffset title todo-fmtd anchor numbers)
contents "\n</section>\n")
```

however, this runs into a blackfriday limitation you have experienced
elsewhere: https://github.com/russross/blackfriday/issues/404

From your comments there it sounds like you already have a workaround
but unfortunately when I try to add the section tags I completely lose
parsing of the markdown.  Here'ssome example md (the org source is
trivial):

```markdown
---
title: "WDW235 Syllabus"
author: ["Matt Price"]
draft: false
banner: "testbanner"
menu:
  main:
    identifier: "wdw235-syllabus"
    weight: 10
---

<section class="outline-container">

## Headline 2 {#headline-2}

some content

</section>

<section class="outline-container">

## headline 2 {#headline-2}

some more ocntent

</section>
````


So, it may ultimately be entirely impossible to do this (!), unless you
have found some other way around bf's limitations.

Kaushal Modi <notifications@github.com> writes:

>> I guess this would be done in org-hugo-headline, 
>
> It probably wouldn't be `org-hugo-headline` because that processes just the headline, and not the whole section under it. 
>
>
>
>> probably by adding html directly to the markdown file (?). 
>
> Yes, that would be the only way. 
>
>> How hard does this sound to you @kaushalmodi?
>
> As ox-html already does it, I'd guess that it should be easy. 
>
>> I can take a crack at it maybe in the next few days, but if you can give me some guidance ..
>
> Sure, I'll accept a PR. If you haven't already check out the [`HTML_CONTAINER_CLASS`][1] subtree property. As ox-hugo indirectly extends from ox-html, that might just work right out of box (I haven't tried), and if not, then looking at ox-html code should help port the `HTML_CONTAINER_CLASS` support to ox-hugo. 
>
> [1]: https://orgmode.org/manual/CSS-support.html


--

**Comment by kaushalmodi** [comment]
Try doing:

```emacs-lisp
(concat "<section class=\"outline-container\">\n  </section><section>\n\n"
        (org-hugo--headline-title style level loffset title todo-fmtd anchor numbers)
        contents
        "\n</section>\n")
```

---

PS: Markdown formatting when written via email interface doesn't work on Github.

**Comment by kaushalmodi** [comment]
> No luck. Maybe I need to update hugo? using 0.54, I think

No, this has nothing to do with Hugo version. I had not tried that snippet.

It's possible that Markdown/Blackfriday does not allow wrapping markdown headings in section tags. I'll need to visit the implementation of this feature some time next week.

**Comment by kaushalmodi** [comment]
I completely forgot about this issue until today.

I realized that I made a mistake in my suggestion earlier in https://github.com/kaushalmodi/ox-hugo/issues/271#issuecomment-490232502 .. I swapped the `</section>` and `<section>`.

This should work:

```
(concat "<section class=\"outline-container\">\n  <section></section>\n\n"
        (org-hugo--headline-title style level loffset title todo-fmtd anchor numbers)
        contents
        "\n</section>\n")
```

Here's what I tried in my local repo at this line:

https://github.com/kaushalmodi/ox-hugo/blob/4c34d422671c2835b18f500531920505a139c573/ox-hugo.el#L1778

```
(t
        (let ((anchor (format "{#%s}" ;https://gohugo.io/extras/crossreferences/
                              (or (org-element-property :CUSTOM_ID headline)
                                  (org-hugo-slug title))))
              (section-tag-indent (make-string (* 2 (1- level)) ? )))
          (format (concat "%s<section class=\"outline-container level-%d\">\n"
                          "%s  <section></section>\n\n"
                          "%s%s\n"
                          "%s</section>")
                  section-tag-indent level
                  section-tag-indent
                  (org-hugo--headline-title style level loffset title todo-fmtd anchor numbers)
                  contents section-tag-indent)))
```

**Comment by kaushalmodi** [comment]
@titaniumbones Do you want to try out the https://github.com/kaushalmodi/ox-hugo/commit/df224239fa281b0f02a300d2da0f17c5d221cf5a commit in the [**headline-container**][1] branch of this repo?

I will commit it into master once it is briefly tested and I have tests added for it.

[1]: https://github.com/kaushalmodi/ox-hugo/tree/headline-container

**Comment by rolojf** [comment]
@titaniumbones : how did it go? 
I tried a few cases and HTML_CONTAINER did work for me bue HTML_CONTAINER_CLASS didn't
I am not good at all with elisp, so no can help much.
Also didn't merge it with current master branch.

@kaushalmodi Hope to see it merged, thanks

**Comment by kaushalmodi** [comment]
@rolojf As you can see in https://github.com/kaushalmodi/ox-hugo/commit/24f781734b6a3c94065715a6583117fa47a154bc#diff-e74ea2b6e9a85fc36705123847c81688R19, the HTML_CONTAINER and HTML_CONTAINER_CLASS seem to work fine.

I cannot yet merge this PR, because it can use few more tests and also the related documentation in the ox-hugo-manual.org.

I hope to get back to merging this in a proper way in the next 2 weeks.

In the mean time, try to checkout the `headline-container` branch of this repo, evaluate the updated ox-hugo file and try exporting again.. see the basic test added in this branch.

**Comment by titaniumbones** [comment]
Hi , sorry I missed that last round of improvements - I will try this out as soon as I can, probably in about 4 or 5 days - my clasers stsrt today so I'm already a bit scattered!

**Comment by titaniumbones** [comment]
Finally got a chance to try this, and I htink something is going wrong between the `.md` file and the `.html`; so htere may be a more serious problem with blackfriday.  Hven't dug aorund yet, ubt with a simple org file, e.g.: 

```
* simple test

content para

- list item 1
- list item 2 

```

I get this md that looks fine: 

```
---
title: "Assignments deletem Assignments"
author: ["Matt Price"]
lastmod: 2019-09-07T17:33:46-04:00
draft: false
---

<container class="outline-1">
  <container></container>

## simple test {#simple-test}

content para

-   list item 1
-   list item 2

</container>
```

but in the resultant HTML, the headline is not wrapped, and instead I get a `<p>` element contianing hte container elements:

```

<p><container class="outline-1">
  <container></container></p>

<h2 id="simple-test">simple test</h2>

<p>content para</p>

<ul>
<li>list item 1</li>
<li>list item 2</li>
</ul>

<p></container></p>

```

So... I hope to be abl to look into this somehwere, but maybe I need to set a variable for blackfriday somewhere.  Or maybe it's not going to be possible...

**Comment by titaniumbones** [comment]
**REVISED:** sith HTML_CONTAINER set to `section` this code seems to work perfectly. It's somewhat sensitive to whitespace (see https://github.com/russross/blackfriday/issues/184 which you've already referenced above) and I haven't odne extensive testing yet, but so far it looks good.

**Comment by kaushalmodi** [comment]
OK, I will merge this with more tests this weekend.
