### ISSUE TITLE
Support embedding video using <video> tag

### ISSUE THREAD

**Issue by RidaAyed** [kaushalmodi/ox-hugo#274]
Thank you for that outstanding piece of work and useful package.

Instead of displaying a video with this line:

    My video [[file:./images/sample.mp4]]

I only see this text displayed:

    My video <./images/sample.mp4>

Currently I'm converting mp4 to gif as workaround. Gif works using the upper syntax.

**Comment by kaushalmodi** [comment]
Thanks and I'm glad that you find this package useful.

`ox-hugo` doesn't know what files should be considered as "attachments" (the files that need to be copied to the static dir), so there's a defcustom for that: `org-hugo-external-file-extensions-allowed-for-copying`.

It makes sense that .mp4 should be considered an attachment too, so I am adding that to the default value of that variable.

**Comment by kaushalmodi** [comment]
@RidaAyed This issue got auto-closed as I annotated the commit adding `"mp4"` to `org-hugo-external-file-extensions-allowed-for-copying` with this issue.

Feel free to comment further in this thread if this issue is still not fixed for you.

**Comment by RidaAyed** [comment]
Thank you for taking your time to help me @kaushalmodi

Upated the package, still no video.

Now I got `My video` rendered instead of `My video <./images/sample.mp4>`

The .mp4 files are copied to `ox-hugo's` /static folder

**Comment by kaushalmodi** [comment]
> Upated the package, still no video.

The video .mp4 file should now get correctly hyperlinked from your page. Regarding how to show the video inline in the page, I haven't done that. But I believe that you would need to insert some video showing HTML element perhaps?

**Comment by kaushalmodi** [comment]
You probably need an Org macro that inserts this? https://www.w3schools.com/html/html5_video.asp

Before you work on Org macro, try using the `#+begin_export html` .. `#+end_export` syntax to inline HTML in the Org document to embed that video.

**Comment by kaushalmodi** [comment]
@RidaAyed You can see [this example commit][1] to `ox-hugo` test that generates https://ox-hugo.scripter.co/test/posts/embedded-video/.

Later I will think of a better way to support the `<video>` tag from `ox-hugo`.

[1]: https://github.com/kaushalmodi/ox-hugo/commit/25e6aea7ada7666baa5e69c5e75ebed075eb45c3#diff-6fa190cf16cc1fe9ba0fa6673ddb5970

**Comment by RidaAyed** [comment]
Note, while a org-mode picture's path works with `./images/pic.png`, the video src block path requires `/ox-hugo/sample.mp4`, regardless of having both in the image folder.

e.g. 

```
#+begin_export html
 <video width="320" height="240" controls>
 <source src="/ox-hugo/sample.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>
#+end_export
```

Tested on localhost only

**Comment by kaushalmodi** [comment]
If I understood you correctly, if you use the above `#+begin_export html` method to wrap the `<video>` tag, then, yes, you need to manually place the video file in the `static/` dir of your site. `ox-hugo` does not manage the copying of files in the `#+begin_export html` construct.

The path does not have to be `ox-hugo/..`. In the test commit ( https://github.com/kaushalmodi/ox-hugo/commit/25e6aea7ada7666baa5e69c5e75ebed075eb45c3#diff-7e989f996a5ba14acdd4d1c9c1c0f293 ), you can see that I have manually put the .mp4 file in the test site's `static/videos/` directory.

**Comment by RidaAyed** [comment]
> ..if you use the above..then, yes, you need..

What other option is there? Nevermind if I misunderstood that `if` @kaushalmodi 😊

**Comment by kaushalmodi** [comment]
> What other option is there?

Sorry, yeah, there's no other option.. the "option" would be available once `ox-hugo` starts exporting `<video>` tags.

**Comment by kaushalmodi** [comment]
Once https://github.com/kaushalmodi/ox-hugo/pull/524 is merged, this will work:

```org
#+attr_html: :width 320 :height 240 :controls t
#+begin_video
<source src="/videos/sample.mp4" type="video/mp4">
Your browser does not support the video tag.
#+end_video
```

**Note**: You will still need to set the `src` attribute in `source` tag to the path in your site's `static/` directory.

**Comment by RidaAyed** [comment]
Thank you for your endless effort @kaushalmodi :clap:
