### ISSUE TITLE
Verify/fix support for spaces in paths referencing to images

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#277]
Why wouldn't you want spaces in filenames ;-) ? I stumbled upon the issue when I converted an old website with a lot of images with spaces in them.

I will provide a minimal example:

This org-file
```
#+hugo_base_dir: ../
#+hugo_section: test
#+title: Test

#+caption: Test
#+name: Test
[[../files-to-be-copied-to-static/images/big/test image.gif][file:../files-to-be-copied-to-static/images/small/test_image.gif]]
```
is converted to this markdown:
```
+++
title = "Test"
draft = false
+++

<a id="org73cea7d"></a>

{{< figure src="/ox-hugo/test_image.gif" caption="Figure 1: Test" link="/ox-hugo/test image.gif" >}}
```

But with a space in the path of the link-description:
```
#+hugo_base_dir: ../
#+hugo_section: test
#+title: Test

#+caption: Test
#+name: Test
[[../files-to-be-copied-to-static/images/big/test image.gif][file:../files-to-be-copied-to-static/images/small/test image.gif]]
```
It is converted to this markdown:
```
+++
title = "Test"
draft = false
+++

<a id="org4bdfd37"></a>

[file:../files-to-be-copied-to-static/images/small/test image.gif](/ox-hugo/test image.gif)
```

_Originally posted by @fvdbeek in https://github.com/kaushalmodi/ox-hugo/pull/276#issuecomment-502974403_

**Comment by fvdbeek** [comment]
This issue arises from the fact that the image link in the description is matched by the regexp in `org-plain-link-re` and is not allowed to contain whitespace. This regexp isn't part of ox-hugo and cannot easily be changed without side-effects. As a workaround, spaces in the filename could be URL encoded to "%20". I added a pull request to address this.
