### ISSUE TITLE
Org verse block should be wrapped by <p class="verse">

### ISSUE THREAD

**Issue by ruibinx** [kaushalmodi/ox-hugo#281]
## Actual Behavior
Org verse block:

```
#+begin_verse
Roses are red,
tulips are black. 
You’d look great with a knife in your back.
#+end_verse
```

produces result:

```
Roses are red,<br />
tulips are black.<br />
You’d look great with a knife in your back.<br />
```

when export.

## Expected Behavior

While default org markdown backend produces result:

```
<p class="verse">
Roses are red,<br />
tulips are black.<br />
You’d look great with a knife in your back.<br />
</p>
```

## How to Reproduce the Issue

Export using `org-hugo-export-to-md`.

I wonder if it might be an intended feature, however I do think `<p class="verse">` wrapper provides more convinence for style customizing.

For those who are also interested, currently I wrote a patch to solve this:

```
    (defun my-advice-to/org-blackfriday-verse-block (origin-func &rest args)
      (let* ((origin-val (apply origin-func args)))
        (concat "<p class=\"verse\">\n"
                origin-val
                "</p>\n")))

    (advice-add 'org-blackfriday-verse-block :around #'my-advice-to/org-blackfriday-verse-block)
```

Thanks.

**Comment by kaushalmodi** [comment]
Hello,

Thanks for your thorough feature request with the suggested outcome too.

It makes sense to make `ox-hugo` behave similar to `ox-md`. I have committed this change locally and will push it soon.
