### ISSUE TITLE
after update, I got a bug

### ISSUE THREAD

**Issue by GTrunSec** [kaushalmodi/ox-hugo#283]
I'm sure this bug appeared in new commit.

On use-package when I press  `C-c C-e H h` and `C-c C-e H o` 
```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 3) 4)
  org-hugo-export-to-md(nil nil nil nil)
  (org-open-file (org-hugo-export-to-md nil nil s v))
  (if a (org-hugo-export-to-md nil t s v) (org-open-file (org-hugo-export-to-md nil nil s v)))
  (lambda (a s v _b) (if a (org-hugo-export-to-md nil t s v) (org-open-file (org-hugo-export-to-m
  org-export-dispatch(nil)
  funcall-interactively(org-export-dispatch nil)
  call-interactively(org-export-dispatch nil nil)
  command-execute(org-export-dispatch)
```

On local-path to load ox-hugo, I got more details about this issue 

```
org-open-file: Wrong number of arguments: ((t) (&optional async subtreep visible-only) "Export current buffer to a Hugo-compatible Markdown file.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should happen
asynchronously.  The resulting file should be accessible through
the `org-export-stack' interface.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don't export
contents of hidden elements.

Return output file's name." (interactive) (org-hugo--before-export-function subtreep) (let* ((org-use-property-inheritance (org-hugo--selective-property-inheritance)) (info (org-combine-plists (org-export--get-export-attributes (quote hugo) subtreep visible-only) (org-export--get-buffer-attributes) (org-export-get-environment (quote hugo) subtreep))) (pub-dir (org-hugo--get-pub-dir info)) (outfile (org-export-output-file-name ".md" subtreep pub-dir))) (prog1 (org-export-to-file (quote hugo) outfile async subtreep visible-only) (org-hugo--after-export-function info outfile)))), 4
user-error: Minibuffer window is not active
Mark set
```

So, this time I just downgraded ox-hugo (git checkout 45cbd5eff3e9c3682caff8685b7e87fe0faf29fb). to make sure it working

**Comment by kaushalmodi** [comment]
Oops! Thanks for the report; I'll fix it in few hours as soon as I get to a computer. 

If you don't mind upgrading to the latest for a while, can you confirm if `C-c C-e H H` works while `C-c C-e H h` doesn't?

**Comment by kaushalmodi** [comment]
I'm on my phone, but I believe making this change in your local area will fix it. I'll commit the fix once I test it on my computer. 

On line https://github.com/kaushalmodi/ox-hugo/blob/4c34d422671c2835b18f500531920505a139c573/ox-hugo.el#L740, remove the first argument (`nil`) from the call to `org-hugo-export-to-md`.

Similarly, remove the **first** `nil` argument to that function on 

https://github.com/kaushalmodi/ox-hugo/blob/4c34d422671c2835b18f500531920505a139c573/ox-hugo.el#L748 

and 

https://github.com/kaushalmodi/ox-hugo/blob/4c34d422671c2835b18f500531920505a139c573/ox-hugo.el#L749

too. 

As I said earlier `C-c C-e H H` should still work fine without the above fixes too.

**Comment by kaushalmodi** [comment]
I have auto-closed this issue from the commit. But feel free to let me know in a follow-up comment in this thread if this fix worked for you.

Thanks.
