### ISSUE TITLE
how to disable export in some file

### ISSUE THREAD

**Issue by vinurs** [kaushalmodi/ox-hugo#286]
i use orgmode as my  knowledge management  tool, but in the project root dir i set .dir-locals.el
```
((org-mode . ((eval . (org-hugo-auto-export-mode)))))
```
sometimes some file i don't want to export, then how can i disable export in the file

**Comment by kaushalmodi** [comment]
Hello, in order to disable the auto-export only for the selected files, just disable that minor mode in the File Variables section. See https://ox-hugo.scripter.co/doc/auto-export-on-saving/#enable-for-the-whole-project-except-for-few-org-files.

**Comment by vinurs** [comment]
thanks, it's ok now
