### ISSUE TITLE
The web-site is currently unavailable

### ISSUE THREAD

**Issue by Paul-Stern** [kaushalmodi/ox-hugo#287]
Hello, kaushalmodi! Thank you so much for your work! I'm happy to use your project. But there's a **problem** now, as the project web-site is currently unavailable. Could you please fix it up? I hope it won't take long

Regards,
Paul.

**Comment by kaushalmodi** [comment]
Hello, can you paste the link you tried? https://ox-hugo.scripter.co/ is working fine for me.

**Comment by kaushalmodi** [comment]
And I'm glad you're liking ox-hugo :)

**Comment by Paul-Stern** [comment]
Actually, now it's working back again =) Sorry for distracting you.
