### ISSUE TITLE
can i export all files at once?

### ISSUE THREAD

**Issue by vinurs** [kaushalmodi/ox-hugo#292]
i have many org files in one directory, and there maybe directories in the directory, can i export these org files to markdown at once?

**Comment by kaushalmodi** [comment]
You can use a combination of a [Makefile][1] and an [Elisp setup file][2] like I do in this repo. Check out the instructions on https://ox-hugo.scripter.co/doc/tests-site/; in there when you do `make md`, it re-exports posts from all the Org files. The per-file approach or per-subtree approach is figured out automatically. 

[1]: https://github.com/kaushalmodi/ox-hugo/blob/master/Makefile

[2]: https://github.com/kaushalmodi/ox-hugo/blob/master/test/setup-ox-hugo.el

**Comment by vinurs** [comment]
ok, thanks very much
