### ISSUE TITLE
Links using a baseURL like https://domain.com/subdir/

### ISSUE THREAD

**Issue by iris-garcia** [kaushalmodi/ox-hugo#295]
## Actual Behavior
Probably this is not an issue, but I could not figure out how to achieve this after two days, reading the documentation and trying, so I decided to ask here.

I have a domain like `https://domain.com/subdir/` set as `baseURL` in the `config.toml` config file.
Then if I try to link an image for example (`[[/images/test.png][an image]]`) it transforms to `https://domain.com/images/test.png` which of course is a broken link.

So my question basically is, how can I achieve this? if this is even possible.

Thanks.

**Comment by kaushalmodi** [comment]
Hello,

This is a known issue with Hugo. 

ox-hugo test site is also served on a subdirectory, so I had spent quite some time to figure out the workaround for this same issue.

Workaround is to set `canonifyURLs = true` in the config.toml for such sites.

See https://github.com/kaushalmodi/ox-hugo/blob/6325a377d2f9b54762a5774d7f612be0898c5ac1/test/site/config.toml#L6-L13.

**Comment by kaushalmodi** [comment]
A while ago I had done some analysis on the topic of images, baseURL with subdirectory, relative and absolute URLs: https://github.com/gohugoio/hugo/issues/4733#issuecomment-390195852

**Comment by iris-garcia** [comment]
Oh man, this is so useful, thanks a lot. I was going crazy using macros with my domain/subdir hardcoded there :(
