### ISSUE TITLE
how can i only export some subtree

### ISSUE THREAD

**Issue by vinurs** [kaushalmodi/ox-hugo#296]
i use the  per-subtree method to write articles, then how can i only export some subtrees
```
​* Footnotes
​* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode -1)
# End:
```
seems affect the whole file's subtrees

**Comment by kaushalmodi** [comment]
`(org-hugo-auto-export-mode -1)` disables the auto-exporting of subtrees on saving the buffer. It does not disable exports. You can still export using `C-c C-e H H`. 

If you want to enable auto-exporting of selected subtrees, you'll need to move those to a separate file where you have the auto exporting enabled. 

_You can have multiple source Org files, some exported using per-file flow, and some using per-subtree flow if you wish._ All that matters is that they all export to the same HUGO_BASE_DIR. 

Now, if you want to completely disable the export, where even `C-c C-e H H` doesn't work, mark the subtrees or a parent subtree holding all such post subtrees with the classic `:noexport:` tag.

**Comment by vinurs** [comment]
because i want to write a series of articles about a subject, so i manage them in one org file, but some maybe drafts or my personal articles, so i dont want some of them to be exported, as u say, then i have to move them to another file?

**Comment by kaushalmodi** [comment]
> but some maybe drafts

It's fine to export them. If you have them in TODO state, they would be marked draft and Hugo won't publish them. You may even choose to not commit the draft .md files. 

> my personal articles

Of you plan to never make them public, they would be best suited in a separate Org file that you never export.

**Comment by vinurs** [comment]
^_^ there is workaround, i write a shell script that only submit the md files that's not draft, so i can play them in one file and add TODO state

**Comment by kaushalmodi** [comment]
What is your website deploying flow?

I simply commit the non-draft files and leave the draft files on my local machine.

When I push the .md files to my git repo, Netlify (https://netlify.com) kicks off a Hugo build on its server and my website updates.

So while my committed Org files have draft/TODO subtrees, my draft .md files are never committed.

**Comment by vinurs** [comment]
i manage all my articles in my private repos, it's a directory with some sub directories, and then  when i want to publish some articles  to my website i export some of them to my github.io repo's source branch(that's a hugo directory), then use github actions to auto publish it to master branch.

**Comment by kaushalmodi** [comment]
Can I then close this issue? :)
