### ISSUE TITLE
generalize `wim` scope?

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#298]
Hi Kaushal,

Not a bug report! I'm looking to reuse your work scoping subtree exports to "closest-parent-with-export-file-name-set". , and thought I'd ask for some guidance. A quick look at your code suggests that there are several interrelated functions that collectively manage scoping -- `org-hugo--get-valid-subtree`, `org-hugo--export-subtree-to-md`, and org-subtree-wim-to-md`.  If I want to copy your work, should I just start with `org-hugo--get-valid-subtree`, and use that to write wim scopes for my own export functions? IIUC it will return a subtree or nil, so I can run exports inside an `if` statement? 

Thanks much as always.

**Comment by kaushalmodi** [comment]
Yes, `org-hugo--get-valid-subtree` is the key function here. The important thing this function does is also to **move the point** to the found "valid subtree".

From it's docstring:

> As this function is intended to be called inside a valid Hugo post subtree, doing so also moves the point to the beginning of the heading of that subtree.

Once the point is at the right place, you simply do the Org export with "subtree scope", i.e. set the `SUBTREEP` arg to non-nil. That is what any `C-c C-e C-s ..` command does.

---

*PS: I know that I said that I will work on creating a general "wim" export function for `ox.el`, but I am not still finding time to get to that.*

**Comment by titaniumbones** [comment]
oh man, @kaushalmodi , I now have code that looks like this in my course repos:

```emacs-lisp
(defun org-lms-export-wim ()
  "find valid subtree and do the right thing"
  (interactive)
  (let ((ol-section (or (org-lms-get-keyword "ORG_LMS_SECTION")
                        (org-lms-get-keyword "HUGO_SECTION"))))
    (pcase ol-section
      ("assignment"
       (org-lms-assignment-wim)
       (org-hugo-export-wim-to-md))
      ((or "lecture" "slides")
       (org-lms-lecture-wim))
      ("announcement"
       (org-lms-announcement-wim)
       (mwp-subtree-to-slack-wim))
      ("syllabus"
       (org-lms-post-syllabus)
       (org-hugo-export-wim-to-md))
      (_
       (message "Sorry, I can't tell what to do. Please set keyword ORG_LMS_SECTION to use this")))))
```
which means that anywhere in any file I can just type `org-lms-export-wim` and emacs will immediately do what I want.  It's sort of unreal -- cognitive overhead &#8594;  0.  Thank you!

**Comment by kaushalmodi** [comment]
You're welcome! :)
