### ISSUE TITLE
After Hugo Update, Homepage template doesn't work

### ISSUE THREAD

**Issue by jarss** [kaushalmodi/ox-hugo#299]
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by jarss** [comment]
I've made a couple of changes to my website and at some point I lost the layout of my homepage. 

My homepage usually displays a summary of my recent posts, as you can see on the website as it is now: [joshrollinswrites.com](https://joshrollinswrites.com/). When I run a local server now though, on my own machine, I see the headers of the site's main sections (I have four) instead. I am not sure if this is a ox-hugo issue or something else that got messed up in hugo. 

Everytime I run the local server, even though I restored my old .org file which I use for the site and files I deleted (these were sync-conflict files created by syncthing at times, I don't think these affect anything since nothing at Hugo would point to the unusual naming convention syncthing uses when creating these conflict files).

According to the [Hugo documents I found](https://gohugo.io/templates/homepage/), the homepage template is just a special list template. It needs to be saved as index.html in layout. I do have one there, with the following code: 

```
{{ define "main" -}}
{{ range .Data.Pages -}}
{{ .Title }}
{{ .Date.Format "2006-01-02" }}{{ partial "tags.html" .}} {{ .Summary }} {{ if .Truncated }}
Read More ↴
{{ end }}
{{- end }}
{{- end }} 
```
I haven't touched this file recently, and from what I can tell it should still work -- but I don't see my posts. 

I'm not sure where to start looking for the problems. Any suggestions?

**Comment by kaushalmodi** [comment]
>  I am not sure if this is a ox-hugo issue or something else that got messed up in hugo.

`ox-hugo` only exports Org mode to Markdown. As long as your exported Markdown looks the exact same as before and the pages from that Markdown rendered fine before, this is not an ox-hugo issue.

It's very easy to figure out if it's a Hugo issue ..

- Roll back to the last Hugo version that worked for you. If things are back to good, this was a Hugo issue.

Note the last working version of Hugo and read the release notes of all major versions since then: https://gohugo.io/news/.

My wild guess would be the consistency improvement related to `.Pages` in https://gohugo.io/news/0.58.0-relnotes/:

> home.Pages now behaves like all the other sections, see [#6240](https://github.com/gohugoio/hugo/issues/6240). If you want to list all the regular pages, use .Site.RegularPages.

If you were able to get your site working by reverting to the older Hugo version (please always report  the before and after Hugo versions in issues), you can incrementally download static binaries of all the Hugo versions and figure out which Hugo version started causing this breakage.

As always, https://discourse.gohugo.io/ is superb for Hugo related troubleshooting; whether it is for discussing a tentative bug or general help to get a site working after a breaking change :).

**Comment by jarss** [comment]
This consistency improvement seems like it could be it. I had an older version that worked well.

I'll update when I have a result.

-------- Original Message --------

**Comment by kaushalmodi** [comment]
btw note that the `.Data` in `.Data.Pages` in your example is redundant.

Related: https://github.com/schollz/onetwothree/pull/12/files.

**Comment by jarss** [comment]
downloaded Hugo 57.2, which is the latest one my distro (Manjaro) provides from the community repo. Then I read the warning, which states clearly every time you run the thing: 

**WARN 2019/10/01 06:47:06 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.**
WARN 2019/10/01 06:47:06 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
WARN 2019/10/01 06:47:06 In the next Hugo version (0.58.0) we will change how $home.Pages behaves. If you want to list all regular pages, replace .Pages or .Data.Pages with .Site.RegularPages in your home page template.


The last one seems to be related to what happened, however, using this version still doesn't solve the issue after I build the site (run hugo). I still don't get my old homepage list page. It seems to me it's better to work on these issues (the first and last warning seem like the same thing, the last one, RSS related, different, still not sure what it means or where I find this code in my site)

I'll explore more. I know they are practically showing me what's the issue and it's staring me in the face but I need to find that code wherever it is, change it, and then understand why it works or why it doesn't... 

Thanks for the useful info so far.

**Comment by kaushalmodi** [comment]
>  I remembered

Next time, use grep or ripgrep (rg)! :)

> It works now, the issue is solved

Ok, great! 

> However, I'm still not sure why

Hmm, figure it out while you're at it. Otherwise, it will probably come bite you again :)

**Comment by jarss** [comment]
Ripgrep? could have used grep, that's true...

-------- Original Message --------

**Comment by kaushalmodi** [comment]
> Ripgrep?

https://github.com/BurntSushi/ripgrep/releases

> ripgrep is a line-oriented search tool that recursively searches your current directory for a regex pattern. By default, ripgrep will respect your .gitignore and automatically skip hidden files/directories and binary files. ripgrep has first class support on Windows, macOS and Linux, with binary downloads available for every release. ripgrep is similar to other popular search tools like The Silver Searcher, ack and grep.
