### ISSUE TITLE
Deicde how to treat figures

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#3]
the figure shortcode in Hugo allows images to be embedded in a `<figure>` tag.  Org has its own captioning sy ntax, which AFAIK is not implemented in the markdown exporters. We should decide how to manage this.

**Comment by kaushalmodi** [comment]
Random thought.. export Org figure syntax as HTML? Possible in the Hugo exporter?

Markdown anyways supports inline HTML.

**Comment by kaushalmodi** [comment]
Labeled this as *enhancement* for now. Let me know if this should be a *requirement* now.

This will eventually updated to *requirement* when the existing *requirement* issues are closed.

**Comment by kaushalmodi** [comment]
We decided on using the `figure` short code. Closing this for now.
