### ISSUE TITLE
Support cross-post linking for subtree-based exports (Hugo relref)

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#30]
https://gohugo.io/extras/crossreferences#document-names

Example: Link to a post in `posts/a.md` from `articles/b.md` and having those export to `relref` shortcode in Hugo.

**Comment by kaushalmodi** [comment]
[Discussion on Org mailing list][1]

[1]: https://lists.gnu.org/archive/html/emacs-orgmode/2017-07/msg00488.html

**Comment by siddharthshekar** [comment]
Any updates on this? Alternatively, is there any way to have the one-subtree-per-post workflow and be able to reference other subtrees (that also are being exported)?

**Comment by kaushalmodi** [comment]
Sorry, this is the **only thing** that's missing. The way Org exports happen, when one subtree is exported, it's completely blind about other subtrees.. so even if you try to link other subtrees using their CUSTOM_ID, the export would fail.

I can definitely use some help in tackling this problem, or until I get a lot of time to look into solving this.

*Luckily a workaround (an ugly one) exists.. just link to the URL's of other posts... This is not too bad, as people don't keep on changing URL's of their previous posts.*

**Comment by siddharthshekar** [comment]
I see. While this works for the export, this then breaks linking within org-mode itself. Another hack-job solution would be to have a "dry run" before the actual export where you just figure out what the eventual export targets end up looking like. Not sure how easy/hard this would be to implement, though.

**Comment by kaushalmodi** [comment]
If time is spent on solving this, I'd (or anyone else who wishes to) rather do it the right way:

- Create a hash table of all the subtree posts and their export file names.
- When Org finds an "invalid" CUSTOM_ID reference during export, it should use that hash table as a fallback lookup.
- If found in that hash-table, insert an appropriate `{{ < relref .. >}}` over there. The `relref` shortcode is the best bet here as then we don't have to figure out the section, etc. of the destination link.. `{{ < relref "foo" >}}` would work just as fine as `{{ < relref "posts/foo.md" >}}` (Of course as long as the post is uniquely named "foo" in the whole site.. which should not be too stringent of a condition.).

**Comment by kaushalmodi** [comment]
See https://github.com/itf/org-export-head.
