### ISSUE TITLE
Cyrillic text issue

### ISSUE THREAD

**Issue by allarm** [kaushalmodi/ox-hugo#300]
## Actual Behavior

In the resulting markdown file lines stick together if they're written in Cyrillic letters. If the line ends on a punctuation mark it works as it should be.

## Expected Behavior

Org file

```
Тест
Тест
```

should export to this markdown:

```
Тест
Тест
```

## How to Reproduce the Issue

Try exporting the text from the example org file below.

### Example Org File

```
Тест
Тест

Test
Test
```

### Generated Markdown File or Error

```
ТестТест

Test
Test
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.1 (build 1, x86_64-apple-darwin18.0.0, NS appkit-1671.00 Version 10.14 (Build 18A391))
     of 2018-10-05

## Org Version

    Org mode version 9.3 (nil @ /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/)

## Hugo Version

    Hugo Static Site Generator v0.58.3/extended darwin/amd64 BuildDate: unknown

### Org `load-path` shadows

**Warning**: Possible mixed installation of Org

    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-stan hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-stan
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-comint hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-comint
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-exp hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-exp
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-ctags hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-ctags
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-emacs-lisp hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-emacs-lisp
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-texinfo hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-texinfo
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-irc hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-irc
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-num hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-num
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-mhe hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-mhe
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-shell hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-shell
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-attach hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-attach
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-C hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-C
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-macs hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-macs
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-entities hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-entities
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-dot hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-dot
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-sql hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-sql
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-eww hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-eww
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-datetree hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-datetree
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-macro hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-macro
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-eval hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-eval
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-haskell hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-haskell
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-asymptote hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-asymptote
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-abc hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-abc
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-org hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-org
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-rmail hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-rmail
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-awk hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-awk
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-groovy hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-groovy
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-shen hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-shen
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-icalendar hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-icalendar
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-octave hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-octave
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-scheme hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-scheme
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-mobile hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-mobile
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-processing hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-processing
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-ledger hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-ledger
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-picolisp hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-picolisp
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-colview hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-colview
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-R hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-R
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-table hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-table
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-html hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-html
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-fortran hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-fortran
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-plantuml hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-plantuml
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-docview hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-docview
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-perl hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-perl
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-sqlite hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-sqlite
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-sed hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-sed
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-ditaa hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-ditaa
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-ruby hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-ruby
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-habit hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-habit
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-gnus hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-gnus
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-screen hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-screen
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-mouse hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-mouse
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-css hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-css
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-inlinetask hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-inlinetask
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-lisp hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-lisp
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-eshell hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-eshell
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-pcomplete hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-pcomplete
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-lint hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-lint
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-id hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-id
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-vala hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-vala
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-capture hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-capture
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-sass hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-sass
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-tangle hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-tangle
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-calc hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-calc
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-java hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-java
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-compat hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-compat
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-attach-git hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-attach-git
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-beamer hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-beamer
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-coq hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-coq
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-protocol hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-protocol
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-element hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-element
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-lob hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-lob
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-mscgen hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-mscgen
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-tempo hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-tempo
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-python hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-python
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-latex hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-latex
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-w3m hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-w3m
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-agenda hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-agenda
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-ocaml hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-ocaml
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-ref hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-ref
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-lilypond hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-lilypond
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-table hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-table
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-clojure hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-clojure
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-indent hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-indent
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-plot hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-plot
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-latex hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-latex
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-src hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-src
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-duration hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-duration
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-makefile hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-makefile
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-info hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-info
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-ebnf hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-ebnf
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-clock hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-clock
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-forth hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-forth
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-odt hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-odt
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-publish hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-publish
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-archive hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-archive
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-org hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-org
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-lua hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-lua
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-keys hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-keys
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-eshell hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-eshell
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-faces hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-faces
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-man hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-man
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-list hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-list
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-md hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-md
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-goto hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-goto
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-bbdb hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-bbdb
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-loaddefs hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-loaddefs
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ol-bibtex hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ol-bibtex
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-J hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-J
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox-ascii hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox-ascii
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-matlab hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-matlab
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ox hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ox
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-timer hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-timer
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-core hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-core
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-feed hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-feed
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-io hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-io
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-gnuplot hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-gnuplot
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-js hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-js
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-footnote hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-footnote
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-maxima hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-maxima
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/ob-hledger hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/ob-hledger
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-install hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-install
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org-plus-contrib/org-crypt hides /Users/allarm/.dotfiles/emacs.d/.local/straight/build/org/org-crypt
    /Users/allarm/.dotfiles/emacs.d/.local/straight/build/ox-hugo/org-hugo-auto-export-mode hides /Users/allarm/.dotfiles/emacs.d/.local/elpa/ox-hugo-20190905.303/org-hugo-auto-export-mode

Study the output of `M-x list-load-path-shadows`.

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">&ldquo;posts&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">&ldquo;ox-hugo&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">(&ldquo;jpg&rdquo; &ldquo;jpeg&rdquo; &ldquo;tiff&rdquo; &ldquo;png&rdquo; &ldquo;svg&rdquo; &ldquo;gif&rdquo; &ldquo;mp4&rdquo; &ldquo;pdf&rdquo; &ldquo;odt&rdquo; &ldquo;doc&rdquo; &ldquo;ppt&rdquo; &ldquo;xls&rdquo; &ldquo;docx&rdquo; &ldquo;pptx&rdquo; &ldquo;xlsx&rdquo;)</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">&ldquo;%Y-%m-%dT%T%z&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">&ldquo;&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>
</tbody>
</table>

  

</details>

**Comment by kaushalmodi** [comment]
Thanks for the report. I will figure out how to prevent doing this, may be using a new ox-hugo setting.

**Comment by kaushalmodi** [comment]
I am thinking of the best way to solve this issue. The behavior that you see right now makes sense for Chinese. So I need to enable this behavior only if Chinese characters are detected.. thinking of how to do that in Elisp. I hope to have a solution in 2 days.

**Comment by kaushalmodi** [comment]
@allarm As a quick workaround try putting this in your config and evaluate it:

```el
(with-eval-after-load 'ox-hugo
  (defun org-hugo-paragraph (paragraph contents info)
    "Transcode PARAGRAPH element into Hugo Markdown format.
CONTENTS is the paragraph contents.  INFO is a plist used as a
communication channel."
    (let (;; The label is mainly for paragraphs that are standalone
          ;; images with #+name keyword.
          (label (let ((lbl (and (org-element-property :name paragraph)
                                 (org-export-get-reference paragraph info))))
                   (if lbl
                       (format "<a id=\"%s\"></a>\n\n" lbl)
                     "")))
          ret)

      (unless (org-hugo--plist-get-true-p info :hugo-preserve-filling)
        (setq contents (concat (mapconcat 'identity (split-string contents) " ") "\n")))

      (setq contents (replace-regexp-in-string
                      ;; Glue footnotes to the words before them using
                      ;; &nbsp; so that the footnote reference does not
                      ;; end up on a new line by itself.
                      ;; "something FN" -> "something&nbsp;FN"
                      "[[:blank:]]+\\(\\[\\^[^]]+\\]\\)" "&nbsp;\\1"
                      (replace-regexp-in-string
                       ;; "FN ." -> "FN."
                       "\\(\\[\\^[^]]+\\]\\)[[:blank:]]*\\([.]+\\)" "\\1\\2"
                       contents)))
      ;; (message "[org-hugo-paragraph DBG] para 3: %s" contents)
      (setq ret (concat label
                        (org-md-paragraph paragraph contents info)))

      ;; Wrap the paragraph with HTML div tag with user-specified
      ;; attributes, unless the paragraph is a standalone image (or few
      ;; other conditions as shown below).  These conditions are taken
      ;; from `org-html-paragraph'.
      (let* ((parent (org-export-get-parent paragraph))
             (parent-type (org-element-type parent)))
        ;; (message "[ox-hugo-para DBG] standalone image? %s\ncontents: %s"
        ;;          (org-html-standalone-image-p paragraph info)
        ;;          contents)
        (unless (or
                 ;; First paragraph in an item has no tag if it is alone
                 ;; or followed, at most, by a sub-list.
                 (and (eq parent-type 'item)
                      (not (org-export-get-previous-element paragraph info))
                      (let ((followers (org-export-get-next-element paragraph info 2)))
                        (and (not (cdr followers))
                             (memq (org-element-type (car followers)) '(nil plain-list)))))
                 ;; Standalone image.
                 (org-html-standalone-image-p paragraph info))
          (setq ret (org-blackfriday--div-wrap-maybe paragraph ret))))
      ret)))
```

**Comment by allarm** [comment]
Hey @kaushalmodi, that worked, thanks a lot for quick turnaround, really appreciate it. Interesting enough, the fact that I was the first Russian who reported this issue makes me (probably) the first Russian using `ox-hugo` (or at least the first Russian responsible enough to report this behaviour :). 

If you need any help with troubleshooting any more Cyrillic - do let me know.

And thank you for this wonderful package!

**Comment by kaushalmodi** [comment]
@allarm Hello The workaround I suggested in my earlier post should not be needed any more. Please remove that workaround and update ox-hugo from Melpa. Feel free to report back any issues in this thread (even though it is closed).

**Comment by allarm** [comment]
Nice, thanks a lot!

**Comment by vyorkin** [comment]
Yes, I can confirm that it is fixed.
Thank you @kaushalmodi for fixing the issue and @allarm for reporting this
