### ISSUE TITLE
Youtube shortcode video id underscores are escaped

### ISSUE THREAD

**Issue by elsatch** [kaushalmodi/ox-hugo#303]
## Actual Behavior
I added this shortcode to insert a video: {{< youtube v_jDFgS2AqE >}} 

As I export it to Markdown, it gets converted to` {{< youtube v\_jDFgS2AqE >}}`, so the link is broken later on the final build using Hugo.

## Expected Behavior
I expect video ID in Youtube shortcodes not to be altered during ox-hugo export.

Note: This might be related to #43 and #126. Indeed, if I replace the original shortcode with:
 `#+html: {{< youtube v_jDFgS2AqE >}}` 
it works.
 
## How to Reproduce the Issue
Create a Youtube shortcode like {{< youtube v_jDFgS2AqE >}} in an org-mode file. Use ox-hugo to export to MD.

### Example Org File
```
** Check this nice video
{{< youtube v_jDFgS2AqE >}}

```
### Generated Markdown File or Error
```
+++
author = ["Cesar Garcia Saez"]
draft = false
+++

## Check this nice video {#check-this-nice-video}

{{< youtube v\_jDFgS2AqE >}}
```
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511))
     of 2019-09-02

## Org Version

    Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)

## Hugo Version

    =hugo= binary not found in PATH

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

  

</details>

**Comment by kaushalmodi** [comment]
@elsatch 

ox-hugo does not officially support the Hugo Shortcodes because its aim is to enable writing content in natural Org mode syntax which is exportable to usual Org backends as well. If you use Hugo shortcodes in the Org source, then you are handcuffing that Org source just to Hugo exports.

Given that, using `#+html:` is the best way to avoid the `_` escaping.

**Comment by kaushalmodi** [comment]
@elsatch  Does this example help?: https://github.com/kaushalmodi/ox-hugo/commit/463d2f319e7cf3c417d86467d5891757b20c4e9c

That creates https://ox-hugo.scripter.co/test/posts/using-org-macros-in-lieu-of-hugo-shortcodes/.

**Comment by elsatch** [comment]
Thanks @kaushalmodi for your response! I thought it was possible to use the shortcodes, but given your explanation, it would make more sense to take the org-mode macro approach.

I'm trying the Academic theme for Hugo, that offers tons of Widgets itself. I will experiment with those to see how well does the macro approach work.

I'm wondering if it would be helpful to create an org-macro collection for Hugo. Given I will need to create those for my Yassnippet, I could setup a repo and share them too.

**Comment by kaushalmodi** [comment]
> I'm wondering if it would be helpful to create an org-macro collection for Hugo. Given I will need to create those for my Yassnippet, I could setup a repo and share them too.

That's a great idea! Please do share it once you have it. I will link it from the ox-hugo docs.

**Comment by elsatch** [comment]
Thanks for your support @kaushalmodi! Do you have any recommendation regarding the naming of the repo? org-macro-hugo-shortcodes ? org-macro-shortcodes? org-macros-html?

I also feel I need to create both a list with the macros and the Yasnippet versions, for people looking for generic codes.

**Comment by kaushalmodi** [comment]
If I were I pick, I would prefer _org-macros-html_, because technically those Org Macros will simply specify the formatting for the html export.. it's just mimicking what the Hugo shortcodes do, but doesn't have any dependency on Hugo.

You can also look at https://github.com/fniessen/org-macros for inspiration.

**Comment by kaushalmodi** [comment]
I believe I can safely close this issue. Please feel free for any further queries in this same thread or a new issue thread.
