### ISSUE TITLE
org-hugo-auto-export-mode can not use 

### ISSUE THREAD

**Issue by dreamerjackson** [kaushalmodi/ox-hugo#304]
File local-variables error: (void-function org-hugo-auto-export-mode)

**Comment by kaushalmodi** [comment]
Do you have the latest ox-hugo installed from Melpa (not the stable Melpa)?

**Comment by kaushalmodi** [comment]
@dreamerjackson Hello, can you confirm this issue after uninstalling and reinstalling ox-hugo from the master branch of this repo (or using the regular Melpa, not stable Melpa)?

I cannot reproduce the issue you are seeing, so there's nothing I can "fix".
