### ISSUE TITLE
Export to code fences with attributes instead of using the buggy highlight shortcode

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#305]
Do this only if Hugo v0.60+ is detected.

- https://gohugo.io/content-management/syntax-highlighting/#highlighting-in-code-fences
- Buggy `highlight` shortcode: https://github.com/gohugoio/hugo/issues/4717

**Comment by finex** [comment]
I agree, currently you can use the old Markdown syntax inside the .org file, but it doesn't works well. For example parameters with `_` are wrongly escaped:

+ Org:
``` 
{{< highlight php5 "linenos=inline.table,hl_lines=1 3-4,linenostart=1" >}}
```

+ Markdown generated by ox-hugo: 
```
{{< highlight php5 "linenos=inline.table,hl\_lines=1 3-4,linenostart=1" >}}
```

**Comment by kaushalmodi** [comment]
You are not supposed to use the highlight shortcode in Org!

**Comment by kaushalmodi** [comment]
Write this instead:

```org
#+begin_src php5 -n 1 :hl_lines 1,3-4
// https://www.php.net/manual/en/language.basic-syntax.comments.php
echo 'This is a test'; // This is a one-line c++ style comment
/* This is a multi line comment
    yet another line of comment */
echo 'This is yet another test';
echo 'One Final Test'; # This is a one-line shell-style comment
#+end_src
```

That exports to:

```
{{< highlight php5 "linenos=table, linenostart=1, hl_lines=1 3-4" >}}
// https://www.php.net/manual/en/language.basic-syntax.comments.php
echo 'This is a test'; // This is a one-line c++ style comment
/* This is a multi line comment
    yet another line of comment */
echo 'This is yet another test';
echo 'One Final Test'; # This is a one-line shell-style comment
{{< /highlight >}}
```

**Comment by kaushalmodi** [comment]
See https://ox-hugo.scripter.co/doc/source-blocks/ for more details.

**Comment by finex** [comment]
Thank you, I've missed that :-)

**Comment by jahierwan** [comment]
ok, but what if I want to export 
`{{< highlight php5 "linenos=inline, ...}}`
?
its seems that the `linenos=table` is hardcoded: 
https://github.com/kaushalmodi/ox-hugo/blob/master/ox-hugo.el#L2663

I ask, because line numbers, scrolling, and the table mode of lineos interacts very badly (2 scrollbars are created: one for the code, ans one for the line numbers!)

Ideally, I'd like to be able to write

```org
#+BEGIN_SRC ocaml  -n :linenos inline
let x=42
[snip a very long program that does not fit in "max-height"]
#+END_SRC
```

**Comment by kaushalmodi** [comment]
@jahierwan 

> ok, but what if I want to export `{{< highlight php5 "linenos=inline, ...}}`

You cannot do that at the moment. _Using Hugo Shortcodes inline in Org source will never be supported._

Let's move the discussion specific to this in https://github.com/kaushalmodi/ox-hugo/issues/326

**Comment by kaushalmodi** [comment]
Fixed by https://github.com/kaushalmodi/ox-hugo/pull/499.
