### ISSUE TITLE
Remove the "<div></div>" hack needed by Blackfriday

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#306]
Do this only if Hugo v0.60+ is detected.

**Comment by kaushalmodi** [comment]
Good thing is that that hack does not bother Goldmark.

**Comment by titaniumbones** [comment]
awesome to be able to get rid of htis.  Just looking at hugo stuff for hte first time in months, seems like goldmark is a substantial improvement. Glad to have it available.
