### ISSUE TITLE
do not export description when backend is latex

### ISSUE THREAD

**Issue by msteamc** [kaushalmodi/ox-hugo#309]
Dear Sir. 

now ox-hugo support description block as summary, this is very handy. However, when I export the org file as latex(then pdf ) file. The description block is also exported which is not what I want. 

a minimum working description block will be like:
#+begin_description
this will be exported as summary.
#+end_description

Maybe it can be solved by set up the org export options. I tried my best and failed. 

Hopefully, I can find a solution here. Thanks a lot.

**Comment by kaushalmodi** [comment]
Hello,


> However, when I export the org file as latex(then pdf ) file. The description block is also exported which is not what I want.

It's not possible for ox-hugo on how ox-latex exports the Org blocks. 

A workaround is to use EXPORT_HUGO_DESCRIPTION property or #+hugo_description keyword instead of that begin/end block.

**Comment by msteamc** [comment]
yes, sir, you are right. I use #+hugo_description and description>summary before. Occasionally, I found that the description block is supported.  I works.
But when the description is long, it does  not look so beautiful. :(

**Comment by kaushalmodi** [comment]
Another way is to advise the `org-latex-special-block` from `ox-latex.el` to not do anything when the block type is "description".

Here is the source of that function:

```el
(defun org-latex-special-block (special-block contents info)
  "Transcode a SPECIAL-BLOCK element from Org to LaTeX.
CONTENTS holds the contents of the block.  INFO is a plist
holding contextual information."
  (let ((type (org-element-property :type special-block))
	(opt (org-export-read-attribute :attr_latex special-block :options))
	(caption (org-latex--caption/label-string special-block info))
	(caption-above-p (org-latex--caption-above-p special-block info)))
    (concat (format "\\begin{%s}%s\n" type (or opt ""))
	    (and caption-above-p caption)
	    contents
	    (and (not caption-above-p) caption)
	    (format "\\end{%s}" type))))
```

You'll need to advise it so that it returns an empty string when the internal variable `type` is `"description"`.

**Comment by msteamc** [comment]
I am not an elisp expert. maybe, #+hugo_description will exsits in my org file for a long time when some sharp guy get his hand dirty to handle it.  Now, #+hugo_description works well for me , just not so tidy.
