### ISSUE TITLE
Document how to export front matter in YAML

### ISSUE THREAD

**Issue by msteamc** [kaushalmodi/ox-hugo#310]
Dear sir:

      sometimes I want to export the org subtree as a post, but with the front matter in YAML format.

     Now, the hugo support TOML.

    It will be better to have a switch to choose whick kind of format is used.

    Thank you very much.
 
Best Wishes

**Comment by msteamc** [comment]
sorry sir, After reading your doc, I found the variable org-hugo--fm-yaml, It is great :)

**Comment by kaushalmodi** [comment]
Nooo! That's an internal variable! (Any variable with `--` in its name is an internal variable. The same applies to functions too.)

Surpringly, I haven't yet documented this..

Add this to the top of your Org file instead:

```
#+hugo_front_matter_format: yaml
```

PS: TOML rocks though 😃

**Comment by kaushalmodi** [comment]
@msteamc This is now documented at https://ox-hugo.scripter.co/doc/org-meta-data-to-hugo-front-matter/#front-matter-format.

**Comment by msteamc** [comment]
yeach, TOML rocks, definitely
