### ISSUE TITLE
the link to source code disappear when I export .org file to .md file

### ISSUE THREAD

**Issue by msteamc** [kaushalmodi/ox-hugo#311]
## Actual Behavior
when I add a target in org src block like `(ref:filldraw)` , I then refer to it in the text like `[[(ref:filldraw)]]`, I expect there is a link from the text to the source code, but it did not appear.
## A Minimum Working Example will be 
```

#+caption: another minimum working example
#+name: another-minimum-working-example
#+header: :file  "../../img/tikz/example4.png"
#+begin_src latex -n -r  :results raw :exports code
\usetikzlibrary{intersections,arrows.meta}
\begin{tikzpicture}[scale=3]
  \clip (-0.6,-0.2) rectangle (0.6,1.51);
  \draw[step = .5cm, help lines] (-1.4,-1.4) grid (1.4,1.4);
  \filldraw[fill=green!20,draw = green!50!black] (0,0) -- (3mm,0mm)   (ref:filldraw)
  arc [start angle = 0, end angle = 30,radius = 3mm] -- cycle;        (ref:arc)
  \draw[->] (-1.5,0) -- (1.5,0);
  \draw[->] (0,-1.5) -- (0,1.5);
  \draw (0,0) circle [radius=1cm];
  \foreach \x in {-1,-0.5,1}
  \draw(\x cm, 1pt) -- (\x cm, -1 pt) node [anchor = north] {$\x$};
  \foreach \y in {-1,-0.5,1}
  \draw(1pt,\y cm) -- (-1pt, \y cm) node[anchor = east] {$\y$};
\end{tikzpicture}
#+end_src
This is a ref to line [[(ref:filldraw)]].
```

It will be ref to line 5. But I cannot clik the 5 then goto the source code. 

However, when I export the source code to the html directly (instead of md), I can click the 5 and goto the source code. 

There must be sth wrong with the process from org to md, during which the link disappear.

B.R.

**Comment by kaushalmodi** [comment]
Hello, 

Sorry to say that this is one of the the features that I cannot export from Org to Hugo/Goldmark compatible Markdown. 

If someone/you has ideas or PR, I'd be happy to review/discuss/merge those. 

I believe only ox-html supports for reference links to code block lines.

**Comment by kaushalmodi** [comment]
I'm already tracking this issue here: https://github.com/kaushalmodi/ox-hugo/issues/162.

**Comment by msteamc** [comment]
Dear sir,

Are all the link feature  not supported ? or just the link from the source code? what about the radio link in Org mode? 

Thank you for your hard work. I really appreciate it. Thanks.

**Comment by kaushalmodi** [comment]
> Dear sir,

You are being too formal, no need to "sir" :)

> Are all the link feature not supported ?

Almost all kinds of internal and external linking is supported

> what about the radio link in Org mode?

I'll open another issue for that.

> Thank you for your hard work. I really appreciate it. Thanks.

Thank you.

**Comment by kaushalmodi** [comment]
@msteamc Radio targets are now supported. I have added a test at https://ox-hugo.scripter.co/test/posts/radio-targets/.

**Comment by kaushalmodi** [comment]
@msteamc I believe it's safe to close this issue. Feel free to comment in this thread even if it's closed. Thanks.
