### ISSUE TITLE
auto-export fails after switching machines?

### ISSUE THREAD

**Issue by jarss** [kaushalmodi/ox-hugo#312]
## Actual Behavior:
org-mode's dispatches does not creates the .md file automatically as described at https://ox-hugo.scripter.co/doc/auto-export-on-saving/. Need to export manually (C-c C-e). 

## Expected Behavior
With .dir-locals.el in place, this should work. When saving the org file, ox-hugo was to auto-export the .md and results should be seen on the local server (hugo server).

## How to Reproduce the Issue
I am not sure why it's not working so not sure how to reproduce. 

What I did: changed computers, copied all org files and settings of my hugo project with it. Directory struction in the old machine was different than this one, perhaps this is what's causing it, but the project's folder is still in the same relative location.

### Example Org File

[TAONAW.org.gz](https://github.com/kaushalmodi/ox-hugo/files/3965120/TAONAW.org.gz)

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.22.30)

## Org Version

    Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.3/lisp/org/)

## Hugo Version

    Hugo Static Site Generator v0.61.0-9B445B9D linux/amd64 BuildDate: 2019-12-11T08:27:34Z

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-default-section-directory</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "pdf" "odt")</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
> Directory struction in the old machine was different than this one, perhaps this is what's causing it

Possibly.. depends on the location of the .dir-locals.el

Where is the .dir-locals.el placed with respect to the Org content files?

**Comment by kaushalmodi** [comment]
Also,

1. What is the value of `C-h v org-hugo-auto-export-mode`?

2. Does the auto export start working after you do `M-x org-hugo-auto-export-mode`?

**Comment by jarss** [comment]
> > Directory struction in the old machine was different than this one, perhaps this is what's causing it
> 
> Possibly.. depends on the location of the .dir-locals.el
> 
> Where is the .dir-locals.el placed with respect to the Org content files?

It's on the main dir of the project, where the only .org file of the project exists. This is exactly the same setup I had on the laptop. The file contains "((org-mode . ((eval . (org-hugo-auto-export-mode)))))" only.

**Comment by jarss** [comment]
> Also,
> 
>     1. What is the value of `C-h v org-hugo-auto-export-mode`?

...I don't have that. no org-hugo-auto-export-mode

>     2. Does the auto export start working after you do `M-x org-hugo-auto-export-mode`?

... don't have this either. I have three other org-hugo-exports: to-md, wim-to-md, as-md.

**Comment by kaushalmodi** [comment]
Do you then somehow have an older version of ox-hugo?

If you are using the stable channel of Melpa, then you might be getting an older version of ox-hugo. 

Ensure that the ox-hugo installation elpa dir contains the org-hugo-auto-export-mode.el.

**Comment by jarss** [comment]
Possible... If memory serves, I have 0.80 (not in front of it right now). I might have just added stable Melpa.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jarss** [comment]
This was indeed the issue. I had the stable melpa only. Now it works... kinda. It keeps informing me "the buffer [mypost.md] does not end in new line, add one? (y/n)" every time I save. I take it this is more of an Emacs issue than ox-Hugo though?

**Comment by kaushalmodi** [comment]
> I take it this is more of an Emacs issue than ox-Hugo though?

Yes. That sounds like something related to `require-final-newline`.

**Comment by kaushalmodi** [comment]
@jarss Given that the auto exports now works, I am closing this issue.

Regarding your last comment, see http://www.gnu.org/software/emacs/manual/html_node/emacs/Customize-Save.html.

You probably changed the value of `require-final-newline` when you switched machines?

From the above manual node (_emphasis mine_):

> If the value of the variable `require-final-newline` is `t`, saving or writing a file silently puts a newline at the end if there isn't already one there. 

> If the value is `visit`, Emacs adds a newline at the end of any file that doesn't have one, just after it visits the file. (This marks the buffer as modified, and you can undo it.)

> If the value is `visit-save`, Emacs adds such newlines both on visiting and on saving. 

> If the value is `nil`, Emacs leaves the end of the file unchanged; 

> **any other non-nil value means Emacs asks you whether to add a newline.** 

> The default is `nil`.
