### ISSUE TITLE
Can't export elisp blocks

### ISSUE THREAD

**Issue by CeleritasCelery** [kaushalmodi/ox-hugo#315]
## Actual Behavior

when I have a source code block with the language set to `elisp` or `emacs-lisp` the block will not export properly. Instead it will render like this 

    ```nillangnilswitchesnilflags
    nilbody
    ```

If I change the language to `lisp` (or almost any other language) it works fine. 

## Expected Behavior
Emacs lisp source code blocks to export properly. I know this worked about 10 months ago when I wrote my first blog post. But something in either hugo, ox-hugo, or my config has regressed.

## How to Reproduce the Issue

Try to export an elisp source code block. Hopefully you can reproduce this 🤞 

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-suse-linux-gnu, GTK+ Version 2.24.20)
     of 2019-09-19

## Org Version

    Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/intel/pkgs/emacs/26.3/share/emacs/26.3/lisp/org/)

## Hugo Version

    Hugo Static Site Generator v0.62.1-A1518704 linux/amd64 BuildDate: 2020-01-01T17:38:33Z

### Org `load-path` shadows

No Org mode shadows found in `load-path`  

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

  

</details>

**Comment by kaushalmodi** [comment]
Hello,

> But something in either hugo, ox-hugo, or my config has regressed.

Based on your snippet, the exported Markdown itself is incorrect. So hugo is not to blame here.

Also the ox-hugo tests have been passing (see [this page][1] rendered using [this ox-hugo exported Markdown file with an emacs-lisp block][2]), so it's not a change in ox-hugo either.

So it's one of two things:

1. You have discovered a corner case ox-hugo bug which is not covered by any of the existing tests.
2. Something changed in your Org mode setup that's messing up the emacs-lisp src block exports.

Can you provide a minimal example? Also try this snippet from one of the ox-hugo tests.. does that export fine for you?

```org
This code block contains no backticks:
#+begin_src emacs-lisp
(message "Hello again x2")
#+end_src
```

[1]: https://ox-hugo.scripter.co/test/posts/code-fenced-src-blocks/

[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/code-fenced-src-blocks.md

**Comment by CeleritasCelery** [comment]
> Also try this snippet from one of the ox-hugo tests.. does that export fine for you?

No I get the same result with that code block.

> Can you provide a minimal example?

```lisp
#+BEGIN_SRC elisp
(comint-simple-send (get-buffer-process (current-buffer)) "git\t\x15")
#+END_SRC
```

**Comment by CeleritasCelery** [comment]
Spurred by your questions I started to track this down. I tried it with `emacs -Q` and it worked fine, so I knew I had something wrong in my config. turns out that I had a bad value for `org-babel-default header-args:emacs-lisp`. The documentation says `A value of "yes" or t causes src blocks to be eval'd using lexical scoping.` But setting it to `t` is what broke the exporting. When I changed that it worked. Thank you for your time.

**Comment by kaushalmodi** [comment]
Awesome! Thanks for the follow up. I'm glad you figured it out.

**Comment by kaushalmodi** [comment]
> The documentation says A value of "yes" or t causes src blocks to be eval'd using lexical scoping. But setting it to t is what broke the exporting.

If something is not working as per the documentation, bring it up on the Org mode mailing list. Someone usually replies, and if something needs to be fixed, it gets fixed.
