### ISSUE TITLE
Add support for "title" attribute on Org syntax links

### ISSUE THREAD

**Issue by finex** [kaushalmodi/ox-hugo#316]
Hi, currently you can insert link using the following org syntax:
```
[[https://www.example.com][Text]]
```
It will be converted in markdown:
```
[Text](https://www.example.com)
```

It works well but using markdown you can write this code:
```
[Text](https://www.example.com "Title")
```
which Hugo renders in:
```
<a href="https://www.example.com" title="Title">Text</a>
```

Would be possible to extend ox-hugo to support this feature?

P.S: now you can put the Markdown syntax on the .org file and it works fine... but it's not Org :-)

**Comment by kaushalmodi** [comment]
Hello,

The attributes like "title" ("target", etc.) are HTML-specific and Org does not have a native syntax to support those.

Though, `ox-hugo` supports `#+attr_html:` before the links. That attr applies to the first link that follows after that.

As an example (from existing ox-hugo tests):

```org
#+attr_html: :target _blank :rel noopener
[[https://orgmode.org/manual/Hyperlinks.html][This link (to Hyperlinks chapter in Org manual)]] will open in a new tab
as it is annotated with ~target="_blank"~.

#+attr_html: :target _self
[[https://orgmode.org/manual/Hyperlinks.html][Here's the same link]] but with ~target="_self"~ annotation. So
clicking it will open that link in this same tab!

[[https://orgmode.org/manual/Hyperlinks.html][Here's the same link again]], but this time there is no =#+attr_html=
annotation. So the behavior of clicking this link will depend on the
browser (typically an external link will open in a new tab
automatically).
```

You can see the above snippet a part of this ox-hugo exported test: https://ox-hugo.scripter.co/test/posts/links-with-target-attribute

To directly answer your query, try this out:

```org
#+attr_html: :title "Title"
[[https://www.example.com][Text]]
```



I hope that helps.

**Comment by kaushalmodi** [comment]
Kind of related.. also look at this test: https://ox-hugo.scripter.co/test/posts/figure-shortcode-and-attr-html

To find its Org source, search for "figure-shortcode-and-attr-html" in the [test Org file][1].

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/all-posts.org

**Comment by finex** [comment]
Hi, I tried the `#+attr_html: :title "Title"` but it works only if you enable `unsafe = true` on Hugo settings, otherwise it will render `<!-- raw HTML omitted -->`. I'm trying to keep that option off but I suspected that attributes like "title" are not available on Org syntax. Anyway thanks for your quick feedback, I really appreciate it :-)

**Comment by kaushalmodi** [comment]
> but it works only if you enable unsafe = true on Hugo settings

That's correct. See https://github.com/kaushalmodi/ox-hugo/issues/307.

> I'm trying to keep that option off

Why? Nothing is "unsafe" about that option. This has been brought up on the Hugo forums many times. Earlier behavior was equivalent to the unsafe being defaulted to true. But the Hugo developer somehow chose to default that to false when switching to Goldmark. The Commonmark spec also allows having inline HTML in Markdown.

There's nothing "unsafe" in having inline HTML as you know what HTML is committed in the Markdown.

A more correct term for that "unsafe" parameter would be "allow-inline-HTML".

**Comment by kaushalmodi** [comment]
Hello, is this issue resolved?

**Comment by kaushalmodi** [comment]
Closing the issue.

**Comment by finex** [comment]
Yes, thank you for the explanation :-)
