### ISSUE TITLE
Heading tags h5 and h6 not working

### ISSUE THREAD

**Issue by finex** [kaushalmodi/ox-hugo#317]
Hi, ox-hugo correctly convert heading until `<h4>` but nested title are bugged: h5 and h6 are rendered as nested list items:

```
-    Title
```

instead of:

```
##### Text
```

**Comment by kaushalmodi** [comment]
See https://orgmode.org/manual/Export-settings.html.

The default value of `org-export-headline-levels` is 3. You can either set that variable in your emacs config, or add this to the top of your Org file:

```org
#+options: h:6
```

Related tests:

- https://ox-hugo.scripter.co/test/tags/nested

**Comment by kaushalmodi** [comment]
Hello, is your issue resolved?

**Comment by kaushalmodi** [comment]
Closing the issue.

**Comment by finex** [comment]
Hi, thanks... yes the option you suggested did the trick :-)
