### ISSUE TITLE
Documentation: How to link to .md file already in content/posts from your org file? 

### ISSUE THREAD

**Issue by jrmiller82** [kaushalmodi/ox-hugo#318]
In a Hugo markdown file you'd do a link like `[link text]({{< ref "filename.md" >}})` to create a hyperlink to the post in filename.md. 

How do we do the same in our .org file?

Thanks!

**Comment by kaushalmodi** [comment]
You need to deduce the link the Markdown file will generate if that file is not generated by the Org file.  *If that Markdown file is generated from Org, you can link to the original Org heading or file as you'd normally do in Org.*

Examples of linking to a Markdown file:

- To link to a `content/foo.md` do `[[/foo][link desc]]`.
- To link to a `content/posts/foo.md` do `[[/posts/foo][link desc]]`.

---

Suggestion: Convert that Markdown file to Org using pandoc, add that Org content as a separate post subtree or a separate file, and then link to it as you'd do in Org.

**Comment by kaushalmodi** [comment]
Another alternative is that you write an Org macro that exports to the Hugo ref style links. 

Here's an untested example:

```

#+macro: hugoref @@md:[$2]({{<ref "$1" >}})@@
```

You'd then write the above examples as `{{{hugoref(foo,link desc)}}}` (the `ref` shortcode does not need the file extension) and `{{{hugoref(bar,link desc)}}}` (if the file name is unique in the entire content, you don't even need to provide the entire path relative to the content directory).

**Comment by jrmiller82** [comment]
Thanks for this. I anticipate new articles going forward to be written in a single org file so I can use the normal org internal linking; I have about 40 blog posts in .md form that were *not* generated from ox-hugo that need to be converted into the org file. Some of those link to each other using the hugo ref form, so I'll probably just bring those into my org file. 

I think your response right here would be helpful to add into the docs right around where it is discussing image links and the static directory.

**Comment by jrmiller82** [comment]
@kaushalmodi Is there some I'm doing wrong with internal linking? I can't seem to get internal links to work when they're in the format like this:

```
** SUPER LONG HEADING THAT I DON'T WANT TO HAVE TO TYPE INTO AN INTERNAL LINK
:PROPERTIES:
:CUSTOM_ID: slh1
:END:

then lots of intervening space to another article...

[[#slh1][link description]] 
```
Org will follow the link with a `C-c o` just fine; it's ox-hugo that aborts when it encounters it. 

Any strategies? Thanks in advance.

**Comment by jrmiller82** [comment]
@kaushalmodi Weird behavior just discovered. `ox-hugo` only doesn't like that link format if the link is contained in the same blog post. The separate blog posts linked just fine with the `[[#foo][bar]]` form.

I'm making a table of other posts in an introductory post, and while I don't have to link to the same post, it's nice to have it all in one place for presentation.

**Comment by kaushalmodi** [comment]
Let me try to understand.. are you trying link to the same blog post within itself? (I haven't tried that). 

Also, I am wondering if this is an XY problem. Instead of manually collecting link to the self and other posts in one post, may be use Hugo templating to do the same automatically. I have used Hugo templating to collect all the links to posts of the same series.

**Comment by jrmiller82** [comment]
Yes, the link that fails is a `[[#foo][decription]]` style link inside the same blog post that links to itself. 

Do you have documentation on the templating solution? That seems a little overboard when it's just a single link in the body of a blog post (as opposed to say, a sidebar of a front page).

**Comment by kaushalmodi** [comment]
You can do:

```org
[[./][link to self]]
```

> Do you have documentation on the templating solution? 

There is extensive documentation on Hugo templating. That will be out of scope of this project, but ...

> That seems a little overboard when it's just a single link in the body of a blog post (as opposed to say, a sidebar of a front page).

I agree. If you simply want to link the current post, try the above `./` link.

**Comment by kaushalmodi** [comment]
@jrmiller82 I have continued the conversation for this use case in https://github.com/kaushalmodi/ox-hugo/issues/322.

**Comment by kaushalmodi** [comment]
> Another alternative is that you write an Org macro that exports to the Hugo ref style links.

This is now documented here: https://ox-hugo.scripter.co/doc/shortcodes/#org-macros
