### ISSUE TITLE
Customize css between src block and result of src block by adding parameters to org babel block ? 

### ISSUE THREAD

**Issue by reyman** [kaushalmodi/ox-hugo#319]
Hi,
It's more a question than a bug, what is the canonical way to differentiate css for src block and result block ? 

Src block and result block are equally exported with :  

`<div class="highlight"> <pre code style ="" ...> `

Is there a way to parametrize that directly in org ? By adding for example a `class="org-source"` or `class="org-result" `to div class highlight ?

**Comment by kaushalmodi** [comment]
I thought a little bit about this. I cannot implement this consistently for small and large result blocks.

Org babel auto-generates an **example** block for large Org babel result blocks. 

```org
#+RESULTS:
#+begin_example
abc
def
ghi
jkl
mno
pqr
stu
vwx
yz0
123
456
789
#+end_example
```

Whereas it generates a **fixed** block for small result blocks.

```org
#+results:
: 	bc
```

I need to dig into the ob-core.el to see if anything can be done here.

**Comment by kaushalmodi** [comment]
A solution might involve advising this function in ob-core.el:

```el
(defun org-babel-examplify-region (beg end &optional results-switches inline)
  "Comment out region using the inline `==' or `: ' org example quote."
  (interactive "*r")
  (let ((maybe-cap
	 (lambda (str)
	   (if org-babel-uppercase-example-markers (upcase str) str))))
    (if inline
	(save-excursion
	  (goto-char beg)
	  (insert (format org-babel-inline-result-wrap
			  (delete-and-extract-region beg end))))
      (let ((size (count-lines beg end)))
	(save-excursion
	  (cond ((= size 0))	      ; do nothing for an empty result
		((< size org-babel-min-lines-for-block-output)
		 (goto-char beg)
		 (dotimes (_ size)
		   (beginning-of-line 1) (insert ": ") (forward-line 1)))
		(t
		 (goto-char beg)
		 (insert (if results-switches
			     (format "%s%s\n"
				     (funcall maybe-cap "#+begin_example")
				     results-switches)
			   (funcall maybe-cap "#+begin_example\n")))
		 (let ((p (point)))
		   (if (markerp end) (goto-char end) (forward-char (- end beg)))
		   (org-escape-code-in-region p (point)))
		 (insert (funcall maybe-cap "#+end_example\n")))))))))
```

**Comment by kaushalmodi** [comment]
@reyman 

After updating to the latest code on ox-hugo master branch, try putting something like this **directly above** the `#+results:` section that Org Babel generates.

Here's an example:

```org
#+begin_src python :exports both :results output
str = 'd\tef'
print(str[1:])
#+end_src

#+attr_html: :class results-fixed-block
#+attr_css: :color blue
#+results:
: 	ef
```

The rendered HTML from the .md exported from above can be seen on this test page: https://ox-hugo.scripter.co/test/posts/org-babel-results/.

**Comment by kaushalmodi** [comment]
@reyman I saw the thumbs up.. Does that mean that this issue is now fixed? If so, you can close the issue.

**Comment by reyman** [comment]
I try and i answer you during week :)

**Comment by kaushalmodi** [comment]
I'll assume that this issue is fixed and close this. Feel free to comment here if the suggestion in https://github.com/kaushalmodi/ox-hugo/issues/319#issuecomment-577380432 doesn't work for you.

**Comment by reyman** [comment]
Sorry for the delay, it's in my todo list, if something don't work, i reopen this ticket.
