### ISSUE TITLE
Helper function to create subtrees for new posts with required property drawers

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#32]
Need to take post title from minibuffer, and auto-generate EXPORT_DATE, EXPORT_FILE_NAME properties.

**Comment by kaushalmodi** [comment]
Though it would be good to have this function as I won't have a capture template for all Org blog files.

**Comment by jave** [comment]
this code helps me anyway:

(defun jv-ox-prop ()                                                                                                                                                                                               
(interactive)                                                                                                                                                                                                      
(org-set-property "EXPORT_FILE_NAME" (org-hugo-slug (org-get-heading                                                                                                                                               
t t))))   

I used it together with a simple keyboard macro to convert a large org tree.

**Comment by kaushalmodi** [comment]
Thanks! I have something similar *work-in-progress*.. haven't committed yet.

**Comment by digizeph** [comment]
It's a great quality-of-life feature to have! Any updates on this matter?

**Comment by kaushalmodi** [comment]
Hello, as I use the [org-capture flow][1], I haven't yet needed to create post subtrees after manually opening Org files. Do you want to try out the capture flow?

[1]: https://ox-hugo.scripter.co/doc/org-capture-setup/

**Comment by digizeph** [comment]
@kaushalmodi Hey, this capture flow looks very much what I will need! 

Sorry, I should have gone through the documentation first. I didn't notice the capture flow is already in the documentation site. Thanks!

**Comment by dorneanu** [comment]
> I used it together with a simple keyboard macro to convert a large org tree.

@jave can you please share your code how to call that function for a large Org tree? Thanks!

**Comment by kaushalmodi** [comment]
Closing this issue because the Org capture flow can already do this: https://ox-hugo.scripter.co/doc/org-capture-setup/

No need to bake this thing into ox-hugo.
