### ISSUE TITLE
Japanese characters also need text-unwrapping without space

### ISSUE THREAD

**Issue by tera-p** [kaushalmodi/ox-hugo#320]
I'm starting to use ox-hugo for a blog written in Japanese, and found an issue about text-unwrapping.

Text-unwrapping without inserting whitespace isn't only needed for Chinese texts but also needed for Japanese texts (and maybe also for Korean, but I'm not sure).

## Actual Behavior

Unwrapping the Japanese text below (e.g. for generating summary and footnotes):

```
これは
テストです．
```

becomes:

```
これは テストです．
```
(A whitespace is inserted between "は" and "テ")

## Expected Behavior

```
これはテストです．
```
(No whitespace is inserted)

## How to fix (IMO)

A quick (and straightforward) fix will be:
1. to add a checking logic `(string-prefix-p "ja" lang)` to `org-hugo-paragraph` in addithion to checking Chinese ("zh"), and 
2. also to add the same logic to `org-blackfriday-footnote-section` (maybe with checking Chinese texts; currently this function does not have a logic for unwrapping CJK texts), 

which work well in my environment (I can send PR if needed).

The second option is to use `isCJKLanguage` instead of checking languages individually; which might be simpler, but I'm not sure if Korean texts need this behavior.

The third (and probably the best) option will be to check if both of the characters surrounding a newline are CJK characters (i.e. having CJK code point in Unicode), which should be ideal and enables a multi-lingual page to be adequately processed, but I'm not sure if it can be easily implemented.

**Comment by kaushalmodi** [comment]
> Text-unwrapping without inserting whitespace isn't only needed for Chinese texts but also needed for Japanese texts (and maybe also for Korean, but I'm not sure).

Thanks for reporting the issue. The quality of this package for languages not used by me depends on users like you.

Please see the latest commit on master. For now I have added only "ja" to list of languages where the unwrapping shouldn't a space. Now it will be easy to add other languages to this list:

https://github.com/kaushalmodi/ox-hugo/blob/0fafc2a01ec5948a1b79a969c6374c7f1566c43e/ox-hugo.el#L2476

> A quick (and straightforward) fix will be:  to add a checking logic (string-prefix-p "ja" lang) to org-hugo-paragraph in addithion to checking Chinese ("zh"), and

I went ahead with a similar fix.

> also to add the same logic to org-blackfriday-footnote-section (maybe with checking Chinese texts; currently this function does not have a logic for unwrapping CJK texts),

I have now done that too: https://github.com/kaushalmodi/ox-hugo/commit/4d3890dfafc1ae7385c0a0799bfa8c669e7d2baf

Please try out the latest ox-hugo and let me know if it now works as expected.

**Comment by tera-p** [comment]
Thank you very much for your quick and excellent fix.

> Please see the latest commit on master. For now I have added only "ja" to list of languages where the unwrapping shouldn't a space. Now it will be easy to add other languages to this list:
> 
> https://github.com/kaushalmodi/ox-hugo/blob/0fafc2a01ec5948a1b79a969c6374c7f1566c43e/ox-hugo.el#L2476

Yeah, more elegant fix than mine.  I'll try it sooner.

> > A quick (and straightforward) fix will be:  to add a checking logic (string-prefix-p "ja" lang) to org-hugo-paragraph in addithion to checking Chinese ("zh"), and
> 
> I went ahead with a similar fix.
> 
> > also to add the same logic to org-blackfriday-footnote-section (maybe with checking Chinese texts; currently this function does not have a logic for unwrapping CJK texts),
> 
> I have now done that too: [4d3890d](https://github.com/kaushalmodi/ox-hugo/commit/4d3890dfafc1ae7385c0a0799bfa8c669e7d2baf)
> 
> Please try out the latest ox-hugo and let me know if it now works as expected.

seems perfect.  I'll try them and report the results later.

> > The second option is to use isCJKLanguage instead of checking languages individually; which might be simpler, but I'm not sure if Korean texts need this behavior.
> 
> Where is that `isCJKLanguage` defined? For now, I defined one locally in `ox-hugo`: [c60a839](https://github.com/kaushalmodi/ox-hugo/commit/c60a839821d7d265647bf5df79ab15419a304d18) .

I meant the variable defined at `ox-hugo`:L3322:
https://github.com/kaushalmodi/ox-hugo/blob/4d3890dfafc1ae7385c0a0799bfa8c669e7d2baf/ox-hugo.el#L3322
which seems to reflect `HUGO_ISCJKLANGUAGE` property if my understanding of the code is correct...

BTW, I mentioned that Korean texts also might need this behavior (but unsure) in my previous post, but I found it can be incorrect (sorry).  According to [Wikipedia](https://en.wikipedia.org/wiki/Word_divider), traditionally they used to, but modern hangul (characters used in Korea) texts use a space as word divider.  However, I'm not familiar with hangul, I leave it to native Korean people.

> > The third (and probably the best) option will be to check if both of the characters surrounding a newline are CJK characters (i.e. having CJK code point in Unicode), which should be ideal and enables a multi-lingual page to be adequately processed, but I'm not sure if it can be easily implemented.
> 
> I just went ahead with the simplest and less performance-intensive approach (we do not want the exports to become slower).

Yes, I agree.  The current solution might be practically the best until `delete-identation` function in Emacs honors this problem and we can throw the problem to it. ;-)

**Comment by tera-p** [comment]
> I'll try them and report the the results later.

I created [a test page](https://tera-p.gitlab.io/post/ox-hugo-japanese-unwrapping-test/).

In summary, the first fix works perfectly, but the second fix (related to footnotes) seems to have introduced regression about unwrapping English words (cf. Test 4 and 6 in my test page).

## Test 4

```
This is a test[fn::of
footnote].
```
makes footnote entry:
```
[^fn:2]: offootnote
```
(no space between "of" and "footnote")

## Test 6

```
これは[fn::footnote
の] test です．

これも test[fn::of
脚注] です．
```
makes:
```
[^fn:3]: footnoteの
[^fn:4]: of脚注
```
(acceptable, but a space between "footnote" and "の", and also between "of" and "脚注" is preferred)

**Comment by kaushalmodi** [comment]
The behavior you see is expected.. I am expecting the footnotes to be all Japanese or all English. To support a mix of English and Japanese, we need to do character checks and figure out if the char before/after newline is Chinese, Japanese, English, etc.

**Comment by tera-p** [comment]
> The behavior you see is expected.. I am expecting the footnotes to be all Japanese or all English. To support a mix of English and Japanese, we need to do character checks and figure out if the char before/after newline is Chinese, Japanese, English, etc.

Hmm... But it's quite usual to involve English words in Japanese (and probably Chinese) texts.

How about this fix?  I tested this patch using the test page I mentioned above and seems to work well.
```
--- ox-blackfriday.el.orig      2020-01-23 00:51:28.329653100 +0900
+++ ox-blackfriday.el   2020-01-23 01:01:25.017346400 +0900
@@ -145,12 +145,11 @@
         ;; Support multi-line footnote definitions by folding all
         ;; footnote definition lines into a single line as Blackfriday
         ;; does not support that.
-        (setq def (replace-regexp-in-string
-                   "\n"
-                   ;; Do not insert spaces when joining newlines for
-                   ;; CJK languages.
-                   (if is-cjk "" " ")
-                   def))
+        (when is-cjk
+         (setq def (replace-regexp-in-string
+                    "\\([[:multibyte:]]\\)[[:blank:]]*\n[[:blank:]]*\\([[:multibyte:]]\\)" "\\1\\2"
+                    def)))
+        (setq def (replace-regexp-in-string "\n" " " def))
         ;; Replace multiple consecutive spaces with a single space.
         (setq def (replace-regexp-in-string "[[:blank:]]+" " " def))
         (push (cons n def) fn-alist-stripped)
```

**Comment by kaushalmodi** [comment]
hah! I am currently working on the same.. 

![image](https://user-images.githubusercontent.com/3578197/72911594-56972480-3d08-11ea-85a4-ebef6e0846b1.png)

**Comment by tera-p** [comment]
Great!
I'll test it when uploaded.

**Comment by kaushalmodi** [comment]
@tera-p I pushed the change to master. Thanks for testing.

**Comment by kaushalmodi** [comment]
Actually, please wait for few minutes.. I made a hasty commit.

**Comment by kaushalmodi** [comment]
It should be now fixed in https://github.com/kaushalmodi/ox-hugo/commit/81e29a045ddd30589556d53b3637da95f2271aa5.

**Comment by tera-p** [comment]
I tested it and the results were perfect.
Thanks again for your excellent and lightning fix!

**Comment by kaushalmodi** [comment]
Awesome! If everything is resolved here, you can close this issue.

**Comment by tera-p** [comment]
Yeah, I'll close this issue now.
