### ISSUE TITLE
way to disable automatic Figure N insertion for #+CAPTION: attribute

### ISSUE THREAD

**Issue by andreyorst** [kaushalmodi/ox-hugo#321]
pretty much as in this SO question https://emacs.stackexchange.com/questions/17619/how-can-i-turn-off-numbering-for-figures

Currently resulting markdown has `Figure N` for captions which I'd like to remove, as those take too much place under really small images that I still want to have captions. Is this possible?

**Comment by kaushalmodi** [comment]
It will be possible to mask the "Figure N:" prefixes to captions once https://github.com/kaushalmodi/ox-hugo/issues/205 is implemented. 

I'll look into implementing that feature soon (it was just that there was no need of it so far :) ).

**Comment by andreyorst** [comment]
This also expands to code snippets and other media.

**Comment by treitmaier** [comment]
I removed the unwanted Figure N: prefix by overriding hugo's built-in [figure shortcode](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/figure.html). 
Just place the below `figure.html` file in the `layouts/shortcodes/` directory of your hugo (theme). It uses a simple regex on line 1 to remove the unwanted prefix. 

```
{{ $caption := replaceRE "^Figure [0-9]+: " "" (.Get "caption") }}
<figure{{ with .Get "class" }} class="{{ . }}"{{ end }}>
    {{- if .Get "link" -}}
        <a href="{{ .Get "link" }}"{{ with .Get "target" }} target="{{ . }}"{{ end }}{{ with .Get "rel" }} rel="{{ . }}"{{ end }}>
    {{- end }}
    <img src="{{ .Get "src" }}"
         {{- if or (.Get "alt") $caption }}
         alt="{{ with .Get "alt" }}{{ . }}{{ else }}{{ $caption | markdownify| plainify }}{{ end }}"
         {{- end -}}
         {{- with .Get "width" }} width="{{ . }}"{{ end -}}
         {{- with .Get "height" }} height="{{ . }}"{{ end -}}
    /> <!-- Closing img tag -->
    {{- if .Get "link" }}</a>{{ end -}}
    {{- if or (or (.Get "title") $caption) (.Get "attr") -}}
        <figcaption>
            {{ with (.Get "title") -}}
                <h4>{{ . }}</h4>
            {{- end -}}
            {{- if or $caption (.Get "attr") -}}<p>
                {{- $caption | markdownify -}}
                {{- with .Get "attrlink" }}
                    <a href="{{ . }}">
                {{- end -}}
                {{- .Get "attr" | markdownify -}}
                {{- if .Get "attrlink" }}</a>{{ end }}</p>
            {{- end }}
        </figcaption>
    {{- end }}
</figure>
```

**Comment by kaushalmodi** [comment]
After the previous commit, you can hide the caption numbers for different elements this way in CSS:

**Hiding `figure` caption numbers**

```css
.figure-number {
  display: none;
}
```

**Hiding Org source block caption numbers**

```css
.src-block-number {
  display: none;
}
```

**Hiding Table caption numbers**

```css
.table-number {
  display: none;
}
```

**Comment by kaushalmodi** [comment]
@andreyorst Please try out the lastest commit with the suggested CSS. We can reopen this issue if it's still not fixed.

**Comment by jackbaty** [comment]
I don't know if this is the right place to mention this, but using latest ox-hugo with figure captions, HTML markup in the captions are rendered encoded, e.g.:

```
<figcaption>
          <p>&lt;span class=&#34;figure-number&#34;&gt;Figure 1: &lt;/span&gt;Mom and Dad (1971)</p>
</figcaption>
```

This is from the following Org content:

```
#+caption: Mom and Dad (1971)
[[/img/2022/20220118-MomDadDressup.jpg]]
```

The Markdown renders as:

```
{{< figure src="/img/2022/20220118-MomDadDressup.jpg" caption="<span class=\"figure-number\">Figure 1: </span>Mom and Dad (1971)" >}}
```

I'm running latest doom emacs with unpinned ox-hugo. Let me know if there's a better place for this or if I'm missing something. Thanks.

**Comment by andreyorst** [comment]
> @andreyorst Please try out the latest commit with the suggested CSS. We can reopen this issue if it's still not fixed.

yes, it works, thank you!
