### ISSUE TITLE
Support linking to the post in which the link is present

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#322]
Yes, the link that fails is a `[[#foo][decription]]` style link inside the same blog post that links to itself. 

Do you have documentation on the templating solution? That seems a little overboard when it's just a single link in the body of a blog post (as opposed to say, a sidebar of a front page).

_Originally posted by @jrmiller82 in https://github.com/kaushalmodi/ox-hugo/issues/318#issuecomment-578839336_

**Comment by kaushalmodi** [comment]
You can do:

```org
[[./][link to self]]
```

> Do you have documentation on the templating solution? 

There is extensive documentation on Hugo templating. That will be out of scope of this project, but ...

> That seems a little overboard when it's just a single link in the body of a blog post (as opposed to say, a sidebar of a front page).

I agree. If you simply want to link the current post, try the above `./` link.

**Comment by kaushalmodi** [comment]
@jrmiller82 I see the ability to link a post in itself as a very rare use case.

In fact, none of the inbuilt Org exporters support it. For example try this:

```org
* Some post                
:PROPERTIES:
:EXPORT_FILE_NAME: some-post
:END:
[[*Some post][link to self]]
```

- Create above Org file
- Move cursor to `[[*Some post][link to self]]`
- Do `C-c C-e C-s t A` (export only that subtree to ascii).
- You will get _user-error: Unable to resolve link: "*Some post"_.

The workaround (will probably work only for `ox-hugo`) is to do `[[./][link to self]]`, but that link of course will not work with `C-c C-o`.

**Comment by kaushalmodi** [comment]
A better alternative (if you are looking for auto-linking posts from the same series) would be to get acquainted with [Hugo Templates][1] and let Hugo do that job for you.

Here's [an example][2] which auto-generates series sections like this:

![image](https://user-images.githubusercontent.com/3578197/73198111-82e3e400-4100-11ea-825b-8e94aa554ce9.png)


[1]: https://gohugo.io/documentation/
[2]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/e0a6e87f245211317f2fcd13a44608fc3ebf9224/layouts/partials/series.html

**Comment by jrmiller82** [comment]
Thanks for this information @kaushalmodi ! I also really appreciate your responsiveness on this project. A+ work!

I will likely investigate that templating when I do a "popular series" page for my blog. In the meantime, I'll try the `[[./][descr]]` form.
