### ISSUE TITLE
Allow specifying `linenos` arg value to the `highlight` shortcode in the exported Markdown

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#326]
ok, but what if I want to export 
`{{< highlight php5 "linenos=inline, ...}}`
?
its seems that the `linenos=table` is hardcoded: 
https://github.com/kaushalmodi/ox-hugo/blob/master/ox-hugo.el#L2663

I ask, because line numbers, scrolling, and the table mode of lineos interacts very badly (2 scrollbars are created: one for the code, ans one for the line numbers!)

Ideally, I'd like to be able to write

```org
#+BEGIN_SRC ocaml  -n :linenos inline
let x=42
[snip a very long program that does not fit in "max-height"]
#+END_SRC
```

_Originally posted by @jahierwan in https://github.com/kaushalmodi/ox-hugo/issues/305#issuecomment-580751338_

**Comment by kaushalmodi** [comment]
@jahierwan

> its seems that the linenos=table is hardcoded

At the time of coding this, `linenos=inline` was the only option that worked with Chroma. Can you investigate and point me to the docs where more `linenos` options are supported?

**Comment by kaushalmodi** [comment]
Also:

> I ask, because line numbers, scrolling, and the table mode of lineos interacts very badly (2 scrollbars are created: one for the code, ans one for the line numbers!)

Can you create a minimal example of the issue and report it on https://discourse.gohugo.io/ ?

**Comment by jahierwan** [comment]
> @jahierwan
> 
> > its seems that the linenos=table is hardcoded
> 
> At the time of coding this, `linenos=table` was the only option that worked with Chroma. Can you investigate and point me to the docs where more `linenos` options are supported?

https://gohugo.io/content-management/syntax-highlighting/

**Comment by jahierwan** [comment]
> Can you create a minimal example of the issue and report it on https://discourse.gohugo.io/ ?

ok, I'll give it a try

**Comment by kaushalmodi** [comment]
> https://gohugo.io/content-management/syntax-highlighting/

I believe that is outdated. The Chroma highlighter supports either using "table" or not.

See this code in hugo:

https://github.com/gohugoio/hugo/blob/40a092b0687d44ecb53ef1fd53001a6299345780/markup/highlight/config.go#L139-L140

That said, I will look into the option of specifying the `linenos` style.

**Comment by jahierwan** [comment]
> > Can you create a minimal example of the issue and report it on https://discourse.gohugo.io/ ?
> 
> ok, I'll give it a try

I use highlight.js for coloring. It is the culprit somehow. if I remove from my
`layouts/partial/footer.html` the call to `hljs.initHighlightingOnLoad();`, it works fine.

**Comment by jahierwan** [comment]
> That said, I will look into the option of specifying the `linenos` style.

That would be great, thanks (for that and for the excellent hugo-ox stuff!)

**Comment by kaushalmodi** [comment]
@jahierwan Thanks for the follow-up. And you're welcome.  :)

**Comment by kaushalmodi** [comment]
@jahierwan I got a chance to finally look into this.

We can now specifying custom `:linenos`. Please see the updated doc: https://ox-hugo.scripter.co/doc/source-blocks/#line-number-style--linenos

Updated test:
- https://ox-hugo.scripter.co/test/posts/source-block-with-line-numbers/
  - https://raw.githubusercontent.com/kaushalmodi/ox-hugo/main/test/site/content/posts/source-block-with-line-numbers.md

**Comment by jahierwan** [comment]
It looks great, thanks!
