### ISSUE TITLE
use dvisvgm for latex equation export

### ISSUE THREAD

**Issue by andreyorst** [kaushalmodi/ox-hugo#327]
Hello. I'm trying to set up latex exporting to svg via `dvisvgm` instead of relying on `mathjax`. Currently if I set this option at the top of my org mode file I see exported images in resulting markdown files in this facion:

Org file:
```org
#+options: tex:dvisvgm
... text ...
\[ a + b \]
... text ...
```

Markdown:
```md
... text ...
<object type="image/svg+xml" data=".ltximg/blog_bbacb5f50664161c1c001269e2c3c77fd5202d24.svg" class="org-svg">
Sorry, your browser does not support SVG.</object>
... text ...
```
Which will not work because the path to the image is wrong after hugo builts the page.

There's an option for that `org-preview-latex-image-directory` but if I set it to something like `./static/ltximg` it still doesn't work because of wrong path.

Is it possible to set the correct path or configure ox-latex in a way that it will copy images somewhere?

**Comment by kaushalmodi** [comment]
I just realized that I forgot to reply to this thread after reading the issue. This is not being ignored. 

I'll see if I can get time to implement this feature in next 2 weeks. PR's are always welcome. 

In the meanwhile, would the Mathjax solution work for you?

**Comment by andreyorst** [comment]
I would like to avoid using JavaScript as I disable it on most sites, so
mathjax is not an option for me. dvisvgm is good solution for me because
orgmode supports it natively for inline previews of latex equations so it
seem natural to support it in ox-hugo. Same goes for dvipng, I don't use
it, but seems that general process can be shared between those, as they
both can be used in previews.

Currently I manually place generated images to static directory.

>

**Comment by kaushalmodi** [comment]
@andreyorst Hello! I am replying to this thread after a while. If you are still using ox-hugo, try out the latest commit on the `main` branch and let me know if it works as expected for you.

It worked well for me from my local testing.

**Comment by andreyorst** [comment]
Just tested and it seems to work!
