### ISSUE TITLE
Tag subtree within post

### ISSUE THREAD

**Issue by dorneanu** [kaushalmodi/ox-hugo#328]
## Actual Behavior
I have a collection of books where I constantly highlight text using my e-reader. While it's straight forward to use `org-mode` with `ox-hugo` to manage the books collection, I have some problems 
managing the quotes. 

Let's consider following content:

```
◉ Books
  :PROPERTIES:
  :EXPORT_FILE_NAME: index
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nocomment true :nodate true :nopaging true :noread true
  :EXPORT_HUGO_MENU: :menu main
  :EXPORT_HUGO_SECTION: books
  :EXPORT_HUGO_WEIGHT: auto
  :END:
**○ Books index
    :PROPERTIES:
    :EXPORT_FILE_NAME: _index
    :END:
**○ Mybook                                       :@cool:@updates:bookie:
    :PROPERTIES:
    :EXPORT_FILE_NAME: mybook
    :END:

****✸ Quotations
******✿ Note 1                            :@cool:...
******✿ Note 10 ...
```

I can see the tags related to `Mybook`. However, inside that post I'd like to have several quotations marked with specific tags (e.g. `Note 1` taged with `@cool`). 

## Expected Behavior

I would expect the subtree `Note 1` to be appear in the posts/pages list related to tag `@cool`. 

## How to Reproduce the Issue

Just use my sample content. 

### Example Org File
See above. 

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment]
There are 2 issues with Org structuring here:

1. "Note 1" doesn't have its own `EXPORT_FILE_NAME` property.
2. The intended post is nested inside another post i.e. another subtree with `EXPORT_FILE_NAME` property. 

The fix is to:

1. Give the "Note 1" (and all other notes which you want to see on separate pages) to have its own `EXPORT_FILE_NAME` property, and
2. Ensure that that note subtree is not nested any other subtree (directly or indirectly) with that `EXPORT_FILE_NAME` property.

**Comment by dorneanu** [comment]
>  "Note 1" doesn't have its own EXPORT_FILE_NAME property.

Hmmm... I actually didn't want to export every note aka having additional posts for every single note. And regarding the `EXPORT_FILE_NAME` property: Is there any way to automate the setting of this property?!

**Comment by kaushalmodi** [comment]
> Hmmm... I actually didn't want to export every note aka having additional posts for every single note. 

> I would expect the subtree Note 1 to be appear in the posts/pages list related to tag @cool.

You can tag only "posts". This is to correlate with the `tags` metadata in Hugo post front-matter that associates with the whole post.

**Comment by kaushalmodi** [comment]
> And regarding the EXPORT_FILE_NAME property: Is there any way to automate the setting of this property?!

What kind of automation are you looking for? I use [Org Capture][1] to auto-set the EXPORT_FILE_NAME for my posts.

[1]: https://ox-hugo.scripter.co/doc/org-capture-setup/

**Comment by kaushalmodi** [comment]
Also ..

> I would expect the subtree Note 1 to be appear in the posts/pages list

You cannot have just a part of a post (Note 1) appear in a list. Hugo's smallest level chunk is a post or a page. You can have list of pages or list of list of pages. But you cannot associate tags with sections in a post, without a heavily engineered Hugo template system, I believe.

**Comment by dorneanu** [comment]
> What kind of automation are you looking for? I use Org Capture to auto-set the EXPORT_FILE_NAME for my posts.

I don't use org capture to create posts on the fly. I already have my list of books and their quotes. So for existing quotes I'd like to easily add `EXPORT_FILE_NAME`. Is there any way to do so?

**Comment by kaushalmodi** [comment]
> Is there any way to do so?

This is Emacs, so the answer is **yes**; but you will need to make your hands dirty with Emacs Lisp.

Here's an example of how one `ox-hugo` user auto-set the `EXPORT_FILE_NAME` for a subtree under point. You can even add a wrapper elisp around that to loop through all subtrees and auto-add this property. The possibilities are endless.

But that of course resides outside the scope of `ox-hugo`. If you have a nice solution, I would happily add that to ox-hugo documentation. If you blog about it, I can even mention it in the ox-hugo docs.

**Comment by dorneanu** [comment]
That's for the example. That's exactly what I'm looking for. I'm still quite new to emacs (after almost 15 years in VIM). I'm using spacemacs to keep things easy. But sometimes (like in this case) I need to rely on others solutions. 

Unfortunately I have no clue how to loop through all subtrees and auto-add the property. I should be fine with some manual steps.

**Comment by kaushalmodi** [comment]
@dorneanu 

> I'm still quite new to emacs (after almost 15 years in VIM). I'm using spacemacs to keep things easy. But sometimes (like in this case) I need to rely on others solutions.

Welcome to the awesome world of Emacs and Elisp! :D

If your issue is resolved, feel free to close this.
