### ISSUE TITLE
Auto Generated Header ID Overriding Custom Header ID

### ISSUE THREAD

**Issue by smpentecost** [kaushalmodi/ox-hugo#332]
## Actual Behavior
\* My Heading {#customid}
exported as:
\#\# My Heading {#customid} {#my-heading-customid}

## Expected Behavior

\* My Heading {#customid}
exported as:
\#\# My Heading {#customid}

## How to Reproduce the Issue

Export org file with custom id on header.

### Example Org File

[orgexample.org.txt](https://github.com/kaushalmodi/ox-hugo/files/4207732/orgexample.org.txt)

### Generated Markdown File or Error

[index.md.txt](https://github.com/kaushalmodi/ox-hugo/files/4207734/index.md.txt)

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
     of 2019-09-16

## Org Version

    Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.3/lisp/org/)

## Hugo Version

    Hugo Static Site Generator v0.64.1/extended linux/amd64 BuildDate: 2020-02-10T05:20:31Z

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by smpentecost** [comment]
I just realized what I was doing wrong. I clearly need to read more about Goldmark vs Blackfriday. Thanks for the quick response!

**Comment by kaushalmodi** [comment]
> I clearly need to read more about Goldmark vs Blackfriday.

The custom anchor works the same way between Goldmark and Blackfriday. ox-hugo works with Hugo when using Goldmark as well!

> I just realized what I was doing wrong. 

Yes, the issue was that you were using the Markdown syntax for specifying custom anchor in the Org file. In Org file, you specify the custom anchor using the `CUSTOM_ID` Org property below that header and `ox-hugo` translates that to the Markdown style anchor. And that works with both Blackfriday and Goldmark. 

And thanks for that detailed bug report. I appreciate that. These don't have to be opened just for actual bugs. Opening issues for such questions for clarification is also absolutely fine.
