### ISSUE TITLE
How to include = in verbatim 

### ISSUE THREAD

**Issue by tabroughton** [kaushalmodi/ox-hugo#337]
I'd like to be able to export `<div id="example">this is some html</div>` inline using verbatim `=`

So `=<div id="example">this is some html</div>=` in my org content would export as per example above.

But of course the second `=` closes the verbatim in org.  

Does anyone know how I can do this?  Is there an escape char I can use?

**Comment by kaushalmodi** [comment]
You can wrap using `~` instead of `=`.

**Comment by tabroughton** [comment]
Oh yes, thanks
