### ISSUE TITLE
special block aside with name example not exporting correctly

### ISSUE THREAD

**Issue by tabroughton** [kaushalmodi/ox-hugo#338]
## Actual Behavior
org content:
```
#+NAME: Aside A
#+BEGIN_aside
/Some/ *text* --- 1
#+END_aside
```
is exporting this (notice `id` attribute and empty `<aside>` tag
```
<aside id="Aside A">
  <aside></aside>
<p><em>Some</em> <strong>text</strong> — 1</p>
</aside>
```
## Expected Behavior

```
<aside name="Aside A">
<p><em>Some</em> <strong>text</strong> — 1</p>
</aside>
```

## How to Reproduce the Issue

I was using [this example](https://github.com/kaushalmodi/ox-hugo/commit/a2e9396771c8a7ce13c19e20226b1768335aad6c#diff-6fa190cf16cc1fe9ba0fa6673ddb5970R2657) 

I removed the table for simplicity.

**Comment by kaushalmodi** [comment]
> notice id attribute

That's expected. If you need to add custom attributes like `name` look at the `#+html_attr` examples in the test suite. 

> and empty <aside> tag

That's expected as well (it's a hack originally added for Blackfriday, but works fine for Goldmark too). The empty aside tag should not change anything in the behavior.

**Comment by tabroughton** [comment]
Ok thanks, in the example I linked to it has `*** Block with NAME` so I assumed it meant with `name` attribute not `id` attribute.  

I think I'll define a couple of org macros for what I want to do this time.  Thanks for quick response

**Comment by kaushalmodi** [comment]
> so I assumed it meant with name attribute not id attribute.

Yeah, the `#+name` keyword is one of the standard keywords in Org. And I believe that the inbuilt ox-html exporter also deals with custom blocks the same way as in ox-hugo.

**Comment by marcus-crane** [comment]
Ah, I'm glad to finally track down the cause of this

I was looking at adding support for `<aside>` to my site and had applied padding to the element.

While semantically, an extra aside tag is fine, having two meant I would get double padding :(

I'll just opt to make use of `#+html: <aside>` instead
