### ISSUE TITLE
how to set footer as https://ox-hugo.scripter.co/ displays

### ISSUE THREAD

**Issue by 007tom** [kaushalmodi/ox-hugo#342]
## Actual Behavior
`This site is generated using Hugo 0.68.3 + Onyx`
## Expected Behavior
`Exported from test.org using Emacs 26.3.50 + Org mode 9.1.9 + ox-hugo and published using Hugo 0.59.0-DEV + Onyx`
## How to Reproduce the Issue
`hugo new test.org` and it is created in my blog root dir
### Example Org File
#+options: creator: t

**Comment by kaushalmodi** [comment]
Hello,

I am creating that footer in https://github.com/kaushalmodi/hugo-onyx-theme/blob/master/layouts/partials/footer.html .

As you see there, the footer defaults to the string you see if you do not provide the Org source parameters in your site's config.toml. As an example, this is what the ox-hugo doc site has:

```
[Params]

# ..

  [Params.source]
    url = "https://github.com/kaushalmodi/ox-hugo"
    org_dir = "doc"
    org_file = "doc/ox-hugo-manual.org"

```

**Comment by 007tom** [comment]
YOU SAVED MY LIFE !
