### ISSUE TITLE
support org literal example ?

### ISSUE THREAD

**Issue by 007tom** [kaushalmodi/ox-hugo#343]
## Actual Behavior
no effect
## Expected Behavior
In HTML, hovering the mouse over such a link`[[(sc)]]` remote-highlights the corresponding code line

### Example Org File
```org
#+BEGIN_SRC emacs-lisp -n -r
  (save-excursion                 (ref:sc)
     (goto-char (point-min))      (ref:jump)
#+END_SRC
```
In line `[[(sc)]]` we remember the current position. `[[(jump)][Line (jump)]]`
jumps to point-min.

**Comment by kaushalmodi** [comment]
Those are Org coderef's and unfortunately they cannot be supported right now because of a limitation in Hugo (it does not create a hyperlink for each code line). 

I am already tracking this in this issue: https://github.com/kaushalmodi/ox-hugo/issues/162

**Comment by 007tom** [comment]
Thank you for the quick reply !!!
And... should I close the issue ?

**Comment by kaushalmodi** [comment]
Yes please.
