### ISSUE TITLE
nested list indentation of 4 spaces causes <pre> blocks in hugo

### ISSUE THREAD

**Issue by sprajagopal** [kaushalmodi/ox-hugo#344]
## Actual Behavior
I am exporting my org files with ox-hugo. I opened an [issue](https://github.com/gohugoio/hugo/issues/7142) but it seems this behaviour as per markdown spec.
I went through `ox-hugo.el` and found reference to `tabSpaceEight` which may solve this issue. But I am not sure how to enable this extension.
## Expected Behavior
Nested lists should not have 4 space indent.
## How to Reproduce the Issue
Export the following org file.
### Example Org File
```
#+TITLE: hugo nested lists issue
#+SETUPFILE: hugo_setup.org
* Level 2
** Level 3
*** Level 4
**** Level 5
***** Level 6
****** Level 7
******* Level 8
******** Level 9
********* Level 10

```
### Generated Markdown File or Error
```
+++
title = "hugo nested lists issue"
author = ["pp"]
lastmod = 2020-04-07T22:54:49+05:30
draft = false
+++

## Level 2 {#level-2}


### Level 3 {#level-3}


#### Level 4 {#level-4}


##### Level 5 {#level-5}


###### Level 6 {#level-6}

-    Level 7

    -    Level 8

        -    Level 9

            -    Level 10

```
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment]
I can reproduce that on [this commonmark dingus][1]. Can you play around with that can come up with a markdown format that acts as a workaround?

> I went through `ox-hugo.el` and found reference to `tabSpaceEight` which may solve this issue. 

I am not aware of `tabSpaceEight` (just grepped through the whole ox-hugo repo; didn't find anything.  Can you provide a reference? If it's an extension, it would go in your hugo site's `config.toml`.

[1]: https://spec.commonmark.org/dingus/?text=%23%23%20Level%202%20%7B%23level-2%7D%0A%0A%23%23%23%20Level%203%20%7B%23level-3%7D%0A%0A%23%23%23%23%20Level%204%20%7B%23level-4%7D%0A%0A%23%23%23%23%23%20Level%205%20%7B%23level-5%7D%0A%0A%23%23%23%23%23%23%20Level%206%20%7B%23level-6%7D%0A%0A-%20%20%20%20Level%207%0A%0A%20%20%20%20-%20%20%20%20Level%208%0A%0A%20%20%20%20%20%20%20%20-%20%20%20%20Level%209%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20%20%20%20Level%2010

**Comment by kaushalmodi** [comment]
OK, look like it works if I remove those extra spaces from after the hyphen: [demo][1]

[![image](https://user-images.githubusercontent.com/3578197/78711404-e9496780-78e4-11ea-83be-743831040c11.png)][1]


[1]: https://spec.commonmark.org/dingus/?text=%23%23%20Level%202%20%7B%23level-2%7D%0A%0A%23%23%23%20Level%203%20%7B%23level-3%7D%0A%0A%23%23%23%23%20Level%204%20%7B%23level-4%7D%0A%0A%23%23%23%23%23%20Level%205%20%7B%23level-5%7D%0A%0A%23%23%23%23%23%23%20Level%206%20%7B%23level-6%7D%0A%0A-%20Level%207%0A%0A%20%20%20%20-%20Level%208%0A%0A%20%20%20%20%20%20%20%20-%20Level%209%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20Level%2010

**Comment by kaushalmodi** [comment]
Turns out that the extras spaces after the hyphens are coming from somewhere in `ox.el`. I'll need some time to figure that out.

**Comment by kaushalmodi** [comment]
@sprajagopal Can you confirm the fix?

**Comment by sprajagopal** [comment]
Hello,
I updated and tried this now. The resulting markdown is as follows.
```
## Level 2 {#level-2}
### Level 3 {#level-3}
#### Level 4 {#level-4}
##### Level 5 {#level-5}
###### Level 6 {#level-6}

<!--list-separator-->

-  Level 7

    <!--list-separator-->

    -  Level 8

        <!--list-separator-->

        -  Level 9

            <!--list-separator-->

            -  Level 10

```
It renders correctly in html also with hugo.
Thanks a lot for a superfast fix! 
( I expected someone would comment a workaround not that the actual issue would be fixed overnight :D)

**Comment by sprajagopal** [comment]
> I can reproduce that on [this commonmark dingus](https://spec.commonmark.org/dingus/?text=%23%23%20Level%202%20%7B%23level-2%7D%0A%0A%23%23%23%20Level%203%20%7B%23level-3%7D%0A%0A%23%23%23%23%20Level%204%20%7B%23level-4%7D%0A%0A%23%23%23%23%23%20Level%205%20%7B%23level-5%7D%0A%0A%23%23%23%23%23%23%20Level%206%20%7B%23level-6%7D%0A%0A-%20%20%20%20Level%207%0A%0A%20%20%20%20-%20%20%20%20Level%208%0A%0A%20%20%20%20%20%20%20%20-%20%20%20%20Level%209%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20%20%20%20Level%2010) (somehow that link doesn't work for me on Firefox, but works on Chrome).
> 
> [![image](https://user-images.githubusercontent.com/3578197/78709506-c1a4d000-78e1-11ea-9f4c-7034ef3c4461.png)](https://spec.commonmark.org/dingus/?text=%23%23%20Level%202%20%7B%23level-2%7D%0A%0A%23%23%23%20Level%203%20%7B%23level-3%7D%0A%0A%23%23%23%23%20Level%204%20%7B%23level-4%7D%0A%0A%23%23%23%23%23%20Level%205%20%7B%23level-5%7D%0A%0A%23%23%23%23%23%23%20Level%206%20%7B%23level-6%7D%0A%0A-%20%20%20%20Level%207%0A%0A%20%20%20%20-%20%20%20%20Level%208%0A%0A%20%20%20%20%20%20%20%20-%20%20%20%20Level%209%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20%20%20%20Level%2010)
> 
> Can you play around with that can come up with a markdown format that acts as a workaround?
> 
> > I went through `ox-hugo.el` and found reference to `tabSpaceEight` which may solve this issue.
> 
> I am not aware of `tabSpaceEight` (just grepped through the whole ox-hugo repo; didn't find anything. Can you provide a reference? If it's an extension, it would go in your hugo site's `config.toml`.

Sorry I typoed. It was `tabSizeEight` in `ox-hugo.el`
```
(defvar org-hugo-blackfriday-extensions                                                                                                                                     
  '("noIntraEmphasis"                                                                                                                                                       
    "tables"                                                                                                                                                                
    "fencedCode"                                                                                                                                                            
    "autolink"                                                                                                                                                              
    "strikethrough"                                                                                                                                                         
    "laxHtmlBlocks"                                                                                                                                                         
    "spaceHeaders"                                                                                                                                                          
    "hardLineBreak"                                                                                                                                                         
    "tabSizeEight"                                                                                                                                                          
    "footnotes"                                                                                                                                                             
    "noEmptyLineBeforeBlock"                                                                                                                                                
    "headerIds"                                                                                                                                                             
    "titleblock"                                                                                                                                                            
    "autoHeaderIds"                                                                                                                                                         
    "backslashLineBreak"                                                                                                                                                    
    "definitionLists"                                                                                                                                                       
    "joinLines")   
```

**Comment by kaushalmodi** [comment]
> It was tabSizeEight in ox-hugo.el

Ah right! It's been a while since I added that. Those are Blackfriday extensions, and will not work with Goldmark. Both are Markdown rendering libraries. Goldmark is a much better one as it is compliant with commonmark. Hugo switched to making Goldmark as the default library since Hugo 0.60.0. At some point, I will move out the dead Blackfriday code in this repo to a separate library in an archived state.
