### ISSUE TITLE
Is there a way to not generate anchor for headlines?

### ISSUE THREAD

**Issue by goofansu** [kaushalmodi/ox-hugo#345]
Hi, thank you for the package. I migrated from Hugo to GatsbyJS (just for fun), but want to keep writing posts with org-mode. 

ox-hugo generates anchor for headlines, like `First point {#first-pont}`, maybe Hugo will hide the anchor part, but in GatsbyJS it just shows the full content. I wonder is there a way to avoid generating the anchor?

Thanks

**Comment by kaushalmodi** [comment]
You can copy/paste the `org-hugo-headline` function, modify it to remove the anchor portion and then do `:override` advice so that your modified function gets used instead of the original function.

**Comment by kaushalmodi** [comment]
Btw for Gatsby, I thought there was a good JS library for Org support.

**Comment by goofansu** [comment]
@kaushalmodi Wow, thank you for your advice, I will override the function as it won't change my workflow too much. Thanks again!

**Comment by kaushalmodi** [comment]
No problem! Let me know how it works out. Off you need to end up advising more functions, consider extending ox-hugo to ox-gatsby or something and then you can pick which Org elements' export function you want to be customized. The ones you don't specify will fall back to the version set by ox-hugo.

**Comment by goofansu** [comment]
@kaushalmodi Ok, I will tell you when finished. Thank you.

**Comment by goofansu** [comment]
Hi @kaushalmodi, thank you for the guide. I added `:override` advice on `org-hugo-headline` and `org-hugo-link` and meet my requirements. I created a gist for it: https://gist.github.com/goofansu/0a70074d31c26d9130b0e09ceb08b8d0.

**Comment by jmn** [comment]
I have the same use case (Gatsby) and everything seems to be working well for me except two things: the headline anchors and the fact that I needed to change the filenames in two places in in `ox-hugo.el` to be .mdx and not .md. It would be great if this worked: 
`#+EXPORT_FILE_NAME: 2020-12-11-my-post.mdx` and ox-hugo would respect the filename ending.

`advice-add #'org-hugo-link :override #'org-md-link)` didn't seem to do the trick for me so I edit ox-hugo.el to set `(let* ((anchor (format "{#%s}"` to `(let* ((anchor (format ""`  (line 1843).

I realize this is not the use case for ox-hugo!
