### ISSUE TITLE
straight update always prompty dirty work tree

### ISSUE THREAD

**Issue by amosbird** [kaushalmodi/ox-hugo#346]
```
  > Repository "ox-hugo" has a dirty worktree:

     M doc/themes/hugo-onyx-theme
     M test/site/themes/hugo-bare-min-theme
     M test/site/themes/hugo-debugprint

       1) Abort
       2) Stash changes
       3) Discard changes (Recommended)
```

I guess this should be tracked or git ignored?

**Comment by kaushalmodi** [comment]
Hello, that error probably means that you have files in those git submodules which are not committed. Those directories are for the ox-hugo doc and test site sources. So doing the Discard Changes step will not break the package. 

@raxod502 Is there a way to configure a package pull to not do that recursively? All users probably don't need to have all the git submodules in the ox-hugo repo. Those submodules are just Hugo themes that I use for the ox-hugo doc and test site generation.

**Comment by amosbird** [comment]
> that error probably means that you have files in those git submodules which are not committed

Yeah, but that's generated by the package itself. I encountered this everytime when I update.

**Comment by kaushalmodi** [comment]
Sorry, I haven't used straight.el, so I cannot give any better advise. All I can tell is that if you did not modify those themes, feel free to discard those. Alternatively, see if straight.el can be configured to pull in only elisp files and not do recursive clone of submodules.

**Comment by raxod502** [comment]
You can provide a custom recipe `(straight-use-package '(ox-hugo :nonrecursive t))` to avoid cloning submodules. However, really the submodules should be cloned and managed automatically, as per https://github.com/raxod502/straight.el/issues/238. This is not a bug in ox-hugo; I apologize for the inconvenience.

**Comment by kaushalmodi** [comment]
> I apologize for the inconvenience.

Of course not! Thanks for helping out with this.

**Comment by amosbird** [comment]
I guess I'll wait for the fix of straight then. Thanks!
