### ISSUE TITLE
Multilingual option for "one post per org" subtree

### ISSUE THREAD

**Issue by juanwolf** [kaushalmodi/ox-hugo#347]
Maybe I am missing something in this package but I can't find a way to configure ox-hugo to export an org subtree for a specific language.

For example, with hugo, I would create a translation for a post adding the language in the file name like `my-post.<language-shortcode>.md`

Here's my 2 cents solution: 

Adding a `LANGUAGE` property could solve the problem

```
* My Post
  :PROPERTIES:
  :LANGUAGE: en
  :EXPORT_FILE_NAME: my-post
  :END:
* Mon Article
  :PROPERTIES:
  :LANGUAGE: fr
  :EXPORT_FILE_NAME: my-post
  :END:
```

which will generate `<ORG_CONTENT>/<section>/my-post.{en,fr}.md`

**Comment by kaushalmodi** [comment]
I have not written multilingual posts myself, but I have seen that people usually separate posts by languages in their subdirectories.

See [these docs on Hugo Multilingual Mode][1] for reference.

```
* English posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: en
:END:
** My Post
:PROPERTIES:
:EXPORT_FILE_NAME: my-post
:END:
This will be created as ~content/en/my-post.md~.
* French posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: fr
:END:
** Mon Article
:PROPERTIES:
:EXPORT_FILE_NAME: my-post
:END:
This will be created as ~content/fr/my-post.md~.
```

This should work right away, though, I believe that that's not the recommended way for organizing multilingual posts in Hugo.

```
* My Post
  :PROPERTIES:
  :EXPORT_FILE_NAME: my-post.en.md
  :END:
* Mon Article
  :PROPERTIES:
  :EXPORT_FILE_NAME: my-post.fr.md
  :END:
```


[1]: https://gohugo.io/content-management/multilingual/

**Comment by kaushalmodi** [comment]
This blog shows both approaches for organizing the multilingual content: https://regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/ .

**Comment by juanwolf** [comment]
Thanks for the really quick response.

I was hoping we could get a way to propagate the language to the filename rather than changing the whole content directory for the different languages.

In my personal case it's because I've used the "filename" method in Markdown rather than the directory one and need to change the whole content structure... Not ideal.

I can use one post per org file, it's not a big deal. I was wondering if that would be a functionality people would be interested in. Looks like not 😂

**Comment by kaushalmodi** [comment]
Does the second approach I mentioned above work for you? I'll convert this issue to an enhancement request as this is the first request I got for this.

**Comment by juanwolf** [comment]
Sorry for the delay I was fighting with `HUGO_EXPORT_SECTION` and discovered `HUGO_EXPORT_SECTION*` with this commit https://github.com/kaushalmodi/ox-hugo/commit/a8d3eb06304458340095a1d395bae5ef42ebe3aa (Thanks a lot for writing such descriptive commits 🙇 ) 

It's working perfectly, thanks for your help. I believe you can close this issue.

**Comment by kaushalmodi** [comment]
Thanks for the follow-up. Glad that the EXPORT_HUGO_SECTION* based approach is working for you. Feel free to open a new issue for any questions. I'll close this one.
