### ISSUE TITLE
Sequence <N \\ in Latex leads to inconsistencies

### ISSUE THREAD

**Issue by visika** [kaushalmodi/ox-hugo#348]
## Actual Behavior
The sequence `<N \\`, where N is a digit, in an equation environment breaks the escaping in the following lines. Placing a space between `<` and `N` solves the issue. Some characters like the underscore get escaped mistakenly.
## Expected Behavior
The sequence should not trigger the event.
## How to Reproduce the Issue
Use a math environment with multiple lines, like `cases` or `align`.
### Example Org File
This produces the weird result:
```
\begin{equation}
\begin{cases}
u_t = ku_{xx} \\
u(x,0) = T_1 , & x <0 \\
u(x,0) = T_2 , & x > 0
\end{cases}
\end{equation}
```
This way we get the expected result:
```
\begin{equation}
\begin{cases}
u_t = ku_{xx} \\
u(x,0) = T_1 , & x < 0 \\
u(x,0) = T_2 , & x > 0
\end{cases}
\end{equation}
```
### Generated Markdown File or Error

| Good | Bad |
|---|---|
| ![immagine](https://user-images.githubusercontent.com/2254049/79621846-331c2400-8115-11ea-8623-0e51d7c39992.png) | ![immagine](https://user-images.githubusercontent.com/2254049/79622027-e258fb00-8115-11ea-9535-f041b480c351.png) | 

Bad TeX output:
```
\begin{equation}
\begin{cases}
u_t = ku_{xx} \\

u(x,0) = T_1 , & x <0 \\\\\\
u(x,0) = T\_2 , & x > 0
\end{cases}
\end{equation}
```

Good TeX output:
```
\begin{equation}
\begin{cases}
u_t = ku_{xx} \\

u(x,0) = T_1 , & x < 0 \\

u(x,0) = T_2 , & x > 0
\end{cases}
\end{equation}
```
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11)
     of 2019-09-23, modified by Debian

## Org Version

    Org mode version 9.4 (nil @ /home/REDACTED/.emacs.d/.local/straight/build/org-mode/)

## Hugo Version

    Hugo Static Site Generator v0.57.2/extended linux/amd64 BuildDate: 2019-08-18T05:29:32Z

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">&ldquo;posts&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">&ldquo;ox-hugo&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">(&ldquo;jpg&rdquo; &ldquo;jpeg&rdquo; &ldquo;tiff&rdquo; &ldquo;png&rdquo; &ldquo;svg&rdquo; &ldquo;gif&rdquo; &ldquo;mp4&rdquo; &ldquo;pdf&rdquo; &ldquo;odt&rdquo; &ldquo;doc&rdquo; &ldquo;ppt&rdquo; &ldquo;xls&rdquo; &ldquo;docx&rdquo; &ldquo;pptx&rdquo; &ldquo;xlsx&rdquo;)</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">&ldquo;%Y-%m-%dT%T%z&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">&ldquo;&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
I am unable to reproduce this issue, though I will add your snippet to the ox-hugo test suite.

**Comment by kaushalmodi** [comment]
ox-hugo test link: https://ox-hugo.scripter.co/test/posts/equations-bf-escaping/

With this in the Org file:

```
\begin{equation}
\begin{cases}
u_t = ku_{xx} \\
u(x,0) = T_1 , & x <0 \\
u(x,0) = T_2 , & x > 0
\end{cases}
\end{equation}
```

ox-hugo generates this Markdown:

```
\begin{equation}
\begin{cases}
u\_t = ku\_{xx} \\\\\\
u(x,0) = T\_1 , & x <0 \\\\\\
u(x,0) = T\_2 , & x > 0
\end{cases}
\end{equation}
```

which Hugo 0.68.3 renders as:

![image](https://user-images.githubusercontent.com/3578197/79710695-cbd8ae00-8293-11ea-8329-af065ba9d155.png)

**Comment by visika** [comment]
This time I had the same Markdown output as yours, but still the TeX commands that MathJax showed were wrong. It was because of Hugo; I updated to the latest release and everything is fine now.

Thank you very much. You can safely remove the snippet from the test suite.
