### ISSUE TITLE
title is not double quoted after exported to markdown

### ISSUE THREAD

**Issue by showgood** [kaushalmodi/ox-hugo#350]
## Actual Behavior
title is not double quoted after exported to markdown
## Expected Behavior
title should be double quoted after exported to markdown
## How to Reproduce the Issue
export the example org file and examine the exported markdown file
### Example Org File
```
#+HUGO_BASE_DIR: ..
#+hugo_auto_set_lastmod: t
#+OPTIONS: H:2
#+HUGO_SECTION: journal
#+TITLE: 2020-04-18
One World: Together At Home
```
### Generated Markdown File or Error
```
+++
title = 2020-04-18
author = ["showgood"]
lastmod = 2020-04-18T22:45:44-04:00
draft = false
+++

One World: Together At Home
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.0.0, NS appkit-1894.10 Version 10.15.1 (Build 19B88))
     of 2020-02-16 (commit 3480071dfab30eaca7f1d014600b864d2ea22f62)

## Org Version

    Org mode version 9.4 (nil @ /Users/showgood/.emacs.d/.local/straight/build/org-mode/)

## Hugo Version

    Hugo Static Site Generator v0.62.1/extended darwin/amd64 BuildDate: unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" rules="all" frame="border">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">&ldquo;posts&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">&ldquo;ox-hugo&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">(&ldquo;jpg&rdquo; &ldquo;jpeg&rdquo; &ldquo;tiff&rdquo; &ldquo;png&rdquo; &ldquo;svg&rdquo; &ldquo;gif&rdquo; &ldquo;mp4&rdquo; &ldquo;pdf&rdquo; &ldquo;odt&rdquo; &ldquo;doc&rdquo; &ldquo;ppt&rdquo; &ldquo;xls&rdquo; &ldquo;docx&rdquo; &ldquo;pptx&rdquo; &ldquo;xlsx&rdquo;)</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">&ldquo;%Y-%m-%dT%T%z&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">&ldquo;&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
I see that this is an untested case where the title contains only numerics chars and hyphens.. matching the TOML date format. I'll investigate and fix it.

**Comment by kaushalmodi** [comment]
This issue got auto-closed as I referenced this issue in the fix commit. Feel free to comment here if the issue is still not fixed for you; I'll reopen it.

ox-hugo test page showing this issue fixed: https://ox-hugo.scripter.co/test/posts/title-with-just-date-chars/

Markdown source (generated by ox-hugo) of that test page: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/title-with-just-date-chars.md

**Comment by showgood** [comment]
thanks a lot for the prompt fix!!
