### ISSUE TITLE
Local images are exported as Markdown images or caption is not added

### ISSUE THREAD

**Issue by oxddr** [kaushalmodi/ox-hugo#360]
## Actual Behavior
Link to a local image (in the subdir of org file) is exported to Markdown as an Markown image (`![]()`). Caption added via `#+caption` is not exported at all. 

## Expected Behavior
Image should be exported as figure shortcode (similarly to how images linked via http). Caption should be added. 

## How to Reproduce the Issue
Just export the snippet from the above. 

### Example Org File

```
#+CAPTION: CAPTION
[[file:image.jpg]]
```

### Generated Markdown File or Error
```
![](/ox-hugo/image.jpg)
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109))
     of 2019-09-02

## Org Version

    Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /Applications/Emacs.app/Contents/Resources/lisp/org/)

## Hugo Version

    Hugo Static Site Generator v0.59.1/extended darwin/amd64 BuildDate: unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

  

</details>

**Comment by kaushalmodi** [comment]
I think it's required by ox.el to have the `#+name:` keyword too (See https://orgmode.org/org.html#Images ).

Can you try:

```
#+NAME: foo
#+CAPTION: CAPTION
[[file:image.jpg]]
```

**Comment by kaushalmodi** [comment]
I have quite a few tests for image exports. Search for "\*\* Image links" on https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/all-posts.org .

**Comment by kaushalmodi** [comment]
Hello @oxddr, were you able to confirm that adding `#+name` fixed the issue for you?

**Comment by oxddr** [comment]
> Hello janluk, were you able to confirm that adding `#+name` fixed the issue for you?

I've tried adding `#+name`, but it didn't help - no caption has been generated. 

In the meantimes, is there any way to force ox-hugo to export images as [figures](https://gohugo.io/content-management/shortcodes/#figure)?

**Comment by kaushalmodi** [comment]
The problem is that I cannot make it not export without the figure shortcode :)

I need to get a recipe to reproduce the issue you are seeing. 

Quick check: Are you using Melpa and **not** Melpa Stable?

**Comment by kaushalmodi** [comment]
I have added tests for this issue in https://github.com/kaushalmodi/ox-hugo/commit/d6138da6c09b0ccd14de6e124aaac64767c882ee .

I generated the page as both regular page and leaf bundle page, and the `figure` code showed up fine:
- Regular page: [exported Markdown][1] | [Hugo generated HTML][2]
- Leaf bundle page: [exported Markdown][3] | [Hugo generated HTML][4]

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/issues/360.md 
[2]: https://ox-hugo.scripter.co/test/issues/360/
[3]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/issues/360-bundle/index.md
[4]: https://ox-hugo.scripter.co/test/issues/360-bundle/

**Comment by kaushalmodi** [comment]
Hello, I haven't heard back on this issue. As I am unable to reproduce this issue (I have added new tests to show that the `figure` shortcode exports fine), I am closing this.

Feel free to comment here with more info that can help me fix this issue for you.
