### ISSUE TITLE
Document that the Org timestamps work in the date related Org export properties/keywords

### ISSUE THREAD

**Issue by jrmiller82** [kaushalmodi/ox-hugo#363]
Hi,

I would like to be able to set a timestamp or other method or ordering posts that were written on the same day. 

I can't tell from the website docs if this is possible using the the properties drawer.

```
:PROPERTIES:
:EXPORT_FILE_NAME: ox-FOO
:EXPORT_DATE: 2020-05-16
:END:
```
Can I add a timestamp to that EXPORT_DATE? And if yes, then I think the docs on https://ox-hugo.scripter.co/doc/org-meta-data-to-hugo-front-matter/ should be updated. 

Thanks in advance!

**Comment by kaushalmodi** [comment]
Hello, `EXPORT_DATE` property is supported (exports to the `date` front matter) and also documented on the page you linked. May be I am misunderstanding?

**Comment by jrmiller82** [comment]
Sorry, I think I didn't phrase the issue correctly. If I have two posts with the same `EXPORT_DATE` how can I force the ordering of those posts?

**Comment by kaushalmodi** [comment]
Sorry, that's a Hugo templating question. You'd just order the posts by the date Params in the list.html. 

ox-hugo only exports the front matter and content. The ordering, HTML layout etc is done in Hugo.

**Comment by jrmiller82** [comment]
So you can't add a timestamp onto the `EXPORT_DATE` property?

**Comment by jrmiller82** [comment]
Looks like you can add a timestamp to an `EXPORT_DATE` property. That's what I was saying about the docs page I linked above, it seems to imply only a date can be placed there and not a date+timestamp.

**Comment by kaushalmodi** [comment]
Ah, I see. I'll add a note somewhere: Basically all date Params (date, publishdate, etc.) take the date as a plain date string or Org date timestamp.

**Comment by kaushalmodi** [comment]
This is now documented in https://ox-hugo.scripter.co/doc/dates/#date-formats .
