### ISSUE TITLE
Is it possible to export an org file to multiple HUGO_BASE_DIRs?

### ISSUE THREAD

**Issue by sprajagopal** [kaushalmodi/ox-hugo#364]
## Actual Behavior
I have one `#+HUGO_BASE_DIR` defined. But could I export the same `.org` file to two different hugo sites.

## Expected Behavior
The result `md` files should appear in two different hugo folders.

## How to Reproduce the Issue
I tried adding two `HUGO_BASE_DIR` but the second one is not used at all. 

### Example Org File
```
#+HUGO_BASE_DIR: ../site1
#+HUGO_BASE_DIR: ../site2
```
### Generated Markdown File or Error
No errors.

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment]
Hello, this is not supported. 

Out of curiosity, what is the use case of doing this?

**Comment by sprajagopal** [comment]
Hi,
Got it, thanks!
For me the use case is maintaining two different blogs. One is a rough notes version and there is a subset that's actually published. So some files are exported to both blogs but some only in one.

**Comment by kaushalmodi** [comment]
You can do this right now: 

```org
# blog1.org
#+hugo_base_dir: ~/blogs/1

* Posts only for blog 1
** Post 1
:PROPERTIES:
:EXPORT_FILE_NAME: post1
:END:
* Posts for both blogs
** Post Shared 1 
:PROPERTIES:
:EXPORT_FILE_NAME: post2 
:END:
Foo Bar
```

```org
# blog2.org
#+hugo_base_dir: ~/blogs/2
* Posts only for blog 2
** Post 1
:PROPERTIES:
:EXPORT_FILE_NAME: post1
:END:
* Posts for both blogs
** Post Shared 
:PROPERTIES:
:EXPORT_FILE_NAME: post2 
:END:
#+include: "./blog1.org::*Post Shared 1" :only-contents t
```

This is just 1 quick draft.. but it's easily possible to share content across Org files like this.

Ref: https://orgmode.org/manual/Include-Files.html

**Comment by sprajagopal** [comment]
Ah okay, got it. Yes, this works!
