### ISSUE TITLE
Subtree section management -- Requirement to NOT nest subtrees with EXPORT_FILE_NAME property

### ISSUE THREAD

**Issue by finex** [kaushalmodi/ox-hugo#365]
Hi, I'm currently using a single _org_ file for both blog posts and regular pages (like privacy, contact us etc.).  The _org_ file is on `content-org` directory and it has the following structure:

```
#+hugo_base_dir: ../
#+hugo_weight: nil

* Blog
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SECTION: blog
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :section_subtitle "lorem ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "dolor sit amet."
:END:

** Category one :@category_one:
*** Post one :tag_one:tag_two:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: post-name-url
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :post_subtitle "Lorem ipum "
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor sit amet"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "blog"
:END:

[... post content ...]

** Category two :@category_two:

[... like the other category ...]

* Pages
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:END:
** Contacts
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: contacts
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :post_subtitle "Lorem ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor sit amet."
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "page"
:END:

[... page content ...]

** Privacy
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: privacy
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :post_subtitle "Lorem ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor sit amet."
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "page"
:END:

[... page content ...]
```

I've put some data on the `Blog` tree using `:PROPERTIES:` because I need to customize the `/blog` page with a title, a subtitle and a description. But the generated _markdown_ file (`/content/blog/_index.md`) contains all the blog posts even if I don't need them on that file.

The blog template does't print the posts because I iterate the post archive so the output is fine but all the inline images referenced inside the blog posts are extra copied to the `ox-hugo` fallback directory and referenced on the file `/content/blog/_index.md`.

I've tried to look at the docs but I've not found what's the best practice for customizing the `/blog` page with a title/subtitle/meta.

What's the correct way to handle this situation?

And is it correct to create *Blog* and *Pages* subtrees or should I do something different? Thank you :smile:

**Comment by kaushalmodi** [comment]
The issue is that you are nesting subtrees containing EXPORT_FILE_NAME property. `ox-hugo` is designed with the intent that the user **never** nests subtrees containing EXPORT_FILE_NAME.

See this earlier comment of mine in a different issue (that also has an example): https://github.com/kaushalmodi/ox-hugo/issues/210#issuecomment-424300174

---

_I need to document this.. some how._

**Comment by kaushalmodi** [comment]
@finex Here's a quick untested draft, but that should give you an idea of what I am trying to explain:

```org
#+hugo_base_dir: ../
#+hugo_weight: nil

* Blog Pages
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :section_subtitle "lorem ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "dolor sit amet."
:END:
** Blog 
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:
This is the /blog landing page, the branch bundle.
** Blog posts
*** Category one                                              :@category_one:
**** Post one                                               :tag_one:tag_two:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: post-name-url
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :post_subtitle "Lorem ipum "
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor sit amet"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "blog"
:END:

[... post content ...]

*** Category two                                              :@category_two:

[... like the other category ...]
```

**Comment by finex** [comment]
Hi  @kaushalmodi , I've tested your suggestion but it doesn't work. I've done some other tests and I've found a solution which works quite well: the `/blog` page is a separated element with his own `:PROPERTIES:` data. The hugo section is set on top of the file. For the static pages like "privacy" and "contacts" I've keep the separated tree with `:EXPORT_HUGO_SECTION: /` property, so the pages will not be stored on the blog section.

Now I only need to find a way to set a custom meta description for tags and categories. But for today I'm quite happy :-) 

The following is the current working /org/ file :smile: 

Let me know if I can organize it better :+1: 

```
#+hugo_base_dir: ../
#+hugo_section: blog
#+hugo_weight: nil

* Blog
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :section_subtitle "Lorem Ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor sit Amet."
:END:

* Category one :@category_one:

** Post one :tag:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: post-one
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :post_subtitle "Lorem Ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor Sit Amet"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "blog"
:END:

...Post content...

** Post two :tag:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: post-two
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :post_subtitle "Lorem Ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor Sit Amet"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "blog"
:END:

...Post content...

* Pages
:PROPERTIES:
:EXPORT_HUGO_SECTION: /
:END:
** Contacts
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: contacts
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :post_subtitle "Lorem ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor sit amet."
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "page"
:END:

[... page content ...]

** Privacy
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: privacy
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER:  :post_subtitle "Lorem ipsum"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :description "Dolor sit amet."
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "page"
:END:

[... page content ...]
```

**Comment by kaushalmodi** [comment]
> I've tested your suggestion but it doesn't work

I am curious to know what didn't work.. but I am glad that you have something work.

I see that you have a lot of repetition for `:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type "..."`. Those can live in a parent subtree.

Also, you don't need custom front matter for those.. you can already do `:EXPORT_HUGO_TYPE: page` or `:EXPORT_HUGO_TYPE: blog`

**Comment by finex** [comment]
Hi, thank you for the hint. I've tried to do the same with `:EXPORT_LANGUAGE: it`, but this setting is not inherited.
