### ISSUE TITLE
Make the LANGUAGE keyword inheritable

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#366]
Hi, thank you for the hint, it works perfectly.

I've also tried to do the same with `:EXPORT_LANGUAGE: it`, but this setting is not inherited. I've had to put on top of the org file:
```
#+language: it
```
And this works fine (I'm using to localize "Table of contents" hugo string) :+1:

_Originally posted by @finex in https://github.com/kaushalmodi/ox-hugo/issues/365#issuecomment-635671894_

**Comment by kaushalmodi** [comment]
@finex LANGUAGE is now inheritable.

**Comment by finex** [comment]
Wow, thank you @kaushalmodi :-)
