### ISSUE TITLE
Html entities on table of content

### ISSUE THREAD

**Issue by finex** [kaushalmodi/ox-hugo#368]
## Actual Behavior
I've a heading with something like
``` org
* Heading with three dots: ...
```

When org/ox-hugo generate the toc, the result is:
``` markdown
[Heading with three dots: ...](url)
```
(_where url is the anchor to the section_)

Then Hugo exports the following html:
``` html
<a href="url">Heading with three dots: &amp;hellip;</a>
```

## Expected Behavior
Markdown/Hugo wants the html entity inside the link in order to generate the correct markup, so ox-hugo should generate the following markdown:

``` markdown
[Heading with three dots: &hellip;](url)
```

Then Hugo, with this markdown code, will produce the correct html output:
``` html
<a href="url">Heading with three dots: &hellip;</a>
```

## Workaround:
I'm currently putting `&hellip;` on the org file but it's not a great solution.

What do you think about?

**Comment by finex** [comment]
I've also noticed that if I put `&amp;` on the org file, Hugo will render this code in `&amp;` instead of `&` like he does with the hellip code, so maybe there is a bug on their side.

**Comment by kaushalmodi** [comment]
With this Markdown:

```
[Heading with three dots: ...](url)
```

Hugo is generating:

```
<a href="url">Heading with three dots: &amp;hellip;</a>
>
```

So it looks like a Hugo/Goldmark bug.

Can you create a ticket on the hugo repo?

**Comment by kaushalmodi** [comment]
Possible workaround in `ox-hugo`:
- In `org-hugo--headline-title`, post process the heading string through `org-html-convert-special-strings` (See `C-h v org-html-special-string-regexps`).

**Comment by finex** [comment]
> With this Markdown:
> 
> ```
> [Heading with three dots: ...](url)
> ```
> 
> Hugo is generating:
> 
> ```
> <a href="url">Heading with three dots: &amp;hellip;</a>
> ```
> 
> So it looks like a Hugo/Goldmark bug.
> 
> Can you create a ticket on the hugo repo?

yes, of course, I will link the ticket here just for future reference :-)

**Comment by finex** [comment]
Hugo bug reference: https://github.com/gohugoio/hugo/issues/7346

**Comment by finex** [comment]
@kaushalmodi hi, after some test I've found it was a theming problem due to missing `| renderHTML` on the custom render link template. :-)

**Comment by mrprofessor** [comment]
Ugh! I had the same issue. Thank you @finex  @kaushalmodi
