### ISSUE TITLE
Can't export all subtrees using the `org-hugo-auto-export-mode` minor mode

### ISSUE THREAD

**Issue by bphenriques** [kaushalmodi/ox-hugo#371]
Hello :wave:

I have a custom `org-capture` template that fails to export using the `org-hugo-auto-export-mode`.  As far as I read, it is due to the fact that `:all-subtrees` is not passed when invoking [`org-hugo-export-wim-to-md`](https://github.com/kaushalmodi/ox-hugo/blob/59bbff946048dce0f498a438f5486f375b65040c/org-hugo-auto-export-mode.el#L29) in the hook. Changing the default affects many workflows therefore I see two options:
* Additional minor mode `org-hugo-auto-export-mode-all-subtrees`. I recognise that this will export all subtrees automatically, therefore this mode should be [enabled only for particular org files](https://ox-hugo.scripter.co/doc/auto-export-on-saving/).
* `org-hugo-auto-export-mode` could receive additional options that can be passed as follows:
```
* Footnotes
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode :all-subtrees t)
# End:
```

I am willing to contribute but I have limited experience with both emacs and elisp. Your feedback would be great to know which approach is best.

## Actual Behavior

Can't export the subtree.

## Expected Behavior

A new file `/tmp/hugo-root/content/docs/some-section/_index.md` must be exported.

## How to Reproduce the Issue

1. Add the following utilitary:
```
(defun get-string-from-file (filePath)
  "Return filePath's file content."
  (with-temp-buffer
    (insert-file-contents filePath)
    (buffer-string)))
```

2. Add the following org-capture:
```
'("t" "Test") (file "/tmp/hugo-root/org/some-section/_index.org") (get-string-from-file "/tmp/template-org-file.org") :immediate-finish t)
```

3. Create the following org-file at `/tmp/template-org-file.org`:

```org
#+HUGO_BASE_DIR: ../..
#+HUGO_SECTION: docs/
#+HUGO_BUNDLE: some-section

* Some Section
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookFlatSection true
:EXPORT_FILE_NAME: _index
:END:
```

4. Reload and execute the `org-capture`.

### Generated Markdown File or Error

The standard "Point is not a valid post subtree: move to one and try again"

## Ox-Hugo Debug Information

N/A

## Additional Notes

I am using the `_index.org` formatted as mentioned as I am referencing the file for the other pages as follows:
```
#+SETUPFILE: ./_index.org
#+TITLE: My Content

* My Content
Some Content
```

The alternative is to move the common "HUGO_*" properties to a different file `setup-section.org` and change the template to (untested):
```
#+SETUPFILE: ./setup-section.org
#+EXPORT_HUGO_CUSTOM_FRONT_MATTER: :bookFlatSection true
#+EXPORT_FILE_NAME: _index
#+TITLE: Some Section
```

Would like to keep one file is possible to keep things tidier.

**Comment by kaushalmodi** [comment]
>  As far as I read, it is due to the fact that :all-subtrees is not passed when invoking org-hugo-export-wim-to-md in the hook.

I do not recommend passing :all-subtrees to the export. It will making saving files very annoying, because once you are above a dozen posts or so, the "all export" time will be tangible.. couple of seconds.

> Additional minor mode org-hugo-auto-export-mode-all-subtrees

This is a better option. Though I am not convinced that this should become part of ox-hugo.el. Do you want to create that minor mode in your emacs config and try it out for some time.

> org-hugo-auto-export-mode could receive additional options that can be passed as follows

This is not possible as far as I know. `org-hugo-auto-export-mode` is a minor mode, not a regular elisp function.

---

> The standard "Point is not a valid post subtree: move to one and try again"

You need to save the file when your cursor is inside a post subtree.

**Comment by bphenriques** [comment]
> This is a better option. Though I am not convinced that this should become part of ox-hugo.el. Do you want to create that minor mode in your emacs config and try it out for some time.

Sure. I will explore 👍 

> You need to save the file when your cursor is inside a post subtree.

This is tricky as the file is automatically saved using the flag `:immediate-finish t` in the org-capture.

**Comment by kaushalmodi** [comment]
The Org Capture flow is also not designed to instantly export the post.

In fact, I disable the auto-export when capturing using Org Capture. The suggested flow is:
- Use Org Capture to quickly jot down blog ideas
- Later refine the post, add tags, etc., proof read it, remove TODO and finally export and publish.

**Comment by kaushalmodi** [comment]
See this snippet where I disable the auto-export during Org Capture:

https://github.com/kaushalmodi/ox-hugo/blob/f8e26aaee92491ca348c2b6f7fb49627642b3176/org-hugo-auto-export-mode.el#L23-L29

**Comment by bphenriques** [comment]
Gotcha. I am not using this for a "blog" and for a knowledge base therefore I am okay having "draft" notes being exported automatically during org-captures. I will explore solutions locally.

**Comment by kaushalmodi** [comment]
> I am not using this for a blog but for a knowledge base therefore I am okay having "draft" notes being exported automatically during org-captures.

In that case, you definitely need your own minor mode. The default `org-hugo-auto-export-mode` disables auto-export during Org Capture.

Suggestion:
- Define your own minor mode where it allows exporting during capture as well
- As for the "Point is not a valid post subtree: move to one and try again" issue, figure out what the `(point)` value is when you set `:immediate-finish t` in your Org Capture template.

I'd be happy to add your solution to the ox-hugo docs for other users who come looking for a similar behavior of auto-exports.

**Comment by bphenriques** [comment]
Thank you 👍  Feel free to close the ticket. Will notify if I have a sound solution to my use-case. Will be happy to share in the ox-hugo docs.

**Comment by kaushalmodi** [comment]
Thanks. Looking forward to it!
