### ISSUE TITLE
Creating level 1 headers

### ISSUE THREAD

**Issue by epsilon-0** [kaushalmodi/ox-hugo#375]
Is it possible to add level 1 headers in the subtree mode, without making that header into another file ?

**Comment by kaushalmodi** [comment]
Can you explain with an example? I am not following.

> without making that header into another file ?

It feels like you have the case of "nested subtrees with EXPORT_FILE_NAME" property.

**Comment by epsilon-0** [comment]
Ah, sorry, I wasn't sure what the terminology was.
```
* Contact
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :chapter true
:EXPORT_AUTHOR: "Aisha Tammy"
:END:
trying this out to see what is happening
* I want this to be a level 1 header in contact file
this should be beneath the header
** sub header
sub header things
* another level 1 header
so one
```
Currently, what I get is that Contacts goes to a file and its sub headers just disappear ??

I think I'm doing some dum dum thing :crying_cat_face:

**Comment by kaushalmodi** [comment]
The header levels in Org are relative.. So do this instead

```org
* Contact
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :chapter true
:EXPORT_AUTHOR: "Aisha Tammy"
:END:
trying this out to see what is happening
** I want this to be a level 1 header in contact file
this should be beneath the header
*** sub header
sub header things
** another level 1 header
so one
```

**Comment by kaushalmodi** [comment]
See this small example: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/screenshot-subtree-export-example.org

**Comment by epsilon-0** [comment]
Ah, yes this works, but then in the markdown, the `**` as replaced by `##`

**Comment by epsilon-0** [comment]
So there is no possibility to get a `#` header in the generated markdown ?

A lot of the hugo themes treat the `#` header with different css, so it might be useful to be able to export such a one.

**Comment by epsilon-0** [comment]
This was the markdown generated (using `C-c C-e H A`):
```
+++
title = "Contact"
author = ["Aisha Tammy"]
lastmod = 2020-06-16T15:20:49-04:00
draft = false
weight = 1002
chapter = true
+++

trying this out to see what is happening


## I want this to be a level 1 header in contact file {#i-want-this-to-be-a-level-1-header-in-contact-file}

this should be beneath the header


### sub header {#sub-header}

sub header things


## another level 1 header {#another-level-1-header}

so one

```

**Comment by kaushalmodi** [comment]
> So there is no possibility to get a # header in the generated markdown ?

There is..

Note that Markdown levels translate one-to-one to HTML. So the `#` headings translate to `h1` heading in HTML. Ideally you must have only **one** h1 heading on an HTML page and that is usually reserved for the HTML page title. So for that reason, I default the minimum heading in Markdown to `##` or `h2` HTML.

**I don't advise** doing this, but you can add this to the top of your Org file: `#+hugo_level_offset: 0`. Instead, I think that the themes to be fixed.

**Comment by kaushalmodi** [comment]
Regarding the recommendation to use only **one** `h1` per page, you will find many resources online. Here's just one from a quick Google: https://www.w3schools.com/tags/tag_hn.asp

**Comment by epsilon-0** [comment]
haha, while I agree with you, I don't have(or care to learn) enough html to fix themes :smirk_cat: 
The theme I am talking about and using: https://github.com/matcornic/hugo-theme-learn
Its one of the most popular themes, so a lot of themes follow what its doing.
The page where they show weird header alignment (though admittedly not more than one h1), they still need a different `h1` header and a `title` separately: https://learn.netlify.app/en/cont/pages/#types

**Comment by kaushalmodi** [comment]
Let me know if that resolves your level 1 header related issues.

**Comment by epsilon-0** [comment]
Yes that worked. Thanks!

**Comment by Ruborcalor** [comment]
It was very helpful for me to read over this issue. Maybe put a notice of this practice in the docs? While it makes sense to have only one `h1` heading on a page, I and possibly others don't expect the behavior and think that they are doing something wrong.
