### ISSUE TITLE
Support for file links with spaces?

### ISSUE THREAD

**Issue by sprajagopal** [kaushalmodi/ox-hugo#376]
## Actual Behavior
A file link `[[file:name with spaces][link description]]` appears as `[link description](name with spaces)` in the final html.

## Expected Behavior
A file link with spaces needs escaping with `<>` as mentioned here [https://github.com/gohugoio/hugo/issues/6742](https://github.com/gohugoio/hugo/issues/6742). So ideally the file link should be: `[link description](<path with spaces>)`

## How to Reproduce the Issue
An org mode file linking to a file with spaces, then export and run `hugo server` to see the html output.

### Example Org File
```
 [[file:~/Downloads/sample file name.pdf][file description]],
```

### Generated Markdown File or Error
[file description](~/Downloads/sample file name.pdf)

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment]
@sprajagopal This issue is auto-closed because I tagged a commit for fixing this issue. But please do confirm if this actually fixes the issue for you.

**Comment by sprajagopal** [comment]
> @sprajagopal This issue is auto-closed because I tagged a commit for fixing this issue. But please do confirm if this actually fixes the issue for you.

Hello,
commit `77050d2` adds angular brackets for file links as expected: `[pdf](</ox-hugo/file name with spaces>)` and the regression from `9825a5e` related to org-roam is also solved.
Thanks!

**Comment by kaushalmodi** [comment]
@sprajagopal I believe you meant that https://github.com/kaushalmodi/ox-hugo/commit/9825a5e698b033241468709f1f5cd3e79c5925cd added the angled brackets.

What's the regression related to org-roam?

**Comment by sprajagopal** [comment]
> @sprajagopal I believe you meant that [9825a5e](https://github.com/kaushalmodi/ox-hugo/commit/9825a5e698b033241468709f1f5cd3e79c5925cd) added the angled brackets.
> 
> What's the regression related to org-roam?

Ignore that. I didn't restart emacs fully after updating to the commit. No regression
