### ISSUE TITLE
super long article,page truncated

### ISSUE THREAD

**Issue by longlu** [kaushalmodi/ox-hugo#378]
for very long article(and with hundreds of headings in it ,not too much content under each heading),   the exported markdown file only have part of the content

**Comment by kaushalmodi** [comment]
Hello, can you point me to the repo so that I can reproduce the issue?

**Comment by longlu** [comment]
just rename it to test.org  directly , and try to export that as a post.
[test.org.zip](https://github.com/kaushalmodi/ox-hugo/files/4810577/test.org.zip)

**Comment by longlu** [comment]
solved but I forgot exactly what cause ,   probably has to do   '***' somewhere,around some text  which is useless so i removed that if i remember correctly. solved after done that

**Comment by kaushalmodi** [comment]
Thanks for getting back. Yes, the *** could have created a boundary for a new post if that subtree had the EXPORT_FILE_NAME property.
