### ISSUE TITLE
Support latex export blocks

### ISSUE THREAD

**Issue by kiranshila** [kaushalmodi/ox-hugo#381]
## Actual Behavior
Org File
```org
#+BEGIN_EXPORT latex
\begin{equation}
E = mc^{2}
\end{equation}
#+END_EXPORT
```
Markdown file empty
## Expected Behavior
```md
```latex
\begin{equation}
E = mc^{2}
\end{equation}```
```
## How to Reproduce the Issue
Export an org file with the above export block
### Example Org File
See actual behavior
### Generated Markdown File or Error
Contains just the front matter
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

* Debug information for =ox-hugo=
** Emacs Version
#+begin_example
GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.17.3, Xaw scroll bars)
 of 2020-05-23 (commit f7e488d20694dea6d2cbb5f74381f7e6f1e4d484)
#+end_example
** Org Version
#+begin_example
Org mode version 9.4 (nil @ /home/kiran/.emacs.d/.local/straight/build/org-mode/)
#+end_example
** Hugo Version
#+begin_example
=hugo= binary not found in PATH
#+end_example
*** Org =load-path= shadows
No Org mode shadows found in =load-path=
** =ox-hugo= defcustoms
|org-hugo-section                                      |"posts"|
|org-hugo-use-code-for-kbd                             |nil|
|org-hugo-preserve-filling                             |t|
|org-hugo-delete-trailing-ws                           |t|
|org-hugo-prefer-hyphen-in-tags                        |t|
|org-hugo-allow-spaces-in-tags                         |t|
|org-hugo-tag-processing-functions                     |(org-hugo--tag-processing-fn-replace-with-spaces-maybe org-hugo--tag-processing-fn-replace-with-hyphens-maybe)|
|org-hugo-auto-set-lastmod                             |nil|
|org-hugo-export-with-toc                              |nil|
|org-hugo-export-with-section-numbers                  |nil|
|org-hugo-front-matter-format                          |"toml"|
|org-hugo-default-static-subdirectory-for-externals    |"ox-hugo"|
|org-hugo-external-file-extensions-allowed-for-copying |("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")|
|org-hugo-date-format                                  |"%Y-%m-%dT%T%z"|
|org-hugo-paired-shortcodes                            |""|
|org-hugo-langs-no-descr-in-code-fences                |nil|
|org-hugo-suppress-lastmod-period                      |0.0|
|org-hugo-front-matter-format                          |"toml"|
</details>

## Motivation
I use emacs-jupyter extensively and one feature I would love to have is to have latex embedded in my ox-hugo output. emacs-jupyter will insert an `#+begin_export latex` block if the MIME type of the output supports it (like sympy). It seems trivial to support this, as it would be functionally identical to copying the block's body into a `\[ \]` form.

**Comment by kaushalmodi** [comment]
Hello, I believe that ox-hugo should not be supporting this.. `#+BEGIN_EXPORT latex` is an Org construct reserved for the latex exporter backend and ox-hugo should not be caring about that.

The best way might be to use the `org-export-before-parsing-hook` hook that Org mode provides ([ref][1]). See the example on that linked manual page. Using that, you can search/replace your Org buffer to change the `#+begin_export latex .. #+end_export` to  `#+begin_src latex .. #+end_src` _just before the export_.

[1]: https://orgmode.org/manual/Advanced-Export-Configuration.html#Advanced-Export-Configuration

**Comment by kaushalmodi** [comment]
If you look up online, you will find many references to this hook. Here's one blog post that might help you: http://kitchingroup.cheme.cmu.edu/blog/2015/12/01/Post-processing-an-org-buffer-on-export/.

**Comment by kiranshila** [comment]
>Hello, I believe that ox-hugo should not be supporting this.. #+BEGIN_EXPORT latex is an Org construct reserved for the latex exporter backend and ox-hugo should not be caring about that.
Point taken. Thanks for your advise.
