### ISSUE TITLE
Extra newline created between `\[\left\{` and `\begin{align}` in equation blocks

### ISSUE THREAD

**Issue by kishvanchee** [kaushalmodi/ox-hugo#382]
## Actual Behavior
A new line is being parsed as a newline itself, instead of ignoring it, in the math environment. But when some random text is appended, for some reason the newline no longer exists when exporting to markdown. This is the [screenshot](https://ibb.co/kG3SDth)

## Expected Behavior
Hoping a newline should not appear. Newline in org should not affect the markdown export. This is not how it happens when I export to latex. PDF export works fine.

## How to Reproduce the Issue

In the below example, I have shown 3 implementations, 1st and 3rd render properly, the 2nd doesn't. Please let me know if my explanation is sufficient from below. I'm not sure where the error is, whether latex/markdown/ox-hugo/mathjax.

### Example Org File
```
\[\left\{\begin{align}
  \dot{x} & = \sigma(y-x) \newline
  \dot{y} & = \rho x - y - xz \newline
  \dot{z} & = -\beta z + xy
  \end{align} \right.\]


\[\left\{
\begin{align}
  \dot{x} & = \sigma(y-x) \newline
  \dot{y} & = \rho x - y - xz \newline
  \dot{z} & = -\beta z + xy
  \end{align}
\right.\]


\[\left\{ % but say if I insert comments here/random text
\begin{align}
  \dot{x} & = \sigma(y-x) \newline
  \dot{y} & = \rho x - y - xz \newline
  \dot{z} & = -\beta z + xy
  \end{align} % or random text here, problem goes away
\right.\]
```

### Generated Markdown File or Error
```
\\[\left\\{\begin{align}
  \dot{x} & = \sigma(y-x) \newline
  \dot{y} & = \rho x - y - xz \newline
  \dot{z} & = -\beta z + xy
  \end{align} \right.\\]

\\[\left\\{

\begin{align}
  \dot{x} & = \sigma(y-x) \newline
  \dot{y} & = \rho x - y - xz \newline
  \dot{z} & = -\beta z + xy
  \end{align}
    
\right.\\]

\\[\left\\{ % but say if I insert comments here/random text
\begin{align}
  \dot{x} & = \sigma(y-x) \newline
  \dot{y} & = \rho x - y - xz \newline
  \dot{z} & = -\beta z + xy
  \end{align} % or random text here, problem goes away
\right.\\]
```
### To reproduce in Latex
```
\left{
\begin{aligned}
  \dot{x} & = \sigma(y-x) \\
  \dot{y} & = \rho x - y - xz \\
  \dot{z} & = -\beta z + xy
\end{aligned}
\right.
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
     of 2020-05-19

## Org Version

    Org mode version 9.4 (nil @ /home/kishore/.emacs.d/.local/straight/build/org-mode/)

## Hugo Version

    Hugo Static Site Generator v0.73.0/extended linux/amd64 BuildDate: unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">&ldquo;posts&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">&ldquo;ox-hugo&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">(&ldquo;jpg&rdquo; &ldquo;jpeg&rdquo; &ldquo;tiff&rdquo; &ldquo;png&rdquo; &ldquo;svg&rdquo; &ldquo;gif&rdquo; &ldquo;mp4&rdquo; &ldquo;pdf&rdquo; &ldquo;odt&rdquo; &ldquo;doc&rdquo; &ldquo;ppt&rdquo; &ldquo;xls&rdquo; &ldquo;docx&rdquo; &ldquo;pptx&rdquo; &ldquo;xlsx&rdquo;)</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">&ldquo;%Y-%m-%dT%T%z&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">&ldquo;&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>
</tbody>
</table>

  

</details>

**Comment by kaushalmodi** [comment]
@kishvanchee Sorry for the late reply.

I am able to reproduce the bug. But this seems to be an upstream bug from `ox-html.el` (because for parsing of certain constructs like latex equation, ox-hugo delegates the job to parent parsers like ox-html.

When I export the 2nd (not working) equation using `ox-html` I see

```html
<p>
\[\left\{
</p>
\begin{align}
  \dot{x} & = \sigma(y-x) \newline
  \dot{y} & = \rho x - y - xz \newline
  \dot{z} & = -\beta z + xy
  \end{align}
<p>
\right.\]
</p>
```

As you notice, it is introduce a paragraph break after `\[\left\{` and before `\right.\]`. The best course of action would be to report this bug to the Org mode mailing list by emailing emacs-orgmode@gnu.org .

In the mean time, I feel that the workaround in the 1st equation you showed above looks like the best one.

**Comment by kaushalmodi** [comment]
@kishvanchee Can you email about this issue to the Org mailing list?

Fixing this is out if the scope of ox-hugo. 

The org-element library breaks up the elements and the exporters export each element in the custom way defined by that exporter. 

Here, the exporter is receiving the `\[\left\{` and `\begin{align}..` sections as separate elements and so the newline is inserted between them (and we see the same with ox-html export). 

Once this is fixed upstream, it should get fixes here automatically. If not, we will pick it up from here later. 

Please let me know once you email the list.

**Comment by verdsveven** [comment]
I am still having this issue after updating to the newest version of org. Is it fixed?

**Comment by kaushalmodi** [comment]
@verdsveven Please report this issue to the Org mailing list. This fix is out of the scope of ox-hugo.
