### ISSUE TITLE
How to visually distinguish between source code and result

### ISSUE THREAD

**Issue by RidaAyed** [kaushalmodi/ox-hugo#385]
Hi

I'm looking to for a solution to display source code and results differently in order to improve the comprehension:

```
*** Requirements
    Python
    #+begin_src sh :results output :exports both
    python --version
    #+end_src

    #+RESULTS:
    : Python 3.8.1

```
Screenshot: No visual difference between src and RESULTS:
![Screenshot](https://i.imgur.com/YoHNS9X.png)

**Comment by kaushalmodi** [comment]
You can manually add the `#+attr_html` and `#+attr_css` keywords above the the `#+results` block as shown in [here][1]. 

Adding those attributes automatically is out of the scope of ox-hugo as the results block is created by a function from ob-core library, and any change there would affect all the exporters. 

Look in the [Org exporter hooks][2] in the manual. The org-export-before-parsing-hook should be a good place where you parse the whole buffer and auto-inject the above attribute keywords above all `#+results` keywords. 

[1]: https://github.com/kaushalmodi/ox-hugo/issues/319#issuecomment-577380432

[2] https://orgmode.org/manual/Advanced-Export-Configuration.html
