### ISSUE TITLE
Many themes don't accept a list for authors

### ISSUE THREAD

**Issue by AdamBark** [kaushalmodi/ox-hugo#387]
## Actual Behavior
The export creates the line `author = ['Anonymous']` of type string[] which breaks in many themes with the following error:
`error calling safeHTML: unable to cast []string{"Anonymous"} of type []string to string`
## Expected Behavior
I'm not sure what the correct thing to do is as author doesn't seem to defined by hugo https://gohugo.io/content-management/front-matter/ some options would be to just write a plain string or to skip it entirely.
## How to Reproduce the Issue
Use a theme such as beautifulhugo with author set either by default or by specifying one
### Example Org File
```
#+HUGO_BASE_DIR: ..
#+hugo_section: 
#+title: Title
#+author: Anonymous
* A header
  :PROPERTIES:
  :export_file_name: _index
  :END:
A paragraph...almost!
** A post!
   :PROPERTIES:
   :export_hugo_section: posts
   :export_file_name: a-post
   :END:
Maybe?
```
### Generated Markdown File or Error
```
+++
title = "A post!"
author = ["Anonymous"]
draft = false
+++

Maybe?
```

> Rebuild failed:
> 
> Failed to render pages: render of "home" failed: execute of template failed: template: index.html:14:15: executing "main" at <partial "post_preview" .>: error calling partial: execute of template failed: template: partials/post_preview.html:20:11: executing "partials/post_preview.html" at <partial "post_meta.html" .>: error calling partial: "/tmp/hugotest/themes/beautifulhugo/layouts/partials/post_meta.html:16:72": execute of template failed: template: partials/post_meta.html:16:72: executing "partials/post_meta.html" at <safeHTML>: error calling safeHTML: unable to cast []string{"Anonymous"} of type []string to string
>

**Comment by kaushalmodi** [comment]
Hello, have you looked at this: https://ox-hugo.scripter.co/doc/author/#tweaking-your-hugo-template-to-support-list-author

It explains how you can make author be a string.

**Comment by AdamBark** [comment]
I hadn't seen that specifically but I had figured out how to work around it but I thought it might be a less than ideal default?

**Comment by kaushalmodi** [comment]
I had arrived to a decision to keep author as array as a lot of thinking. Eventually, I want to keep ox-hugo more faithful to Org, where we use the `#+author` keyword for one or more authors. So the current behavior cannot change. If you want to export the author front matter as a string, you can apply that workaround at the top of your Org file. It can even go into an Org Setup File that you use for all your Org files. 

I know of some themes who already support author both as a string and an array. May be you can provide a PR to your favorite theme to support that.

**Comment by kaushalmodi** [comment]
.. and it's quite trivial for the themes to support this. [Here's a PR supporting this][1] in the Ananke theme from Hugo's official tutorial. 

[1]: https://github.com/theNewDynamic/gohugo-theme-ananke/pull/221

**Comment by AdamBark** [comment]
OK. Thanks for taking the time to discuss this and making ox-hugo, it's very useful!
