### ISSUE TITLE
Support cross-post linking to page bundle subtrees

### ISSUE THREAD

**Issue by dpertin** [kaushalmodi/ox-hugo#389]
Hey! This is my first issue here, so I would like to thank you for this amazing project :+1: 

Now regarding my issue, here is the context. Since I use the [academic theme](https://github.com/gcushen/hugo-academic) I export each subtree in an `index.md` file stored in different directories. Thus, each subtree has the following properties:

```
:PROPERTIES:
:EXPORT_HUGO_SECTION: post/post1                                            
:EXPORT_FILE_NAME: index
:END:
``` 

And in this example, the exported file is stored in `content/post/post1/index.md` which works well :+1:.

Now, I create a new subtree with a custom ID:

```
:PROPERTIES:
:EXPORT_HUGO_SECTION: post/post2                                            
:EXPORT_FILE_NAME: index
:CUSTOM_ID: post2
:END:
```
and I want to add a link in the first subtree, referencing the second one, as follows: `[[#post2][Link to post2]]`.

However, the exported result is the following: `[Link to post2]({{< relref "index" >}})` which fails since it should be `[Link to post2]({{< relref "post/post2" >}})`. The result is thus based on `EXPORT_FILE_NAME` while I want it to be based on `EXPORT_HUGO_SECTION`. Am I doing something wrong?

**Comment by kaushalmodi** [comment]
The cross posting to Hugo bundle pages is not yet supported because the I need to create relref's to the bundles' dir names and not the file names (which will always be index or _index). 

For now, please create hard coded cross references like [[/post/post2][Link to post2]].

I'll keep this issue open until I add support for cross referencing page bundles.

**Comment by kaushalmodi** [comment]
This now works!!

```org
#+hugo_base_dir: .
#+hugo_section: /

* Articles
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: articles
:EXPORT_FILE_NAME: _index
:END:
Content in a branch bundle

- Link to [[*Post 1]]
- Link to [[*Post 2]]

* Blog posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:END:
** Post 1
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: post-1
:EXPORT_FILE_NAME: index
:END:
Content in a "post-1" *leaf* bundle

- Link to [[*Articles]]
- Link to [[*Post 2]]

** Post 2
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: post-2
:EXPORT_FILE_NAME: index
:END:
Content in a "post-2" *leaf* bundle

- Link to [[*Articles]]
- Link to [[*Post 1]]
```
