### ISSUE TITLE
best way to publish subtrees

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#39]
I'm not clear on how to tell org-publish how to publish all subtrees in a file, in the context of `org-publish-project-alist`.  Do you have an idea how htis would be done? We are sort of sidestepping hte normal org publishing mechanism, right?

**Comment by kaushalmodi** [comment]
>We are sort of sidestepping hte normal org publishing mechanism, right?

Yes, because we need to only export the subtrees that have the `EXPORT_FILE_NAME` property defined. So `C-u M-x org-hugo-publish-subtree` will publish all eligible subtrees in the file... with using `org-publish` though.

**Comment by kaushalmodi** [comment]
In addition, as I note [here][1], I cannot figure out how to get the TODO status and tags for the subtree from inside `org-hugo-export-to-md`. So I need that wrapper function.

[1]: https://github.com/kaushalmodi/ox-hugo/blob/1e9c4c020da6ac13d210bcf7aab636b51c1fd898/ox-hugo.el#L768-L772

**Comment by titaniumbones** [comment]
> with using org-publish though.
do you mean "without using `org-publish`"? 
I have wirtten this which works fine ofr me, but I think something more org-likewould be preferable, especially for complex projects:

```emacs-lisp
  (defun mwp-publish-hh-site ()
    (interactive)
    (let* ((src-dir "~/HackingHistory/")
           (subtree-files '("Assignments.org" "Labs.org"))
           (single-items '("His455Outline.org"))
           )
      (dolist (single single-items)
        (save-window-excursion
          (find-file (concat src-dir single))
          (org-hugo-export-to-md nil)))
      (dolist (sub subtree-files)
        (save-window-excursion
          (find-file (concat src-dir sub))
          (org-hugo-publish-subtree t)))
      (shell-command (format "%s %s" "hugo" "-s ~/HackingHistory/hugoplayground -t hh-courseware"))
      (shell-command (format "%s %s" "rsync" "-azvbP ~/HackingHistory/hugoplayground/public/ shimano:/var/www/2017.hackinghistory.ca"))))
```

**Comment by kaushalmodi** [comment]
> > with using org-publish though.
> do you mean "without using org-publish"?

Yes, I meant 'without'.. I've now fixed that comment. 

> I have wirtten this which works fine ofr me, but I think something more org-like would be preferable, especially for complex projects:

Once this package is good enough, I'll be submitting this to the org mode list for comments, before I can commit it to the Org source. Hopefully we find an answer then.

**Comment by kaushalmodi** [comment]
This commit https://github.com/kaushalmodi/ox-hugo/commit/99ec1b1bbe225e76efbedd7e1bb571635103101c works towards solving this issue.

**Comment by simonthum** [comment]
I don't know if this is related, but I'm likewise met with difficulties trying to automate export to hugo. I do

```
 $ emacs -batch -l ~/.emacs.d/init.el blog/blog.org --eval "(org-hugo-export-to-md :all-subtrees)" --kill
Loading /home/simon/org/scripts/org-mode.el (source)...
Created tel link.
Created thunderlink link.
Loading /home/simon/org/scripts/custom.el (source)...
Loading paren...
Restoring clock data
Loading /home/simon/.emacs.d/org-clock-save.el (source)...
Initializing asynchronous export process

Wrong type argument: stringp, nil
```

From inside a babel elisp source block the behaviour is the same. Different or same issue?

**Comment by kaushalmodi** [comment]
@simonthum See if https://github.com/kaushalmodi/ox-hugo/blob/master/test/setup-ox-hugo.el helps.. I use that in the [Makefile][1] for generating the [doc][2] and [test][3] websites from command line using `make doc` and `make md` respectively.

[1]: https://github.com/kaushalmodi/ox-hugo/blob/master/Makefile
[2]: https://ox-hugo.scripter.co
[3]: https://ox-hugo.scripter.co/test

**Comment by simonthum** [comment]
So far I did not find something, but I managed to break the interactive export by enabling async export. Maybe I need to explicitly disable that on the CLI.

**Comment by kaushalmodi** [comment]
> So far I did not find something, but I managed to break the interactive export by enabling async export. 

Honestly, I have never used async export (on `ox-hugo` or any of the inbuilt exporters). 

About the error you pasted earlier:

> Wrong type argument: stringp, nil

Can you enable `toggle-debug-on-error` in your batch mode emacs and get the full backtrace.

.. and open a new issue for this async issue. I am not an expert in async debugging, so might have to mark it as "Help wanted" if I couldn't get anywhere with it.

**Comment by simonthum** [comment]
There is no error it would trigger on, apparently. But I'll make a new issue for automating subtree export.

**Comment by simonthum** [comment]
I fixed it (it just was the wrong function) and I don't really care about the async export. Also, async seems to work interactively, it just doesn't on the CLI (which was triggered by accident) and interactively it does just report errors - I don't think something really doesn't work. Might be a matter of interpreting success and failure. 

So from my side everything seems fine now.

**Comment by kaushalmodi** [comment]
> So from my side everything seems fine now.

Thanks for the update.

**Comment by kaushalmodi** [comment]
I have been using a Makefile with a minimal setup file in Elisp to batch export the test and doc sites for this package, for quite a few months; see [this earlier comment of mine for links][1]. 

Org publish has a limitation that won't allow it to loop through all the post subtrees (as of today). 

So, closing this issue as a working solution already exists. 

[1]: https://github.com/kaushalmodi/ox-hugo/issues/39#issuecomment-340273529
