### ISSUE TITLE
Support all built-in Hugo shortcodes

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#4]
See the full list here:

https://gohugo.io/extras/shortcodes/

cf also #3

**Comment by kaushalmodi** [comment]
I am on a fence about this.

Reasoning: I plan to keep the format of my blog Org files such that they export fine using the default export backends like html, pdf, text, etc. too.

If I use Hugo shortcodes in Org, they won't work for normal exports and then my blog source is bound to just Hugo.

Taking the `figure` shortcode for example, wouldn't it be fine to just use the Org way of inserting figures? That would export to Markdown format just fine. 

I believe that the equivalent of shortcodes for youtube, twitter, etc, would be Org links.

There would also be shortcodes that do not have a direct equivalent in Org.

And so I am not completely sure if this support should be added.

Might help to start with a list of your favorite Hugo shortcodes.

WDYT?

**Comment by titaniumbones** [comment]
hmm.  You make some good points! I also plan to reuse all my materials in multiple formats, so "hugoizing" the source would be a bad solution.

And actually, I still haven't really looked at all the hugo plugins. But in general, I think the less HTML we can end up putting into the exported files, the better.  So if Hugo supports an advanced feature (that Org also supports), then I think we should strive to *eventually* convert materials to hugo-inflected Markdown rather thhan do the HTML export ourselves.  THis also gives control over presentation back to Hugo; then we don't have to mess with classes or other HTMl-specific stuff from inside Org, and if, for instance, a site has mixed content (partly exported from Org, but also partly composed in Markdown from the beginning) then the styling will probably be more consistent if we can export to Hugo as much as possible.

So, I'm on the fence too.  Can we leave this open for a while till we have an exporter that meets our other goals, and see what we think at that point? Along the way we'll probably also both become more familiar with Hugo.

**Comment by kaushalmodi** [comment]
> So, I'm on the fence too. Can we leave this open for a while till we have an exporter that meets our other goals, and see what we think at that point? 

That's what I think too :)

**Comment by titaniumbones** [comment]
See this commit for one way to do this: https://github.com/titaniumbones/ox-hugo/commit/f7711600fcaef85c6d07a19e9465aa2b714be76e

**Comment by kaushalmodi** [comment]
If you use the Hugo shortcodes in the Org file, they will be retained as they are in the exported Markdown. So `ox-hugo` doesn't need to do anything special for support the shortcodes. Just note that by taking that route, the Org source will be tied to Hugo.
