### ISSUE TITLE
latex figure environment

### ISSUE THREAD

**Issue by asthagiri** [kaushalmodi/ox-hugo#400]
Does ox-hugo support `figure` environment in LaTeX?

**Comment by kaushalmodi** [comment]
Hello, I am not familiar with LaTeX environments.

ox-hugo mainly leverages what's already supported by Org, and simply adds extra escaping needed for Hugo Markdown parser (Goldmark). Can you provide an example Org snippet? Also please mention if that snippet exports fine using ox-html.

**Comment by asthagiri** [comment]
I have it working. I went with the approach org mode provides:

#+NAME: fig-title
#+CAPTION: some text here
[[./img/filename.jpg]]

This exports as needed using ox-hugo. Thanks!
