### ISSUE TITLE
Support: Advice for image processing and ox-hugo (render hooks?)

### ISSUE THREAD

**Issue by anaxonda** [kaushalmodi/ox-hugo#402]
Hello,

I have a question regarding how best to approach image processing when using ox-hugo.

I am using page bundles, and I would like to be able to resize each image to several different sizes as well as adding a lazy loading html attribute.

It seems that Hugo recommends this be accomplished using [render hooks](https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks). I would use something similar to [this](https://discourse.gohugo.io/t/simple-image-render-hook-template-for-responsive-images/22464).

The issue is that ox-hugo wraps images in the hugo `figure` shortcode, and from reading thus far I am led to believe render hooks cannot process shortcodes (related to this issue: https://github.com/gohugoio/hugo/issues/6703).

I would prefer to keep using the simplicity afforded by ox-hugo, currently I can just use org-download to drag images in, caption them with org syntax, etc. 

One idea I have is modifying the default [figure shortcode](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/figure.html), adding an image processing step and a lazy load attribute.

Appreciate any thoughts on going about this,

Thanks

**Comment by kaushalmodi** [comment]
> One idea I have is modifying the default figure shortcode, adding an image processing step and a lazy load attribute.

As ox-hugo uses the figure shortcode, the simplest way seems to redefine the shortcode in your theme. The refined shortcode will automatically override the default `figure` shortcode. [Here's][1] an example of how I override the `figure` shortcode in the ox-hugo site's theme.

[1]: https://github.com/kaushalmodi/hugo-onyx-theme/blob/551d2bcc0c6c2ea0d8611b7e2e1c81e7ef2fd7ed/layouts/shortcodes/figure.html

**Comment by anaxonda** [comment]
Thank you for that example. Writing a modified shortcode definitely seems to be the best way for now. 

Cheers
