### ISSUE TITLE
Trying to debug table isues

### ISSUE THREAD

**Issue by amca01** [kaushalmodi/ox-hugo#404]
I don't use tables very often; one of the reasons being that I have never got them to compile properly.  For example, a table taken from the ox-hugo org file:

```
#+begin_export html
<style>
.tab4 th,
.tab4 td {
    padding: 20px;
    text-align: left;
}
</style>
#+end_export
#+caption: Table with verbatim CSS
#+attr_html: :class tab4
| h1  | h2  | h3  |
|-----+-----+-----|
| abc | def | ghi |
```

doesn't render properly at all: there's no formatting in my final html file; all the cells are squashed together with no spacing or borders at all:

**h1 h2 h3**
abcdefghi

In the past I have got round this by using either ascii tables, or tables formatted in LaTeX.  I am using Hugo version 0.75.1 and the blackburn theme, and I can't find anything obviously incriminating in either the theme, or in my config file, or in my post itself.  Anyway, I thought the idea of using styles and divs was to be able to override any config settings.

How do I go about working out where the cause of this error might be; or alternatively is there another way of creating tables using ox-hugo?

I've just discovered that in the html file, all the "raw" html around the table has been deleted.  And in the markdown file created by ox-hugo, there's an extra `<div></div>` pair immediately before the table.   So maybe it's a Hugo problem?

Many thanks,
Alasdair

**Comment by kaushalmodi** [comment]
@amca01 If you took that example from the ox-hugo test suite, it certainly works. Here's the rendered page: https://ox-hugo.scripter.co/test/posts/table-styling/#table-with-verbatim-css by Hugo.

If you are using Hugo v0.60 or newer version, you **need** to set this property in your Hugo site's config.toml: https://ox-hugo.scripter.co/doc/goldmark/#enable-unsafe-html

---

> I don't use tables very often; one of the reasons being that I have never got them to compile properly. 

I use tables a lot. Provide provide an example Org snippet that demonstrates that issue.

**Comment by amca01** [comment]
Many thanks, @kaushalmodi - it was in fact setting the unsafe html property of `markup.goldmark.renderer` which made all the difference.  Having set that property my tables are now manageable again.

**Comment by kaushalmodi** [comment]
> Having set that property my tables are now manageable again.

Cool. Glad to see that things are back on track :)
