### ISSUE TITLE
Consider removing DEADLINE to expiryDate mapping

### ISSUE THREAD

**Issue by cpbotha** [kaushalmodi/ox-hugo#415]
## Actual Behavior

Orgmode TODO `DEADLINE` is converted to Hugo `expiryDate`.

Sometimes when I use the Orgmode DEADLINE as an actual due date for writing and publishing the blog post, that post gets published with an expiryDate. If I publish the post on time, it appears, but at next site build, when we've passed the expiryDate (my original due date) the post disappears!

## Expected Behavior

`expiryDate` is a fairly specific Hugo function that does not get used that often. Consider enabling this only via the specific `HUGO_EXPORT_...` field and not via the far more commonly used Orgmode deadline / due date which is often used as, well, a due date. :)

##  Work-around

For now, I'm advising the relevant ox-hugo function not to output an expiryDate, like this:

``` emacs-lisp
;; ox-hugo converts DEADLINE into expiryDate, which led to some of my posts
;; briefly disappearing before I noticed this. To prevent this, advise
;; org-hugo--format-date function so it ignores date-key=:hugo-expirydate
;; https://ox-hugo.scripter.co/doc/dates/#expiry-date
;; https://gohugo.io/variables/page/
(defun no-emit-expirydate (oldfun &rest args)
  ;; args: date-key info
  (if (equal (car args) :hugo-expirydate)
      nil
    (apply oldfun args)))
(advice-add #'org-hugo--format-date :around #'no-emit-expirydate)
```

**Comment by kaushalmodi** [comment]
Hello, do you want to try the [Replace Front-matter Keys](https://ox-hugo.scripter.co/doc/replace-front-matter-keys/) feature?

If you are never using the expiryDate front matter, you can replace that to something else.

**Comment by cpbotha** [comment]
Hi there @kaushalmodi -- it's great to know that that exists (for other reasons), but my advice above works better in my context. I do subtree blogs from many different org-files, so there's a risk I forget the replace front-matter keys config and get another post mysteriously disappearing.

I am actually suggesting here that removing the automatic DEADLINE -> expiryDate mapping would be a usability improvement. ([principle of least surprise](https://www.uxpassion.com/blog/the-principle-of-least-surprise/), and more)

**Comment by kaushalmodi** [comment]
> not via the far more commonly used Orgmode deadline / due date which is often used as, well, a due date. :)

OK, you have convinced me :)

- I myself do not use the `expiryDate` front matter at all.
- Even if this is a breaking change, it's not entirely breaking, as the DEADLINE property used for setting the expiryDate can be replaced with the EXPORT_HUGO_EXPIRYDATE property.
- And most of all, your above argument did make sense.

So now the DEADLINE property is no longer interpreted as expiryDate.

Thanks for bringing this up for discussion.
