### ISSUE TITLE
Not all double underscores are translated to space in tags

### ISSUE THREAD

**Issue by muihlinn** [kaushalmodi/ox-hugo#417]
Not all `__` are converted to spaces, at least in tags. For example, "Blanco__ y__negro" becomes "Blanco y__negro" when the expected string is "Blanco y negro"

## How to Reproduce the Issue

Either exporting a properly configurated or file, or just evaluating this in the scratch buffer

```lisp
(org-hugo--replace-underscores-with-spaces "Blanco__y__negro")
```
I guess the culprit is the regex used in line 3125 of `ox-hugo.el` which seems to ignore one letter between targets , I haven't digged more because I guess there is a good reason for using it instead to just a plain replace of `__` by `  ` . (I haven't reviewed all related code to find out why).

**Comment by kaushalmodi** [comment]
I confirm the bug. Thanks for reporting.

**Comment by kaushalmodi** [comment]
Please update to the master and confirm the fix. Thanks!

**Comment by muihlinn** [comment]
Looks fixed, thanks much!
