### ISSUE TITLE
make md error with pandoc-citeproc

### ISSUE THREAD

**Issue by vinurs** [kaushalmodi/ox-hugo#419]
when i install pandoc-citeproc in macos bigsur, it shows:
```
==> Homebrew was updated to version 2.7.7
The changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/2.7.7
Error: pandoc-citeproc has been disabled because it is deprecated upstream!
```
so when i run `make md`, it outputs
```
Debugger entered--Lisp error: (user-error "[ox-hugo] pandoc-citeproc executable not found in ...")
  user-error("[ox-hugo] pandoc-citeproc executable not found in ...")
  (if (executable-find "pandoc-citeproc") nil (user-error "[ox-hugo] pandoc-citeproc executable not found in ..."))
```

**Comment by kaushalmodi** [comment]
Hello, 

I have the ox-hugo test suite working with Pandoc 2.9.2.1. Please see https://ox-hugo.scripter.co/doc/requirements/#code_contributor_reqs . Can you try installing that version instead of 2.7.7?

I don't use macos, so I am not sure, but you might be able to simply download the pandoc and pandoc-citeproc static binaries and put them in $PATH.

**Comment by kaushalmodi** [comment]
I now see that pandoc-citeproc was deprecated in Oct 2020. I'll find some time to update the test suite dependencies and the test suite itself, because the latest pandoc 2.11.4 is not backward compatiable with 2.9.2.1.

**Comment by kaushalmodi** [comment]
@vinurs I am attempting to update pandoc support to 2.11.4, but I am facing some trouble here: https://github.com/kaushalmodi/ox-hugo/pull/408#issuecomment-769582918

**Comment by kaushalmodi** [comment]
@vinurs Please update to Pandoc 2.11.4, update ox-hugo from its master branch and let me know if this issue is fixed. 

See https://github.com/kaushalmodi/ox-hugo/issues/420 .

**Comment by vinurs** [comment]
Thanks very much, works ok now
