### ISSUE TITLE
how to disable exporting an org file when make md

### ISSUE THREAD

**Issue by vinurs** [kaushalmodi/ox-hugo#421]
in the directory i add
```
((org-mode . ((eval . (org-hugo-auto-export-mode)))))
```
in a org file, i add 
```
​* Footnotes
​* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode -1)
# End:
```
but i run `make md`, it also has been exported，the `org-hugo-auto-export-mode`  doesn't override its enabled state in `.dir-locals.el`

**Comment by kaushalmodi** [comment]
Hello,

This is more of a question about the internal machinery of Emacs; about how the File Local Variables and .dir-locals.el files get evaluated, and what gets the precedence.

This question is out of the scope of `ox-hugo` and best asked on the help-gnu-emacs mailing list.
