### ISSUE TITLE
scalability of 'One post per Org subtree'

### ISSUE THREAD

**Issue by gour** [kaushalmodi/ox-hugo#428]
Hello,

I'm about to convert one non-profit site containing few hundred posts containing images to Hugo and wonder how does "One post per Org subtree" scale, iow. do you still recommend it over 'One post per Org file' ?

Sincerely,
Gour

**Comment by kaushalmodi** [comment]
Hello,

I don't have experience with that number of posts. I still use that approach for my internal work blog and it works well, but I have around 50 posts at the moment. 

Note that you don't have to strictly pick one of subtree-based or file-based approaches; you can mix both. Example: One Org file containing all the posts for one section or topic of posts, and you may have, say, a dozen sections.

**Comment by gour** [comment]
> I don't have experience with that number of posts. I still use that approach for my internal work blog and it works well, but I have around 50 posts at the moment.

OK.

> Note that you don't have to strictly pick one of subtree-based or file-based approaches; you can mix both. Example: One Org file containing all the posts for one section or topic of posts, and you may have, say, a dozen sections.

Yes, that's good idea...maybe I'll try to use one-subtree-per-category and see how it goes. :-)
