### ISSUE TITLE
Hugo fails on internal link to `index.md`

### ISSUE THREAD

**Issue by patmaddox** [kaushalmodi/ox-hugo#429]
## Actual Behavior

An internal link to `index.md` fails to resolve. I have also tried `_index.md`

If I change the `EXPORT_FILE_NAME` to anything other than `index`, the link resolves as expected.

## Expected Behavior

Link to `index` works.

## How to Reproduce the Issue

`C-u M-x org-hugo-export-wim-to-md`

### Example Org File

```org
#+TITLE: hugo test file
#+hugo_base_dir: ~/Desktop/hugo_export
#+hugo_section: /
#+author: Pat Maddox

* Pages
** TODO My first page
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_DATE: 2021-03-06
:CUSTOM_ID: home
:END:
It links to the [[#funky2][second page]].

** My second page
:PROPERTIES:
:EXPORT_FILE_NAME: funky2
:EXPORT_DATE: 2021-03-05
:CUSTOM_ID: funky2
:END:

It links back to the [[#home][main page]].
```

### Generated Markdown File or Error

```
Source changed "/Users/patmaddox/Desktop/hugo_export/content/index.md": CREATE
Source changed "/Users/patmaddox/Desktop/hugo_export/content/funky2.md": CREATE
ERROR 2021/03/06 18:17:55 [en] REF_NOT_FOUND: Ref "index": "/Users/patmaddox/Desktop/hugo_export/content/funky2.md:8:74": page not found
Total in 4 ms
ERROR 2021/03/06 18:17:55 Rebuild failed:

ERROR 2021/03/06 18:17:55 Logged 1 error(s)
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101))
     of 2020-11-14

## Org Version

    Org mode version 9.5 (nil @ /Users/patmaddox/.emacs.d/.local/straight/build-27.1/org-mode/)

## Hugo Version

    hugo v0.81.0+extended darwin/amd64 BuildDate=unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">&ldquo;posts&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">&ldquo;ox-hugo&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">(&ldquo;jpg&rdquo; &ldquo;jpeg&rdquo; &ldquo;tiff&rdquo; &ldquo;png&rdquo; &ldquo;svg&rdquo; &ldquo;gif&rdquo; &ldquo;mp4&rdquo; &ldquo;pdf&rdquo; &ldquo;odt&rdquo; &ldquo;doc&rdquo; &ldquo;ppt&rdquo; &ldquo;xls&rdquo; &ldquo;docx&rdquo; &ldquo;pptx&rdquo; &ldquo;xlsx&rdquo;)</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">&ldquo;%Y-%m-%dT%T%z&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">&ldquo;&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
Hello,

This is a known limitation of `ox-hugo`. Internal linking does not work for Page Bundles.

**Comment by patmaddox** [comment]
I didn't realize that I was using a Page Bundle. I believe I am using the [One post per Org subtree (preferred)](https://github.com/kaushalmodi/ox-hugo#one-post-per-org-subtree-preferred) setup - and admittedly have no prior experience with Hugo. Is there a thing I can change that will make these internal links work?

Also, this report seems to be specifically about the `:EXPORT_FILE_NAME: index` setting - because when I use any other `EXPORT_FILE_NAME`, the internal links work fine.

**Comment by kaushalmodi** [comment]
>Is there a thing I can change that will make these internal links work?

Avoid using `index` as exported md name if you don't intend to use Hugo Page Bundles.

>this report seems to be specifically about the :EXPORT_FILE_NAME: index setting - because when I use any other EXPORT_FILE_NAME, the internal links work fine.

Correct. That's expected. `index.md` and thus `index.html` is a special name for websites in general. For e.g., a URL `example.com/index.html` can be accessed by visiting `example.com/` directly. That `index.html` is not specified in that case.

So I'd suggest that you avoid the `index` name if you don't intend to use Page Bundles.

**Comment by kaushalmodi** [comment]
You can read more about the special export names `index` and `_index` here:

- https://ox-hugo.scripter.co/doc/hugo-bundle/
- https://gohugo.io/content-management/page-bundles/

**Comment by patmaddox** [comment]
> So I'd suggest that you avoid the index name if you don't intend to use Page Bundles.

Okay. If I can't use `index`, how do I define the home page? At this point I can redirect `/` to `/home` but it seems odd that I wouldn't be able to make the top-level home page.

**Comment by kaushalmodi** [comment]
I understand then. Yes, you need the export name to be `index` for the home page.

But as the "index.html" name is special, I don't yet have a way to get the internal links work for such names. 

The good thing is that you should be to link to the home page by just linking to `/` URL. Do you want to try that?

**Comment by patmaddox** [comment]
Got it, thanks for the info. Yeah I can use `/` :)  I like the internal links and wanted to leave it at that, but it's easy enough to treat `/` as a special case and replace it as needed.

Thank you!
