### ISSUE TITLE
Disable export of org-babel src blocks

### ISSUE THREAD

**Issue by dorneanu** [kaushalmodi/ox-hugo#430]
## Actual Behavior

When I export that ORG buffer I get:

        +++
        title = "Testing"
        author = ["Victor Dorneanu"]
        lastmod = 2021-03-10T21:01:32+01:00
        draft = false
        +++
        
        ```bash
        echo "testing"
        ```
        
        ```text
        testing
        ```

## Expected Behavior

I would expect only the #+RESULTS section to be exported. 

        +++
        title = "Testing"
        author = ["Victor Dorneanu"]
        lastmod = 2021-03-10T21:01:32+01:00
        draft = false
        +++
        
        ```text
        testing
        ```

## How to Reproduce the Issue

Create a new ORG buffer with the following content and export using `ox-hugo`.

### Example Org File

```
#+TITLE: ORG Content
#+AUTHOR: Victor Dorneanu
#+STARTUP: indent
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: posts
#+HUGO_AUTO_SET_LASTMOD: t

* Posts
** DONE Testing
:PROPERTIES:
:EXPORT_FILE_NAME: 2021-testing
:END:

#+begin_src bash :exports results :eval never-export
echo "testing"
#+end_src

#+RESULTS:
: testing

```

### Generated Markdown File or Error

      +++
      title = "Testing"
      author = ["Victor Dorneanu"]
      lastmod = 2021-03-10T21:01:32+01:00
      draft = false
      +++
      
      ```bash
      echo "testing"
      ```
      
      ```text
      testing
      ```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  
  |org-hugo-section                                      |"posts"|
|org-hugo-use-code-for-kbd                             |nil|
|org-hugo-preserve-filling                             |t|
|org-hugo-delete-trailing-ws                           |t|
|org-hugo-prefer-hyphen-in-tags                        |t|
|org-hugo-allow-spaces-in-tags                         |t|
|org-hugo-tag-processing-functions                     |(org-hugo--tag-processing-fn-replace-with-spaces-maybe org-hugo--tag-processing-fn-replace-with-hyphens-maybe)|
|org-hugo-auto-set-lastmod                             |nil|
|org-hugo-export-with-toc                              |nil|
|org-hugo-export-with-section-numbers                  |nil|
|org-hugo-front-matter-format                          |"toml"|
|org-hugo-default-static-subdirectory-for-externals    |"ox-hugo"|
|org-hugo-external-file-extensions-allowed-for-copying |("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")|
|org-hugo-date-format                                  |"%Y-%m-%dT%T%z"|
|org-hugo-paired-shortcodes                            |""|
|org-hugo-langs-no-descr-in-code-fences                |nil|
|org-hugo-suppress-lastmod-period                      |0.0|
|org-hugo-front-matter-format                          |"toml"|

</details>

**Comment by dorneanu** [comment]
I've actually figured out how to make this work:

* In my `config.el` (I'm using doom-emacs) I have

```lisp
(after! org
    (setq org-confirm-babel-evaluate nil)
    (setq org-export-use-babel t))

```

* in my org file at the top I have:

```lisp
#+property: header-args :eval never-export
```

Make sure to `C-c C-c` while pointing at that line. Then I can use:

```lisp
  #+begin_src bash :exports results
  ls -l

  #+end_src
```

In the exported markdown file I only have the `result`. Maybe you can also confirm this then I can close this one.

**Comment by kaushalmodi** [comment]
Hello,

I am unable to reproduce this issue as you can see in this test that I just added based on this issue: https://github.com/kaushalmodi/ox-hugo/commit/80a49c096dfa99b6547993cc9b73a6d556bd066d

So I believe that it's something else in your config that's messing this up.

>    In my config.el (I'm using doom-emacs) I have
>
>      (after! org
>          (setq org-confirm-babel-evaluate nil)
>          (setq org-export-use-babel t))

This doesn't change anything, but you don't need `(setq org-export-use-babel t)` .. that's the default value.

> in my org file at the top I have:
>
>     #+property: header-args :eval never-export

I didn't need that.. your Org recipe to reproduce the issue worked just fine.. did not show that issue.

> Make sure to C-c C-c while pointing at that line.

You shouldn't need to do that in any case.. just refreshing the Org buffer always re-evaluates the properties.
