### ISSUE TITLE
include org file cause export error

### ISSUE THREAD

**Issue by vinurs** [kaushalmodi/ox-hugo#431]
i use the `#+INCLUDE: ~/test.org src org` to include test.org as src code, if the test.org file include the code
```
* test

* COMMENT Local Variables            :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode 1)
# End:
```

it will cause ox-hugo auto export the test.org, it shows the error that ` The entire file is attempted to be exported, but it is missing the #+title keyword`,  but i just want it to be org src code

**Comment by kaushalmodi** [comment]
Hello,

I believe this is a result of the default behavior of how `#+include` and [Emacs file local variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html) work. 

`ox-hugo` has no control over that.

**Comment by vinurs** [comment]
sorry, i tried again, it works as I expected.
