### ISSUE TITLE
BEGIN_SRC in footnote exports verbatim

### ISSUE THREAD

**Issue by winny-** [kaushalmodi/ox-hugo#433]
## Actual Behavior

The footnote is exported with the BEGIN_SRC verbatim.

## Expected Behavior

The footnote is exported with a markdown code block.

I tried editing the resulting `md` document so the multi-line code block appears in the footnote, but hugo appears to move the block to the bottom of the post's body.  Could this be a hugo limitation?  In contrast, the Org HTML Export appears to allow code blocks in footnotes.

## How to Reproduce the Issue

```sh
hugo new site testsite .
cd testsite
mkdir -p content-org
emacs  # Create the org file below and run C-c C-e H A
# add a theme and serve the site to inspect
```

### Example Org File

```org
#+hugo_base_dir: ..
#+startup: indent
* Test post
:PROPERTIES:
:EXPORT_FILE_NAME: test-post
:END:
Testing code in a footnote with a  =BEGIN_SRC= directive.[fn:1]

* Footnotes

[fn:1] 
#+BEGIN_SRC elisp
(emacs-version)
#+END_SRC
```

### Generated Markdown File or Error

```md
+++
title = "Test post"
draft = false
+++

Testing code in a footnote with a  `BEGIN_SRC` directive.[^fn:1]

[^fn:1]: \#+BEGIN\_SRC elisp (emacs-version) \#+END\_SRC
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
     of 2021-03-09

## Org Version

    Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.3/lisp/org/)

## Hugo Version

    Hugo Static Site Generator v0.78.1/extended linux/amd64 BuildDate: unknown

### Org `load-path` shadows

**Warning**: Possible mixed installation of Org

    ~/.emacs.d/org-static-blog/org-static-blog hides /home/winston/.emacs.d/elpa/org-static-blog-20210306.1316/org-static-blog

Study the output of `M-x list-load-path-shadows`.

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

  

</details>

**Comment by kaushalmodi** [comment]
Thanks for reporting this. While I don't see the exported Markdown as seen by you, I see that the exported Markdown is not correct for code blocks in footnotes.. I see:

````
[^fn:1]: ```elisp (emacs-version) ```
````

I don't know if Hugo/CommonMark would support code blocks in foot-notes.. This will need to be investigated.

**Comment by kaushalmodi** [comment]
@winny- I just tested this out locally.. it's not possible to support source blocks (or any multi-line element) in the footnotes as Hugo doesn't support multi-line content in footnotes. I have added your test case to the ox-hugo test suite to demonstrate that: https://ox-hugo.scripter.co/test/issues/443-src-block-in-footnote/

**Comment by kaushalmodi** [comment]
@winny- Please bring this up on [Hugo Discourse](https://discourse.gohugo.io/). Active users there might have ideas on how to make this work. If you can come up with a Markdown file that shows the source code formatting correctly in footnotes, I can work to make ox-hugo export in that format.

**Comment by quantumgc** [comment]
Hugo now supports Goldmark by default which [uses a different footnote backend](https://github.com/yuin/goldmark/#footnotes-extension), specifically [php-markdown's footnote extension](https://michelf.ca/projects/php-markdown/extra/#footnotes). This supports multi-line footnotes. Copying the example on the PHP-markdown page,
```md
That's some text with a footnote.[^1]

[^1]: And that's the footnote.

    That's the second paragraph.
 ```
