### ISSUE TITLE
Is there a way for ox-hugo to place the html file (in the iframe src tag) in the hugo static folder? 

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#437]
follow up: is there a way for ox-hugo to place the html file (in the iframe src tag) in the hugo static folder? As it does with images for example.

_Originally posted by @sprajagopal in https://github.com/kaushalmodi/ox-hugo/issues/410#issuecomment-804976362_

**Comment by kaushalmodi** [comment]
>is there a way for ox-hugo to place the html file (in the iframe src tag) in the hugo static folder?

No, `ox-hugo` wouldn't know automatically which files need to be copied to the static folder.

For images, `ox-hugo` knows which files to copy because they are referenced using the Org image syntax.

The iframe tag example use as shown in https://github.com/kaushalmodi/ox-hugo/issues/410#issuecomment-757059705 is not parsed by `ox-hugo`. The contents in `#+begin_export html` are simply dumped into the exported Markdown files. So there's no auto-copying of html files.

**Comment by sprajagopal** [comment]
Got it. My use case was to figure out a way to use plotly. But I guess I'll find another way. Thanks!

**Comment by kaushalmodi** [comment]
Thanks. I will close this issue as this cannot be done in `ox-hugo`.
