### ISSUE TITLE
[Question]: Exporting markdown files via emacs batch mode

### ISSUE THREAD

**Issue by Silipwn** [kaushalmodi/ox-hugo#441]
Thanks for the awesome project :+1:

I was interested in automating the `hugo-export`  part via a CLI script. I tend to keep a set of different org files, so once the file is completed, I want to just run a script, which adds all the necessary info for `ox-hugo`. But the only part that still needs to be manually done is the exporting part.

So, I tried to use the `org-hugo-export-to-md` with 

`emacs test.org --batch --eval '(interactive) (org-hugo-export-to-md)'`

But the auto save feature `(.dir-locals.el)` causes conflicts while running the above command. 

Any suggestions on I should be running this?

**Comment by kaushalmodi** [comment]
Hello, 

The issue might be that you are running interactive from --eval?

You can check out the [Makefile](https://www.github.com/kaushalmodi/ox-hugo/tree/master/Makefile) I use for generating the ox-hugo website from the command line.. actually the site generation happens remotely on Netlify. 

You can see the --eval command I call in that Makefile.

**Comment by Silipwn** [comment]
That was quite helpful. Thanks for the help. :)
