### ISSUE TITLE
Allow for custom `tags` option keyswords to enhance interoperability with other projects

### ISSUE THREAD

**Issue by groakat** [kaushalmodi/ox-hugo#443]
Is it possible to define a variable that specifies which options keyword is being used for tags?

If I read the [documentation](https://ox-hugo.scripter.co/doc/tags-and-categories/#file-based-export) right, then currently using `#+hugo_tags` are the only way to define tags for hugo, if file-based export is used.

I am using `org-roam` to create and manage my notes and `ox-hugo` to export them to a website. `org-roam` relies on `#+roam_tags` which I think work the same as `#+hugo_tags`. I am fairly new to emacs, but I think the only option I have currently is to copy and paste the `#+roam_tags` to also have `#+hugo_tags`, potentially as a post-save-hook. 

It would be much easier if [`:hugo-tags`](https://github.com/kaushalmodi/ox-hugo/blob/805f18b44b113f2f69c491642c53d47ebe9755e1/ox-hugo.el#L3288) were not hard-coded, but configurable, so I can use `#+roam_tags` as tags in both `org-roam` and `ox-hugo`.

I am willing to try to provide a patch with this feature, but I have not contributed to an emacs code-base before. So I first need to figure out how I can load a custom `ox-hugo.el` file in my emacs :joy: . But it might be straight-forward if `plist` contains all options of a file and not just `ox-hugo` specific ones.

**Comment by kaushalmodi** [comment]
@groakat This is a kind of an old project; the first commit was in Feb 2017. Over the time, it has gained a log of `#+hugo_*` keywords. Whatever decision is taken has to be done in a consistent manner.

@jethrokuan Do you have any suggestions on managing both `#+hugo_tags` and `#+roam_tags`? If you use `ox-hugo`, how do you manage those?

**Comment by jethrokuan** [comment]
> @jethrokuan Do you have any suggestions on managing both #+hugo_tags and #+roam_tags? If you use ox-hugo, how do you manage those?

In Org-roam v1, it's possible to add an extraction option to read from `#+hugo_tags` instead of `#+roam_tags`:

```
(defun org-roam--extract-tags-hugo (_file)
  "Extract tags from the current buffer's \"#roam_tags\" global property."
  (let* ((prop (or (cdr (assoc "HUGO_TAGS" (org-roam--extract-global-props '("HUGO_TAGS"))))
                   "")))
    (condition-case nil
        (split-string-and-unquote prop)
      (error
       (progn
         (lwarn '(org-roam) :error
                "Failed to parse tags for buffer: %s. Skipping"
                (or org-roam-file-name
                    (buffer-file-name)))
         nil)))))

(setq org-roam-tag-sources '(hugo))
```

In v2, this customizability is removed: tags are derived from Org tags, or `#+filetags`.

I use ox-hugo, but don't use tagging.

**Comment by kaushalmodi** [comment]
@jethrokuan Thanks!

I remember there was something that didn't allow me to use `#+filetags` for tags in file based export. I'll revisit that.

**Comment by bphenriques** [comment]
> @jethrokuan Thanks!
> 
> I remember there was something that didn't allow me to use `#+filetags` for tags in file based export. I'll revisit that.

Do you recall what was the obstacle? For org-roam v2, for file-based exports, we need to set both `#+filetags` and `#+hugo-tags`. Trying to figure out a workaround 🤔

**Comment by bphenriques** [comment]
I created a workaround by having a save hook that ensures that `HUGO_TAGS` is synced with `FILETAGS` (required by org-roam v2):
```elisp
;; ox-hugo file based exports rely on "#+HUGO_TAGS" and not on "#+FILETAGS" as org-roam does. This syncs both values.
;; If filetags is set, overwrite hugo_tags with its values.
;; If filetags is not set but hugo_tags is, set filetags with the value of hugo_tags.
(defun sync-hugo-tags ()
  (interactive)
  (let ((filetags (car (cdr (car (org-collect-keywords '("filetags"))))))
        (hugotags (car (cdr (car (org-collect-keywords '("HUGO_TAGS")))))))
    (if filetags
        (org-roam-set-keyword "hugo_tags" filetags)
        (when hugotags (org-roam-set-keyword "filetags" hugotags)))))

(add-hook 'before-save-hook 'sync-hugo-tags) ;; Using before so that it works during the capture process.
```

It saves me trouble of manually filling it up. It is not an ideal solution but it is not disruptive in my work-flow ([source](https://github.com/bphenriques/dotfiles/blob/b495589484500b8ed388fec68ee34193681690cb/home/config/emacs/doom/%2Borg-roam.el#L24)).

Note that by use-case is _per-file_ flow.

**Comment by kaushalmodi** [comment]
@groakat I have add support for parsing of `#+filetags` for file-based exports in https://github.com/kaushalmodi/ox-hugo/pull/492. It doesn't tag support for Org Roam as you suggested. But if you have updated to Org Roam v2 (from what I understand, v2 uses `#+filetags` by default), this issue will be fixed for you too.

I wanted to avoid adding a defcustom just for specifying the keywords for tags and categories.

**Comment by bphenriques** [comment]
The workaround I mentioned [above](https://github.com/kaushalmodi/ox-hugo/issues/443#issuecomment-1003687847) is no longer required with the latest version as it supports `#+filetags`.

**Comment by kaushalmodi** [comment]
Thanks all. I will close this issue given that Org Roam v2 works happily with this change.
