### ISSUE TITLE
Option for not using the TODO-Draft functionality

### ISSUE THREAD

**Issue by seshaljain** [kaushalmodi/ox-hugo#445]
## Actual Behavior
In the subtree workflow, setting an item as TODO makes it a draft post

## Expected Behavior
It should be possible to publish a TODO list. Since Org's TODO/DONE has higher priority, it is not possible to publish TODO posts since they become drafts.

**Comment by kaushalmodi** [comment]
Sorry, your suggested change affects the core reason why I started with ox-hugo.. a very easy Org style way to mark posts as in-progress or done. 

If you can expand more on what you need to get done, I can suggest some alternatives.

**Comment by kaushalmodi** [comment]
>It should be possible to publish a TODO list. Since Org's TODO/DONE has higher priority, it is not possible to publish TODO posts since they become drafts.

You can set the [`buildDrafts`](https://gohugo.io/getting-started/configuration/#builddrafts-false) configuration in Hugo's config.toml to true.
