### ISSUE TITLE
Question: How to set arbitrary Hugo MD properties?

### ISSUE THREAD

**Issue by anonimitoraf** [kaushalmodi/ox-hugo#450]
I'm using the theme https://themes.gohugo.io/themes/github-style which supports "pinning" of particular posts via: https://themes.gohugo.io/themes/github-style#pin-post

My question is: How do I do this in org-mode?

I've tried:
 `#+PIN: true`

and

```
:PROPERTIES:
:PIN: true
```

to no avail

**Comment by kaushalmodi** [comment]
Hello, 

Check out https://ox-hugo.scripter.co/doc/custom-front-matter/ 

For your example, you'd want:

```org
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :pin true
:END:
```

**Comment by anonimitoraf** [comment]
Lighting fast response! Thanks for this repo and for your answer!
