### ISSUE TITLE
Double backslashes (\\) are not properly escaped in Latex

### ISSUE THREAD

**Issue by lizhuohua** [kaushalmodi/ox-hugo#458]
When a Latex expression contains double backslashes (`\\`), the output markdown is not properly escaped, for example the org file:

`\[\sum_{\substack{0<i<m\\0<j<n}}\]`

## Actual Behavior
The generated markdown is `\\[\sum\_{\substack{0<i<m\\0<j<n}}\\]`

Then the markdown parser will generate HTML like this `\[\sum_{\substack{0&lt;i&lt;m\0&lt;j&lt;n}}\]`

This is rendered by MathJax like this:

![image](https://user-images.githubusercontent.com/13259389/129144042-5d9f9073-845c-47f6-9120-9296e88c07dd.png)

## Expected Behavior

The double backslashes `\\` should be escaped as `\\\\`, so the generated markdown should be `\\[\sum\_{\substack{0<i<m\\\\0<j<n}}\\]`

The HTML should be `\[\sum_{\substack{0&lt;i&lt;m\\0&lt;j&lt;n}}\]`

The rendered math should be:

![image](https://user-images.githubusercontent.com/13259389/129144254-ecf657f4-3cdd-41ae-9b62-64a7efaafeb5.png)

## How to Reproduce the Issue

Export the example org file into markdown, and rendered using MathJax

### Example Org File

`\[\sum_{\substack{0<i<m\\0<j<n}}\]`

### Generated Markdown File or Error

`\\[\sum\_{\substack{0<i<m\\0<j<n}}\\]`

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.16.0)
     of 2021-08-02 (commit b72f88518b89560accf740a4548368863e6238e0)

## Org Version

    Org mode version 9.4.6 (9.4.6-11-g1ee52c-elpa @ /home/li/.emacs.d/elpa/28.0/develop/org-20210726/)

## Hugo Version

    hugo v0.86.1+extended linux/amd64 BuildDate=unknown

### Org `load-path` shadows

**Warning**: Possible mixed installation of Org

    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-io hides /usr/share/emacs/28.0.50/lisp/org/ob-io
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-colview hides /usr/share/emacs/28.0.50/lisp/org/org-colview
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-screen hides /usr/share/emacs/28.0.50/lisp/org/ob-screen
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-table hides /usr/share/emacs/28.0.50/lisp/org/ob-table
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-maxima hides /usr/share/emacs/28.0.50/lisp/org/ob-maxima
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-man hides /usr/share/emacs/28.0.50/lisp/org/ox-man
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-org hides /usr/share/emacs/28.0.50/lisp/org/ox-org
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-lilypond hides /usr/share/emacs/28.0.50/lisp/org/ob-lilypond
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-footnote hides /usr/share/emacs/28.0.50/lisp/org/org-footnote
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-latex hides /usr/share/emacs/28.0.50/lisp/org/ox-latex
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-python hides /usr/share/emacs/28.0.50/lisp/org/ob-python
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-macro hides /usr/share/emacs/28.0.50/lisp/org/org-macro
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-mobile hides /usr/share/emacs/28.0.50/lisp/org/org-mobile
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-org hides /usr/share/emacs/28.0.50/lisp/org/ob-org
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-R hides /usr/share/emacs/28.0.50/lisp/org/ob-R
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-ref hides /usr/share/emacs/28.0.50/lisp/org/ob-ref
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-publish hides /usr/share/emacs/28.0.50/lisp/org/ox-publish
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-css hides /usr/share/emacs/28.0.50/lisp/org/ob-css
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-processing hides /usr/share/emacs/28.0.50/lisp/org/ob-processing
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-habit hides /usr/share/emacs/28.0.50/lisp/org/org-habit
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-eww hides /usr/share/emacs/28.0.50/lisp/org/ol-eww
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-macs hides /usr/share/emacs/28.0.50/lisp/org/org-macs
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-J hides /usr/share/emacs/28.0.50/lisp/org/ob-J
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-calc hides /usr/share/emacs/28.0.50/lisp/org/ob-calc
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-clock hides /usr/share/emacs/28.0.50/lisp/org/org-clock
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-bibtex hides /usr/share/emacs/28.0.50/lisp/org/ol-bibtex
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-texinfo hides /usr/share/emacs/28.0.50/lisp/org/ox-texinfo
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-makefile hides /usr/share/emacs/28.0.50/lisp/org/ob-makefile
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-js hides /usr/share/emacs/28.0.50/lisp/org/ob-js
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-w3m hides /usr/share/emacs/28.0.50/lisp/org/ol-w3m
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-forth hides /usr/share/emacs/28.0.50/lisp/org/ob-forth
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-attach-git hides /usr/share/emacs/28.0.50/lisp/org/org-attach-git
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-scheme hides /usr/share/emacs/28.0.50/lisp/org/ob-scheme
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-eval hides /usr/share/emacs/28.0.50/lisp/org/ob-eval
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-faces hides /usr/share/emacs/28.0.50/lisp/org/org-faces
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol hides /usr/share/emacs/28.0.50/lisp/org/ol
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-protocol hides /usr/share/emacs/28.0.50/lisp/org/org-protocol
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-hledger hides /usr/share/emacs/28.0.50/lisp/org/ob-hledger
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-emacs-lisp hides /usr/share/emacs/28.0.50/lisp/org/ob-emacs-lisp
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-attach hides /usr/share/emacs/28.0.50/lisp/org/org-attach
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-mscgen hides /usr/share/emacs/28.0.50/lisp/org/ob-mscgen
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-groovy hides /usr/share/emacs/28.0.50/lisp/org/ob-groovy
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-src hides /usr/share/emacs/28.0.50/lisp/org/org-src
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-ruby hides /usr/share/emacs/28.0.50/lisp/org/ob-ruby
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-eshell hides /usr/share/emacs/28.0.50/lisp/org/ob-eshell
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-C hides /usr/share/emacs/28.0.50/lisp/org/ob-C
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-sass hides /usr/share/emacs/28.0.50/lisp/org/ob-sass
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-shen hides /usr/share/emacs/28.0.50/lisp/org/ob-shen
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob hides /usr/share/emacs/28.0.50/lisp/org/ob
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-shell hides /usr/share/emacs/28.0.50/lisp/org/ob-shell
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-lisp hides /usr/share/emacs/28.0.50/lisp/org/ob-lisp
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-sql hides /usr/share/emacs/28.0.50/lisp/org/ob-sql
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-timer hides /usr/share/emacs/28.0.50/lisp/org/org-timer
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-goto hides /usr/share/emacs/28.0.50/lisp/org/org-goto
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-plot hides /usr/share/emacs/28.0.50/lisp/org/org-plot
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-plantuml hides /usr/share/emacs/28.0.50/lisp/org/ob-plantuml
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-capture hides /usr/share/emacs/28.0.50/lisp/org/org-capture
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-feed hides /usr/share/emacs/28.0.50/lisp/org/org-feed
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-gnuplot hides /usr/share/emacs/28.0.50/lisp/org/ob-gnuplot
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org hides /usr/share/emacs/28.0.50/lisp/org/org
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-lua hides /usr/share/emacs/28.0.50/lisp/org/ob-lua
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-entities hides /usr/share/emacs/28.0.50/lisp/org/org-entities
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-fortran hides /usr/share/emacs/28.0.50/lisp/org/ob-fortran
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-ditaa hides /usr/share/emacs/28.0.50/lisp/org/ob-ditaa
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-stan hides /usr/share/emacs/28.0.50/lisp/org/ob-stan
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-vala hides /usr/share/emacs/28.0.50/lisp/org/ob-vala
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox hides /usr/share/emacs/28.0.50/lisp/org/ox
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-dot hides /usr/share/emacs/28.0.50/lisp/org/ob-dot
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-icalendar hides /usr/share/emacs/28.0.50/lisp/org/ox-icalendar
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-beamer hides /usr/share/emacs/28.0.50/lisp/org/ox-beamer
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-archive hides /usr/share/emacs/28.0.50/lisp/org/org-archive
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-haskell hides /usr/share/emacs/28.0.50/lisp/org/ob-haskell
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-tangle hides /usr/share/emacs/28.0.50/lisp/org/ob-tangle
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-ascii hides /usr/share/emacs/28.0.50/lisp/org/ox-ascii
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-agenda hides /usr/share/emacs/28.0.50/lisp/org/org-agenda
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-gnus hides /usr/share/emacs/28.0.50/lisp/org/ol-gnus
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-list hides /usr/share/emacs/28.0.50/lisp/org/org-list
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-mouse hides /usr/share/emacs/28.0.50/lisp/org/org-mouse
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-id hides /usr/share/emacs/28.0.50/lisp/org/org-id
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-lint hides /usr/share/emacs/28.0.50/lisp/org/org-lint
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-asymptote hides /usr/share/emacs/28.0.50/lisp/org/ob-asymptote
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-version hides /usr/share/emacs/28.0.50/lisp/org/org-version
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-perl hides /usr/share/emacs/28.0.50/lisp/org/ob-perl
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-matlab hides /usr/share/emacs/28.0.50/lisp/org/ob-matlab
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-rmail hides /usr/share/emacs/28.0.50/lisp/org/ol-rmail
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-info hides /usr/share/emacs/28.0.50/lisp/org/ol-info
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-abc hides /usr/share/emacs/28.0.50/lisp/org/ob-abc
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-num hides /usr/share/emacs/28.0.50/lisp/org/org-num
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-html hides /usr/share/emacs/28.0.50/lisp/org/ox-html
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-indent hides /usr/share/emacs/28.0.50/lisp/org/org-indent
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-comint hides /usr/share/emacs/28.0.50/lisp/org/ob-comint
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-odt hides /usr/share/emacs/28.0.50/lisp/org/ox-odt
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-pcomplete hides /usr/share/emacs/28.0.50/lisp/org/org-pcomplete
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-octave hides /usr/share/emacs/28.0.50/lisp/org/ob-octave
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-core hides /usr/share/emacs/28.0.50/lisp/org/ob-core
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ox-md hides /usr/share/emacs/28.0.50/lisp/org/ox-md
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-table hides /usr/share/emacs/28.0.50/lisp/org/org-table
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-ledger hides /usr/share/emacs/28.0.50/lisp/org/ob-ledger
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-picolisp hides /usr/share/emacs/28.0.50/lisp/org/ob-picolisp
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-refile hides /usr/share/emacs/28.0.50/lisp/org/org-refile
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-docview hides /usr/share/emacs/28.0.50/lisp/org/ol-docview
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-mhe hides /usr/share/emacs/28.0.50/lisp/org/ol-mhe
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-compat hides /usr/share/emacs/28.0.50/lisp/org/org-compat
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-element hides /usr/share/emacs/28.0.50/lisp/org/org-element
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-ctags hides /usr/share/emacs/28.0.50/lisp/org/org-ctags
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-keys hides /usr/share/emacs/28.0.50/lisp/org/org-keys
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-inlinetask hides /usr/share/emacs/28.0.50/lisp/org/org-inlinetask
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-duration hides /usr/share/emacs/28.0.50/lisp/org/org-duration
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-sqlite hides /usr/share/emacs/28.0.50/lisp/org/ob-sqlite
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-eshell hides /usr/share/emacs/28.0.50/lisp/org/ol-eshell
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-awk hides /usr/share/emacs/28.0.50/lisp/org/ob-awk
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-ebnf hides /usr/share/emacs/28.0.50/lisp/org/ob-ebnf
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-lob hides /usr/share/emacs/28.0.50/lisp/org/ob-lob
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-datetree hides /usr/share/emacs/28.0.50/lisp/org/org-datetree
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-irc hides /usr/share/emacs/28.0.50/lisp/org/ol-irc
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-coq hides /usr/share/emacs/28.0.50/lisp/org/ob-coq
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-clojure hides /usr/share/emacs/28.0.50/lisp/org/ob-clojure
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-install hides /usr/share/emacs/28.0.50/lisp/org/org-install
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-crypt hides /usr/share/emacs/28.0.50/lisp/org/org-crypt
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ol-bbdb hides /usr/share/emacs/28.0.50/lisp/org/ol-bbdb
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-sed hides /usr/share/emacs/28.0.50/lisp/org/ob-sed
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-ocaml hides /usr/share/emacs/28.0.50/lisp/org/ob-ocaml
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-tempo hides /usr/share/emacs/28.0.50/lisp/org/org-tempo
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-java hides /usr/share/emacs/28.0.50/lisp/org/ob-java
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-exp hides /usr/share/emacs/28.0.50/lisp/org/ob-exp
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/ob-latex hides /usr/share/emacs/28.0.50/lisp/org/ob-latex
    /home/li/.emacs.d/elpa/28.0/develop/org-20210726/org-loaddefs hides /usr/share/emacs/28.0.50/lisp/org/org-loaddefs

Study the output of `M-x list-load-path-shadows`.

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"post"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by lizhuohua** [comment]
Hi, I have some questions about the function `org-blackfriday-escape-chars-in-equation`.

One thing I don't understand is, why we need to replace `\\` at EOL with `\\\\\\`, which results in `\\\`? In Latex, we only need double backslashes `\\` for a new line.

Can we simply replace all the `\\` (not necessarily at EOL) with `\\\\`?

**Comment by JPYamamoto** [comment]
Hey @lizhuohua I see that you have a commit that solves this problem. I'm facing the same issue, so I was wondering if you could open a pull-request and maybe your solution can help others. Thanks!

**Comment by lizhuohua** [comment]
@JPYamamoto Sure, I have been using my commit for several weeks and it seems to work fine. I will try to send a pull-request today.
