### ISSUE TITLE
Leading `/` in img leads to broken images if the website's has relative path

### ISSUE THREAD

**Issue by bphenriques** [kaushalmodi/ox-hugo#460]
## Actual Behavior

Images exported to `/static/ox-hugo/*` are exported to markdown with a leading `/` which breaks my current workflow when the website is hosted on a subpath, for example the only image present at https://bphenriques.github.io/knowledge-base (hosted on Github Pages).

Specifically, ox-hugo exports:
```
#+ATTR_HTML: :alt Connecting insights dots leads to building knowledge
[[file:from-data-to-knowledge.png]]
```

To:
```
{{< figure src="/ox-hugo/from-data-to-knowledge.png" alt="Connecting insights dots leads to building knowledge" >}}
```

Which in turn hugo generates:
```html
<img src="/ox-hugo/from-data-to-knowledge.png" alt="Connecting insights dots leads to building knowledge">
```

Leading to broken reference to a image.

## Expected Behavior

Following the Actual behaviour, `HTML` renders correctly images correctly if I omit the leading `/` in the `<img src=...>`:
```html
<img src="ox-hugo/from-data-to-knowledge.png" alt="Connecting insights dots leads to building knowledge">
```

I back-tracked how the markup is generated and this can be fixed if the markdown file omits the leading `/`:
```
{{< figure src="ox-hugo/from-data-to-knowledge.png" alt="Connecting insights dots leads to building knowledge" >}}
```

From the [docs](https://ox-hugo.scripter.co/doc/images-in-content/#images-and-regular-pages), the leading `/ox-hugo/` prefix is added automatically. The resolution seems to be just to omit the leading `/` and be solely `ox-hugo/`.

The devil is in the details but it seems to be a easy fix, or at most can the leading `/` be a configurable behaviour (unless there is an existing workaround)?

Thank you in advance!

### Example Org File

Snippet of my [file](https://raw.githubusercontent.com/bphenriques/knowledge-base/master/org/_index.org):
```
#+TITLE: Home
#+HUGO_SECTION:

#+ATTR_HTML: :alt Connecting insights dots leads to building knowledge
[[file:from-data-to-knowledge.png]]

```
### Generated Markdown File or Error

```
{{< figure src="/ox-hugo/from-data-to-knowledge.png" alt="Connecting insights dots leads to building knowledge" >}}
```

**Comment by kaushalmodi** [comment]
Hello, this has been a known limitation with the default figure shortcode that ships with Hugo. See https://github.com/gohugoio/hugo/issues/4562#issuecomment-378314838 where I describe this issue in detail with a proposed modification of the `figure` shortcode. If you use that modified shortcode in your site layout, this issue will get resolved.

**Comment by bphenriques** [comment]
Thank you for the swift response !

I thought it was ox-hugo related as it is the one generating the `*.md` counterpart , why🤔  I will try out the short-code and close the ticket
