### ISSUE TITLE
Create an org block for custom html?

### ISSUE THREAD

**Issue by karthink** [kaushalmodi/ox-hugo#463]
I have this boilerplate html I need around text for a collapsible section:

```html
<div class="wrap-collabsible">
<input id="collapsible" class="toggle" type="checkbox">
<label for="collapsible" class="lbl-toggle"> BLOCK TITLE HERE </label>
<div class="collapsible-content">
<div class="content-inner">
<p>

LOTS OF TEXT HERE.

</p>
</div>
</div>
</div>
```

I want to avoid using `#+begin_export html` blocks since I want to write the "LOTS OF TEXT HERE" with org-syntax. What is the best way of getting this to work with ox-hugo?

**Comment by kaushalmodi** [comment]
Hello,

Ox-hugo has support for "summary" and "details" tags which are an HTML inbuilt feature for collapsible drawers. 

Here are docs and its test page:

- https://ox-hugo.scripter.co/doc/details-and-summary/
- https://ox-hugo.scripter.co/test/posts/details-and-summary/ (Markdown source)[https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/details-and-summary.md]

---

_As I was typing this, I realized that a regression crept in at some point which doesn't render the export Markdown on the one line of summary or details. I'll fix that some time next week._

**Comment by karthink** [comment]
Successfully used the details block [here](https://karthinks.com/software/avy-can-do-anything).

**Comment by kaushalmodi** [comment]
I am hitting some limitation with the Markdown processing in Hugo regarding the processing of markup in the first line of summary. See https://github.com/kaushalmodi/ox-hugo/issues/464#issuecomment-950241055 for details.

> BTW, what did you have to do in the org source to get the grey CSS block
around this text in the page you linked:

That's from [the CSS I used in my onyx hugo theme][1] for the ox-hugo docs.

> Successfully used the details block here.

That's an amazingly written post! Thanks for sharing.

[1]: https://github.com/kaushalmodi/hugo-onyx-theme/blob/551d2bcc0c6c2ea0d8611b7e2e1c81e7ef2fd7ed/static/css/onyx.css#L378

**Comment by kaushalmodi** [comment]
Seeing that the summary/details special Org blocks are working for your usecase, I am closing this issue. Feel free to comment further in this thread even after it's closed.
