### ISSUE TITLE
backtrace-get-frames being renamed

### ISSUE THREAD

**Issue by yanboyang713** [kaushalmodi/ox-hugo#469]
Hello All,

I am using GNU Emacs 27.2, looks like the function name is changed.

When I followed this [Link](https://www.yanboyang.com/hugo/#write-blog-with-emacs-and-ox-hugo-package) to Auto-export the whole project on Saving. I got the ERROR msg below.

```
Error (after-save-hook): Error running hook "org-hugo-export-wim-to-md-after-save" because: (void-function backtrace-get-frames)
```

Looks like this issue lead by the backtrace-get-frames function being renamed.

![](https://lh5.googleusercontent.com/neJYNs3YmSw7MIMZ0zQdznxx-NBwzMgzOFCjHt-1uhtEIw7uMeroUFuiSCERb66HMTl764mpVxLqi10C2z0OOpEvjpAxqS01dsfemD4C1QmD-8L72swKDakgoezEkomTzPiMzsso)

## Ox-Hugo Debug Information
![](https://emacs-china.org/uploads/default/original/3X/0/5/058249b6b5e1291bacabeb50fb6df0de8f9643b7.png)

**Comment by kaushalmodi** [comment]
Hello,

ox-hugo doesn't call that function. 

Which Org version are you using?

**Comment by kaushalmodi** [comment]
Googling on this error, I found this:

https://github.com/hlissner/doom-emacs/issues/5721#issuecomment-958342837

So looks like org-element.el (which is an internal Org library) is calling that function. 

Also I see this commit on Org main branch 4 days ago: https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=d3836c1a13ab4f1ca991144bb09c4265e0aa4433

I have to guess that you are using the "devel" version of Org i.e. built from its main branch. If so, can you pull from its main branch, rebuild Org, restart emacs and see if this issue still persists?

**Comment by yanboyang713** [comment]
Thanks @kaushalmodi 

Yes, this issue revolved when I (unpin! org-mode).

Thanks :)
