### ISSUE TITLE
Code shortcode exported with escaped characters 

### ISSUE THREAD

**Issue by YoussefBouzekri** [kaushalmodi/ox-hugo#471]
I am using the code shortcode, here is what I have in my configuration
```
{{< code language="toml" title="mpd's configuration" id="1" expand="Show" collapse="Hide"  >}}

music_directory "/home/youssef/music/"
playlist_directory "/home/youssef/.config/mpd/playlists"
db_file "/home/youssef/.config/mpd/mpd.db"
log_file "/home/youssef/.config/mpd/mpd.log"
pid_file "/home/youssef/.config/mpd/mpd.pid"
state_file "/home/youssef/.config/mpd/mpdstate"
audio_output {
	type "pulse"
	name "pulse audio"
}
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

bind_to_address "127.0.0.1"
port "6601"
{{< /code >}}
```
but it shows up like this in my blog using the hello-friend theme
![image](https://user-images.githubusercontent.com/77839865/143574869-ad65b0e5-6243-42a7-8c3c-00f3983ac6b6.png)
as you can see, a lot of characters are escaped when they shouldn't be like that. 

if I use the usual org format for source blocks it gets exported just fine:
```
#+begin_src toml
music_directory "/home/youssef/music/"
playlist_directory "/home/youssef/.config/mpd/playlists"
db_file "/home/youssef/.config/mpd/mpd.db"
log_file "/home/youssef/.config/mpd/mpd.log"
pid_file "/home/youssef/.config/mpd/mpd.pid"
state_file "/home/youssef/.config/mpd/mpdstate"
audio_output {
	type "pulse"
	name "pulse audio"
}
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

bind_to_address "127.0.0.1"
port "6601"
#+end_src
```
to this
![image](https://user-images.githubusercontent.com/77839865/143575221-e0ecc846-e884-426d-a1e2-c4c6de07de64.png)

**Comment by kaushalmodi** [comment]
> if I use the usual org format for source blocks it gets exported just fine

That's exactly right. The whole point of ox-hugo was to to be able to export normal Org format text to blog posts. 

Parsing of Hugo shortcodes isn't officially supported in Org source. 

Think if it this way: If some non-Org text like Hugo shortcodes doesn't get exported using inbuilt ox-html, it wouldn't get exported using ox-hugo either. 

Let me know if doing the same code export the Org way solves this problem:

- Use `#+begin_src toml .. #+end_src`
- Use `#+caption` for the caption
- Use `#+name` to generate a hyperlink to the src block

See the ox-hugo tests in this repo for hundreds of code block examples.

**Comment by kaushalmodi** [comment]
See this link for src block related tests: https://ox-hugo.scripter.co/test/tags/src-block

When you click on each of the tests, you will see the link to the Org source and also the Markdown that got exported from that Org test.

**Comment by YoussefBouzekri** [comment]
Thanks for the help !
