### ISSUE TITLE
Support custom shortcode with images

### ISSUE THREAD

**Issue by behaghel** [kaushalmodi/ox-hugo#474]
The use-case i am after is to enable automatic setup of responsive images. I initially tried to hook it into the md -> html via a file in `layouts/_default/_markup/render-image.html` but ox-hugo use the built-in `figure` shortcode. I then tried to override this shortcode with my definition but it didn't work (override ignored). I understand it should just work but still this solution means every image gets the treatment. It's not ideal. I ended up patching ox-hugo to support `:shortcode` attribute like this:

```
#+attr_html: :class right :shortcode responsive-img
[[file:my-image.jpg]]
```

I'd be curious to hear your thoughts about this problem. If you would welcome a PR with such solution, I'll happily do so.

**Comment by kaushalmodi** [comment]
> I then tried to override this shortcode with my definition but it didn't work (override ignored).

That's strange because I override the built-in figure shortcode in the ox-hugo doc site, and it just works. But it's understood that you wouldn't want the same modified figure shortcode for all images. 

> I ended up patching ox-hugo to support :shortcode attribute like this:

Can you share the patch? I am curious to know how you would pass the attributes to any arbitrary figure-like shortcode a user might have. 

I am not sure if you are aware of the shortcode support in ox-hugo: https://github.com/kaushalmodi/ox-hugo/issues/126. That link has links to the tests for paired and unpaired Hugo shortcodes. That method will allow injecting a shortcode with any name and number of attributes.

**Comment by behaghel** [comment]
Thanks @kaushalmodi for the swift reply!

This is the change: https://github.com/behaghel/ox-hugo/commit/e14503d7e748d8d4f87e1043d95e318bd0cf6dc9

By the way, I tried again to override the built-in `figure` shortcode and it worked. So one solution is to do some magic: e.g. I got a good enough solution working where a class `responsive` trigger a different rendering in `figure`.

But now I have reviewed #126 and I could come up with this which is perfect:

```
#+html: {{< responsive-img src="my-image.jpg" class="right" >}}
```

Therefore I am closing this issue. Thanks!

**Comment by kaushalmodi** [comment]
> I got a good enough solution working where a class responsive trigger a different rendering in figure

That's an awesome solution! That way you have your Org source mostly exportable to a different format like tex/pdf or html as well. 

---

> #+html: {{< responsive-img src="my-image.jpg" class="right" >}}

While this works, I personally don't prefer this as it's locking some pieces of your source to be consumed only by Hugo. If you export the source using ox-html, it will have that shortcode show up on a raw HTML export as well. So, as I mention in the other issue as well, this would be my last resort.

**Comment by kaushalmodi** [comment]
@behaghel I just added this long overdue doc: https://ox-hugo.scripter.co/doc/shortcodes/

> `#+html: {{< responsive-img src="my-image.jpg" class="right" >}}`

As of the latest commit on `main` branch, this will also work:

```
#+hugo: {{< responsive-img src="my-image.jpg" class="right" >}}
```
