### ISSUE TITLE
Could NOT export org mode content as file block

### ISSUE THREAD

**Issue by yanboyang713** [kaushalmodi/ox-hugo#478]
Hello,

I try to export **org mode** content as an example block or source code block, but both methods do NOT work.

```
#+begin_example
* First level heading
** Secondary heading
*** Level 3 heading
#+end_example
```

```
#+begin_src 
* First level heading
** Secondary heading
*** Level 3 heading
#+end_src
```

Any method can export **org mode** content as a file block?

Expected Markdown output:
```md
```file
* First level heading
** Secondary heading
*** Level 3 heading
```
```

**Comment by kaushalmodi** [comment]
You need to escape the asterisks with a comma. 

```
#+begin_src org
,* First level heading
,** Secondary heading
,*** Level 3 heading
#+end_src
```

**Comment by kaushalmodi** [comment]
It's unrelated to ox-hugo: https://orgmode.org/manual/Literal-Examples.html

**Comment by kaushalmodi** [comment]
> Any method can export org mode content as a file block?

What's a "file block"?

**Comment by kaushalmodi** [comment]
In any case, you can do this:

```
#+begin_src file
,* First level heading
,** Secondary heading
,*** Level 3 heading
#+end_src
```

That will export to:

````
```file
* First level heading
** Secondary heading
*** Level 3 heading
```
````

**Comment by yanboyang713** [comment]
Hello @kaushalmodi ,

Good day to you and thanks for your reply.

Yes, add a comma before the asterisks, revolved this issue.

Thanks for your link.

Thanks a lot,
Boyang

**Comment by kaushalmodi** [comment]
Thanks for confirming. I'll close this issue then.

**Comment by finex** [comment]
> You need to escape the asterisks with a comma.
> 
> ```
> #+begin_src org
> ,* First level heading
> ,** Secondary heading
> ,*** Level 3 heading
> #+end_src
> ```

Hi, I've seen that the `,` also escape `#`. is the `,` documented somewhere?

**Comment by kaushalmodi** [comment]
> Hi, I've seen that the , also escape #. is the , documented somewhere?

Yes, see [(org) Literal Examples](https://orgmode.org/manual/Literal-Examples.html)

---

The best way to access Org/Emacs manuals is using `info` from within emacs:

![image](https://user-images.githubusercontent.com/3578197/148252865-5e6f1c07-dd25-4656-a260-56fd08e6b951.png)

**Comment by finex** [comment]
Great, it's an Org-mode feature, not an ox-hugo one. Thank you very much @kaushalmodi :-)
