### ISSUE TITLE
Allow adding custom front matter to posts

### ISSUE THREAD

**Issue by punchagan** [kaushalmodi/ox-hugo#48]
Some themes allow using custom front matter fields, other than the standard ones -- for example [this theme][1] ([screenshot][2]) allows marking posts as `best` posts

There could be a convention for the headline properties to add these custom fields - something like `:EXPORT_FRONT_MATTER_{KEY}: value`  exporting to `key = "value"`

[1]: https://github.com/fuegowolf/cocoa-eh-hugo-theme
[2]: https://raw.githubusercontent.com/fuegowolf/cocoa-eh-hugo-theme/master/images/screenshot.png

**Comment by kaushalmodi** [comment]
I don't know how to make the `KEY` portion in `:EXPORT_FRONT_MATTER_{KEY}: value` dynamic. My understanding is that all the backend keywords need to be defined in the `:options-alist` section of the definition.

This, though, has been on my list. I was thinking of implementing the same way `:HUGO_MENU` is implemented:

```org
** Menu Meta Data in TOML Front Matter
:PROPERTIES:
:EXPORT_HUGO_MENU: :menu "something here" :weight 80 :parent posts :identifier foo1
:END:
```

Along the similar lines, we could have `:HUGO_CUSTOM_FRONT_MATTER`:

```org
** Menu Meta Data in TOML Front Matter
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :foo bar :baz zoo
:END:
```

I would then parse that using a very similar (generalized) version of [this][1].

[1]: https://github.com/kaushalmodi/ox-hugo/blob/c5588d5548a142a5afbc7c9b9869660eb2f9dc04/ox-hugo.el#L614-L626

Planning to tackle https://github.com/kaushalmodi/ox-hugo/issues/37 the same way.

WDYT?

**Comment by punchagan** [comment]
I wasn't aware that backend keywords need to be defined in the `:options-alist`, and I hadn't yet gotten to looking at the Menu front matter implementation. 

This seems like a reasonable way of doing it, especially given that another feature is already using this format/syntax.

**Comment by kaushalmodi** [comment]
I have implemented this in https://github.com/kaushalmodi/ox-hugo/commit/8c9767706515a62ff9431cac0513c590ee7f9c15

Check out the example in that commit. You can close this issue if this works for you.

**Comment by punchagan** [comment]
That was quick, and works beautifully! Thanks!
