### ISSUE TITLE
Unable to resolve link when exporting org file with roam links

### ISSUE THREAD

**Issue by patrolli** [kaushalmodi/ox-hugo#483]
## Actual Behavior
I have an org file A.org and insert roam links like `[[id:434dbbcf-ede9-4315-a131-e6616092c070][B]`, which refers to another org file `B.org`. When exporting the whole org file into md file, the error "Unable to resolve link:  id:434dbbcf-ede9-4315-a131-e6616092c070".  

## Expected Behavior
Can export the org file with roam id links in it. And show a cross-link in the md file.

## How to Reproduce the Issue
1. Using org-roam to capture two org files A.org and B.org. The ID property will be insert at the beggening of the file.
2. Insert a link of file(node) B in A.org, by using `org-roam-node-insert`.
3. Using ox-hugo to export the whole buffer of org file A.  
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
     of 2021-12-10 (commit 6e865a7171d80cd91b54c6d71b88d960b920abe3)

## Org Version

    Org mode version 9.5.1 (release_9.5.1-15-gdb4805 @ /usr/share/emacs/29.0.50/lisp/org/)

## Hugo Version

    hugo v0.89.4+extended linux/amd64 BuildDate=unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"post"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
Hello, 

> Using org-roam to capture two org files A.org and B.org. The ID property will be insert at the beggening of the file.

Can you provide minimal examples of the 2 Org files as modified by org roam?

Also, do those files export without error when exporting to HTML?

**Comment by ChloeZhou1997** [comment]
> Hello,
> 
> > Using org-roam to capture two org files A.org and B.org. The ID property will be insert at the beggening of the file.
> 
> Can you provide minimal examples of the 2 Org files as modified by org roam?
> 
> Also, do those files export without error when exporting to HTML?

Hi, I am having the same issue. What kind of minimal example do you need? Org roam file is just org file with unique id and we can refer to a different id when writing the notes. Typically, I can reference orgfile A with orgfile B using link like this: `[[id:5B11FCD4-EDF1-4382-81C9-C6A9CFF280E6][infinite loop]`but they won't be converted to markdown style correctly.

**Comment by patrolli** [comment]
Sorry for late reply. I have fix my problem. We need to set the variable `org-id-extra-files` to your org-roam-directory files, as

```
(setq org-id-extra-files (find-lisp-find-files org-roam-directory "\.org$"))
```

And refer to this link: https://org-roam.discourse.group/t/org-roam-major-redesign/1198/193

**Comment by kaushalmodi** [comment]
@patrolli Cool! Thanks for the follow up. So the links to other Org files by ID's works for ox-hugo exports after updating that variable? Should this issue be closed?

**Comment by patrolli** [comment]
Sure! I'll close it. In fact, I don't encounter this problem before that, and don't explicitly set this variable. This may be caused after migrating my org version or something else.

**Comment by Schievel1** [comment]
For future reference:
The function `find-lisp-find-files` does not exist on my emacs. For whatever reason, I guess its part of another package. 
` (setq org-id-extra-files (directory-files-recursively org-roam-directory "\\.org$")))` works as well.

**Comment by kaushalmodi** [comment]
@Schievel1 I have also documented that on this discussion page: https://github.com/kaushalmodi/ox-hugo/discussions/632
