### ISSUE TITLE
Can't use PaperMod's archive layout

### ISSUE THREAD

**Issue by Nathan-Furnal** [kaushalmodi/ox-hugo#486]
Hi, 

I'm struggling to use a hugo-theme as expected with `ox-hugo`. Basically, I'd like to reproduce what you  see on [on the PaperMod](https://adityatelange.github.io/hugo-PaperMod/) example page. 

There is an option to add an [archive layout](https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#archives-layout) , I've tried adding the `archives.md` as in the theme docs, but nothing shows up on the page, it's just empty with the "Archive" title. I've tried both manually or as an `org` subtree, neither worked.

This is the basic layout I mustered in a file called `index.org` which is within my `blog` folder (hugo root).

```org
#+title: blog
#+author: me
#+hugo_base_dir: .
#+hugo_section: posts
#+options: author:nil
#+hugo_front_matter_format: toml

* Home
:properties:
:export_hugo_section: /
:export_file_name: _index
:end:

* Posts
:properties:
:export_hugo_section: posts
:end:

** Posts
:properties:
:export_file_name: _index
:export_hugo_menu: :menu "main" :weight 1
:end:

** First blog post :@introduction:
:properties:
:export_file_name: post1
:end:
This is the first post to populate my blog. 

*** More info
blah blah

** Second blog post :@discussion:
:properties:
:export_file_name: post2
:end:
This is another post to populate my blog. 
*** More discussion
blah blah

* Search
:properties:
:export_hugo_section: search
:export_file_name: _index
:export_hugo_menu: :menu "main" :weight 2
:export_hugo_custom_front_matter: :layout "search"
:end:

* Projects
:properties:
:export_hugo_section: projects
:end:

** Projects
:properties:
:export_file_name: _index
:export_hugo_menu: :menu "main" :weight 3
:end:
Empty for now...
```
How can I fix this to have layout display accordingly? [It looks like this](https://adityatelange.github.io/hugo-PaperMod/archives/) in the docs. 

Thanks!

**Comment by kaushalmodi** [comment]
Does the exported Markdown file have the layout value as expected in the front matter? If yes, it will be more of a question related to Hugo or that theme.

Also, you can do the same layout specification using a shorter `:EXPORT_HUGO_LAYOUT: search`.

See if the theme is sensitive to that search page being a regular page vs a Branch bundle (_index).

**Comment by kaushalmodi** [comment]
Also, I am a bit confused. Your example is setting layout to search, while you are mentioning an archives layout. 

Can you provide a super short Org mode example that shows the problem you are seeing with archives?

**Comment by Nathan-Furnal** [comment]
My bad, it's a misunderstanding, the `search` layout has nothing to do with this, it was just an example of having multiple pages with different layouts for the sake of the example! 

The `archive` layout does not appear in my example simply because I couldn't make it work at all. 

See this example instead :

```org
#+title: My blog
#+author: Me
#+hugo_base_dir: .
#+hugo_section: posts
#+options: author:nil
#+hugo_front_matter_format: toml

* Home
:properties:
:export_hugo_section: /
:export_file_name: _index
:end:

* Posts
:properties:
:export_hugo_section: posts
:end:

** Posts
:properties:
:export_file_name: _index
:export_hugo_menu: :menu "main" :weight 1
:end:

** First blog post: an introduction                      :@misc:introduction:
My introduction.

*** Presentation
Hello World!

* Projects
:properties:
:export_hugo_section: projects
:end:

** Projects
:properties:
:export_file_name: _index
:export_hugo_menu: :menu "main" :weight 3
:end:
Empty for now...

* Archive
:properties:
:export_file_name: archives
:export_hugo_section: /
:export_hugo_layout: archives
:export_hugo_menu: :menu "main" :weight 7
:end:
``` 

I'd expect something like in the docs but I get nothing 
![image](https://user-images.githubusercontent.com/45597572/147498900-4166af68-3228-4bdf-8190-ed19456486dd.png)
 
The `archives.md` file is in the `content/` folder : 

```md
+++
title = "Archive"
layout = "archives"
draft = false
[menu.main]
  identifier = "archive"
  weight = 7
+++
``` 
So it seems it's exported correctly but nothing appears.

**Comment by kaushalmodi** [comment]
> So it seems it's exported correctly but nothing appears.

Thanks for confirming. 

As I feared, it's probably a theme issue or Hugo related confusion. Once you have the archives working as you like using manual Markdown, you can make ox-hugo export the same from Org source. 

I'd suggest opening an issue on the theme's repo with a snippet of the Markdown file.

**Comment by kaushalmodi** [comment]
Just guessing what the issue might be by quickly looking through that example (on phone)..  it looks like you might be confusing the theme by exporting the archives.md in content/. Have a look at the tree of files in the theme's example repo and make ox-hugo export only those.

**Comment by kaushalmodi** [comment]
I edited my last comment. I see the archives.md in https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content

So you might be exporting that correctly. But try to match everything in that exampleSite's content and config.toml, Hugo version, etc and see if that helps. 

I am away from computer and anyways I think that the theme author should be quicker in spotting the problem in the set of your exported files.

**Comment by Nathan-Furnal** [comment]
Honestly I've been running in circles with this problem and I hoped someone exterior could spot an obvious problem, I'll try over at the theme's author then!

**Comment by kaushalmodi** [comment]
I would help if you create a small repo containing the full site source: config.toml, theme submodule, exported Markdown and ask the theme author and Hugo Discourse forum to help you with that. 

If someone is able to reproduce the issue with a simple git clone and running Hugo, they can help you.

**Comment by kaushalmodi** [comment]
@Nathan-Furnal here's an example of one of my old sites used to either reproduce a Hugo issue or demonstrate a small feature quickly: https://gitlab.com/hugo-mwe/hugo-throwaway-1

**Comment by Nathan-Furnal** [comment]
Thanks for the help, I've opened an issue on the theme repo, there's not much in my own repo as I created the blog yesterday, it should be doable to clone https://gitlab.com/nathanfurnal/blog, fingers crossed!

**Comment by kaushalmodi** [comment]
Cool! Btw your repo doesn't show the contents/archives.md.

**Comment by Nathan-Furnal** [comment]
Thanks for catching that, I pushed to the repo!

**Comment by Nathan-Furnal** [comment]
For future reference, it was because I didn't export the dates on my posts with `export_date`!

**Comment by kaushalmodi** [comment]
Thanks for the follow up. Btw if you use the Org todo states (TODO/DONE) on the post subtree heading, you won't need to manually type the EXPORT_DATE.

**Comment by kaushalmodi** [comment]
You might have already seen this: https://ox-hugo.scripter.co/doc/org-meta-data-to-hugo-front-matter/#for-subtree-based-exports, but pasting it here for completeness.

**Comment by Nathan-Furnal** [comment]
No problem, thanks for your help!
