### ISSUE TITLE
How to export "maps" of single values?

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#488]
hi, 

is there a way to do this when using the `yaml` metadata format?

id like some nesting like

```
---
cover:
    image: "/myimage.jpg"
---
```

but i can't really figure out how to do that, any help ?

_Originally posted by @arjunkathuria in https://github.com/kaushalmodi/ox-hugo/issues/139#issuecomment-1000910930_

**Comment by kaushalmodi** [comment]
@arjunkathuria Please see the examples in the manual: https://ox-hugo.scripter.co/doc/custom-front-matter/#maps-of-single-and-list-values

Exporting to yaml or toml should work (or not work) the same way.

**Comment by arjunkathuria** [comment]
hi @kaushalmodi,

i forgot to update, i've since moved to using the toml format using the nested syntax as mentioned in the docs and it seems to work as intended. i'll test converting back to yaml when i get a chance.

Thanks for taking the time to reply.

**Comment by kaushalmodi** [comment]
> i've since moved to using the toml format using the nested syntax as mentioned in the docs

But I am surprised why moving to toml fixed this. I have tests in both TOML and YAML for maps exports.

- https://ox-hugo.scripter.co/test/posts/custom-front-matter-with-nested-maps-yaml/
  - Exported YAML in front matter: https://github.com/kaushalmodi/ox-hugo/raw/main/test/site/content/posts/custom-front-matter-with-nested-maps-yaml.md
  - If you scroll further down on that test page, you can see Hugo parsing the nested YAML correctly
     
    ![image](https://user-images.githubusercontent.com/3578197/147775510-2b4f5b88-9073-4d4a-983c-a10970fc27f7.png)

**Comment by kaushalmodi** [comment]
In any case, if you able to reproduce the issue, please reply in this thread, and I will re-open this issue.

**Comment by arjunkathuria** [comment]
Will do.

Again, thanks for all your work on this Kaushal. org-exports for writing blog posts is such a blessing
