### ISSUE TITLE
LaTeX formatting not working

### ISSUE THREAD

**Issue by zeeros** [kaushalmodi/ox-hugo#509]
I've been trying to export some org files containing LaTex formatting. For what I see [here](https://ox-hugo.scripter.co/doc/equations/) no further settings are needed to enable this type of formatting, however Hugo is not processing this correctly. So something like this

```
#+TITLE: A

We can model a packet filter by setting
- The filtering actions as $A_f$
- The filtering conditions as $C_{pf}$, such as IP address and port of source and destination, protocol
- The resolution strategy, as first matching rule resolution
- The default actions as $A_f$

\begin{align}
  & A_f=\{\text{Allow},\text{Deny}\}\\
  & C_{pf}=\{IPsrc,IPdst,Psrc,Pdst,protType\}\\
  & cap_{pf}=(A_f;C_{pf};\text{FMR};A_f)
\end{align}
```

Is rendered as follows in the final page

![image](https://user-images.githubusercontent.com/1713464/148796856-4ec37a35-7bfb-4a6a-9332-3c889e63e1f7.png)

While I'm expecting something like this

![image](https://user-images.githubusercontent.com/1713464/148797113-c671e989-36ae-4350-a05c-5cebcc0de31e.png)

**Comment by kaushalmodi** [comment]
@zeeros You need to add MathJax scripts to your site head.

**Comment by kaushalmodi** [comment]
I just added this to the ox-hugo manual: https://ox-hugo.scripter.co/doc/equations/#mathjax-config-example

Let me know if that helps.

**Comment by zeeros** [comment]
Yes now it works, thanks! 👍
