### ISSUE TITLE
Enable exporting of sub-heading tags; recognize `#+options: tags:t`

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#513]
Ref: https://github.com/kaushalmodi/ox-hugo/discussions/512

Export something similar to https://github.com/kaushalmodi/ox-hugo/discussions/512#discussioncomment-1943772 but with a div of tags exported soon after the markdown heading.

Recognize `org-export-with-tags` or `#+options: tags:t`

@stefanv

**Comment by kaushalmodi** [comment]
https://ox-hugo.scripter.co/test/posts/sub-headings-with-tags/

![image](https://user-images.githubusercontent.com/3578197/148982960-16f03fc2-1d51-4968-91fa-57f16e11847b.png)

**Comment by stefanv** [comment]
I admire that you took the time to figure out how to test this package; it's a neat scheme!  This also makes me rest easy that this is not just a feature that will appear and again disappear by accident :pray:
