### ISSUE TITLE
org generated table of content for non english charaters

### ISSUE THREAD

**Issue by longlu** [kaushalmodi/ox-hugo#521]
## Actual Behavior

org generated toc doesn't seem to work  for non English characters

the hugo generated toc work for the theme I'm testing

## Expected Behavior
the toc link work should work if i click on it

also the generated TOC stick to the top by default , which covers the main text
## How to Reproduce the Issue
can be tested with a random article
https://zh.wikipedia.org/wiki/2006%E5%B9%B4%E9%A3%93%E9%A3%8E%E7%BA%A6%E7%BF%B0
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment]
Sorry, can you please paste a minimum example of an Org file by which I can reproduce this issue? It's not clear what that link has to do with the toc.

**Comment by kaushalmodi** [comment]
I added a toc test for non-English language: https://ox-hugo.scripter.co/test/real-examples/nn-intro/

The links in the TOC are working fine there. They are generated using `#+toc: headlines 2`.

**Comment by longlu** [comment]
I inspected the html , 
org generated link looks like this:
<a href="/#%e8%8f%9c%e6%a0"></a>
Hugo generated toc link looks like this:

<a href="#中中">中中</a>   (this one would work)

**Comment by longlu** [comment]
i just tried another theme and inspected the html, looks same as above  ^

but both toc ,works on that theme,  so  it's not  caused by that difference .

**Comment by longlu** [comment]
On the theme that doesn't work,
`<a href="/#%e8%8f%9c%e6%a0">汉字</a>`
when the mouse is over the link ,  it shows this think: xxx.com/#汉字

`<a href="#汉字">汉字</a> (this one would work)`
when the mouse is over the link it shows  this:    xxx.com/page/#汉字

**Comment by longlu** [comment]
> On the theme that doesn't work, `<a href="/#%e8%8f%9c%e6%a0">汉字</a>` when the mouse is over the link , it shows this think: xxx.com/#汉字
> 
> `<a href="#汉字">汉字</a> (this one would work)` when the mouse is over the link it shows this: xxx.com/page/#汉字

so with this theme , when hugo try to convert markdown to html , it added a  '/'  before  '#%e8%8f%9c%e6%a0'

that's why it doesn't work

**Comment by kaushalmodi** [comment]
See the [relUrl](https://gohugo.io/functions/relurl/#readout) documentation. It converts the links without a forward slash prefix to be one beginning with a forward slash as if the link were starting from your site's baseUrl. Also note that `safeUrl` might be not what you want; see the docs. The opposite of `relUrl` is `absUrl`. 

Ox-hugo is only concerned with exporting Org to Markdown. Later how that Markdown is processed and displayed depends entirely on the Hugo templating, CSS and JS. 

Please ask theme related questions to the theme's repo or Hugo's Discourse forum. I'll close this issue as it's unrelated to ox-hugo.
