### ISSUE TITLE
Hard Line break not working

### ISSUE THREAD

**Issue by Raialbe** [kaushalmodi/ox-hugo#526]
## Actual Behavior
The line breaking logic implemented by the hardLineBreak blackfriday flag seems to be broken.
The test case is here https://ox-hugo.scripter.co/test/posts/blackfriday-ext-hardlinebreak-toml/
In the test website the three newline separated letters appear on the same line.
![CopyQ jdZWNG](https://user-images.githubusercontent.com/25611931/149627877-ac81e8e4-8d3b-400c-9fc3-5098956404c9.png)

## Expected Behavior
The three letters should appear on different lines as described by the test case.
### Example Org File
*** Hard line break (TOML)                                             :toml:
:PROPERTIES:
:EXPORT_FILE_NAME: blackfriday-ext-hardlinebreak-toml
:EXPORT_HUGO_BLACKFRIDAY: :extensions hardLineBreak
:END:
a
b
c

Above, /a/, /b/ and /c/ must appear on separate lines.
### Generated Markdown File or Error
+++
title = "Hard line break (TOML)"
tags = ["blackfriday", "toml"]
draft = false
[blackfriday]
  extensions = ["hardLineBreak"]
+++

a
b
c

Above, _a_, _b_ and _c_ must appear on separate lines.

**Comment by kaushalmodi** [comment]
Thanks for bringing this up. I need to remove the deprecated Blackfriday extensions from ox-hugo.

See the latest Hugo documentation for extensions: https://gohugo.io/getting-started/configuration-markup

**Comment by kaushalmodi** [comment]
Do you need to retain line breaks in the whole post?

**Comment by kaushalmodi** [comment]
@Raialbe It looks like that unless you switch back to the deprecated Blackfriday renderer in Hugo, you cannot set the extension enables in the front matter. 

See https://discourse.gohugo.io/t/front-matter-override-for-goldmark/26125

The Goldmark equivalent of hardLineBreaks is hardWraps, but that has to be enabled in your global config, the site config. 

Btw https://github.com/kaushalmodi/ox-hugo/issues/527 is fixed you can enable hard line breaks per post by `<br/>` insertion done by ox-hugo.

If you need Hugo to support Goldmark settings in front matter, you need to voice your opinion in the Hugo Discourse forum first and ask the Hugo developers to add that feature to Hugo.

**Comment by Raialbe** [comment]
This is awesome, I solved it by setting goldmark in the global config.
Thanks for all the help, much appreciated!

**Comment by kaushalmodi** [comment]
> I solved it by setting goldmark in the global config.

I didn't understand. It's Goldmark that doesn't support these extensions. The test site is generated using the default Goldmark parser.

**Comment by kaushalmodi** [comment]
> I solved it by setting goldmark in the global config.

Did you add this to the global config?

```toml
[markup.goldmark.renderer]
  hardWraps = true
```

**Comment by Raialbe** [comment]
Yeah, now the lines are breaking as expected.

**Comment by kaushalmodi** [comment]
ok, that's expected if you are enabling that extension globally.

I just wanted to clarify that Goldmark doesn't allow enabling extensions using front-matter in posts.

I'll then close this issue as it solves your particular problem.

---

- If you need to enable hardwraps only in selected posts, you would be able to do that once https://github.com/kaushalmodi/ox-hugo/issues/527 is fixed.
- As for the test pages for Blackfriday-specific extensions that you referenced above, I will remove those tests as they don't apply to Goldmark any more, and because the test site will be generated using Goldmark renderer. All that cleanup will happen in https://github.com/kaushalmodi/ox-hugo/issues/528.

**Comment by kaushalmodi** [comment]
You can enable the "hardWraps" behavior per post by setting the post's "\n:t" option. See the test added in https://github.com/kaushalmodi/ox-hugo/pull/530.

**Comment by kaushalmodi** [comment]
> The test case is here https://ox-hugo.scripter.co/test/posts/blackfriday-ext-hardlinebreak-toml/

FYI, now that https://github.com/kaushalmodi/ox-hugo/pull/531 is merged, above will give a 404 error as that and other Blackfriday option/extension tests have been removed.
