### ISSUE TITLE
Add markup for <kbd> tags

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#53]

**Comment by kaushalmodi** [comment]
@punchagan @titaniumbones Guys, this feature addition might break things for you if you are using `~foo~` syntax for verbatim text instead of `=foo=` in Org.

To "unbreak" things, and if you do not care about having `<kbd>` tags in the final HTML, you can set `org-hugo-use-code-for-kbd` to `nil`.

**Comment by kaushalmodi** [comment]
See the Org source in [`all-posts.org`][1] under *Formatting* -> *General* heading and how it exports to Markdown in [`general-formatting.md`][2].

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/example-site/content-org/all-posts.org
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/example-site/content/posts/general-formatting.md

**Comment by punchagan** [comment]
Thanks for the mention, @kaushalmodi
