### ISSUE TITLE
Figure captions: HTML (and markdown) not getting rendered

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#535]
I don't know if this is the right place to mention this, but using latest ox-hugo with figure captions, HTML markup in the captions are rendered encoded, e.g.:

```
<figcaption>
          <p>&lt;span class=&#34;figure-number&#34;&gt;Figure 1: &lt;/span&gt;Mom and Dad (1971)</p>
</figcaption>
```

This is from the following Org content:

```
#+caption: Mom and Dad (1971)
[[/img/2022/20220118-MomDadDressup.jpg]]
```

The Markdown renders as:

```
{{< figure src="/img/2022/20220118-MomDadDressup.jpg" caption="<span class=\"figure-number\">Figure 1: </span>Mom and Dad (1971)" >}}
```

I'm running latest doom emacs with unpinned ox-hugo and Hugo v0.92.0+extended. Let me know if there's a better place for this or if I'm missing something. Thanks.

_Originally posted by @jackbaty in https://github.com/kaushalmodi/ox-hugo/issues/321#issuecomment-1015532613_

**Comment by kaushalmodi** [comment]
@jackbaty I will need more details. 

The test page is exporting alright:

- https://ox-hugo.scripter.co/test/posts/image-captions/
  - [exported md that's generating that page](https://raw.githubusercontent.com/kaushalmodi/ox-hugo/main/test/site/content/posts/image-captions.md)

Looking at the HTML source of that test page, the HTML inside the captions looks good:

```html
    <p>Some text before image.</p>
<figure><img src="https://ox-hugo.scripter.co/test/images/org-mode-unicorn-logo.png"
         alt="Figure 1: A unicorn! &amp;ldquo;Something in double quotes&amp;rdquo;"/><figcaption>
            <p><span class="figure-number">Figure 1: </span>A unicorn! &ldquo;Something in double quotes&rdquo;</p>
        </figcaption>
</figure>

<p>Some more text, after image.</p>
<figure><img src="https://ox-hugo.scripter.co/test/images/org-mode-unicorn-logo.png"
         alt="Figure 2: The same figure again, testing a link too!"/><figcaption>
            <p><span class="figure-number">Figure 2: </span>The <em>same</em> figure <strong>again</strong>, testing <a href="https://ox-hugo.scripter.co">a link</a> too!</p>
        </figcaption>
</figure>
```

The test site is using Hugo v0.92.0 (regular version, not extended).


---

Do you happen to have a custom `figure` shortcode in your theme that's overriding the default `figure` shortcode?

**Comment by kaushalmodi** [comment]
@jackbaty

> Do you happen to have a custom figure shortcode in your theme that's overriding the default figure shortcode?

[Looks like it](https://github.com/jackbaty/daily-jane/blob/73d9c6d964003f50e9c38fb010bbb9372309c204/layouts/shortcodes/figure.html).

---

Replace this line:

https://github.com/jackbaty/daily-jane/blob/73d9c6d964003f50e9c38fb010bbb9372309c204/layouts/shortcodes/figure.html#L24

with

```html
{{ .Get "caption" | markdownify }}
```

**Comment by kaushalmodi** [comment]
Coincidentally, I was involved this fixing the default `figure` shortcode in Hugo to allow rendering of HTML in "caption" and "attr" more than (gasp!) 3 years back! -> https://github.com/gohugoio/hugo/pull/5276

So I kind of guessed quickly what was going on with this issue 😄 .

**Comment by jackbaty** [comment]
Oh my, I'd forgotten I was using a custom shortcode. Sorry for the noise. You're right, calling markdownify on those elements takes care of the problem. Thank you much!
