### ISSUE TITLE
Support consecutive quote blocks

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#54]

**Comment by kaushalmodi** [comment]
@punchagan 

Looks like consecutive quotes already work. I just added an example in https://github.com/kaushalmodi/ox-hugo/commit/68597d2583c7b6df200e45677e0dc3c5c8497b22.

Can you verify?

**Comment by punchagan** [comment]
All the consecutive quotes appear in a single `blockquote` when the markdown is parsed by hugo.  This is different from the behavior of the org exporter, which puts each of the quote in a separate `blockquote`.

**Comment by kaushalmodi** [comment]
@punchagan Try it out now, it's fixed using the same comment insertion trick you suggested. Thanks!

**Comment by punchagan** [comment]
@kaushalmodi Works nicely! Thank you :+1:

**Comment by kaushalmodi** [comment]
@punchagan Thanks. I just pushed a cleanup commit.. now the separator comments will be inserted only when needed.
