### ISSUE TITLE
`$HOME` changes to <repo>/test/ when running `make md`

### ISSUE THREAD

**Issue by vinurs** [kaushalmodi/ox-hugo#541]
## Actual Behavior
if i modify the `hugo_base_dir` in org file，it doesn't  place the md files in the correct directory.
for example, if i modify the file `test/site/content-org/single-posts/post-yaml.org`, change the `hugo_base_dir` from
`hugo_base_dir: ../../` to `hugo_base_dir: ~/hello/`, it generate the md file in `ox-hugo/test/hello`,  not in `~/hello/`

## Expected Behavior
it generate the md files in `~/hello/`

## How to Reproduce the Issue
just modiry the `post-yaml.org` and make md can reproduce it

**Comment by kaushalmodi** [comment]
@vinurs I tried the change you suggested to reproduce the issue:

```diff
--- a/test/site/content-org/single-posts/post-yaml.org
+++ b/test/site/content-org/single-posts/post-yaml.org
@@ -2,7 +2,7 @@
 #+author:
 #+date: 2017-07-20
 
-#+hugo_base_dir: ../../
+#+hugo_base_dir: ~/hello/
 #+hugo_front_matter_format: yaml
 
 #+hugo_section: singles
```

but I am seeing the file begin generated at `~/hello/content/singles/post-yaml.md` correctly.

I cannot reproduce this issue.

**Comment by vinurs** [comment]
@kaushalmodi it's strange
```
diff --git a/test/site/content-org/single-posts/post-yaml.org b/test/site/content-org/single-posts/post-yaml.org
index 645d992..27d89b1 100644
--- a/test/site/content-org/single-posts/post-yaml.org
+++ b/test/site/content-org/single-posts/post-yaml.org
@@ -2,7 +2,7 @@
 #+author:
 #+date: 2017-07-20

-#+hugo_base_dir: ../../
+#+hugo_base_dir: ~/hello1/
 #+hugo_front_matter_format: yaml

 #+hugo_section: singles
```

<img width="604" alt="图片" src="https://user-images.githubusercontent.com/37489300/151478737-b509e95a-537c-4423-8154-3e26314ab4ea.png">


if i open the org file and use `org-hugo-export-wim-to-md` , it generated the file at `~/hello1/` correcttly, my os is macos monterey 12.2 m1 max

**Comment by kaushalmodi** [comment]
> if i open the org file and use org-hugo-export-wim-to-md , it generated the file at ~/hello1/ correctly

How did you export earlier when it got exported to the wrong place?

**Comment by kaushalmodi** [comment]
ok.. I have a good guess on what this happened.. you are running `make test` or using the Makefile that ships with the ox-hugo tests.

https://github.com/kaushalmodi/ox-hugo/blob/430c967491299956a85e26bbf013be1e71127bb5/Makefile#L124-L133

The ox-hugo test's Makefile is designed to work as if in a sandbox and should not touch the user's `$HOME`, so it overrides that env var to the repo's `test/` directory.

So if you do this, it will work:

```org
#+hugo_base_dir: /Users/vinurs/hello
```

**Comment by vinurs** [comment]
😄 thanks， works now
