### ISSUE TITLE
attr_shortcode not recognised

### ISSUE THREAD

**Issue by johanwk** [kaushalmodi/ox-hugo#546]
I'm trying to use shortcodes with attributes, but `attr_shortcode` is ignored, in the following and with other examples.

My org file:
```
** Add a button                                                        :test:
:PROPERTIES:
:EXPORT_FILE_NAME: test-varia
:EXPORT_HUGO_PAIRED_SHORTCODES: button
:END:

#+attr_shortcode :href https://github.com/thegeeklab/hugo-geekdoc
#+begin_button
my button
#+end_button
```

The markdown result:
```
\#+attr_shortcode :href <https://github.com/thegeeklab/hugo-geekdoc>

{{< button >}}
my button
{{< /button >}}
```

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)
     of 2021-03-26 (commit deef5efafb70f4b171265b896505b92b6eef24e6)

## Org Version

    Org mode version 9.4.4 (release_9.4.4 @ c:/opt/emacs/share/emacs/27.2/lisp/org/)

## Hugo Version

    hugo v0.89.2-63E3A5EB+extended windows/amd64 BuildDate=2021-11-08T15:22:24Z VendorInfo=gohugoio

### Org `load-path` shadows

No Org mode shadows found in `load-path`

</details>

**Comment by kaushalmodi** [comment]
You are missing a colon after `#+attr_shortcode`.

**Comment by kaushalmodi** [comment]
All Org keywords **need** to be followed by a colon, like `#+options: toc: 2`.

**Comment by johanwk** [comment]
Oh my, oh my.

I really owe you one. Thanks a million!

**Comment by johanwk** [comment]
PS! In the documentation at https://ox-hugo.scripter.co/doc/shortcodes/, those colons are absent.

**Comment by kaushalmodi** [comment]
@johanwk Thanks for pointing that out! That doc page will auto-update in 1-2 minutes.
