### ISSUE TITLE
Literal export of Non-markdown Shortcodes ({{< .. >}}) contents 

### ISSUE THREAD

**Issue by f0-x** [kaushalmodi/ox-hugo#547]
Please help me on exporting the Greater than(>) and Less than (<) symbol literally from org to markdown. I want the ox-hugo to export the contents inside of my Non-markdown shortcode (*mermaid*) without any changes. Like here, the ">" & "<" symbols gets exported to "&gt" and "&lt" respectively. Thank you for this awesome tool :) 
![shortcode](https://user-images.githubusercontent.com/96965109/152329642-f477b214-733b-493b-96b7-3acdefc017d8.png)

**Comment by kaushalmodi** [comment]
Hello, please check out this doc page: https://ox-hugo.scripter.co/doc/shortcodes/ -- there are multiple ways of exporting shortcodes.

**Comment by kaushalmodi** [comment]
Related: https://github.com/kaushalmodi/ox-hugo/issues/540

**Comment by kaushalmodi** [comment]
@f0-x Sorry, I slightly misread this issue.

To fix what you are seeing, you will need to set the `:raw` property for the special block type `mermaid` to `t`.

See https://ox-hugo.scripter.co/doc/org-special-blocks/#raw-org-contents.

So try this out:

```emacs-lisp
(with-eval-after-load 'ox-hugo
  (add-to-list 'org-hugo-special-block-type-properties '("mermaid" . (:raw t))))
```

**Comment by f0-x** [comment]
I just discovered the same thing reading your documentation and you just posted the same thing here. 😁 Sorry for wasting your time Mr. Modi. Cheers for this awesome tool 💛

**Comment by kaushalmodi** [comment]
The related issue was actually https://github.com/kaushalmodi/ox-hugo/issues/377.

I also also added an example of setting `:raw t` property to the documentation: https://ox-hugo.scripter.co/doc/org-special-blocks/#code-snippet--example-update-raw-special-block-prop
