### ISSUE TITLE
Cannot export Non-Markdown Shortcodes ({{< .. >}}) which have no closing </shortcode> tag

### ISSUE THREAD

**Issue by f0-x** [kaushalmodi/ox-hugo#548]
The theme I'm using has a Non-markdown Shortcode (i.e {{< mapbox >}}) with no closing tag (i.e {{< /mapbox >}}).  
![shortcode](https://user-images.githubusercontent.com/96965109/152333756-5aa9021e-243a-492d-8ac7-f964d7fe34b5.png)

How do I write the corresponding org for this shortcode ?

I tried writing this on my org file.
![mapbox](https://user-images.githubusercontent.com/96965109/152334187-87d2812f-2326-4346-b21d-1759b7de746b.png)

But got the following error. :(
![build error](https://user-images.githubusercontent.com/96965109/152334220-19606b22-d744-40de-999e-fcec0857e7cb.png)

**Comment by kaushalmodi** [comment]
Above syntax generates a paired Hugo shortcode like

```
{{< mapbox >}}
something
{{< /mapbox >}}
```

Such a shortcode requires the shortcode definition to do something with the `.Inner` (body of that shortcode).

---

For your unpaired shortcode case, simply prefix that line with `#+hugo:` .

Doc: https://ox-hugo.scripter.co/doc/shortcodes/#plus-hugo-keyword

**Comment by kaushalmodi** [comment]
I'll close this issue as it's similar to the other issue you opened: https://github.com/kaushalmodi/ox-hugo/issues/547.

**Comment by kaushalmodi** [comment]
Feel free to comment here if you need to reopen this issue.

**Comment by f0-x** [comment]
I need to sharpen my documentation reading skills. Thanks for pointing it out Mr. Modi.

**Comment by muihlinn** [comment]
what if I need to use a very long list of `#+attr_shortcode` with an unpaired shortcode?
`#+hugo:` seems to ignore the attributes.

I've managed to make it work as paired just typing something  in the org block and assigning `.Inner` to a template unused variable, works, but looks messy.

**Comment by kaushalmodi** [comment]
@muihlinn Hello! Can you please create a new issue with minimal example in Org showing what you tried doing and didn't work?
