### ISSUE TITLE
Problem with SVGs containing hyperlinks on Windows

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#552]
I have a problem with SVGs containing hyperlinks: The output shown in HTML is the XML code of the SVG, with "<" converted to `&lt;`, etc. 

My image is generated with PlantUML, as in the example at https://ox-hugo.scripter.co/doc/inlined-svgs/. So, there's an org-babel block with the PlantUML code, then the generated SVG image.

Clue: If I add `<p>` ... `</p>` immediately around the <svg> content _in the generated Markdown file_, the image is displayed properly.

_Originally posted by @johanwk in https://github.com/kaushalmodi/ox-hugo/issues/470#issuecomment-1030093495_

**Comment by kaushalmodi** [comment]
@johanwk Can you please provide a minimum reproducible example? As you see in the inlined-svgs test, I don't see that issue.

**Comment by johanwk** [comment]
Here's an example. Entered as follows, with `:inlined t` before the PlantUML block, the svg is _not_ inlined, and the hyperlink doesn't work.

```
#+caption: My class diagram
#+attr_html: :inlined t
#+begin_src plantuml :file asdf.svg :exports both
  class A
  url of A is [[http://example.org/]]
#+end_src

#+RESULTS:
[[file:asdf.svg]]
```

If `:inlined t` is placed immediately before `[[file:asdf.svg]]`, the SVG content is included in the generated Markdown file, but without `<p>` tags around it. Snippet:
```
<div class="src-block-caption">
  <span class="src-block-number">Code Snippet 2</span>:
  My class diagram
</div>
                                  <<<< want <p> here
<svg
xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink"
```

... and after adding `<p>` ... `</p>` into the MD file, to surround the SVG content, the image is correctly displayed, with hyperlink working.

**Comment by kaushalmodi** [comment]
I am still unable to reproduce the issue:

![image](https://user-images.githubusercontent.com/3578197/152563777-a868add4-bc00-4c07-be0f-2eb11e17652d.png)

The link in the Hugo rendered HTML is working alright. 

What is your Hugo version? I am testing using 0.92.0.

**Comment by johanwk** [comment]
hugo v0.89.2-63E3A5EB+extended windows/amd64 BuildDate=2021-11-08T15:22:24Z VendorInfo=gohugoio

**Comment by kaushalmodi** [comment]
Also note that you have `:inlined t` attribute at the wrong place in your example. That attr needs to be directly above the `#+RESUTLS:`.

**Comment by johanwk** [comment]
> Also note that you have `:inlined t` attribute at the wrong place in your example. That attr needs to be directly above the `#+RESUTLS:`.

I see. However, when taking the PlantUML source code block out and following the pattern at https://ox-hugo.scripter.co/doc/inlined-svgs/ with the following, the produced HTML shows the SVG XML source instead of the image.

```
#+caption: My class diagram
#+attr_html: :inlined t
[[file:asdf.svg]]
```

(in the generated MD, I see this:

```
           (a blank line)
<svg
xmlns="http://www.w3.org/2000/svg"
...
y1="47" y2="47"/></a></g></svg>
           (a blank line)
```

**Comment by kaushalmodi** [comment]
> the produced HTML shows the SVG XML source instead of the image

I cannot reproduce that issue both locally and on Netlify published doc and test sites. I can fix it if I can see the issue 😃 .

**Comment by johanwk** [comment]
> I cannot reproduce that issue both locally and on Netlify published doc and test sites. I can fix it if I can see the issue 😃 .

So, maybe the Hugo version makes a difference here. Don't hesitate to voice your opinion on that :)

**Comment by kaushalmodi** [comment]
> (in the generated MD, I see this:

The generated md **will** show the SVG code.. because that's that the `:inline t` attribute does. It inlines the SVG in the exported file instead of linking to it.

> So, maybe the Hugo version makes a difference here.

I see that you have Hugo 0.89. This SVG inlining feature has been there for a while, may be I test is for the first time on Hugo 0.5x.xx or 0.7x.xx.

**Comment by johanwk** [comment]
> The generated md **will** show the SVG code.. because that's that the `:inline t` attribute does. It inlines the SVG in the exported file instead of linking to it.

Yes, I realize this is necessary. However, as far as I can see, what's missing is to enclose the svg content within `p` tags.

**Comment by kaushalmodi** [comment]
@johanwk See this updated test: https://ox-hugo.scripter.co/test/posts/inlined-svg/

I added your test Org snippet to that. May be you can compare the HTML (do view-source in browser or Ctrl+u) between that test site and what you see locally.

I have also updated the manual page for Inlined SVGs: https://ox-hugo.scripter.co/doc/inlined-svgs/

**Comment by kaushalmodi** [comment]
If you download this markdown test file ( https://raw.githubusercontent.com/kaushalmodi/ox-hugo/main/test/site/content/posts/inlined-svg.md ) and put it in your `content/` directory, does it work?

**Comment by johanwk** [comment]
> does it work?

as one would expect, the answer is yes, it works perfectly :-D

**Comment by kaushalmodi** [comment]
> it works perfectly :-D

Great! Now can you share the .svg file that your PlantUML version creates? :)

**Comment by johanwk** [comment]
Here:

```
<svg
xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink"
contentScriptType="application/ecmascript" contentStyleType="text/css"
height="69px" preserveAspectRatio="none"
style="width:61px;height:69px;background:#FFFFFF;" version="1.1"
viewBox="0 0 61 69" width="61px" zoomAndPan="magnify"><defs><filter
height="300%" id="ffzno5ewu4su5" width="300%" x="-1"
y="-1"><feGaussianBlur result="blurOut"
stdDeviation="2.0"/><feColorMatrix in="blurOut" result="blurOut2"
type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .4
0"/><feOffset dx="4.0" dy="4.0" in="blurOut2"
result="blurOut3"/><feBlend in="SourceGraphic" in2="blurOut3"
mode="normal"/></filter></defs><g><a href="http://example.org/" target="_top"
title="http://example.org/" xlink:actuate="onRequest"
xlink:href="http://example.org/" xlink:show="new"
xlink:title="http://example.org/" xlink:type="simple"><rect
codeLine="1" fill="#FEFECE" filter="url(#ffzno5ewu4su5)" height="48"
id="A" style="stroke:#A80036;stroke-width:1.5;" width="40" x="7"
y="7"/><ellipse cx="22" cy="23" fill="#ADD1B2" rx="11" ry="11"
style="stroke:#A80036;stroke-width:1.0;"/><path d="M24.7656,18.875
Q24.9219,18.6563 25.1094,18.5469 Q25.2969,18.4375 25.5156,18.4375
Q25.8906,18.4375 26.125,18.7031 Q26.3594,18.9531 26.3594,19.5625
L26.3594,21.0156 Q26.3594,21.625 26.125,21.8906 Q25.8906,22.1563
25.5156,22.1563 Q25.1719,22.1563 24.9688,21.9531 Q24.7656,21.7656
24.6563,21.25 Q24.6094,20.8906 24.4219,20.7031 Q24.0938,20.3281
23.4844,20.1094 Q22.875,19.8906 22.25,19.8906 Q21.4844,19.8906
20.8438,20.2188 Q20.2188,20.5469 19.7188,21.2969 Q19.2344,22.0469
19.2344,23.0781 L19.2344,24.1719 Q19.2344,25.4063 20.125,26.2344
Q21.0156,27.0469 22.6094,27.0469 Q23.5469,27.0469 24.2031,26.7969
Q24.5938,26.6406 25.0156,26.2031 Q25.2813,25.9375 25.4219,25.8594
Q25.5781,25.7813 25.7813,25.7813 Q26.1094,25.7813 26.3594,26.0469
Q26.625,26.2969 26.625,26.6406 Q26.625,26.9844 26.2813,27.3906
Q25.7813,27.9688 24.9844,28.2969 Q23.9063,28.75 22.6094,28.75
Q21.0938,28.75 19.8906,28.125 Q18.9063,27.625 18.2188,26.5625
Q17.5313,25.4844 17.5313,24.2031 L17.5313,23.0469 Q17.5313,21.7188
18.1406,20.5781 Q18.7656,19.4219 19.8594,18.8125 Q20.9531,18.1875
22.1875,18.1875 Q22.9219,18.1875 23.5625,18.3594 Q24.2188,18.5156
24.7656,18.875 Z " fill="#000000"/><text fill="#000000"
font-family="sans-serif" font-size="12" lengthAdjust="spacing"
textLength="8" x="36" y="27.9102">A</text><line
style="stroke:#A80036;stroke-width:1.5;" x1="8" x2="46" y1="39"
y2="39"/><line style="stroke:#A80036;stroke-width:1.5;" x1="8" x2="46"
y1="47" y2="47"/></a></g></svg>
```

**Comment by kaushalmodi** [comment]
That's the sanitized version that ox-hugo inserts. Can you share the whole .svg file that PlantUML generates on disk?

(You can open the .svg in Emacs if your version supports that and do C-c C-c to view its source.)

**Comment by johanwk** [comment]
Oh, sorry. Trying again:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentScriptType="application/ecmascript" contentStyleType="text/css" height="69px" preserveAspectRatio="none" style="width:61px;height:69px;background:#FFFFFF;" version="1.1" viewBox="0 0 61 69" width="61px" zoomAndPan="magnify"><defs><filter height="300%" id="ffzno5ewu4su5" width="300%" x="-1" y="-1"><feGaussianBlur result="blurOut" stdDeviation="2.0"/><feColorMatrix in="blurOut" result="blurOut2" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .4 0"/><feOffset dx="4.0" dy="4.0" in="blurOut2" result="blurOut3"/><feBlend in="SourceGraphic" in2="blurOut3" mode="normal"/></filter></defs><g><!--MD5=[a46ee5ce0ceb0380cf446a08a056dce4]
class A--><a href="http://example.org/" target="_top" title="http://example.org/" xlink:actuate="onRequest" xlink:href="http://example.org/" xlink:show="new" xlink:title="http://example.org/" xlink:type="simple"><rect codeLine="1" fill="#FEFECE" filter="url(#ffzno5ewu4su5)" height="48" id="A" style="stroke:#A80036;stroke-width:1.5;" width="40" x="7" y="7"/><ellipse cx="22" cy="23" fill="#ADD1B2" rx="11" ry="11" style="stroke:#A80036;stroke-width:1.0;"/><path d="M24.7656,18.875 Q24.9219,18.6563 25.1094,18.5469 Q25.2969,18.4375 25.5156,18.4375 Q25.8906,18.4375 26.125,18.7031 Q26.3594,18.9531 26.3594,19.5625 L26.3594,21.0156 Q26.3594,21.625 26.125,21.8906 Q25.8906,22.1563 25.5156,22.1563 Q25.1719,22.1563 24.9688,21.9531 Q24.7656,21.7656 24.6563,21.25 Q24.6094,20.8906 24.4219,20.7031 Q24.0938,20.3281 23.4844,20.1094 Q22.875,19.8906 22.25,19.8906 Q21.4844,19.8906 20.8438,20.2188 Q20.2188,20.5469 19.7188,21.2969 Q19.2344,22.0469 19.2344,23.0781 L19.2344,24.1719 Q19.2344,25.4063 20.125,26.2344 Q21.0156,27.0469 22.6094,27.0469 Q23.5469,27.0469 24.2031,26.7969 Q24.5938,26.6406 25.0156,26.2031 Q25.2813,25.9375 25.4219,25.8594 Q25.5781,25.7813 25.7813,25.7813 Q26.1094,25.7813 26.3594,26.0469 Q26.625,26.2969 26.625,26.6406 Q26.625,26.9844 26.2813,27.3906 Q25.7813,27.9688 24.9844,28.2969 Q23.9063,28.75 22.6094,28.75 Q21.0938,28.75 19.8906,28.125 Q18.9063,27.625 18.2188,26.5625 Q17.5313,25.4844 17.5313,24.2031 L17.5313,23.0469 Q17.5313,21.7188 18.1406,20.5781 Q18.7656,19.4219 19.8594,18.8125 Q20.9531,18.1875 22.1875,18.1875 Q22.9219,18.1875 23.5625,18.3594 Q24.2188,18.5156 24.7656,18.875 Z " fill="#000000"/><text fill="#000000" font-family="sans-serif" font-size="12" lengthAdjust="spacing" textLength="8" x="36" y="27.9102">A</text><line style="stroke:#A80036;stroke-width:1.5;" x1="8" x2="46" y1="39" y2="39"/><line style="stroke:#A80036;stroke-width:1.5;" x1="8" x2="46" y1="47" y2="47"/></a><!--MD5=[09083846bcca48cfe0cf3768bdd496d2]
@startuml

class A

url of A is [[http://example.org/]]

@enduml


PlantUML version 1.2021.10(Mon Aug 30 15:43:48 CEST 2021)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Default Encoding: Cp1252
Language: en
Country: US
--></g></svg>
```

**Comment by johanwk** [comment]
> Trying again

I could mention that the lines quoting the PlantUML source (`@startuml`, etc.) all end in `^M` on my Windows machine. That came out as newlines in the above comment.

**Comment by kaushalmodi** [comment]
I copied your SVG and still couldn't recreate the issue. Can you upload your file somewhere, like on https://gist.github.com/ ?

**Comment by johanwk** [comment]
does this work? https://gist.github.com/johanwk/ff0f94a3a71d26645e4e5be483e2344c#file-asdf-svg

**Comment by johanwk** [comment]
I could try this. However, isn't the following strange: When I paste the svg from my ox-hugo md output into the file you sent, the svg image is actually rendered correctly, with hyperlink. Maybe there's something else in my file that creates a problem.

**Comment by kaushalmodi** [comment]
> Maybe there's something else in my file that creates a problem.

Wait, so you cannot reproduce the issue if you have a post containing just the snippet you have in https://github.com/kaushalmodi/ox-hugo/issues/552#issuecomment-1030129079 ?

Please share the entire minimum reproducible example of the Org file and the generated Markdown.

**Comment by kaushalmodi** [comment]
> When I paste the svg from my ox-hugo md output into the file you sent, the svg image is actually rendered correctly, with hyperlink.

So that takes the Hugo and plantuml versions out of the equation.

**Comment by johanwk** [comment]
Aight! It's the buffer encoding that causes the trouble.

Setting encoding in the MD file to `utf-8-unix` and saving produces the right result. `utf-8-dos` produces the error.

This indicates that explicitly setting the encoding to `utf-8-unix` in ox-hugo would help, I think.

**Comment by kaushalmodi** [comment]
This is kind of going out of my knowledge domain. I'll need to learn how to do this correctly? Why don't the default Org exporters have any file encoding related setting?

You will need to find out what's setting the buffer encoding to dos in your setting? Maybe it's because you are probably working on a Windows machine?

**Comment by johanwk** [comment]
Surely it's due to the Windows environment. I'll try to look for a solution.

**Comment by kaushalmodi** [comment]
I think you are somehow mixing up unix and windows line endings in your exported Markdown and so you are seeing this issue. 

- You mentioned that you default your emacs to use unix line endings, but then the SVG that gets inlined has windows line endings. Can you make sure that the SVG is cleaned up by replacing dos line endings with unix line endings before you export?

**Comment by johanwk** [comment]
Here's a possible solution: Towards the end of `org-hugo-export-to-md`, set `org-export-coding-system`:

```
    (prog1
        (let ((org-export-coding-system 'utf-8-unix))
          (org-export-to-file 'hugo outfile async subtreep visible-only))
```

**Comment by kaushalmodi** [comment]
> would likely be safe for anyone else as well.

I cannot take that risk. People use a variety of encoding systems. Enforcing utf-8-unix on export could result in another set of difficult to debug problems like this one.

**Comment by johanwk** [comment]
> > would likely be safe for anyone else as well.
> 
> I cannot take that risk. People use a variety of encoding systems. Enforcing utf-8-unix on export could result in another set of difficult to debug problems like this one.

True. One could check for a Windows OS, but your point would still apply.

Maybe use a configuration variable that one could set, as with the various `#+hugo_myvariable:` in-buffer settings? Then `org-hugo-export-to-md` could check whether this is set with `boundp`, and if so, use it to set `org-export-coding-system`.

**Comment by kaushalmodi** [comment]
@johanwk 

`org-export-coding-system` is a defcustom. If setting that works for you, you just need to put something like this in your config.

```el
(with-eval-after-load 'ox
  (setq org-export-coding-system 'utf-8-unix))
```

If you can try this out after a clean restart of emacs and loading of ox-hugo, I can put this in the ox-hugo-manual.org in a "Windows users" section.

**Comment by johanwk** [comment]
I'm afraid I don't have time to restart right now.

_However_, I'm confident that this customization does solve the problem (just changed the variable in customize) -- results are correct with the unchanged `org-hugo-export-to-md`). However, it will of course also affect any _other_ export that the user produces, and that could once again be a problem -- while an option just for ox-hugo would be rather safe.

**Comment by johanwk** [comment]
Once again, thank you _so much_ for taking the time to investigate this problem. Being able to produce SVGs with links in them is very important for me.

**Comment by kaushalmodi** [comment]
> while an option just for ox-hugo would be rather safe.

This is the first time I am seeing such an issue being reported. So I'll wait to see if anyone else also sees the same problem.

Until then, you can define [an `:around` advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html) like this:

```el
(defun my/org-hugo-export-to-md-always-utf-8-unix (orig-fun &rest args)
  (let ((org-export-coding-system 'utf-8-unix))
    (apply orig-fun args)))

(with-eval-after-load 'ox-hugo
  (advice-add 'org-hugo-export-to-md :around #'my/org-hugo-export-to-md-always-utf-8-unix)
```

**Comment by kaushalmodi** [comment]
Also, in this stream you messages, you probably missed this:

> You mentioned that you default your emacs to use unix line endings, but then the SVG that gets inlined has windows line endings. Can you make sure that the SVG is cleaned up by replacing dos line endings with unix line endings before you export?

Can you find out how you can make plantuml export the SVG with the unix-style line endings? I think that once the SVG and your exported md line endings are in harmony (either everything unix style or everything dos style), this issue will go away.

**Comment by johanwk** [comment]
Unfortunately, there doesn't seem to be an option for PlantUML that will ask for unix-style line endings.

**Comment by kaushalmodi** [comment]
Ok, if the advice in https://github.com/kaushalmodi/ox-hugo/issues/552#issuecomment-1030268849 works for you, I'll document it in the manual and close this issue.

**Comment by johanwk** [comment]
Yes, please. It's working great over here :)

**Comment by kaushalmodi** [comment]
@johanwk This is now documented in https://ox-hugo.scripter.co/doc/troubleshooting/ .
