### ISSUE TITLE
Error when exporting: Symbol’s function definition is void: when-let*

### ISSUE THREAD

**Issue by jackbaty** [kaushalmodi/ox-hugo#56]
ox-hugo is a great idea, thanks.

Forgive me if I've missed something obvious, but when I run `org-hugo-export-subtree-to-md` using the all-posts.org example file I see the following error and no files are rendered:

```
[ox-hugo] Exporting ‘Post 1’ ..
helm-M-x: Symbol’s function definition is void: when-let*
```
I don't know the best way to post my environment info, but I'm using Spacemacs (tried both master (0.200.9) and develop as of today.

Emacs (emacs-plus via Homebrew) 25.2.1

**Comment by kaushalmodi** [comment]
Sorry about that, please update and try again. The `when-let` and `if-let` macros are new in emacs master. So they won't be out until the next major release (emacs 26+).

**Comment by jackbaty** [comment]
All good now, thanks!
