### ISSUE TITLE
Multilingual setup and org-hugo-citations-plist setting as local variable doesn't work

### ISSUE THREAD

**Issue by madanyang** [kaushalmodi/ox-hugo#574]
Hi,

I'm using ox-hugo with multi-lingual Hugo theme and the limitation of org-hugo-citations-plist not being local-varible is slowing me down.

In order to produce the org-hugo-citations-plist :bibliography-section-heading in the language of the document I need to manually evaluate (plist-put org-hugo-citations-plist :bibliography-section-heading "Desired Language") so I can change the output of the bibliography section heading according to the document language I am working at that time.

When I place the following nothing happens if the previous heading was set to something else

```
#+print_bibliography:
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (plist-put org-hugo-citations-plist :bibliography-section-heading "Kaynakça")
# eval: (org-hugo-auto-export-mode)
# End:

```
org-hugo-citations-plist are cons of string so it should be safe to include as a local variable. I am doing this wrong or is this a bug or missing feature.

**Comment by kaushalmodi** [comment]
Thanks. I think I'll implement a way to use the `org-export-translate` map from ox.el to translate "References" to the right language detected by the `#+language:` keyword in the buffer. 

As of now, I am not seeing Turkish translations in that variable in ox.el. You can either set those translations in your emacs config, or better yet, suggest the translations in the Org mode mailing list.

**Comment by madanyang** [comment]
line 6065 ("tr" :default "Referanslar")) is what is there in org version 9.5.2-gfbff08 that comes from gnu. My choice is another alternative. I'll try and see what happens. Neverhteless it should not be limited to language and one other thing where does this <style> coming from and if it is from ox-hugo that weird as that is the reason of using a static generator hugo theme should handle it

**Comment by kaushalmodi** [comment]
> My choice is another alternative.

You can then customize the `org-export-translate` in your emacs config. It won't work though until I use it for References. I am tracking that in this issue. 

> where does this <style> coming from

From `citeproc.el`.

**Comment by madanyang** [comment]
Thanks for the info. I might be wrong but looks like not many people are doing multilingual in a single document.

**Comment by kaushalmodi** [comment]
@madanyang Once is https://github.com/kaushalmodi/ox-hugo/pull/575 merged, you can get the translation as you intend by adding this to your Emacs config:

```el
(with-eval-after-load 'ox
  (setcdr (assoc "tr" (assoc "References" org-export-dictionary)) '(:default "Kaynakça")))
```

**Comment by kaushalmodi** [comment]
@madanyang This issue is auto-closed by that merge. But feel free to comment here further.

**Comment by kaushalmodi** [comment]
I have also added a page in the ox-hugo manual for multi-lingual support: https://ox-hugo.scripter.co/doc/multi-lingual-support/.
