### ISSUE TITLE
Wrap embedded SVG with caption in <figure> element

### ISSUE THREAD

**Issue by andreyorst** [kaushalmodi/ox-hugo#579]
After #476 when I use `#+include: path/to/img.svg` I get escaped representation. I guess this is now the expected behavior, but how can I acheive this inline inclusion? It's impossible to use `#+include` inside `#+begin_export` or in `@@html:...@@`. 

## How to Reproduce the Issue

Use `#+include` with an svg image.

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 29.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
     of 2022-01-31 (commit e8c66036d155adba9a75fb8304c241b55512c93c)

## Org Version

    Org mode version 9.5.2 (release_9.5.2-9-g7ba24c @ /home/alist/.local/share/emacs/29.0.50/lisp/org/)

## Hugo Version

    Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
As far as I know, the `#+include` keyword is for including Org files.

Are you looking for the [SVG Inlining](https://ox-hugo.scripter.co/doc/inlined-svgs/) feature?

**Comment by andreyorst** [comment]
Yes this seems to work, wasn't aware of that. However the caption generated by using this uses different tags.

When I use 

```org
#+caption: caption
[[file:static/img.svg]]
```

I get

```html
<figure>
  <img src="http://localhost:1313/img.svg" alt="caption">
  <figcaption>
    <p><span class="figure-number">Figure 2: </span>caption</p>
  </figcaption>
</figure>
```

But when I add `#+attr_html: :inlined t` the result is:

``` html
<?xml version="1.0" encoding="UTF-8"?><svg>...</svg></p>
<div class="figure-caption">
  <p><span class="figure-number">Figure 1: </span>caption</p>
</div>
```

Is this expected? I guess it is, as it's inlined, so I have to wrap it myself. Please correct me if I'm wrong.

**Comment by kaushalmodi** [comment]
> However the caption generated by using this uses different tags.

you can apply CSS to 

```css
figcaption, .figure-caption {
  /* something */
}
```

**Comment by kaushalmodi** [comment]
I don't mind having ox-hugo export with `figure` wrapper; just that I went though a lot of examples online and none of them wrap the `svg` tag. Also, none of them use captions with SVG tags.

Few of those links:

- https://vecta.io/blog/best-way-to-embed-svg
- https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started
- https://www.freecodecamp.org/news/use-svg-images-in-css-html/

I am surprised that there's not much new content regarding `<svg>` tags. All of the above links and more which I found online seem to be pretty much plagiarized from one-another 😄.

**Comment by kaushalmodi** [comment]
I just found http://html5doctor.com/the-figure-figcaption-elements/

> No need to constrain your <figure>s to images and code examples. Other content suitable for use in <figure> includes audio, video, charts (perhaps using <canvas> or <svg>), poems, or tables of statistics.

I like the cleanliness of `<figcaption>` compared to `<div class="figure-caption">`. I will test doing the figure wrapping soon.

**Comment by kaushalmodi** [comment]
@andreyorst See https://github.com/kaushalmodi/ox-hugo/pull/582. Once that is merged, SVGs with captions will be wrapped in `figure` elements and the captions will be placed in `figcaption` element.

**Comment by kaushalmodi** [comment]
@andreyorst The issue auto-closed when I merged that PR, but feel free to comment here.

**Comment by andreyorst** [comment]
I've tried it with some of my articles and it works. Thanks!
