### ISSUE TITLE
DOC: export bindings does not describe the function

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [kaushalmodi/ox-hugo#583]
This is about that part of the docu about export bindings
https://ox-hugo.scripter.co/#export-bindings

The key's are described but not the functions behind them.

Of course I know how to `describe-key` but I assume it would be more helpful for the users to see them in that introduction docu.

`describe-key` +  `C-c C-e H A` even does not work. It brokes up after `C-c C-e` and shows me `org-export-dispatch`.

**Comment by kaushalmodi** [comment]
Updated the doc page: https://ox-hugo.scripter.co/doc/usage/#export-bindings
