### ISSUE TITLE
DOC: reference is missing

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [kaushalmodi/ox-hugo#584]
I understand that in the Emacs universe the habits are a bit different. But I try. ;)

On https://ox-hugo.scripter.co/ I am not able to find any function references. I mean a list of all functions that ox-hugo offers and there description. The same content I would see when looking into the source files and reading the docstring for each function.

**Comment by kaushalmodi** [comment]
I don't have an automated way of doing this. I'd gladly accept a PR to add that automation. 

I can manually add in descriptions for each function and variable in the doc site, but that would be painstaking to begin with and then even more to maintain.

**Comment by kaushalmodi** [comment]
@Codeberg-AsGithubAlternative-buhtz Let me know if you have a way to automate this, otherwise I'll need to close this issue as "won't fix".

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I am not familiar with Lisp code. But I would assume that something like Doxygen or Sphinx does exist for Lisp code also.

But I don't know about this and close.

**Comment by kaushalmodi** [comment]
Leaving this here for reference if someone wants to take a stab at creating a PR for this: https://kitchingroup.cheme.cmu.edu/blog/2014/10/17/Generate-emacs-lisp-documentation/
