### ISSUE TITLE
Date should be optional in the front-matter?

### ISSUE THREAD

**Issue by punchagan** [kaushalmodi/ox-hugo#59]
Hugo (or some themes?) allows for posts/pages to not have a date in the front-matter.  But, `ox-hugo` seems to always add the current date, even when a post doesn't have `EXPORT_DATE` set.  Should this be configurable?

**Comment by kaushalmodi** [comment]
I agree. I had only considered dated blog posts till now, not pages like "About Me", etc. Will commit a fix soon.

**Comment by kaushalmodi** [comment]
Passes all the existing tests.. please try it out

**Comment by punchagan** [comment]
Thanks for the quick fix! :+1:
