### ISSUE TITLE
short codes phrase with {{< >}} (what am I doing wrong...)

### ISSUE THREAD

**Issue by jarss** [kaushalmodi/ox-hugo#602]
### Sample:

** PUBLISHED TAONAW: The Art of Not Asking Why
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: TAONAW
   :EXPORT_FILE_NAME: _index
   :EXPORT_HUGO_LAYOUT: single
   :EXPORT_HUGO_PAIRED_SHORTCODES: rawhtml
   :END:

This website is essentially free to maintain[fn:134]. 

TAONAW is built with [[https://gohugo.io/][Hugo Go]], a free open-source static-site generator. It is designed and authored on a free Linux OS using [[https://www.gnu.org/software/emacs/][Emacs]] [[https://orgmode.org/][org-mode]] and [[https://ox-hugo.scripter.co/][ox-hugo]].  Bandwidth is currently supplied free of charge by GitLab. 

I write posts in my free time because I want to and I enjoy doing so. No one is supporting me, sponsoring me, or otherwise paying me anything to write or create or publish any content. The goal is to keep things this way. 

If you enjoy what you find here, you can go ahead leave a one-time [[https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XBBGQRR2CX5EJ&source=url][tip]]. This is not payment: you're tipping me for a service I gave (a post you like), not a service you want to get (asking me to write a post). 

A note about copying/using the code and other parts of this site: 
I use free tools and free knowledge to build this site, and you are welcome to take and use anything you'd like, /except/ the logo. The logo of the owl and the book was not free and therefore, you may /not/ copy or re-use it. It was created by another artist, who I hired for money. If you want the name, I'll be more than happy to give it to you. Just ask.  

You can also go ahead and copy the content of the posts as well, just please link back to this site.

```
{{< rawhtml >}}
<a href="https://liberapay.com/JTR/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a>
{{< /rawhtml >}}
```

### on the site, it shows as following: 

![2022-03-24_09-07](https://user-images.githubusercontent.com/29918693/159922798-cf107c31-2e8b-4c1b-9432-d272bfd0c656.png)

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

 
# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
     of 2021-02-13

## Org Version

    Org mode version 9.3 (release_9.3 @ /usr/local/share/emacs/27.1/lisp/org/)

## Hugo Version

    Hugo Static Site Generator v0.80.0-792EF0F4/extended linux/amd64 BuildDate: 2020-12-31T13:46:18Z

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by jarss** [comment]
Looking at the .md file, 

The original code was: 
`<a href="https://liberapay.com/JTR/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a>`

but ox-hugo creates:
```
{{< rawhtml >}}
&lt;a href="<https://liberapay.com/JTR/donate>"&gt;&lt;img alt="Donate using Liberapay" src="![](https://liberapay.com/assets/widgets/donate.svg)"&gt;&lt;/a&gt;
{{< /rawhtml >}}
```

in the .md file

I'm not sure why this happens.

**Comment by kaushalmodi** [comment]
> ox-hugo supposed to "leave these alone" as these don't work in org-mode

But default, ox-hugo auto-escapes angle brackets as they are special characters in HTML (like `<a>`). You see the same behavior when you export the same Org snippet using ox-html. The main reason for this behavior was that I didn't want some Org content to have surprisingly different behavior when exporting using ox-html vs ox-hugo. Escaping the HTML special characters or not is a very base level behavior that I didn't want to change. 

The side effect of this decision is that the users don't inadvertently lock-in their Org mode content to be exportable using just Hugo! **The aim of ox-hugo is to allow any normal Org content to be easily exportable to Hugo after adding just one ox-hugo specific thing: the HUGO_BASE_DIR keyword** (the EXPORT_FILE_NAME subtree property is not ox-hugo specific, but ox-hugo needs that for subtree exports to understand the root level of a post). Now, it would be ironic that people have their Org content polluted with non-Org syntax like `{{< foo >}}` that would export sensibly with only ox-hugo! And that's way, that syntax is not accepted in raw Org even for ox-hugo. 

Due to that, people might also discover inbuilt Org features they didn't know existed :)

For your example:

```
{{< rawhtml >}}
<a href="https://liberapay.com/JTR/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a>
{{< /rawhtml >}}
```
, the same can be done with:

```
#+begin_export html
<a href="https://liberapay.com/JTR/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a>
#+end_export
```

Even better: If you using that frequently at multiple places, convert that to an Org macro (details in the below link). 

I have a full section on exporting [Shortcodes](https://ox-hugo.scripter.co/doc/shortcodes/). Check it out for more options on how to use Hugo shortcodes with ox-hugo.

**Comment by jarss** [comment]
I don't follow the solution.

I read through the shorcodes part (that's how I know to include     :EXPORT_HUGO_PAIRED_SHORTCODES: rawhtml, for example). The expected behavior, "Use :EXPORT_HUGO_PAIRED_SHORTCODES: myshortcode ... let the Org Special Block parsing logic know that “myshortcode” tag needs to be exported as a paired shortcode." 

So this means, if I use the short code paired property, the exported .md file should contain the {{ < > }} markings, correct? 
If that's true, I don't see that in the .md, I see the code I posted in the comment. 

So, I'm thinking...

1. I'm missing a part, of included the wrong syntax somewhere, because I don't understand how this work (this is usually the case) or:
2. there's a problem elsewhere that exports my code in the way it shows above, which is wrong. Not sure where though.

**Comment by jarss** [comment]
OK. I'm at a lost. 
I rebuilt the site, I tried again (with export html), and now it works. 
I must be tired and I did something else wrong, even though I swear all I did is copy paste. Since I can't replicate this, I will push and see if this work on the site, if it does, I'll close this. must be human error....

**Comment by kaushalmodi** [comment]
> The expected behavior, "Use :EXPORT_HUGO_PAIRED_SHORTCODES: myshortcode ... let the Org Special Block parsing logic know that “myshortcode” tag needs to be exported as a paired shortcode."

That's for the Org Special Blocks. 

If you use that, you need to do 

```
#+begin_rawhtml
..
#+end_rawhtml
```

That doesn't mean that you can use Hugo shortcode syntax directly in Org source. See the "myshortcode" example in https://ox-hugo.scripter.co/doc/shortcodes/#hugo-paired-shortcodes

**Comment by jarss** [comment]
Ok, since I can't replicate this and it seems to work now... I'll close this. It's odd,  what you suggest (#+begin_rawhtml and
#+end_rawhtml) lead to the same issue, which makes me think something else was going on that was not related to this issue at all. 

It works now, I'm using export html option instead.
