### ISSUE TITLE
High CPU and memory usage

### ISSUE THREAD

**Issue by nelimee** [kaushalmodi/ox-hugo#605]
## Actual Behavior

Exporting takes an enormous amount of time and memory. In order have absolute values, I witnessed things like
- More than 30 seconds to export a small post (less than 100 lines, no image, a few links).
- HUGE memory usage (more 18GB in the benchmarks attached below).

A few things I noticed:
- The time / memory taken seems to increase each time I am exporting, even though the only modification performed is "adding a newline".
- It seems like posts that appear first in the main org file section are exporting faster. 
- Re-starting `emacs` does not solve the issue.
- Copying the whole folder containing all the hugo-related files to another location on disk and opening this "fresh" version seems to make the bug disapear as I am able to export this "fresh" org file without any speed/memory issue.

The last 2 points make me think that this might be an issue with persistent files (cache files?) but I was unable to find any files to delete.

## Expected Behavior

The export should be reasonably fast and consume a reasonable amount of memory.

## How to Reproduce the Issue

I was unable to get a minimal example that suffer from this issue. The main org file where the issue arise contains personal information that I would rather not share publicly here. I can send the org file privately though.

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 28.0.92 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
     of 2022-03-28 (commit 968af794ba84d90d547de463448de57b7dff3787)

## Org Version

    Org mode version 9.5.2 (9.5.2-g6304af @ ~/.emacs.d/straight/build/org/)

## Hugo Version

    hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio

### Org `load-path` shadows

**Warning**: Possible mixed installation of Org

    ~/.emacs.d/straight/build/org/ob-processing hides /usr/local/share/emacs/28.0.92/lisp/org/ob-processing
    ~/.emacs.d/straight/build/org/ob hides /usr/local/share/emacs/28.0.92/lisp/org/ob
    ~/.emacs.d/straight/build/org/org-mouse hides /usr/local/share/emacs/28.0.92/lisp/org/org-mouse
    ~/.emacs.d/straight/build/org/org-indent hides /usr/local/share/emacs/28.0.92/lisp/org/org-indent
    ~/.emacs.d/straight/build/org/ol-bibtex hides /usr/local/share/emacs/28.0.92/lisp/org/ol-bibtex
    ~/.emacs.d/straight/build/org/ob-lob hides /usr/local/share/emacs/28.0.92/lisp/org/ob-lob
    ~/.emacs.d/straight/build/org/ob-ditaa hides /usr/local/share/emacs/28.0.92/lisp/org/ob-ditaa
    ~/.emacs.d/straight/build/org/ob-haskell hides /usr/local/share/emacs/28.0.92/lisp/org/ob-haskell
    ~/.emacs.d/straight/build/org/ob-perl hides /usr/local/share/emacs/28.0.92/lisp/org/ob-perl
    ~/.emacs.d/straight/build/org/ob-C hides /usr/local/share/emacs/28.0.92/lisp/org/ob-C
    ~/.emacs.d/straight/build/org/ol-eww hides /usr/local/share/emacs/28.0.92/lisp/org/ol-eww
    ~/.emacs.d/straight/build/org/ox-man hides /usr/local/share/emacs/28.0.92/lisp/org/ox-man
    ~/.emacs.d/straight/build/org/ob-eshell hides /usr/local/share/emacs/28.0.92/lisp/org/ob-eshell
    ~/.emacs.d/straight/build/org/org hides /usr/local/share/emacs/28.0.92/lisp/org/org
    ~/.emacs.d/straight/build/org/ob-scheme hides /usr/local/share/emacs/28.0.92/lisp/org/ob-scheme
    ~/.emacs.d/straight/build/org/ob-ruby hides /usr/local/share/emacs/28.0.92/lisp/org/ob-ruby
    ~/.emacs.d/straight/build/org/org-keys hides /usr/local/share/emacs/28.0.92/lisp/org/org-keys
    ~/.emacs.d/straight/build/org/org-capture hides /usr/local/share/emacs/28.0.92/lisp/org/org-capture
    ~/.emacs.d/straight/build/org/ob-dot hides /usr/local/share/emacs/28.0.92/lisp/org/ob-dot
    ~/.emacs.d/straight/build/org/oc hides /usr/local/share/emacs/28.0.92/lisp/org/oc
    ~/.emacs.d/straight/build/org/org-tempo hides /usr/local/share/emacs/28.0.92/lisp/org/org-tempo
    ~/.emacs.d/straight/build/org/ox hides /usr/local/share/emacs/28.0.92/lisp/org/ox
    ~/.emacs.d/straight/build/org/ol-info hides /usr/local/share/emacs/28.0.92/lisp/org/ol-info
    ~/.emacs.d/straight/build/org/org-attach-git hides /usr/local/share/emacs/28.0.92/lisp/org/org-attach-git
    ~/.emacs.d/straight/build/org/org-ctags hides /usr/local/share/emacs/28.0.92/lisp/org/org-ctags
    ~/.emacs.d/straight/build/org/ob-calc hides /usr/local/share/emacs/28.0.92/lisp/org/ob-calc
    ~/.emacs.d/straight/build/org/org-src hides /usr/local/share/emacs/28.0.92/lisp/org/org-src
    ~/.emacs.d/straight/build/org/ob-comint hides /usr/local/share/emacs/28.0.92/lisp/org/ob-comint
    ~/.emacs.d/straight/build/org/org-feed hides /usr/local/share/emacs/28.0.92/lisp/org/org-feed
    ~/.emacs.d/straight/build/org/ob-lua hides /usr/local/share/emacs/28.0.92/lisp/org/ob-lua
    ~/.emacs.d/straight/build/org/org-list hides /usr/local/share/emacs/28.0.92/lisp/org/org-list
    ~/.emacs.d/straight/build/org/ox-publish hides /usr/local/share/emacs/28.0.92/lisp/org/ox-publish
    ~/.emacs.d/straight/build/org/org-duration hides /usr/local/share/emacs/28.0.92/lisp/org/org-duration
    ~/.emacs.d/straight/build/org/ob-emacs-lisp hides /usr/local/share/emacs/28.0.92/lisp/org/ob-emacs-lisp
    ~/.emacs.d/straight/build/org/org-agenda hides /usr/local/share/emacs/28.0.92/lisp/org/org-agenda
    ~/.emacs.d/straight/build/org/ob-shell hides /usr/local/share/emacs/28.0.92/lisp/org/ob-shell
    ~/.emacs.d/straight/build/org/org-compat hides /usr/local/share/emacs/28.0.92/lisp/org/org-compat
    ~/.emacs.d/straight/build/org/ox-ascii hides /usr/local/share/emacs/28.0.92/lisp/org/ox-ascii
    ~/.emacs.d/straight/build/org/ob-css hides /usr/local/share/emacs/28.0.92/lisp/org/ob-css
    ~/.emacs.d/straight/build/org/org-num hides /usr/local/share/emacs/28.0.92/lisp/org/org-num
    ~/.emacs.d/straight/build/org/ox-html hides /usr/local/share/emacs/28.0.92/lisp/org/ox-html
    ~/.emacs.d/straight/build/org/ob-ref hides /usr/local/share/emacs/28.0.92/lisp/org/ob-ref
    ~/.emacs.d/straight/build/org/ob-eval hides /usr/local/share/emacs/28.0.92/lisp/org/ob-eval
    ~/.emacs.d/straight/build/org/ol-doi hides /usr/local/share/emacs/28.0.92/lisp/org/ol-doi
    ~/.emacs.d/straight/build/org/ob-table hides /usr/local/share/emacs/28.0.92/lisp/org/ob-table
    ~/.emacs.d/straight/build/org/org-crypt hides /usr/local/share/emacs/28.0.92/lisp/org/org-crypt
    ~/.emacs.d/straight/build/org/org-mobile hides /usr/local/share/emacs/28.0.92/lisp/org/org-mobile
    ~/.emacs.d/straight/build/org/ol hides /usr/local/share/emacs/28.0.92/lisp/org/ol
    ~/.emacs.d/straight/build/org/org-macro hides /usr/local/share/emacs/28.0.92/lisp/org/org-macro
    ~/.emacs.d/straight/build/org/ob-fortran hides /usr/local/share/emacs/28.0.92/lisp/org/ob-fortran
    ~/.emacs.d/straight/build/org/ob-awk hides /usr/local/share/emacs/28.0.92/lisp/org/ob-awk
    ~/.emacs.d/straight/build/org/ob-matlab hides /usr/local/share/emacs/28.0.92/lisp/org/ob-matlab
    ~/.emacs.d/straight/build/org/ol-eshell hides /usr/local/share/emacs/28.0.92/lisp/org/ol-eshell
    ~/.emacs.d/straight/build/org/ob-ocaml hides /usr/local/share/emacs/28.0.92/lisp/org/ob-ocaml
    ~/.emacs.d/straight/build/org/ob-latex hides /usr/local/share/emacs/28.0.92/lisp/org/ob-latex
    ~/.emacs.d/straight/build/org/ob-java hides /usr/local/share/emacs/28.0.92/lisp/org/ob-java
    ~/.emacs.d/straight/build/org/oc-natbib hides /usr/local/share/emacs/28.0.92/lisp/org/oc-natbib
    ~/.emacs.d/straight/build/org/org-archive hides /usr/local/share/emacs/28.0.92/lisp/org/org-archive
    ~/.emacs.d/straight/build/org/ob-groovy hides /usr/local/share/emacs/28.0.92/lisp/org/ob-groovy
    ~/.emacs.d/straight/build/org/org-macs hides /usr/local/share/emacs/28.0.92/lisp/org/org-macs
    ~/.emacs.d/straight/build/org/ol-docview hides /usr/local/share/emacs/28.0.92/lisp/org/ol-docview
    ~/.emacs.d/straight/build/org/ob-tangle hides /usr/local/share/emacs/28.0.92/lisp/org/ob-tangle
    ~/.emacs.d/straight/build/org/ob-screen hides /usr/local/share/emacs/28.0.92/lisp/org/ob-screen
    ~/.emacs.d/straight/build/org/ox-texinfo hides /usr/local/share/emacs/28.0.92/lisp/org/ox-texinfo
    ~/.emacs.d/straight/build/org/ob-js hides /usr/local/share/emacs/28.0.92/lisp/org/ob-js
    ~/.emacs.d/straight/build/org/ob-core hides /usr/local/share/emacs/28.0.92/lisp/org/ob-core
    ~/.emacs.d/straight/build/org/org-datetree hides /usr/local/share/emacs/28.0.92/lisp/org/org-datetree
    ~/.emacs.d/straight/build/org/ol-gnus hides /usr/local/share/emacs/28.0.92/lisp/org/ol-gnus
    ~/.emacs.d/straight/build/org/oc-basic hides /usr/local/share/emacs/28.0.92/lisp/org/oc-basic
    ~/.emacs.d/straight/build/org/ob-sass hides /usr/local/share/emacs/28.0.92/lisp/org/ob-sass
    ~/.emacs.d/straight/build/org/oc-csl hides /usr/local/share/emacs/28.0.92/lisp/org/oc-csl
    ~/.emacs.d/straight/build/org/ol-rmail hides /usr/local/share/emacs/28.0.92/lisp/org/ol-rmail
    ~/.emacs.d/straight/build/org/ob-clojure hides /usr/local/share/emacs/28.0.92/lisp/org/ob-clojure
    ~/.emacs.d/straight/build/org/org-pcomplete hides /usr/local/share/emacs/28.0.92/lisp/org/org-pcomplete
    ~/.emacs.d/straight/build/org/ol-mhe hides /usr/local/share/emacs/28.0.92/lisp/org/ol-mhe
    ~/.emacs.d/straight/build/org/ol-man hides /usr/local/share/emacs/28.0.92/lisp/org/ol-man
    ~/.emacs.d/straight/build/org/org-entities hides /usr/local/share/emacs/28.0.92/lisp/org/org-entities
    ~/.emacs.d/straight/build/org/ob-makefile hides /usr/local/share/emacs/28.0.92/lisp/org/ob-makefile
    ~/.emacs.d/straight/build/org/ob-sqlite hides /usr/local/share/emacs/28.0.92/lisp/org/ob-sqlite
    ~/.emacs.d/straight/build/org/ob-sed hides /usr/local/share/emacs/28.0.92/lisp/org/ob-sed
    ~/.emacs.d/straight/build/org/org-footnote hides /usr/local/share/emacs/28.0.92/lisp/org/org-footnote
    ~/.emacs.d/straight/build/org/ox-odt hides /usr/local/share/emacs/28.0.92/lisp/org/ox-odt
    ~/.emacs.d/straight/build/org/ob-plantuml hides /usr/local/share/emacs/28.0.92/lisp/org/ob-plantuml
    ~/.emacs.d/straight/build/org/ol-irc hides /usr/local/share/emacs/28.0.92/lisp/org/ol-irc
    ~/.emacs.d/straight/build/org/ob-R hides /usr/local/share/emacs/28.0.92/lisp/org/ob-R
    ~/.emacs.d/straight/build/org/org-lint hides /usr/local/share/emacs/28.0.92/lisp/org/org-lint
    ~/.emacs.d/straight/build/org/ob-julia hides /usr/local/share/emacs/28.0.92/lisp/org/ob-julia
    ~/.emacs.d/straight/build/org/ob-sql hides /usr/local/share/emacs/28.0.92/lisp/org/ob-sql
    ~/.emacs.d/straight/build/org/org-table hides /usr/local/share/emacs/28.0.92/lisp/org/org-table
    ~/.emacs.d/straight/build/org/ob-exp hides /usr/local/share/emacs/28.0.92/lisp/org/ob-exp
    ~/.emacs.d/straight/build/org/org-clock hides /usr/local/share/emacs/28.0.92/lisp/org/org-clock
    ~/.emacs.d/straight/build/org/org-habit hides /usr/local/share/emacs/28.0.92/lisp/org/org-habit
    ~/.emacs.d/straight/build/org/ox-latex hides /usr/local/share/emacs/28.0.92/lisp/org/ox-latex
    ~/.emacs.d/straight/build/org/org-goto hides /usr/local/share/emacs/28.0.92/lisp/org/org-goto
    ~/.emacs.d/straight/build/org/ob-gnuplot hides /usr/local/share/emacs/28.0.92/lisp/org/ob-gnuplot
    ~/.emacs.d/straight/build/org/ob-org hides /usr/local/share/emacs/28.0.92/lisp/org/ob-org
    ~/.emacs.d/straight/build/org/org-refile hides /usr/local/share/emacs/28.0.92/lisp/org/org-refile
    ~/.emacs.d/straight/build/org/org-faces hides /usr/local/share/emacs/28.0.92/lisp/org/org-faces
    ~/.emacs.d/straight/build/org/ol-bbdb hides /usr/local/share/emacs/28.0.92/lisp/org/ol-bbdb
    ~/.emacs.d/straight/build/org/org-loaddefs hides /usr/local/share/emacs/28.0.92/lisp/org/org-loaddefs
    ~/.emacs.d/straight/build/org/ox-koma-letter hides /usr/local/share/emacs/28.0.92/lisp/org/ox-koma-letter
    ~/.emacs.d/straight/build/org/org-attach hides /usr/local/share/emacs/28.0.92/lisp/org/org-attach
    ~/.emacs.d/straight/build/org/org-id hides /usr/local/share/emacs/28.0.92/lisp/org/org-id
    ~/.emacs.d/straight/build/org/oc-biblatex hides /usr/local/share/emacs/28.0.92/lisp/org/oc-biblatex
    ~/.emacs.d/straight/build/org/org-install hides /usr/local/share/emacs/28.0.92/lisp/org/org-install
    ~/.emacs.d/straight/build/org/org-version hides /usr/local/share/emacs/28.0.92/lisp/org/org-version
    ~/.emacs.d/straight/build/org/ob-lilypond hides /usr/local/share/emacs/28.0.92/lisp/org/ob-lilypond
    ~/.emacs.d/straight/build/org/ol-w3m hides /usr/local/share/emacs/28.0.92/lisp/org/ol-w3m
    ~/.emacs.d/straight/build/org/org-timer hides /usr/local/share/emacs/28.0.92/lisp/org/org-timer
    ~/.emacs.d/straight/build/org/ob-python hides /usr/local/share/emacs/28.0.92/lisp/org/ob-python
    ~/.emacs.d/straight/build/org/ob-lisp hides /usr/local/share/emacs/28.0.92/lisp/org/ob-lisp
    ~/.emacs.d/straight/build/org/ob-octave hides /usr/local/share/emacs/28.0.92/lisp/org/ob-octave
    ~/.emacs.d/straight/build/org/org-plot hides /usr/local/share/emacs/28.0.92/lisp/org/org-plot
    ~/.emacs.d/straight/build/org/ox-md hides /usr/local/share/emacs/28.0.92/lisp/org/ox-md
    ~/.emacs.d/straight/build/org/ox-icalendar hides /usr/local/share/emacs/28.0.92/lisp/org/ox-icalendar
    ~/.emacs.d/straight/build/org/org-colview hides /usr/local/share/emacs/28.0.92/lisp/org/org-colview
    ~/.emacs.d/straight/build/org/org-protocol hides /usr/local/share/emacs/28.0.92/lisp/org/org-protocol
    ~/.emacs.d/straight/build/org/ob-forth hides /usr/local/share/emacs/28.0.92/lisp/org/ob-forth
    ~/.emacs.d/straight/build/org/org-element hides /usr/local/share/emacs/28.0.92/lisp/org/org-element
    ~/.emacs.d/straight/build/org/ob-maxima hides /usr/local/share/emacs/28.0.92/lisp/org/ob-maxima
    ~/.emacs.d/straight/build/org/org-inlinetask hides /usr/local/share/emacs/28.0.92/lisp/org/org-inlinetask
    ~/.emacs.d/straight/build/org/ox-beamer hides /usr/local/share/emacs/28.0.92/lisp/org/ox-beamer
    ~/.emacs.d/straight/build/org/ox-org hides /usr/local/share/emacs/28.0.92/lisp/org/ox-org

Study the output of `M-x list-load-path-shadows`.

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>
</details>

## Profiling reports

<details>
  <summary>Tree view of the interesting part of the **CPU Profiler**</summary>
<pre>
       66668  99% - command-execute
       66668  99%  - call-interactively
       66616  99%   - funcall-interactively
       66562  99%    - save-buffer
       66562  99%     - basic-save-buffer
       66554  99%      - run-hooks
       66548  99%       - org-hugo-export-wim-to-md-after-save
       66548  99%        - org-hugo-export-wim-to-md
       66531  99%         - org-hugo--export-subtree-to-md
       66165  98%          - org-hugo--get-pre-processed-buffer
          96   0%           + org-element-interpret-data
          68   0%           + org-element-parse-buffer
           4   0%           + org-export-get-environment
         350   0%          + org-hugo-export-to-md
           8   0%          + org-export-get-environment
           4   0%          + org-get-outline-path
           4   0%            org-find-olp
          13   0%         + org-hugo--buffer-has-valid-post-subtree-p
           4   0%         + org-id-update-id-locations
           5   0%       + magit-after-save-refresh-status
           1   0%       + flycheck-handle-save
           4   0%      + vc-before-save
           4   0%      + basic-save-buffer-1
          41   0%    + previous-line
          13   0%    + execute-extended-command
          52   0%   + byte-code
         332   0% + ...
         132   0% + redisplay_internal (C function)
</pre>
</details>
<details>
  <summary>Tree view of the interesting part of the **Memory Profiler** (yes that is nearly 19GB of memory usage)</summary>
<pre>
 18,919,498,084  99% - command-execute
 18,919,497,028  99%  - call-interactively
 18,919,214,009  99%   - funcall-interactively
 18,915,067,984  99%    - save-buffer
 18,915,067,647  99%     - basic-save-buffer
 18,914,552,781  99%      - run-hooks
 18,914,525,902  99%       - org-hugo-export-wim-to-md-after-save
 18,914,525,902  99%        - org-hugo-export-wim-to-md
 18,914,170,834  99%         - org-hugo--export-subtree-to-md
 18,715,883,963  98%          - org-hugo--get-pre-processed-buffer
     16,891,628   0%           + org-element-interpret-data
      7,896,683   0%           + org-element-parse-buffer
        167,704   0%             org-export--get-export-attributes
         94,944   0%           + jit-lock-after-change
         66,729   0%           + org-hugo--org-mode-light
         37,666   0%           + org-export-get-environment
          6,792   0%           + flycheck-handle-change
          4,066   0%             org-element--cache-before-change
          3,072   0%           + version<
          2,096   0%           + org-element--cache-after-change
          1,460   0%             read
          1,024   0%             kill-matching-buffers
             21   0%             generate-new-buffer
    197,593,142   1%          + org-hugo-export-to-md
        167,704   0%            org-export--get-export-attributes
        102,328   0%          + org-export-get-environment
         63,316   0%          + org-find-olp
         17,448   0%          + org-get-outline-path
          2,048   0%          + org-back-to-heading
          1,276   0%          + org-entry-get
            256   0%          + org-hugo--get-elem-with-prop
            144   0%          + org-hugo--get-valid-subtree
             72   0%          + org-hugo--get-tags
        218,926   0%         + org-id-update-id-locations
        127,785   0%         + org-hugo--buffer-has-valid-post-subtree-p
            845   0%           #<compiled 0x1725300d09db2a>
         17,895   0%       + magit-after-save-refresh-status
          8,984   0%       + flycheck-handle-save
        468,767   0%      + basic-save-buffer-1
         28,781   0%      + vc-before-save
         14,933   0%      + vc-after-save
          1,216   0%      + run-hook-with-args-until-success
      3,939,295   0%    + execute-extended-command
         92,986   0%    + previous-line
         53,999   0%    + org-return
         27,352   0%    + handle-focus-in
         20,056   0%    + handle-focus-out
         11,073   0%    + org-delete-backward-char
          1,264   0%    + file-notify-handle-event
        283,019   0%   + byte-code
        321,230   0% + redisplay_internal (C function)
         15,472   0% + flycheck-perform-deferred-syntax-check
          6,512   0% + gcmh-register-idle-gc
          2,728   0% + timer-event-handler
            320   0% + flycheck-maybe-display-error-at-point-soon
              0   0%   ...
</pre>
</details>

[Full CPU profiling report saved after `M-x profiling-report`](https://github.com/kaushalmodi/ox-hugo/files/8361678/ox-hugo-cpu-profiling-report.txt)
[Full memory profiling report saved after `M-x profiling-report`](https://github.com/kaushalmodi/ox-hugo/files/8361572/ox-hugo-profiling-report.txt)

**Comment by kaushalmodi** [comment]
Hello, this looks like this is the same issue as https://github.com/kaushalmodi/ox-hugo/discussions/551.

That issue would happen if:

1. You are using the latest devel version of Org mode (i.e. built from the git `main` branch), and
2. The Org element caching feature is ON (it's on by default). 

It know that you said that you cannot get a minimal example that demonstrates this issue. But it would be great if you tried further to get one; check out the details on Org mode profiling and debugging [here](https://lists.gnu.org/r/emacs-orgmode/2022-03/msg00375.html) created by @yantar92.

---

## Workaround for this issue

1. Switch back to the latest stable version of Org mode (install the version from GNU Elpa), or
2. Temporarily set `org-element-use-cache` to _nil_ when this high CPU usage happens (but don't put that in your Emacs config!).

**Comment by kaushalmodi** [comment]
> Copying the whole folder containing all the hugo-related files to another location on disk and opening this "fresh" version seems to make the bug disapear as I am able to export this "fresh" org file without any speed/memory issue.

Can you also check if `M-x org-element-cache-reset` fixes this problem temporarily?

**Comment by kaushalmodi** [comment]
Thanks for confirming. I'll then close this issue. Please update with your findings in #551.
