### ISSUE TITLE
Headings that contain % in them cause an error when exporting

### ISSUE THREAD

**Issue by andreyorst** [kaushalmodi/ox-hugo#606]
## Actual Behavior

Given the following heading:
```org
** Example title with % in it
:properties:
:export_file_name: example-title-with-%-in-it
:end:
contents
```
Exporting it as a subtree to a file produces an error:
```
Debugger entered--Lisp error: (error "Not enough arguments for format string")
  message("[ox-hugo] Exporting `Example title with % in it' ....")
  org-hugo--export-subtree-to-md(nil nil)
  org-hugo-export-wim-to-md(nil nil nil)
  (lambda (a _s v _b) (org-hugo-export-wim-to-md nil a v))(nil nil nil nil)
  org-export-dispatch(nil)
  funcall-interactively(org-export-dispatch nil)
  command-execute(org-export-dispatch)
```
Looking at the code, I can see that this is the result of calling `message` with the result of `format` function `org-hugo--export-subtree-to-md`:

https://github.com/kaushalmodi/ox-hugo/blob/d04f41af6d128ccb9421c9bcd83b5fb12d14f440/ox-hugo.el#L4480

The `message` function itself accepts the format string, so an extra call to format should probably not be needed. And that's what causes the problem, as `format` in this case returns a string with `%` which `message` sees as a format string on its own.

## Expected Behavior

Headings can contain special format symbols such as `%`.

**Comment by kaushalmodi** [comment]
Thanks for catching that. This regression was caused due to a recent commit: https://github.com/kaushalmodi/ox-hugo/commit/66edee90c6e0fe60e2ae47fc02aa3d7f30a774cd.

I think I did that to fix some inconsistency in the printed messages, but now I'll revisit that at a later point once I document what that commit was fixing.
