### ISSUE TITLE
[feature request] Add flag to change 'author' field

### ISSUE THREAD

**Issue by GinShio** [kaushalmodi/ox-hugo#608]
## Actual Behavior
export 'author' field is list

## Expected Behavior
Add flag like `hugo_disable_author_list` or `hugo_enable_export_authors`

I want to export author field `author = "xxx"` or `authors = ["xxx"]`
and I dont want set `author` nil and use `#+hugo_custom_front_matter: :author "FirstName LastName"`

e.g. 
- `hugo_disable_author_list` is `t`
  ```org
  #+author: XXX
  #+hugo_disable_author_list: t
  ```
  export md like
  ```markdown
  +++
  author = "XXX"
  +++
  ```

- `hugo_disable_author_list` is `nil` or `false`
  ```org
  #+author: XXX
  #+hugo_disable_author_list: nil
  ```
  export md like
  ```markdown
  +++
  author = ["XXX"]
  +++
  ```

## How to Reproduce the Issue
NONE

## Ox-Hugo Debug Information
NO BUG

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment]
I would like to avoid adding such low level hooks if possible. What theme are you using? I can probably suggest a way to fix that theme just for your site.

**Comment by GinShio** [comment]
I use [DoIt](https://github.com/HEIGE-PCloud/DoIt), similar to LoveIt.
I found it support `authors` field, NOTE [here](https://github.com/HEIGE-PCloud/DoIt/issues/167)

**Comment by GinShio** [comment]
If not, maybe I'll change the theme as suggested here https://github.com/kaushalmodi/ox-hugo/issues/387#issuecomment-667447227

**Comment by kaushalmodi** [comment]
> I found it support authors field

In that case, you probably need to just add this to your Org file(s):

```org
#+hugo_front_matter_key_replace: author>authors
```

This key replacement feature is documented [here](https://ox-hugo.scripter.co/doc/replace-front-matter-keys/).

**Comment by GinShio** [comment]
**SRY** I did not notice
**THX**
good luck and good night

**Comment by kaushalmodi** [comment]
I have now added an example of author>authors replacement to the documentation: https://ox-hugo.scripter.co/doc/replace-front-matter-keys/#replace-author-with-authors
