### ISSUE TITLE
org-columns and EXPORT_HUGO_SECTION*

### ISSUE THREAD

**Issue by johanwk** [kaushalmodi/ox-hugo#615]
Regarding https://ox-hugo.scripter.co/doc/hugo-section/ and the use of `EXPORT_HUGO_SECTION*` for path fragments,

The use of `*` in the name of this org property doesn't work with `org-columns` for showing an overview of properties. Or, at least I haven't been able to use the property with an asterisk in its name in a `#+columns:` specification -- the value of the property is not shown.

Maybe an alias for `EXPORT_HUGO_SECTION*` could be introduced?

**Comment by johanwk** [comment]
Right .. but I think it would be good enough to just see the literal value of the `EXPORT_HUGO_SECTION*` property. It's not that important to see the concatenated path that is assembled on export, since the column view will make that fairly easy to see anyway.

**Comment by kaushalmodi** [comment]
@johanwk Please replace all occurrences of `EXPORT_HUGO_SECTION*` with `EXPORT_HUGO_SECTION_FRAG` in your Org files.

See https://ox-hugo.scripter.co/doc/deprecation-notices/#export-hugo-section-frag for details.
