### ISSUE TITLE
org-back-to-heading-or-point-min is not available in older org mode versions

### ISSUE THREAD

**Issue by punchagan** [kaushalmodi/ox-hugo#623]
f7b15f7c14aca06d57f33e1815ab7d5e811562cc seems to have started using `org-back-to-heading-or-point-min` function, which seems to be available in Org mode version 9.5 but not in 9.3.  We should either change the requirements for dependencies or provide our own version of this function in `ox-hugo`.

**Comment by kaushalmodi** [comment]
If you are able to upgrade to Org 9.5, I'll bump up the Org version requirement. 

The CI is tracking the latest stable release of Org, so it's difficult to keep ensuring that older Org versions will be supported. 

---

If you are unable to upgrade Org right now, I can patch this one function if that's the only thing.

**Comment by punchagan** [comment]
I'm unable to upgrade immediately, but I have been able to continue using `ox-hugo` by copying this function into my `.emacs` from the latest version of `org-mode`.  So, it looks like this is the only thing, as of now.

**Comment by kaushalmodi** [comment]
Cool! I'll then make ox-hugo provide that function if not defined already.

**Comment by punchagan** [comment]
Thanks! :)

**Comment by kaushalmodi** [comment]
The https://github.com/kaushalmodi/ox-hugo/commit/124c4a0c5858e82fe7853aa66fdcf978e301fdd2 commit has auto-closed this issue. But please update ox-hugo from the main branch and let me know if this works for you now.

**Comment by punchagan** [comment]
Yes, I can confirm that it works. Thanks @kaushalmodi ! :)
