### ISSUE TITLE
straight quotes rendered as curved quotes in inline src blocks

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#640]
@pdcawley Or you can see this update ox-hugo test: https://ox-hugo.scripter.co/test/posts/inline-code-blocks/#using-custom-css-for-inline-src-blocks

---

Aside.. looks like we triggered a bug in Hugo.. the smart quotes rendering done by GoldMark happens inside the HTML `code` elements too!

![image](https://user-images.githubusercontent.com/3578197/169539744-05304b96-48eb-4526-8720-7cb00042f897.png)

---

See https://bug-smart-quote-conversion-in-code-element--hugo-mwe.netlify.app/posts/double-quotes-in-html-code-elements/

_Originally posted by @kaushalmodi in https://github.com/kaushalmodi/ox-hugo/issues/638#issuecomment-1132911542_

---

Upstream Issues:
- https://github.com/gohugoio/hugo/issues/9911
- https://github.com/yuin/goldmark/issues/308
- https://github.com/commonmark/commonmark-spec/issues/711

**Comment by kaushalmodi** [comment]
@pdcawley Heads up! The required CSS will need to change as I adjust ox-hugo's export to implement a workaround for this limitation in Hugo's Commonmark parser.

**Comment by kaushalmodi** [comment]
Updated test: https://ox-hugo.scripter.co/test/posts/inline-code-blocks/#using-custom-css-for-inline-src-blocks

![image](https://user-images.githubusercontent.com/3578197/169885313-458100b9-77c3-45c8-bde7-fc0dfc723e31.png)

**Comment by pdcawley** [comment]
Cool!
