### ISSUE TITLE
Hope to support \newline in Latex 

### ISSUE THREAD

**Issue by LuciusChen** [kaushalmodi/ox-hugo#658]
## Actual Behavior
![image](https://user-images.githubusercontent.com/4947981/174953607-96ae7ff7-e2e4-4f6c-acb0-f1f2b1a43ea2.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/4947981/174953671-ba39bbb6-47b8-4b78-a21d-fe1e9e0827e2.png)

Hope to support \newline in Latex

**Comment by kaushalmodi** [comment]
- Can you paste the Org mode text?
- I'd like to compare the exported versions when exported with ox-html and and ox-md.

**Comment by kaushalmodi** [comment]
If the purpose is to just have a syntax to force a newline in the export, `ox-hugo` supports the `\\` characters at the end of line. See https://orgmode.org/manual/Paragraphs.html.

So this:

```org
abc \\
def
```

will export to 

```md
abc <br />
def
```

I hope that helps. As of now, I am not seeing a good reason to support special LaTeX syntax for newline when Org mode already has built-in support.

Let me know if the `\\` works for you.

**Comment by LuciusChen** [comment]
Thanks for the reply, I knew about `\\`, but in org-roam-ui it only supports `\newline`.😂

**Comment by kaushalmodi** [comment]
Can you open a request on `org-roam-ui` to support the standard Org syntax `\\` for newlines? As you might have realized, `\newline` is not support by `ox-html` or `ox-md`. And so `ox-hugo` has very little reason to support that.

Alternatively, you can use one of the filter hooks ( https://orgmode.org/manual/Advanced-Export-Configuration.html ) to add support for this in your Emacs config.

**Comment by LuciusChen** [comment]
Thanks, I'll take a look at this and then go to org-roam-ui and make a request.
