### ISSUE TITLE
No newline at end of file after re-exporting

### ISSUE THREAD

**Issue by andreyorst** [kaushalmodi/ox-hugo#666]
## Actual Behavior

Unlike initial export, after re-exporting a buffer, either from a file or from a subtree, the resulting file has no newline at the end.

Magit complains about it:

![image](https://user-images.githubusercontent.com/19470159/184509774-f91e82dc-42f0-4ff1-8792-6768ee47d334.png)

(In the old times, the absence of a final newline meant that the file is a binary data)

## Expected Behavior

Newline is appended.

## How to Reproduce the Issue

Re-export any existing file.

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  
# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
     of 2022-08-09 (commit 2504d19dade7bcfcce7cd93011edf06f3c955a50)

## Org Version

    Org mode version 9.5.4 (release_9.5.4-17-g6e991f @ /home/alist/.local/share/emacs/29.0.50/lisp/org/)

## Hugo Version

    hugo v0.93.3+extended linux/amd64 BuildDate=unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
`ox-hugo` doesn't distinguish between first and later exports. 

Were your initial exports on the same day? I am wondering a scenario where you probably had `require-final-newline` set to `t`, but then you removed it later before your later exports.

**Comment by andreyorst** [comment]
oh right, you're correct, there's no newline at the end of the file after the initial export too, I just never noticed this. `require-final-newline` is set to `t` by default, and I never touch this variable.

**Comment by kaushalmodi** [comment]
> require-final-newline is set to t by default, and I never touch this variable

`ox-hugo` doesn't touch this variable either. Is it possible you inherited that variable through some config suite like Spacemacs or Doom?

In any case, if you add `(setq require-final-newline t)` to your config and evaluate that, you will always have empty newlines at the end of your files after each save. The default of this variable is `nil` and in that, the file save operation doesn't modify the end of file newlines. 

---

FWIW I like to end files with newlines and I have `(setq require-final-newline t)` in my Emacs config.

**Comment by andreyorst** [comment]
> `ox-hugo` doesn't touch this variable either. Is it possible you inherited that variable through some config suite like Spacemacs or Doom?

no, I don't use any distributions. I now see that this variable is modified by some major modes, and my assumption that it's `t` by default was misled. Thanks for the suggestion, I'll add this variable to my init. Closing.

**Comment by kaushalmodi** [comment]
>  this variable is modified by some major modes

That should be reported as a bug. That variable should be changed only by the user.

**Comment by kaushalmodi** [comment]
> That variable should be changed only by the user.

Correcting myself a bit. A major mode should not change that variable to nil.

From https://www.gnu.org/software/emacs/manual/html_node/emacs/Customize-Save.html,

> Some major modes are designed for specific kinds of files that are always supposed to end in newlines. Such major modes set the variable require-final-newline to the value of mode-require-final-newline, which defaults to t. By setting the latter variable, you can control how these modes handle final newlines.
