### ISSUE TITLE
Resolving org-roam links when exporting to ox-hugo with multiple folders

### ISSUE THREAD

**Issue by wn** [kaushalmodi/ox-hugo#668]
## Actual Behavior
If my folder structure is of the form 
```
root
  - org
    - reference
      -  apple.org
    - main
      - banana.org
```

and I reference `banana.org` in `apple.org`, the generated markdown will have the format: `[banana]({{< relref "../main/banana.md" >}})`. However, the generated files will be of the form

```
root
  - content
    - posts
      - apple.md
      - banana.md
```

As a result, we get 

```
ERROR 2022/09/03 20:42:33 [en] REF_NOT_FOUND: Ref "../main/banana.md": "/Users/weineng/.org/braindump/content/posts/apples.md:9:26": page not found
```

## Expected Behavior
No errors. Ideally the relref should be "../banana.md" since ox-hugo flattened the tree.

## How to Reproduce the Issue
`hugo serve`

### Example Org File
https://github.com/wn/wn.github.io

### Generated Markdown File or Error
```
~/.org/braindump main
❯ hugo serve
Start building sites …
hugo v0.101.0+extended darwin/arm64 BuildDate=unknown
ERROR 2022/09/03 20:56:07 [en] REF_NOT_FOUND: Ref "../main/banana.md": "/Users/weineng/.org/braindump/content/posts/apple.md:8:40": page not found
Error: Error building site: logged 1 error(s)
Built in 12 ms
```

## Ox-Hugo Debug Information
-

**Comment by kaushalmodi** [comment]
Hello, I might not get to implementing this feature soon. Can you check if the linking works correctly if you do it using the Org ID instead?

**Comment by wn** [comment]
Hello, how do I change to using org id?
Also, could you leave some pointers on how I could implement this feature?

**Comment by wn** [comment]
For posterity, added a hacky fix for this: https://github.com/wn/wn.github.io/blob/main/shitscript.sh.

**Comment by dnaeon** [comment]
> For posterity, added a hacky fix for this: https://github.com/wn/wn.github.io/blob/main/shitscript.sh.

@wn, any chance you can share the script? I have a similar structure and currently exporting via `ox-hugo` results in broken links.

**Comment by dnaeon** [comment]
Posting my own solution here, until a better one exists.

```emacs-lisp
;; My org-roam capture templates store the notes in `notes/YYYY/MM' directory
;; structure.
;;
;; When exporting to Markdown via `ox-hugo' the resulting links are invalid,
;; because they would point to `../MM/filename.md'.
;;
;; Since all files are being exported to the `$HUGO_BASE_DIR/content/notes'
;; directory we are simply stripping any leading directories from the filenames
;; here, in order to have valid links.
(defun org-export-resolve-id-link/strip-directory (val)
  (car (last (file-name-split val))))

(advice-add 'org-export-resolve-id-link :filter-return #'org-export-resolve-id-link/strip-directory)
```

Using this hook I generated links will be valid, since the all generated files reside in the same directory when using `ox-hugo` exporter.
