### ISSUE TITLE
'#+attr_html' will be render as text still

### ISSUE THREAD

**Issue by fingerknight** [kaushalmodi/ox-hugo#669]
Hi, I met troubles when using `#+attr_html` to resize images.

Here is my `org` file snippet:
![image](https://user-images.githubusercontent.com/56252828/189989408-deecbfe8-1733-4015-9278-02b02caea88f.png)

After rendering (`C-c C-e H h`), i got this in `md`:
![image](https://user-images.githubusercontent.com/56252828/189989545-2b9ceaa5-e3a8-4c4a-a2a7-b5054e90dda5.png)

The most interesting thing is, that image shrinks indeed, but `#+attr_html width:50%` is rendered into `html` too.
![image](https://user-images.githubusercontent.com/56252828/189989915-15e51977-54d6-4ccf-af9c-e67e39a15f56.png)

I could not figure out what'd happened. Thanks if anyone helps! :)

**Comment by kaushalmodi** [comment]
There's a typo in the syntax. It should be:

```org
#+attr_html: :width 50%
```

Example from `ox-hugo` test suite:

![image](https://user-images.githubusercontent.com/3578197/189991519-8dd00dc2-e92b-4b2f-978c-92817f09d82e.png)

You can find more examples in the Org mode manual: https://orgmode.org/manual/Images-in-HTML-export.html

**Comment by fingerknight** [comment]
Oh, how careless i was!

And I found another annoying thing.

 `#+attr_html: :width  50%` works, but it just adds a `class` attribute to that element. Actually, the width of the image is controlled by `css style`, i.e., the width in `css style` will override the width in `class` attribute.

I've also tried `#+attr_html: :style width:50%;`, which didn't work at all, it just produced a image without any changes.

Any suggestions?

**Comment by kaushalmodi** [comment]
@fingerknight 

Hello, I am unable to reproduce the issue you are seeing. It will be helpful if you can post a minimal Org file that I can export myself to see the issue.

I have few tests of `#+attr_html` and `:width` in the ox-hugo test suite, and when I changed one of the test to use % for width, it exported as expected:

![image](https://user-images.githubusercontent.com/3578197/190427694-f9c0845b-0132-4993-a02e-191956c90331.png)

**Comment by fingerknight** [comment]
Sorry about confusing, I've found what my problem really is: 

it works i mean `#+attr_html`, my problem is something in `html` and `css`. I am look for other ways.

Thanks for your time. Have fun in your vacation! :)
