### ISSUE TITLE
File link to a static org file

### ISSUE THREAD

**Issue by andreyorst** [kaushalmodi/ox-hugo#674]
Hello! Sorry if this was already answered or exists in the documentation - I wasn't able to find anything on the problem I'm experiencing.

## Actual Behavior

I want to make one of the `.org` files downloadable and link it from the post.
When I add such a file to the `static` directory and add a `[[file:../static/file.org][file.org]]` link, `ox-hugo` creates a relref link to post with the name `file`.
Then, when I start the `hugo server` command, it can't build the pages, and fails with the error:

```
ERROR 2022/09/26 22:04:00 [en] REF_NOT_FOUND: Ref "file": "~/Git/blog/content/posts/post.md:9:2": page not found
ERROR 2022/09/26 22:04:00 [en] REF_NOT_FOUND: Ref "file": "~/Git/blog/content/posts/post.md:9:25": page not found
```

## Expected Behavior

Ability to link to any kind of file as to a static file.

Ideally, I would like to make it possible to download the `.org` source of the post from the post itself, as I've done [here](https://andreyorst.gitlab.io/reproducible-research-with-org-mode-fennel-and-love), but I had to remove the `.org` extension and create a copy of the file in the `static` directory manually.

## How to Reproduce the Issue

I'm using one post per file approach, with a pretty standard configuration where posts go into directory `posts`:

```
.
├── config.toml
├── content
│   └── posts
│       └── post.md
├── posts
│   └── post.org
├── static
│   └── file.org
└── themes
```

### Example Org File

```org-mode
#+hugo_base_dir: ../
#+hugo_section: posts
#+hugo_auto_set_lastmod: t
#+options: tex:dvisvgm
#+macro: kbd @@html:<kbd>$1</kbd>@@

#+title: Post
#+date: 2022-09-26

[[file:../static/file.org]]
```

### Generated Markdown File or Error

```markdown
+++
title = "Post"
author = ["Andrey Listopadov"]
date = 2022-09-26
lastmod = 2022-09-26T22:03:03+03:00
draft = false
+++

[{{< relref "file" >}}]({{< relref "file" >}})
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  
# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
     of 2022-09-19 (commit a7c65fc6660878e244432a5b25fb3a4ff20e8604)

## Org Version

    Org mode version 9.5.5 (release_9.5.5 @ /home/alist/.local/share/emacs/29.0.50/lisp/org/)

## Hugo Version

    hugo v0.93.3+extended linux/amd64 BuildDate=unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
This is tricky. Most people who would be writing a post per file (not following the post-per-subtree flow) might at some point want to link to an Org file, expecting that that converts to a `relref` in Markdown. It would be difficult to tell if the `file:` link is for the purpose of referencing another page (to be rendered from that Org file), or if that Org file is meant to raw download.

Perhaps .. can you define a custom link like `org:` and define its export format so that it copies that file to static and also constructs the link to that file from static?

---

May be if you add `"org"` to `org-hugo-external-file-extensions-allowed-for-copying`, it will work? [I haven't tested.] But then you won't be able to export links to .org links as cross-post references.

Alternatively, if you have only a handful occurrences of Org files meant for download, you may rename those to something like `.orgfile`, and add `"orgfile"` to `org-hugo-external-file-extensions-allowed-for-copying` ?

**Comment by andreyorst** [comment]
>This is tricky. Most people who would be writing a post per file (not following the post-per-subtree flow) might at some point want to link to an Org file, expecting that that converts to a `relref` in Markdown. 

Unfortunately, my blog became really big, and contains a lot of text, images, etc. and Emacs can't handle a buffer of this size without lagging, so i had to convert my blog from post-per-subtree to post-per-size.

So yeah, I'm using crosslinking and I expect them to transform to relrefs. Just not when it is a link to a file in the static/ directory.

>Perhaps .. can you define a custom link like `org:` and define its export format so that it copies that file to static and also constructs the link to that file from static?
>
>May be if you add `"org"` to `org-hugo-external-file-extensions-allowed-for-copying`, it will work? [I haven't tested.] But then you won't be able to export links to .org links as cross-post references.
>
>Alternatively, if you have only a handful occurrences of Org files meant for download, you may rename those to something like `.orgfile`, and add `"orgfile"` to `org-hugo-external-file-extensions-allowed-for-copying` ?
>

Thanks, I'll try these suggestions!



-- 
Andrey Listopadov

**Comment by kaushalmodi** [comment]
@andreyorst Thanks. Let me know what solution works out for you.

**Comment by andreyorst** [comment]
@kaushalmodi I've decided to go with a specialized link type.

As a quick prototype I've tried this:

1. Added `("org" :export export-static-org-file :complete org-link-complete-file)` to `org-link-parameters`
2. Created a function:
   ```emacs-lisp
   (defun export-static-org-file (file &optional text &rest _)
     (let ((new-path (expand-file-name (file-name-concat "../static" file) org-hugo-base-dir)))
       (copy-file (expand-file-name file) new-path t)
       (format "[%s](/%s)" (or text file) (file-name-nondirectory file))))
   ```

Now, when exporting the file, this function handles copying to static and creates an appropriate link.

This seems to work for my particular case, though I guess there might be more to it (looking at how complex the ox-hugo's export link function is)

**Comment by kaushalmodi** [comment]
It's will be too patchy to specially treat links to .org files with `static/` in the path. If the `org:` custom link approach works, can this issue be closed?

**Comment by andreyorst** [comment]
I just noticed, that this trick stopped working when I tried to re-export my old files. For some reason, as far as I see, Org no longer uses my export function from the `org-link-parameters`. I'm not exactly sure what has changed since Oct 2022 in Org, Emacs, or the ox-hugo package.

Upon further inspection, it seems that I need to somehow change the link `:type` for it to work, but I don't understand how would I do it, because it's not something handled by the syntax in the file itself.

In the `ox.el` file the `org-export-custom-protocol-maybe` function is responsible for calling the `:export` function if it exists but it does so for links that are not of the following types: `"coderef"`, `"custom-id"`, `"fuzzy"`, `"radio"`, `nil`. For some reason, the `org` link I've created has the `"fuzzy"` type and I'm not sure who's responsible for that, or how to workaround it. The manual mentions the `org-store-link` and the `:store` function in the `org-link-parameters` but it's for storing links interactively, which isn't my case.

Do you know what I'm doing wrong or can you give any other pointers?

**Comment by andreyorst** [comment]
OK, I panicked too soon. I carefully re-read the manual and it seems that the only change to make it work is to use `org-link-set-parameters` instead of directly modifying `org-link-parameters`.

Sorry for the noise.
