### ISSUE TITLE
#+caption doesnt work with #+begin_quote

### ISSUE THREAD

**Issue by andreyorst** [kaushalmodi/ox-hugo#683]
## Actual Behavior

Writing:

``` org-mode
#+caption: John Doe
#+begin_quote
famous quote
#+end_quote
```

Doesn't produce any caption in the resulting Markdown.

## Expected Behavior

A caption is added similarly to source code blocks

## How to Reproduce the Issue

Export to markdown

### Example Org File

``` org-mode
#+caption: John Doe
#+begin_quote
famous quote
#+end_quote
```

### Generated Markdown File or Error

```markdown
> famous quote
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  
# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4)
     of 2022-10-23 (commit a01bd1a208a5199fd1d76baade373f7f12f912a2)

## Org Version

    Org mode version 9.5.5 (release_9.5.5 @ /home/alist/.local/share/emacs/29.0.50/lisp/org/)

## Hugo Version

    hugo v0.93.3+extended linux/amd64 BuildDate=unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "gif" "mp4" "pdf" "odt" "doc" "ppt" "xls" "docx" "pptx" "xlsx")</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">"%Y-%m-%dT%T%z"</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">""</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment]
Hello, 

Org doesn't expect a caption for quote blocks. You can see the Ascii, Markdown and HTML outputs using `ox-ascii`, `ox-md` and `ox-html` exports respectively:

![image](https://user-images.githubusercontent.com/3578197/199541597-7e87a4ad-6989-4bd3-9e1b-cc2e4d2dca36.png)


---

How do you visualize the `ox-hugo` exported Markdown to render the quote block caption? Or how would you have manually written the quote+caption in Markdown?

**Comment by andreyorst** [comment]
> Org doesn't expect a caption for quote blocks. You can see the Ascii, Markdown and HTML outputs using ox-ascii, ox-md and ox-html exports respectively:

Oh, sorry, should have checked that

> How do you visualize the `ox-hugo` exported Markdown to render the quote block caption? Or how would you have manually written the quote+caption in Markdown?

An example from my blog:

![image](https://user-images.githubusercontent.com/19470159/199545232-2e995458-850e-40e9-be00-f754e3ffb6d4.png)

I have manually written the caption for this in org mode via html export:

```org-mode
#+begin_quote
CL packages are the wrong way to implement packages in Lisp.
As I explained in a discussion two years ago, packages implemented using obarrays (or equivalent) don't work reliably.

We have a much better basis for Lisp packages in the shorthands mechanism.
It only needs to be completed.
#+end_quote
#+begin_export html
<div class="src-block-caption">
<span>Richard Stallman on </span><a href="https://lists.gnu.org/archive/html/emacs-devel/2022-10/msg01786.html">CL packages landed</a>
</div>
#+end_export
```

**Comment by kaushalmodi** [comment]
Canonically, `<cite>` is used with `<blockquote>`. Example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite

I have this `ox-hugo` test:

```org
#+begin_quote
He puts his claw against the divider. "Fist my bump."
#+begin_cite
Andy Weir, Project Hail Mary
#+end_cite
#+end_quote
```

which renders to https://ox-hugo.scripter.co/test/posts/special-blocks/#inline-html5-elements.

Would that `#+begin_cite:` .. `#+end_cite` fit your usecase too?

**Comment by kaushalmodi** [comment]
Alternatively, this will export pretty close to what you have manually put inside the `#+begin_export html` (it will just not have the `<span>` tags):

```org
#+begin_quote
CL packages are the wrong way to implement packages in Lisp.
As I explained in a discussion two years ago, packages implemented using obarrays (or equivalent) don't work reliably.

We have a much better basis for Lisp packages in the shorthands mechanism.
It only needs to be completed.
#+end_quote
#+begin_src-block-caption
Richard Stallman on [[https://lists.gnu.org/archive/html/emacs-devel/2022-10/msg01786.html][CL packages landed]]
#+end_src-block-caption
```

**Comment by andreyorst** [comment]
I think these options will work for me. Thanks for the help!
