### ISSUE TITLE
What's the best way to add frontmatter to a post?

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#7]
@helloyi's implementation uses a somewhat complex parser that ends with a simple `concat` command. 

I think a good solution would have the following characteristics:

- [x] use the built-in [export-filter](http://orgmode.org/manual/Advanced-configuration.html) system (seems more elegant) (**fixed in https://github.com/kaushalmodi/ox-hugo/pull/8**)
- [ ] allow user-defined export properties. The other implementation defines a small set of properties and writes them to the front of the file. A better solution would be to allow any `:HUGO_` properties to be included in the export, since different hugo themes & sites support different export props.  

(also, I hope it's ok to be filing all these issues -- if you'd rather communicate some other way let me know!)

**Comment by kaushalmodi** [comment]
> also, I hope it's ok to be filing all these issues

Yes, it's completely fine. I don't have any experience using export-filter, but will read up on that. Thanks for opening these issues.

**Comment by kaushalmodi** [comment]
>A better solution would be to allow any :HUGO_ properties to be included in the export, since different hugo themes & sites support different export props.

Can you give examples on theme specific export properties? 

Also, is it good to close this issue now if want you planned for the second bullet above is already implemented?

**Comment by kaushalmodi** [comment]
I believe we have a pretty good Org meta data -> front matter conversion setup. WDYT? :)

(There are still many other Hugo front matter variables out there; but we can add them as needed. The most complicated of that, after Menu support, is Blackfriday meta data support. I've opened another issue for that -- https://github.com/kaushalmodi/ox-hugo/issues/37.).

Closing this issue.
