### ISSUE TITLE
helper to add export properties to an existing subtree

### ISSUE THREAD

**Issue by jave** [kaushalmodi/ox-hugo#70]
In my case I have a lot of existing subtrees in an org file, and I'd like some convenient helper to specify the export properties.

I guess some kind of simple macro could be done using org hugo slug, but the function doesnt seem to understand keywords like DONE:

(org-hugo-slug "** DONE BTC Coffe")  => "done-btc-coffee", the done part should be removed.

**Comment by jave** [comment]
(org-set-property "EXPORT_FILE_NAME" (org-hugo-slug (org-get-heading
t t)))

**Comment by jave** [comment]
also it would be nice if EXPORT_DATE could be set from the CLOSED date

**Comment by kaushalmodi** [comment]
> also it would be nice if EXPORT_DATE could be set from the CLOSED date

This is already done in commit https://github.com/kaushalmodi/ox-hugo/commit/fc15f0ca8e14c0751abb8484b6d32eebe9fa3927. Can you update to the latest master (or even from Melpa)?

**Comment by kaushalmodi** [comment]
> In my case I have a lot of existing subtrees in an org file, and I'd like some convenient helper to specify the export properties. 

Can you provide an example?

**Comment by kaushalmodi** [comment]
> (org-hugo-slug "** DONE BTC Coffe") => "done-btc-coffee", the done part should be removed.

Let's get to this later when doing the final touchups.. may be you can advise `org-hugo-slug` on your end..

**Comment by kaushalmodi** [comment]
Thinking more about that, `org-hugo-slug` does not do that within `ox-hugo` as it gets the input argument from the heading *title* property. If you too do the same using the `org-entry-get` or something like that "DONE" shouldn't be passed to `org-hugo-slug` at all.

**Comment by jave** [comment]
this thing seemed to work okay, and i could convert an entire o-blog tree with emacs macrology:

(defun jv-ox-prop ()                                                                                                                                                                                               
(interactive)                                                                                                                                                                                                      
(org-set-property "EXPORT_FILE_NAME" (org-hugo-slug (org-get-heading                                                                                                                                               
t t))))

**Comment by kaushalmodi** [comment]
Great! Good luck with the blog conversion! Feel free to open another issue if something else comes up.
