### ISSUE TITLE
syntax highlighting for R and elisp.

### ISSUE THREAD

**Issue by fkgruber** [kaushalmodi/ox-hugo#700]
Hi
I'm using the old academic theme and hugo 0.5 and my only complain is that code blocks are not color coded. Both R and elisp show in a single color. See for example
![image](https://user-images.githubusercontent.com/4311763/212447184-6f310fa9-a1c8-4a1b-9a6b-96b40f39755d.png)

Is there a simple configuration setting that I'm missing to get the syntax coloring working?

thanks
FKG

**Comment by kaushalmodi** [comment]
You'll need to fix this in Hugo configuration. 

Also, version 0.5 is really old. Please update to the latest Hugo version. 

By default, the syntax highlighting should work right out of the box. See https://gohugo.io/getting-started/configuration-markup/#highlight for more information.

**Comment by fkgruber** [comment]
Updated to the most recent hugo and got fixed. thanks
