### ISSUE TITLE
Use vanilla md links instead of relref

### ISSUE THREAD

**Issue by kchousos** [kaushalmodi/ox-hugo#707]
Hello! Thank you for your amazing package!

I want to export some org-roam files to hugo and use [quartz](https://github.com/jackyzha0/quartz) to render them. But since it looks for backlinks in vanilla md syntax, it doesn't recognize the relrefs.

Is there any way to change this behaviour?

**Comment by kaushalmodi** [comment]
Hello, there isn't a way to customize that behavior as this package is only for Hugo compatible Markdown exports. `relref` allows the export to be relaxed as the exporter doesn't need to figure out full relative paths. `relref` in Hugo does that job for you.

Even if, if you want to tweak that, you can advise the `org-hugo-link` function.

**Comment by kchousos** [comment]
Alright, thanks for the quick reply!
