### ISSUE TITLE
Add configuration for global usage of yaml front-matter

### ISSUE THREAD

**Issue by kchousos** [kaushalmodi/ox-hugo#708]
I am aware of the option `#+hugo_front_matter_format: yaml` that you can put in your org file. But is it possible for a global variable to be implemented such that all ox-hugo exports default to yaml?

There already exists `org-hugo--fm-yaml`, but as described in #310, this is an internal variable that should not be messed with by the user.

If this could be implemented I would be grateful, but I understand if it is not in the scope of the package. Thank you for your work and contribution.

**Comment by kaushalmodi** [comment]
Actually, I plan to remove YAML support altogether. Few months back, I developed a TOML generator that's more generic and robust than the YAML front-matter generator. As that meta-data generator is internally generated by `ox-hugo` only for Hugo's consumption, I plan to simplify things and support only TOML going forward.

**Comment by kaushalmodi** [comment]
Related: https://github.com/kaushalmodi/ox-hugo/pull/629

**Comment by kchousos** [comment]
Understandable. Thank you for your reply and for this amazing package!
