### ISSUE TITLE
How does org-hugo-export-subtree-to-md work?

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#71]
I'm just trying to understand `org-hugo-export-subtree-to-md` so I can reuse it. I have somewhat simpler requirements, though, and don't need to check weight, etc.  I don't see how you are able to inform the exporter that you're requesting the valid parent subtree (rather than the subtree at point).  If you have a chance to explain the code, I'd appreciate it.  See https://github.com/titaniumbones/ox-huveal/issues/4, where I'm looking to reuse your code ( but I will likely use it in other places too!)

**Comment by kaushalmodi** [comment]
Yes, I had to go a bit out of the normal way of designing an Org exporter.

By default, an Org subtree export will export only the subtree in which the point is.. as you already saw. But we need it to be more intelligent, and do the "right thing".. i.e. don't export **just** the current subtree, but the whole subtree encompassing the current post.

.. and the current post or the "valid Hugo post subtree" is defined to be the one with the `EXPORT_FILE_NAME` property.

So the *magic* is to first figure out which heading (could be the current or any of the parent headings) has that property defined, and *jump to that*.. before the call to `(org-hugo-export-to-md async :subtreep visible-only)` is made.

.. and that jumping happens here, inside `org-hugo-export-subtree-to-md`:

```el
          ;; Publish only the current subtree
          (org-back-to-heading :invisible-ok)
          (let ((subtree (org-hugo--get-valid-subtree))
```

**Comment by titaniumbones** [comment]
ah, now I see it, there's no save-excursion in --get-valid-subtree.  So, that means every time `org-hugo--bet-valid-subtree` is called, it hast obe wrappedi n a `save-excursion` in the calling function?

**Comment by kaushalmodi** [comment]
> it has to be wrapped in a save-excursion in the calling function

Correct. I cannot do `save-excursion` inside `org-hugo--get-valid-subtree`.. the point has to be in the *correct scope* at the time of calling the actual export function: `org-hugo-export-to-md`.

So the pseudocode would be:

```
save-window-excursion
  save-restriction
    widen
    save-excursion
      org-hugo--get-valid-subtree
      org-hugo-export-to-md
```

**Comment by kaushalmodi** [comment]
Closing this as the question seems to be resolved.
