### ISSUE TITLE
creating pages with lists of posts?

### ISSUE THREAD

**Issue by jave** [kaushalmodi/ox-hugo#74]
I would like to be able to recreate these two pages:

http://www.verona.se/tags.html

http://www.verona.se/archives.html

They are lists of blog posts with just the headings. One is sectioned with dates, the other with categories.

Is this the responsibility of the Hugo-theme, or ox-hugo?

**Comment by kaushalmodi** [comment]
That would be the theme. `ox-hugo` is mainly for the Markdown content creation. Hugo then takes care of generating those pages. Look into Hugo Taxonomies: https://gohugo.io/content-management/taxonomies/

I would encourage you to read through the Hugo docs to understand the themes. You probably would have come across this: https://themes.gohugo.io/. If not go through the Demo sites for those themes.

**Comment by jave** [comment]
thanks
