### ISSUE TITLE
org-header level 4 and beyond is exported as list

### ISSUE THREAD

**Issue by ssl-bio** [kaushalmodi/ox-hugo#743]
When I export an org file to md, headers level 4 and beyond are exported as lists. In addition an org-header 3 (*** header 3) is exported as md-header 4 (#### header 3). Attached I include code for the main file (main.txt), the post file (theme2.txt) and how it is exported as markdown (index.md) [I used txt extension because I can't attach org files and inserting as code is not rendered correctly]
[main.txt](https://github.com/user-attachments/files/16420333/main.txt)
[index.md](https://github.com/user-attachments/files/16420334/index.md)
[theme2.txt](https://github.com/user-attachments/files/16420335/theme2.txt)

Is there a way to correct this?

Thanks

OS: Debian 12
Emacs: 29.4
ox-hugo: git-hash c4156d9

**Comment by ssl-bio** [comment]
My apologies, I did not search the web correctly. The answer is to add the option
`#+OPTIONS: H:6`
In the main file.
Source: [Emacs StackExchange](https://emacs.stackexchange.com/questions/53797/export-org-mode-headers-level-4-or-above-as-headers-in-texinfo)

**Comment by kaushalmodi** [comment]
Yes, the `ox-hugo` package respects the basic Org Exporter settings. I am glad you figured it out.
