### ISSUE TITLE
Add a thumbnail image to site index along with `.summary`

### ISSUE THREAD

**Issue by fpdotmonkey** [kaushalmodi/ox-hugo#748]
Is there a known way to add thumbnail images for each post to the site index?  I currently am able to do this by providing `:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :thumbnail /path/to/thumb.png` and using that in my theme, but using full resolution images tanks my load times.  I see that there's the `.Resize` function in Hugo that would help, but I haven't had any luck getting Hugo to be able to find my assets in `static/ox-hugo/`.

**Comment by kaushalmodi** [comment]
I haven't tinkered with Hugo image processing, but from its docs, the images need to be in `assets/images/` and not static.

**Comment by kaushalmodi** [comment]
Auto-copying of images to `assets/images/` is not supported.

**Comment by kaushalmodi** [comment]
Auto-copying of images to `assets/images/` is not supported. But here is one way you can use images from page bundle. You will need to update your Hugo theme to pick the image from page bundle, post-process that and use for thumbnail

![image](https://github.com/user-attachments/assets/25ece600-9e1f-420a-acdd-d33d0c873155)

**Comment by kaushalmodi** [comment]
Oh yes, and the Org source for above:

![image](https://github.com/user-attachments/assets/f9c486d0-c585-4968-9506-f6711aec21ff)

**Comment by fpdotmonkey** [comment]
Thank you, this worked for me.  For completeness, this is what I came up with.  In org:
```org
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_BUNDLE: a-short-and-incomplete-history-of-control-system-tooling
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :thumbnail de-reamur-furnace.png
:END:
```
And then the HTML templates
```html
            {{ with .Resources.GetMatch (printf "assets/%s" .Params.thumbnail) }}
	    <div style="flex: 1;">
		{{ if eq .MediaType.SubType "svg" }}
		<img class="thumbnail" src="{{ .RelPermalink }}">
		{{ else }}
		{{ with .Resize "300x" }}
	        <img class="thumbnail" src="{{ .RelPermalink }}">
		{{ end }}
		{{ end }}
	    </div>
	    {{ end }}
```
