### ISSUE TITLE
Broken post draft state when post has sub-headings

### ISSUE THREAD

**Issue by punchagan** [kaushalmodi/ox-hugo#87]
When the post content starts with another headline, the draft state of the post is incorrect, because the point appears to be on the first sub-heading instead of the post title subtree.  

I have added a test [here](https://github.com/punchagan/ox-hugo/commit/61b426cb7a1ab3e9a7e9511789d00bf2a2a2724f) to help reproduce the bug.

**Comment by kaushalmodi** [comment]
I discovered that very recently! https://github.com/kaushalmodi/ox-hugo/commit/e6ebac4c2034c6add6fbeee67db4cd4eb47d40e8

.. and thought that it affected just tags, and fixed that.

Are you on the latest master?

That being said, let me look at your example.

**Comment by kaushalmodi** [comment]
Can you test that this issue goes away if you put a newline before the *Other heading*?

What's confusing is that, these are affected by this issue:

- `(org-entry-get (point) "ALLTAGS")` --- Fetches current + inherited tags **fixed**
- `(org-entry-get (point) "TODO")` --- Fetches TODO state **this bug**

But not:

- `(org-entry-get (point) "ITEM")` --- Fetches title

Any ideas?

**Comment by kaushalmodi** [comment]
Arghh.. affects `(org-entry-get (point) "CLOSED")` too.. but not `(org-entry-get (point) "ITEM")`. See if you can help me debug this.

**Comment by kaushalmodi** [comment]
Update and try again! Looks like this was an *ek teer do shikaar* fix :D

**Comment by punchagan** [comment]
@kaushalmodi I can confirm that this works! Thanks! :+1:
