### ISSUE TITLE
Align Org tags and hugo tags

### ISSUE THREAD

**Issue by simonthum** [kaushalmodi/ox-hugo#89]
I like to use the TAGS line to populate the list of tags I have available on a per-file basis. E.g.:

```
#+TAGS: wtf food drinks
```

However, ox-hugo puts them on all posts. IMO this is what

```
#+FILETAGS: wtf food drinks
```

would do in org-mode (see http://orgmode.org/org.html#Tag-inheritance). The point of the TAGS  line is to merely have such idiosyncratic blog tags available in the tag editor (you can assign keys too).

**Comment by kaushalmodi** [comment]
That's a valid point.  I'll add fixing this the first thing on my list.

**Comment by kaushalmodi** [comment]
To be clear, it will make more sense to apply this breaking change only to subtree based exports. I am assuming you are using subtree-based exports?

**Comment by simonthum** [comment]
Yes definitively.

Along those lines, it would make a lot of sense to have the hugo section inherit from a subtree's property, too. This way I could use headings for different content types.

**Comment by kaushalmodi** [comment]
> have the hugo section inherit from a subtree's property, too.

Sorry, I didn't follow that. Can you open a new issue with an example of your use case?

**Comment by simonthum** [comment]
Sure.

**Comment by kaushalmodi** [comment]
@simonthum Please update from the master and try again (Melpa update should also be out in few hours).

See https://ox-hugo.scripter.co/doc/tags-and-categories/ for details.

**Comment by simonthum** [comment]
Seems to work great. Thank you very much!
