### ISSUE TITLE
ox-hugo should export to hugo content dir by default

### ISSUE THREAD

**Issue by titaniumbones** [kaushalmodi/ox-hugo#9]
If we're using ox-hugo, it's because we want the output to end up in a Hugo blog.  Rather than export in the current directory of org files, send straight to Hugo.  

Behaviour should be controlled by a defcustom, and should also be settable as file-local.

**Comment by titaniumbones** [comment]
being addressed in #12

**Comment by kaushalmodi** [comment]
This has already been implemented.
