### ISSUE TITLE
Use org-mode propery inheritance to organize hugo exort

### ISSUE THREAD

**Issue by simonthum** [kaushalmodi/ox-hugo#90]
The subtree export would become more versatile when property inheritance could be used to modify some ox-hugo properties.

In particular, I find the property `HUGO_SECTION` would be great to set on a parent heading, e.g. for projects and posts in one Org mode file.

http://orgmode.org/manual/Property-inheritance.html

**Comment by kaushalmodi** [comment]
Ah, I now get it. You are probably just missing the `EXPORT_` prefix. I happen to have this test that uses EXPORT_HUGO_SECTION inheritance: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/deep-nesting.org

Here's the Hugo rendered output of that test: https://ox-hugo.scripter.co/test/book1

**Comment by kaushalmodi** [comment]
Almost all EXPORT_HUGO_* properties are auto-inherited.

**Comment by kaushalmodi** [comment]
Search for "EXPORT_" on http://orgmode.org/manual/Export-settings.html to learn why this is so.

**Comment by simonthum** [comment]
OK, I knew I was missing something stupid... Thanks!

**Comment by simonthum** [comment]
While I was indeed doing something stupid, the feature does not work as I would expect. `EXPORT_HUGO_SECTION` is only in effect when the immediately enclosing header defines it. When I have a level of indirection, it falls back to "posts". AFAICT `deep-nesting.org` only tests the immediate case.

**Comment by kaushalmodi** [comment]
Hmm, can you paste a minimal test case here?

**Comment by simonthum** [comment]
Roughly like this:
```
* Blog
 :EXPORT_HUGO_SECTION: blog
** Test 1
 :EXPORT_FILE_NAME: test
 lands in blog
** category        :@cat:
*** test2
:EXPORT_FILE_NAME: test2
lands in posts
* Projects
```

**Comment by kaushalmodi** [comment]
Thanks, I confirm that. I'll look into it tomorrow.

**Comment by kaushalmodi** [comment]
This issue auto-closed as I linked it with that fixing commit. But feel free to reopen this issue if it's still not fixed for you. Thanks for your bug reports! :)

**Comment by kaushalmodi** [comment]
Here's the test:

- [Org][1]
- Markdown -- [Post A1][2], [Post AX][3]
- HTML -- [Post A1][4], [Post AX][5]

[1]: https://github.com/kaushalmodi/ox-hugo/blame/c32359c71e7926c7f13039069d8d7481dfb9bc82/test/site/content-org/all-posts.org#L1838-L1853
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/section-a/post-a1.md
[3]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/section-a/post-ax.md
[4]: https://ox-hugo.scripter.co/test/section-a/post-a1/ 
[5]: https://ox-hugo.scripter.co/test/section-a/post-ax/

**Comment by simonthum** [comment]
Well, thanks for making a package worth making bug reports for ;)

Jokes aside, this seems the most convincing org model blogging package to me due to the subtree export, which is the best I have seen so far. Thanks!
