### ISSUE TITLE
failed to parse page metadata (date/lastmod)

### ISSUE THREAD

**Issue by gour** [kaushalmodi/ox-hugo#92]
Hello,

If `date` and `lastmod` meta fields entries are not quoted:

```
+++
title = "Birthday"
date = "2011-02-09T11:13:00+01:00"
lastmod = "2017-10-31T11:14:22+01:00"
tags = ["gaura-nitai", "prasadam"]
categories = ["devotional"]
weight = 2001
draft = false
+++
```

I get the following errors:

```
$ hugo
Started building sites ...
ERROR 2017/10/31 11:01:12 failed to parse page metadata for "posts/writing-hugo-blog-in-org-subtree-export.md": Near line 3 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got '+' instead
ERROR 2017/10/31 11:01:12 failed to parse page metadata for "posts/birthday.md": Near line 2 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got '+' instead
Error: Error building site: Errors reading pages: Error: failed to parse page metadata for "posts/writing-hugo-blog-in-org-subtree-export.md": Near line 3 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got '+' instead for writing-hugo-blog-in-org-subtree-export.md
Error: failed to parse page metadata for "posts/birthday.md": Near line 2 (last key parsed ''): expected a top-level item to end with a newline, comment, or EOF, but got '+' instead for birthday.md
```

so wonder how does it work for you and/or others?

**Comment by kaushalmodi** [comment]
Hugo had this bug on the master branch briefly after v0.30.2 release and in very old versions.  The latest master has this issue fixed. 

What is your hugo version? I'd suggest updating to v0.30.2.

**Comment by kaushalmodi** [comment]
[`ox-hugo` test for date in +UTC time zone using `hugo` built from latest master branch][1]

[1]: https://ox-hugo.scripter.co/test/posts/date-plus-time-plus-utc/

**Comment by gour** [comment]
> What is your hugo version? 

v0.31-DEV-133CFD17 

> I'd suggest updating to v0.30.2.

Building from the master (v0.31-DEV-76DC811C) helped, but I've another issue with images-in-content. 😉

**Comment by kaushalmodi** [comment]
>  but I've another issue with images-in-content. 😉

No problem. Let's discuss that back in that thread.
