### ISSUE TITLE
Symbol's function definition is void: org-export--get-export-attributes

### ISSUE THREAD

**Issue by bighi** [kaushalmodi/ox-hugo#97]
Hi, I'm a recent Emacs convert from vim. I am trying to use org-mode to organize my life and now to blog too.

I have a fairly empty emacs config, but when I try to export using C-c C-e H H, I get this error:

>  Symbol's function definition is void: org-export--get-export-attributes

I have a very simple org file with a test blog post. This is the content of the file:

```
* Hello World                                                          :blog:
:PROPERTIES:
:EXPORT_FILE_NAME: ~/Dropbox/Projetos/bighi.github.io/content/posts/hello-world.md
:SLUG:     hello-world
:DATE:     2017-11-08
:END:
First post, ok?
```

Anything I'm doing wrong? Any way I can help debug this?

**Comment by bighi** [comment]
Adding more info.

Emacs version: 25.3.1
Org-mode version: 8.3.4
OS: Arch Linux

**Comment by bighi** [comment]
OK, I already know what my mistake was.

Org 9.0+ is needed. The native version of Org is too old, so I installed a newer one.

I'm leaving the answer here in case anyone makes the same mistake. Issue closed.

**Comment by kaushalmodi** [comment]
Great! I was about to reply with that. Glad you figured it out. Feel free to post any other issue you see.
