### ISSUE TITLE
custom front matter to support a list of elements

### ISSUE THREAD

**Issue by Titan-C** [kaushalmodi/ox-hugo#99]
The `:EXPORT_HUGO_CUSTOM_FRONT_MATTER:` property supports key value pairs. The value is a string. I happen to need a list of elements in the value.

My current workaround is to use for a toml front matter
```
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :animals [\"dog\" \, \"cat\", \, \"penguin\"]
```
Is there a possibility to directly use a list
```
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :animals '("dog" "cat" "penguin")
```

**Comment by kaushalmodi** [comment]
I hadn't yet planned to support list values. I am glad to see that at least there's a workaround for that.

I use `org-babel-parse-header-arguments` to parse that whole property. Let me see over this week if a more elegant solution is possible.

For reference, [here's the current code][1] that parses those properties.

[1]: https://github.com/kaushalmodi/ox-hugo/blob/c2992639df68f1bf65ca94dcc96081e7b47ff252/ox-hugo.el#L1523-L1536

**Comment by kaushalmodi** [comment]
I quickly tried:

```el
(org-hugo--parse-property-arguments ":a '(b \"c d\")")
```

and it works as expected.

So below (you wouldn't even need to double quote list elements):

```
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :animals '(dog cat penguin)
```

should be easy to get working.

I am putting implementing this at the top of my list.

**Comment by kaushalmodi** [comment]
@Titan-C Try the latest version from the master (or the next update on Melpa in few hours). Let me know if it works for your use case now.

You can find the test cases for this new feature addition in the above auto-annotated commit.

**Comment by Titan-C** [comment]
Thank you for this improvement. I downloaded from Melpa and it works perfectly for my current use case.
